### ISSUE TITLE
List messages in a Mailbox returns nothing after first page

### ISSUE THREAD

**Issue by iMuFeng** [nodemailer/wildduck#100]
`curl "http://localhost/users/5b84ca5eb5628fd792e33780/mailboxes/5b84ca5eb5628fd792e33785/messages?page=2&next=eyIkZGF0ZSI6IjIwMTgtMDgtMjhUMDQ6MDc6MzkuMzcxWiJ9&limit=20"` 

returns

```
{
  "success": true,
  "total": 46,
  "page": 2,
  "previousCursor": "eyIkZGF0ZSI6IjIwMTgtMDgtMjhUMDQ6MDc6MzguNDAxWiJ9",
  "nextCursor": false,
  "specialUse": "\\Junk",
  "results": []
}
```

That's because of `mongo-cursor-pagination`, I just modify some code like this:  [Link](https://github.com/iMuFeng/mongo-cursor-pagination/commit/2e1112fc25f1ab3ab55964097ebce71210664b09#diff-48452ba50e2dd127d9db30b9dcd711bb), and it's work now.

**Comment by andris9** [comment]
Oh, dang, you're right, no idea how I missed it. I guess it slipped in with some recent upgrade. It is hard to believe that they actually broke the mongo-cursor-pagination but maybe changed the API somehow, I'll take a look.

**Comment by iMuFeng** [comment]
@andris9 Thanks to your work.

**Comment by andris9** [comment]
This should be fixed now in the latest version of WildDuck
