### ISSUE TITLE
Remove zonemta-onion support from setup script

### ISSUE THREAD

**Issue by bunyevacz** [nodemailer/wildduck#104]
Hi,

I think we should remove it, because it results this error in logs:
```
ERR! Plugins Failed loading plugin file <node_modules/zonemta-onion>: Cannot find module '/opt/zone-mta/node_modules/zonemta-onion'
```
It is in [line 63 of 09_install_zone_mta.sh][0].

I tried to search in git history when it was removed from `package.json` from either `zone-mta` or `zone-mta-template`.
I could not find it. 

Either remove the .onion config file creation, or fix the onion support, I really have no preference I do not use .onion.

[0]: https://github.com/nodemailer/wildduck/blob/7e88acca28853223bca58b43c56200bc2054b341/setup/09_install_zone_mta.sh#L63

**Comment by andris9** [comment]
Yeah, the onion thing seemed cool at first but it is not needed by anyone

**Comment by andris9** [comment]
Removed traces of onion support in f754ec1a8f003c29fcf2a2b99e11116575a76cdd
