### ISSUE TITLE
Custom user backend (for example LDAP)

### ISSUE THREAD

**Issue by erdii** [nodemailer/wildduck#105]
Hey @andris9! :)

Would it be possible to create a custom user (and authentication) backend as a wildduck plugin?

Edit: I'd offer up my help at writing documentation what can and can't be done with the plugin api.

**Comment by andris9** [comment]
Currently this is not supported but it would be possible to change user handling in a way to support external methods (eg. ldap), it would probably mean that an user account is instantiated on first successful login.

**Comment by andris9** [comment]
I don’t know about plugin support, I haven’t figured out the best way for it yet even though I have experimented.

Regarding custom authentication, I would probably handle it with HTTP based API - whenever an user tries to authenticate then basic auth request is made against a configured URL. Response headers should contain user id or an error code/message.

**Comment by erdii** [comment]
Ah ok.

I'd guess an external user module would have to provide at least these functions:

From wildduck to external-user-backend:
* verify if a user exists/is still enabled (eg for incoming mail or authentication with an application password which is stored in wildduck itself)
* authenticate user with password

From external-user-backend to wildduck:
* Delete user data permanently (covered in exisiting wildduck api)

What do you think? Let me know if I can help!

**Comment by erdii** [comment]
Any updates on this? :)

**Comment by erdii** [comment]
Ok, just get back to me if you have time for it. I'd like to help out.

Good luck with the rollout!

**Comment by pvagner** [comment]
I'm considering moving from dovecot to wildDuck however I'd like to keep authenticating users via ldap.openldap.

**Comment by flypenguin** [comment]
ldap is nice, unfortunately we have an urgent use case which requires either saml or oauth. so while we're probably not going to use wildduck now i would suggest making authentication pluggable, because flexibility.

**Comment by pierreozoux** [comment]
@flypenguin you again? :P

I'm also following silently this issue, and I also think that having another mean of auth like oauth, OIDC or SAML would make it easier for bigger orgs to adopt it!

**Comment by louis-lau** [comment]
> either saml or oauth

While I agree with having something pluggable, both saml and oauth are meant for the browser and require http.

For oauth IMAP authentication there's no standard right now. So for example google and Microsoft are using something non standard. Even if you were to copy googles implementation, there a good chance that no client will actually be able to use it with your server.

There's [a proposed standard](https://datatracker.ietf.org/doc/rfc7628/) for oauth outside of http, but it's only a _proposed_ standard. And if it does become a standard, you'll have to wait for **all** major email clients to actually implement it if you want to use it as your only authentication method.

I don't think anyone ever implemented saml for IMAP auth. 
And then again, clients won't support it. I'm not that familiar with saml though, so I may be wrong.



Ldap can simply use standard imap authentication and check if the details are correct. In short, I think that what you're asking is impossible at this time :).

If you're only looking for webmail support, you can build some authentication wrapper for your favourite webmail client.

**Comment by flypenguin** [comment]
@louis-lau the "usual" approach is to secure the web frontend using oauth & co (office 365 for example) and to have "application passwords" for anything machine-to-machine-related (imap for example, and used by google & fastmail). LDAP is a PITA when using 2FA ("please enter your password and append your 2FA number" - you can't teach this to non-tech-users).

as for your authentication wrapper - if you have any hints in how to "build" such a thing, feel free to share. I probably won't do it (doesnt scale, and it would be a snowflake solution), but right now I'd not say it was impossible, just incredibly bad / insecure (at least if I am thinking correctly).

**Comment by andris9** [comment]
For SSO the only option right now is to generate WildDuck users without a password, then configure your SSO proxy to set logged in username into a HTTP header and then configure wildduck-webmail to use that header instead of doing actual authentication. Users can then use wildduck-webmail to generate passwords for IMAP and SMTP.

**Comment by flypenguin** [comment]
@andris9 ... that actually sounds ... DOABLE :) thanks a lot!! (IMAP for user access is not even a use case for me btw, so even better).

**Comment by louis-lau** [comment]
> if you have any hints in how to "build" such a thing, feel free to share

Sorry, I understand that that may be easier said than done haha. For wildduck-webmail I would go the above route.

For something like roundcube I would create an authentication application that uses whatever method you want to sign in, and then in the background logs in to roundcube and passes the roundcube cookie to the browser. Then the user is logged in to roundcube. In order to pass valid authentication info to roundcube you could create application passwords on the fly.

I get that that isn't doable for everyone, the point of my comment was that wildduck is an imap server, not a webmail per say. So user backends for wildduck itself would be limited by what imap can do.

**Comment by flypenguin** [comment]
@louis-lau yup, I didn't really get that wildduck is *primarily* an IMAP server, I was more focusing on the webmail part. that makes a lot of sense then.
