### ISSUE TITLE
Why use ZoneMTA instead of Haraka for outgoing mails?

### ISSUE THREAD

**Issue by AuspeXeu** [nodemailer/wildduck#107]
Just out of curiosity, for your scripted installation you use ZoneMTA for outbound emails. From my understanding, Haraka could also do this job, no?

**Comment by andris9** [comment]
Messages are queued to MongoDB, ZoneMTA fetches queued messages on demand (this allows to run multiple ZoneMTA instances that send messages from a single queue). Haraka requires queued messages to be on disk on the same server where Haraka runs. If anything, I would consider replacing Haraka with ZoneMTA for inbound as well, the only reason for keeping Haraka so far is that I do not want to mess with SPF and DKIM validation.
