### ISSUE TITLE
ZoneMta smtp authentication issues 

### ISSUE THREAD

**Issue by LevyT** [nodemailer/wildduck#109]
Hey, so I saw this issue

https://github.com/nodemailer/wildduck/issues/95
^ This fix gives some kind of server error

But that didn't seem to fix it for me, still can't authenticate tried with multiple clients and cli

openssl s_client -connect mail.com:587 -starttls smtp
^ this gives 535 Authentication failed

**Comment by LevyT** [comment]
When using the referred fixed, this is the crash location
```
 /opt/zone-mta/node_modules/mongodb/lib/utils.js:132
Nov 01 09:38:54 WildDuck zone-mta[15501]:       throw err;
Nov 01 09:38:54 WildDuck zone-mta[15501]:       ^
Nov 01 09:38:54 WildDuck zone-mta[15501]: TypeError: Cannot read property 'component' of undefined
Nov 01 09:38:54 WildDuck zone-mta[15501]:     at loggelf (/opt/zone-mta/plugins/wildduck/index.js:45:44)
Nov 01 09:38:54 WildDuck zone-mta[15501]:     at UserHandler.loggelf (/opt/zone-mta/plugins/wildduck/index.js:88:29)
Nov 01 09:38:54 WildDuck zone-mta[15501]:     at authSuccess (/opt/zone-mta/plugins/wildduck/node_modules/wildduck/lib/user-handler.js:568:38)
Nov 01 09:38:54 WildDuck zone-mta[15501]:     at logAuthEvent (/opt/zone-mta/plugins/wildduck/node_modules/wildduck/lib/user-handler.js:751:41)
Nov 01 09:38:54 WildDuck zone-mta[15501]:     at users.collection.findOneAndUpdate (/opt/zone-mta/plugins/wildduck/node_modules/wildduck/lib/user-handler.js:3067:24)
Nov 01 09:38:54 WildDuck zone-mta[15501]:     at result (/opt/zone-mta/node_modules/mongodb/lib/utils.js:414:17)
Nov 01 09:38:54 WildDuck zone-mta[15501]:     at session.endSession (/opt/zone-mta/node_modules/mongodb/lib/utils.js:401:11)
Nov 01 09:38:54 WildDuck zone-mta[15501]:     at ClientSession.endSession (/opt/zone-mta/node_modules/mongodb-core/lib/sessions.js:129:41)
Nov 01 09:38:54 WildDuck zone-mta[15501]:     at executeCallback (/opt/zone-mta/node_modules/mongodb/lib/utils.js:397:17)
Nov 01 09:38:54 WildDuck zone-mta[15501]:     at handleCallback (/opt/zone-mta/node_modules/mongodb/lib/utils.js:128:55)
Nov 01 09:38:54 WildDuck zone-mta[15501]: ERR! SMTP/feeder/15516 Reciver process b293dce82688680cbf7b for feeder exited with 1
```

**Comment by sirakoff** [comment]
In addition to disabling `example-auth`  [#95](https://github.com/nodemailer/wildduck/issues/95)

Add 
```
[wildduck.gelf]
enabled=true
```

to `/etc/zone-mta/plugins/wildduck.toml`

```
[wildduck]
...

[wildduck.gelf]
enabled=true


# SRS settings for forwarded emails

[wildduck.srs]
...

```
and restart start zone-mta service

`service restart zone-mta`

**Comment by ajmalkhanjamro** [comment]
> In addition to disabling `example-auth` [#95](https://github.com/nodemailer/wildduck/issues/95)
> 
> Add
> 
> ```
> [wildduck.gelf]
> enabled=true
> ```
> to `/etc/zone-mta/plugins/wildduck.toml`
> 
> ```
> [wildduck]
> ...
> 
> [wildduck.gelf]
> enabled=true
> 
> 
> # SRS settings for forwarded emails
> 
> [wildduck.srs]
> ...
> ```
> and restart start zone-mta service
> 
> `service restart zone-mta`

this did not fixed my issue i have installed it on my ip not domain  iam try to connect it from my mail sending desktop software here is the error same error iam getting after adding the suggestion you said

9.42.0.437-1
2018-12-02T18:12:07.574Z
Connecting to: 217.199.161.216:587 Enc: SSL
Login: ajmal
Connected.
 220 841474.vps-10.com ESMTP Welcome to feeder! [zone-mta/1.13.3]
 EHLO hosted-by.rootlayer.net
 250-841474.vps-10.com Nice to meet you, hosted-by.rootlayer.net
250-PIPELINING
250-8BITMIME
250-SMTPUTF8
250-AUTH LOGIN PLAIN
250-STARTTLS
250 SIZE 31457280
 STARTTLS
 220 Ready to start TLS
 EHLO hosted-by.rootlayer.net
 250-841474.vps-10.com Nice to meet you, hosted-by.rootlayer.net
250-PIPELINING
250-8BITMIME
250-SMTPUTF8
250-AUTH LOGIN PLAIN
250 SIZE 31457280
 AUTH LOGIN YWptYWw=
 334 UGFzc3dvcmQ6
 SkFtcm8xMjNAIw==
 535 Authentication failed
Disconnected.

**Comment by louis-lau** [comment]
Closing this old issue for inactivity. Let me know if this is still an issue on the latest versions and the issue will be reopened.
