### ISSUE TITLE
MAIL Content Issue

### ISSUE THREAD

**Issue by jagadeesh1113** [nodemailer/wildduck#110]
We are facing issues with mail subject, content. We got a mail from other domains

Japanese content is not displaying properly. as their content transfer encoding is empty.

So it cannot able to read.

Kindly help us to solve the issue

**Comment by andris9** [comment]
Can you provide a raw source of such failing message for debugging?

**Comment by jagadeesh1113** [comment]
When we are getting messages from other mail server, that message is in
Japanese language. They are not sending any content transfer encoding in
their header.

We are able view some junk content instead of that Japanese content

Regards
Jagadeesh Y M

**Comment by louis-lau** [comment]
Closing this old issue for inactivity. If this is still an issue, please provide a message to test with. We'll reopen the issue.
