### ISSUE TITLE
zonemta smtp authentication not working after fix even

### ISSUE THREAD

**Issue by ajmalkhanjamro** [nodemailer/wildduck#111]
hello i have install wildduck using script and seen the fix below as well added that to my server restarted still not worked iam using my desktop software to test connect and my wildduck server is installed on ip not domain what is the solution dose script have issue here is my software log iam getting while connecting

`9.42.0.437-1
2018-12-02T18:12:07.574Z
Connecting to: 217.199.161.216:587 Enc: SSL
Login: ajmal
Connected.
 220 841474.vps-10.com ESMTP Welcome to feeder! [zone-mta/1.13.3]
 EHLO hosted-by.rootlayer.net
 250-841474.vps-10.com Nice to meet you, hosted-by.rootlayer.net
250-PIPELINING
250-8BITMIME
250-SMTPUTF8
250-AUTH LOGIN PLAIN
250-STARTTLS
250 SIZE 31457280
 STARTTLS
 220 Ready to start TLS
 EHLO hosted-by.rootlayer.net
 250-841474.vps-10.com Nice to meet you, hosted-by.rootlayer.net
250-PIPELINING
250-8BITMIME
250-SMTPUTF8
250-AUTH LOGIN PLAIN
250 SIZE 31457280
 AUTH LOGIN YWptYWw=
 334 UGFzc3dvcmQ6
 SkFtcm8xMjNAIw==
 535 Authentication failed
Disconnected.`

**Comment by louis-lau** [comment]
Closing this old issue for inactivity. Sorry this was never replied to. `Authentication failed` can only happen for a wrong username and password when using the zonemta-wildduck plugin.
