### ISSUE TITLE
outband mail problem

### ISSUE THREAD

**Issue by bayton00** [nodemailer/wildduck#113]
hey all,
i am using wildduck with its webmail and zone-mta.
sending / receiving are OK using webmail. but sending using poer 25 says  5.1.1 No such user and says "The remote certificate is invalid according to the validation procedure." for port 587 in outlook and all smtp checker tools. 
how to solve this problem?

**Comment by andris9** [comment]
You can't send messages using port 25, it is for incoming only. For 587 you need a valid TLS certificate. Normally the wildduck setup script generates a valid cert using Let's Encrypt but it might have failed and you ended up either with a self signed cert or a cert for a different hostname than the one you are using to send mail. Make sure that your certs and hostnames are correct.
