### ISSUE TITLE
How to filter spam (global filters)

### ISSUE THREAD

**Issue by bunyevacz** [nodemailer/wildduck#114]
Lately my users gets spammed from @qq.com, about one mail /1min speed. 
So I would like to filter messages on criteria globally  (ie. for all users). 

Where is the best place to filter emails?
Haraka is used for incoming mails and has an access plugin:
https://haraka.github.io/manual/plugins/access.html

I could create a backlist, by creating a 
mail_from.access.blacklist (block)
file.

OR I could patch wildduck to have global filters and put it somewhere here:
https://github.com/nodemailer/wildduck/blob/master/lib/filter-handler.js#L196

I'm wondering how to create global filters. 
a) I could create a user named filter, and create filters there, and check 
filters for both the actual user, and for "filter" user.
b) I could organize users into groups. Right now users have no group properties in mongo database.
And somehow create filters for the group.

The filter structure is a bit limited. Each filter is bonded to a specific user and a specific mailbox.

Any pointer/idea?

**Comment by andris9** [comment]
Currently the "correct" way would be to set global spam filters in Rspamd configuration so that these messages would be flagged as spam and stored in Junk and not in Inbox.

Global filters in WildDuck are currently not implemented because the system was built for an environment with several thousands clients who all have one or few domain names and some accounts, so there can't be anything global as all these clients are different.

**Comment by bunyevacz** [comment]
I would like to delete the emails without traces (Junk folder), because the rate is unbearable (43-60 000 email/month). 
Just too much noise in the Junk folder. It  would prevent user to search legitimate email (wrongly categorized) in the Junk folder.

Right now I made filter for *each* user in wildduck database (mongodb->wildduck->filters).
(from: qq.com, action: delete).

I'm not really convinced it's rspamd's job to deny complete domain. 

I updated the wiki with my workaround (delete emails which already in the system):
https://github.com/nodemailer/wildduck/wiki/Administrating-wildduck-via-command-line

**Comment by andris9** [comment]
One option would be to add a lot of spam points in rspamd for blacklisted domains and then configure Haraka rspamd plugin to reject messages with too high spam score

**Comment by bunyevacz** [comment]
Just an update on the issue.

The real solution was to reject sender from known spam domains (eg. qq.com, 168.com, yahoo.cn) right in haraka. So it just close the connection. The message does not get queued. 

For other spam filtering I do use rspamd and its scores. My current approach to punish emails without spf/dkim/dmarc, and use a whitelist file for exceptions (known domains which has no or bogus dmarc settings)

But there are one kind of spam, which is really hard to get filtered, namely when the `from:` and `to:` matches. And the email looks like it is sent by the user himself. 
And it is hard because of google's "send as" feature. It only attach `X-Google-DKIM-Signature` with domain `1e100.net`, so I should somehow teach haraka to accept `@mydomain.com` from 
- LAN ip address (coworkers send emails to each other)
- from sendgrid's dedicated ip (we do use sendgrid for reports)
- from our own public ip
- *and* if message is signed by `1e100.net` with x-google-dkim-signature field.

The other kind of spam, where the sender's name is the recipient email address, like this:
`user@mydomain.com <info@quomodocunquize.co>` 
It is especially bad, because both MS Outlook and wildduck webmail hides the real email address, and shows the name part only. So the user only see `user@mydomain.com`.
