### ISSUE TITLE
Unable to receive mail on iOS

### ISSUE THREAD

**Issue by DiederikvandenB** [nodemailer/wildduck#115]
Hi,

Recently, I did an `apt-get update` on our email server. Not long after, we started having problems fetching email through a secure IMAP connection on our iOS devices. Our Mac OS Mail clients however seem to be working fine.

Checking the logs of the server, we see `Inflate error`'s occur whenever a mobile connection happens. I dove in to the code and I outputted the entire error, instead of just the message:

https://github.com/nodemailer/wildduck/blob/1a7a7545220c471b105f68653b5983ba7030ba85/imap-core/lib/commands/compress.js#L58-L70

and that gives me this:

```
Jan  8 19:13:06 ip-172-31-9-149 wildduck-server[2052]: sill IMAP [zho5vzyjysjdeh5w] Removed journal listener from 5b86a51713ae840f1f4820f5 (joe@domain.tld)
Jan  8 19:13:06 ip-172-31-9-149 wildduck-server[2052]: info IMAP [zho5vzyjysjdeh5w] Connection closed to 5354DF81.cm-6-5d.dynamic.domain.tld
Jan  8 19:13:06 ip-172-31-9-149 wildduck-server[2052]: sill IMAP Error: unexpected end of file
Jan  8 19:13:06 ip-172-31-9-149 wildduck-server[2052]: sill IMAP     at Zlib.zlibOnError [as onerror] (zlib.js:154:17)
Jan  8 19:13:06 ip-172-31-9-149 wildduck-server[2052]: sill IMAP  [%s] Inflate error %s zho5vzyjysjdeh5w { Error: unexpected end of file
Jan  8 19:13:06 ip-172-31-9-149 wildduck-server[2052]: sill IMAP     at Zlib.zlibOnError [as onerror] (zlib.js:154:17)
Jan  8 19:13:06 ip-172-31-9-149 wildduck-server[2052]: sill IMAP   stack:
Jan  8 19:13:06 ip-172-31-9-149 wildduck-server[2052]: sill IMAP    'Error: unexpected end of file\n    at Zlib.zlibOnError [as onerror] (zlib.js:154:17)',
Jan  8 19:13:06 ip-172-31-9-149 wildduck-server[2052]: sill IMAP   errno: -5,
Jan  8 19:13:06 ip-172-31-9-149 wildduck-server[2052]: sill IMAP   code: 'Z_BUF_ERROR' }
```

That's as far as I got debugging. Now I'm stuck... Any thoughts/ideas?

**Comment by andris9** [comment]
I pushed out new version of WIldDuck where compression is disabled by default. Could you try if this fixes your issue?

**Comment by DiederikvandenB** [comment]
Right, this did resolve the issue for us, but it leaves me with a few questions:

- Is/will it become a problem to have compression disabled and will this be a permanent solution? I guess compression was enabled by default with a reason. 
- Do you know why this issue is specific to iOS only?

**Comment by andris9** [comment]
At this point I do not know the reason for the errors. I have seen the same "unexpected  end of file" errors as well, so it seemed best to disable compression for now. Compression in IMAP is something that may be implemented but is not required. It mostly useful when listing metadata of large batch of messages, not so much for listing message contents as base64 encoded large attachments usually do not gain much from compression. IMAP compression is not even too widely supported, it is most often used with Gmail but not with other providers.
