### ISSUE TITLE
webmail sending message fails

### ISSUE THREAD

**Issue by fmax** [nodemailer/wildduck#122]
i'm just running https://github.com/nodemailer/wildduck/releases/tag/v1.17.1
in webmail when pushing botton i get following error:
'child "from" fails because [child "name" fails because ["name" must be a string]]'

sending an email via API with curl is working - also when using thunderbird as email client, emails can get sent.

what i found out:
- /opt/wildduck/node_modules/joi/lib/language.js - is the file where the error message comes from.

- the logfile only shows a 200 http status code when POST request got received:
> http API 10.0.0.95 5ca5e873e1884b00225ca7fb [-/-] POST /users/5ca5e873e1884b00225ca7fb/submit 200 21ms
> http API 10.0.0.95 5ca5e873e1884b00225ca7fb [-/-] GET /users/5ca5e873e1884b00225ca7fb/mailboxes?counters=true 200 18ms

- browser developer tool shows me following parameter - 'from' seems to be a string: 
> Content-Disposition: form-data; name="from"
> 5ca5e873e1884b00225ca801

so what's going wrong here?
maybe i missed some config options in one of the config files.

**Comment by fmax** [comment]
i  was able to solve the problem:
when creating the users via API, i didn't set `name` because as read in API documentation the field isn't required.
i updated users setting `name` attribute and sending email via webmail is working.

**Comment by andris9** [comment]
getting errors from API is a bug

**Comment by andris9** [comment]
fixed in latest commit of wildduck-webmail

**Comment by fmax** [comment]
whow - thank's for that fast response and fix!
great work!
