### ISSUE TITLE
API create user - `name` must be required

### ISSUE THREAD

**Issue by fmax** [nodemailer/wildduck#123]
as shown in API documentation: https://api.wildduck.email/#api-Users-PostUser

> name optional | String | Name of the User
 
but `name` should be a required field, because if not so, you won't be able to send an email via webmail => https://github.com/nodemailer/wildduck/issues/122

so either set `name` as required attribute or fix the error in webmail, if `name` is `null` then use `from` email address as `name`

**Comment by andris9** [comment]
I'd say it's the webmail that has a bug, not API.
