### ISSUE TITLE
Suggest improvement 

### ISSUE THREAD

**Issue by mhf-ir** [nodemailer/wildduck#124]
I think the ui part of application must be as separate project.

1. Server distribute Docker image (HTTP(S), IMAP, POP3, SMTP), using fastify https://github.com/fastify/fastify as rest api server with json-schema builtin also auto generation of routes with https://gitlab.com/m03geek/fastify-oas (Open API 2/3 Swagger UI). The UI team knows how to intract.
2. Separate UI as distribute Docker another project (SPA). better to be use Vue with Vuetify (https://github.com/vuetifyjs/vuetify) [Native i18n support, RTL suport, zero dependency and etc ]. Publish as Docker image.
3. Test unit / coverate / security / dependency outdate / badges.
4. Linter, standardjs or even better eslint-airbnb
5. Even better to separate packages like imap and pop3 to another npm packages (there is no good alternatives) to test it as standalone packages even may be some one use out of wildduck.
6. Reduce dependency is good point.
7. Using Sentry as optional dependency for error reporting in your demo server or our infra testing stage i think will be good https://github.com/getsentry/sentry-javascript/tree/master/packages/node or in webui https://github.com/getsentry/sentry-javascript/tree/master/packages/browser
8. Metrics **not log** output for service like (smtp,imap,pop3 or etc) connections to telegraf or Prometheus exporter .
9. Swarm and Kubernate guide
10. backup and restore guide

You project is awesome. many dependency and legacy workflow like postfix glusterfs or cepth implementation is too hard, You offer best solution.

Thanks

**Comment by andris9** [comment]
Thanks! I see WildDuck as lower level primitive that can be used to build on top. I do not have any plans for general admin UI for WildDuck, at least for now. Instead I've been improving the API so WildDuck could be more easily integrated with existing custom management systems.

All code is already eslinted / prettified.

IMAP and POP3 as separate packages do not make much sense as these are so much integrated with the database backend. POP3 is a trivial protocol and could be extracted but there is a reason why there aren't any general IMAP layers (with the exception of Apache James) to build upon - everything related to IMAP is heavily coupled to the stored data.

Metrics can be improved, I agree. We use Graylog and it is able to aggregate all the info we need based on the GELF output from WildDuck.

Backing up and restoring large MongoDB clusters is out of scope for WildDuck. In general I'd suggest using Percona MongoDB as it has [hot backup](https://www.percona.com/doc/percona-server-for-mongodb/LATEST/hot-backup.html).

For testing you are welcomed to contribute. See [test](test) and [imap-core/test](https://github.com/nodemailer/wildduck/tree/master/imap-core/test) for existing test system.
