### ISSUE TITLE
About upload file and download file api

### ISSUE THREAD

**Issue by jet10000** [nodemailer/wildduck#125]
Upload a file via API and return the file ID, how to get the file name when download the file through API?

Write an e-mail, upload attachments first, and get the file ID, how can it be merged into an email when it is send?

**Comment by andris9** [comment]
You can link uploaded attachments with an [uploaded draft message](https://api.wildduck.email/#api-Messages-UploadMessage) using `files` property. When requesting [draft information](https://api.wildduck.email/#api-Messages-GetMessage) to edit the message, then you get the linked attachments also in the `files` array. When submitting [draft for delivery](https://api.wildduck.email/#api-Messages-SubmitStoredMessage), use  `deleteFiles` property to clean up linked attachments from the file storage.
