### ISSUE TITLE
Unable to send Email | Setup Was Successfull

### ISSUE THREAD

**Issue by zafeer-birde** [nodemailer/wildduck#126]
With the latest build the setup was successful , **but outbound emails are only getting** 
> 
queue for delivery
> 
. Inbound emails are working well.

1. What could the SMTP issue be ?
2. How does one enable the graylog logs to be able to see the issue above during setup.By default logging has been disabled ?

<img width="372" alt="Screenshot 2019-05-04 at 4 36 22 AM" src="https://user-images.githubusercontent.com/48515877/57169743-36e06900-6e26-11e9-83f3-ea8d2715b23c.png">

**Comment by zafeer-birde** [comment]
Forgot to set the PTR record.

**Comment by Loganrose** [comment]
How did you setup the PTR record
