### ISSUE TITLE
How to setup No-SPOF Architecture

### ISSUE THREAD

**Issue by indrawp** [nodemailer/wildduck#128]
Not an issue, but I just started learning about developing mail server and this git is genius!
I'm really interested in No-SPOF Architecture. I understand that it needs a lot of servers to try this, that's why I haven't tried, but I'm really curious.

So, for the Redis Sentinel, it needs a minimum of 3 servers (1 master, 2 slaves for quorum), and 3 types of mongo deployment (mongos router, configs, and shards), but how about the Wildduck Installation? If they were to be deployed to 3 different servers, are they all consist of the whole package of SMTP (Haraka & ZoneMTA) + IMAP (Wildduck) + Webmail? or is it just the SMTP & IMAP?

**Comment by andris9** [comment]
Haraka and ZoneMTA can run in separate machines

WildDuck can be configured to serve IMAP, POP3 and API in a single instance or create separates instances for each of these services (in that case code would be the same but configuration would be different)

**Comment by jadsolucions** [comment]
Wildduck webmail can connect to a redis sentinel setup?

**Comment by andris9** [comment]
@jadsolucions yes, webmail uses the same redis configuration as WildDuck itself. You do not have to use the same Redis server though as webmail should only need it to store web server sessions
