### ISSUE TITLE
impossible to install

### ISSUE THREAD

**Issue by lug-email** [nodemailer/wildduck#129]
Hello,
I try to install your work but it's impossible to install on ubuntu 16.04. Service wildduck not found, redis not found, npm not installed, nodejs not fully installed...
Could you have a installer for the lastest ubuntu or debian ?
Thank you

**Comment by rqelibari** [comment]
Hello @lug-email,

That is weird indeed. There should be no reason for the scripts not to work on Ubuntu 16.04.

A few questions:
- Have you resolved your problem by now? If not:
   - Was the Ubuntu on your server a fresh install?
   - Did you see any output when you ran the installation script?

**Comment by jadsolucions** [comment]
Debian 9.9 Fresh install output (some repositories problem):

root@email:/home/admin# ./install.sh mydomain.com email.mydomain.com
DOMAINNAME: mydomain.com, HOSTNAME: email.mydomain.com

-- Executing 01_install_commits.sh subscript --

-- Executing 02_install_prerequisites.sh subscript --
Checking lsof
Checking ps


-- Executing 03_install_check_running_services.sh subscript --
Checking programs listening on port 25,587,993,995,80,443
OK: port 25 (SMTP) is free
OK: port 587 (SMTP TLS) is free
OK: port 993 (IMAP SSL/TLS) is free
OK: port 995 (POP3 SSL/TLS) is free
OK: port 80 (HTTP) is free
OK: port 443 (HTTPS) is free

-- Executing 04_install_import_keys.sh subscript --
useradd: user 'wildduck' already exists
User wildduck already exists
useradd: user 'deploy' already exists
User deploy already exists
OK
OK
--2019-07-03 07:57:34--  https://rspamd.com/apt-stable/gpg.key
Resolving rspamd.com (rspamd.com)... 88.99.142.95
Connecting to rspamd.com (rspamd.com)|88.99.142.95|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3122 (3.0K) [text/plain]
Saving to: ‘STDOUT’

-                        100%[================================>]   3.05K  --.-KB/s    in 0s

2019-07-03 07:57:34 (274 MB/s) - written to stdout [3122/3122]

OK
Ign:1 http://repo.mongodb.org/apt/ubuntu stretch/mongodb-org/4.0 InRelease
Ign:2 http://repo.mongodb.org/apt/ubuntu stretch/mongodb-org/4.0 Release
Ign:3 http://cdn-aws.deb.debian.org/debian stretch InRelease
Ign:4 http://repo.mongodb.org/apt/ubuntu stretch/mongodb-org/4.0/multiverse all Packages
Hit:5 http://cdn-aws.deb.debian.org/debian stretch-updates InRelease
Ign:6 http://repo.mongodb.org/apt/ubuntu stretch/mongodb-org/4.0/multiverse amd64 Packages
Ign:7 http://repo.mongodb.org/apt/ubuntu stretch/mongodb-org/4.0/multiverse Translation-en
Ign:8 http://repo.mongodb.org/apt/ubuntu stretch/mongodb-org/4.0/multiverse Translation-en_US
Hit:9 http://security.debian.org/debian-security stretch/updates InRelease
Hit:10 http://cdn-aws.deb.debian.org/debian stretch Release
Ign:4 http://repo.mongodb.org/apt/ubuntu stretch/mongodb-org/4.0/multiverse all Packages
Ign:6 http://repo.mongodb.org/apt/ubuntu stretch/mongodb-org/4.0/multiverse amd64 Packages
Hit:11 http://rspamd.com/apt-stable stretch InRelease
Ign:7 http://repo.mongodb.org/apt/ubuntu stretch/mongodb-org/4.0/multiverse Translation-en
Ign:8 http://repo.mongodb.org/apt/ubuntu stretch/mongodb-org/4.0/multiverse Translation-en_US
Ign:4 http://repo.mongodb.org/apt/ubuntu stretch/mongodb-org/4.0/multiverse all Packages
Ign:6 http://repo.mongodb.org/apt/ubuntu stretch/mongodb-org/4.0/multiverse amd64 Packages
Ign:7 http://repo.mongodb.org/apt/ubuntu stretch/mongodb-org/4.0/multiverse Translation-en
Ign:8 http://repo.mongodb.org/apt/ubuntu stretch/mongodb-org/4.0/multiverse Translation-en_US
Ign:4 http://repo.mongodb.org/apt/ubuntu stretch/mongodb-org/4.0/multiverse all Packages
Ign:6 http://repo.mongodb.org/apt/ubuntu stretch/mongodb-org/4.0/multiverse amd64 Packages
Ign:7 http://repo.mongodb.org/apt/ubuntu stretch/mongodb-org/4.0/multiverse Translation-en
Ign:8 http://repo.mongodb.org/apt/ubuntu stretch/mongodb-org/4.0/multiverse Translation-en_US
Ign:4 http://repo.mongodb.org/apt/ubuntu stretch/mongodb-org/4.0/multiverse all Packages
Ign:6 http://repo.mongodb.org/apt/ubuntu stretch/mongodb-org/4.0/multiverse amd64 Packages
Ign:7 http://repo.mongodb.org/apt/ubuntu stretch/mongodb-org/4.0/multiverse Translation-en
Ign:8 http://repo.mongodb.org/apt/ubuntu stretch/mongodb-org/4.0/multiverse Translation-en_US
Ign:4 http://repo.mongodb.org/apt/ubuntu stretch/mongodb-org/4.0/multiverse all Packages
Err:6 http://repo.mongodb.org/apt/ubuntu stretch/mongodb-org/4.0/multiverse amd64 Packages
  404  Not Found
Ign:7 http://repo.mongodb.org/apt/ubuntu stretch/mongodb-org/4.0/multiverse Translation-en
Ign:8 http://repo.mongodb.org/apt/ubuntu stretch/mongodb-org/4.0/multiverse Translation-en_US
Hit:12 https://deb.nodesource.com/node_10.x stretch InRelease
Reading package lists... Done
W: The repository 'http://repo.mongodb.org/apt/ubuntu stretch/mongodb-org/4.0 Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://repo.mongodb.org/apt/ubuntu/dists/stretch/mongodb-org/4.0/multiverse/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
/home/admin/04_install_import_keys.sh: line 40: apt-add-repository: command not found

-- Executing 05_install_packages.sh subscript --
Ign:1 http://repo.mongodb.org/apt/ubuntu stretch/mongodb-org/4.0 InRelease
Ign:2 http://repo.mongodb.org/apt/ubuntu stretch/mongodb-org/4.0 Release
Ign:3 http://repo.mongodb.org/apt/ubuntu stretch/mongodb-org/4.0/multiverse amd64 Packages
Ign:4 http://repo.mongodb.org/apt/ubuntu stretch/mongodb-org/4.0/multiverse all Packages
Ign:5 http://cdn-aws.deb.debian.org/debian stretch InRelease
Ign:6 http://repo.mongodb.org/apt/ubuntu stretch/mongodb-org/4.0/multiverse Translation-en
Hit:7 http://cdn-aws.deb.debian.org/debian stretch-updates InRelease
Hit:8 http://security.debian.org/debian-security stretch/updates InRelease
Ign:9 http://repo.mongodb.org/apt/ubuntu stretch/mongodb-org/4.0/multiverse Translation-en_US
Ign:3 http://repo.mongodb.org/apt/ubuntu stretch/mongodb-org/4.0/multiverse amd64 Packages
Ign:4 http://repo.mongodb.org/apt/ubuntu stretch/mongodb-org/4.0/multiverse all Packages
Hit:10 http://cdn-aws.deb.debian.org/debian stretch Release
Ign:6 http://repo.mongodb.org/apt/ubuntu stretch/mongodb-org/4.0/multiverse Translation-en
Ign:9 http://repo.mongodb.org/apt/ubuntu stretch/mongodb-org/4.0/multiverse Translation-en_US
Hit:11 http://rspamd.com/apt-stable stretch InRelease
Ign:3 http://repo.mongodb.org/apt/ubuntu stretch/mongodb-org/4.0/multiverse amd64 Packages
Ign:4 http://repo.mongodb.org/apt/ubuntu stretch/mongodb-org/4.0/multiverse all Packages
Ign:6 http://repo.mongodb.org/apt/ubuntu stretch/mongodb-org/4.0/multiverse Translation-en
Ign:9 http://repo.mongodb.org/apt/ubuntu stretch/mongodb-org/4.0/multiverse Translation-en_US
Ign:3 http://repo.mongodb.org/apt/ubuntu stretch/mongodb-org/4.0/multiverse amd64 Packages
Ign:4 http://repo.mongodb.org/apt/ubuntu stretch/mongodb-org/4.0/multiverse all Packages
Ign:6 http://repo.mongodb.org/apt/ubuntu stretch/mongodb-org/4.0/multiverse Translation-en
Ign:9 http://repo.mongodb.org/apt/ubuntu stretch/mongodb-org/4.0/multiverse Translation-en_US
Ign:3 http://repo.mongodb.org/apt/ubuntu stretch/mongodb-org/4.0/multiverse amd64 Packages
Ign:4 http://repo.mongodb.org/apt/ubuntu stretch/mongodb-org/4.0/multiverse all Packages
Ign:6 http://repo.mongodb.org/apt/ubuntu stretch/mongodb-org/4.0/multiverse Translation-en
Ign:9 http://repo.mongodb.org/apt/ubuntu stretch/mongodb-org/4.0/multiverse Translation-en_US
Err:3 http://repo.mongodb.org/apt/ubuntu stretch/mongodb-org/4.0/multiverse amd64 Packages
  404  Not Found
Ign:4 http://repo.mongodb.org/apt/ubuntu stretch/mongodb-org/4.0/multiverse all Packages
Ign:6 http://repo.mongodb.org/apt/ubuntu stretch/mongodb-org/4.0/multiverse Translation-en
Ign:9 http://repo.mongodb.org/apt/ubuntu stretch/mongodb-org/4.0/multiverse Translation-en_US
Hit:12 https://deb.nodesource.com/node_10.x stretch InRelease
Reading package lists... Done
W: The repository 'http://repo.mongodb.org/apt/ubuntu stretch/mongodb-org/4.0 Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://repo.mongodb.org/apt/ubuntu/dists/stretch/mongodb-org/4.0/multiverse/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package mongodb-org
Reading package lists...
Building dependency tree...
Reading state information...
rspamd is already the newest version (1.9.4-1~stretch).
0 upgraded, 0 newly installed, 0 to remove and 12 not upgraded.

-- Executing 06_install_enable_services.sh subscript --
/home/admin/06_install_enable_services.sh: line 10: pwgen: command not found
/home/admin/06_install_enable_services.sh: line 11: pwgen: command not found
/home/admin/06_install_enable_services.sh: line 12: pwgen: command not found
/home/admin/06_install_enable_services.sh: line 13: -e: command not found
Failed to enable unit: File mongod.service: No such file or directory

-- These are the installed and required programs:
/home/admin/06_install_enable_services.sh: line 18: node: command not found
/home/admin/06_install_enable_services.sh: line 19: redis-server: command not found
/home/admin/06_install_enable_services.sh: line 20: mongod: command not found
HOSTNAME: email.mydomain.com
-- Installing npm globally (workaround)
/home/admin/06_install_enable_services.sh: line 25: npm: command not found

-- Executing 06_install_wildduck.sh subscript --
Failed to stop wildduck.service: Unit wildduck.service not loaded.
Removed /etc/systemd/system/multi-user.target.wants/wildduck.service.
/home/admin/07_install_wildduck.sh: line 22: git: command not found
/home/admin/00_install_global_functions_variables.sh: line 240: /var/opt/wildduck.git/hooks/update: No such file or directory
chmod: cannot access '/var/opt/wildduck.git/hooks/update': No such file or directory
/home/admin/07_install_wildduck.sh: line 32: git: command not found
cp: cannot stat '/opt/wildduck/config': No such file or directory
mv: cannot stat '/etc/wildduck/default.toml': No such file or directory
sed: can't read /opt/wildduck/emails/00-example.json: No such file or directory
sed: can't read /etc/wildduck/imap.toml: No such file or directory
sed: can't read /etc/wildduck/pop3.toml: No such file or directory
/home/admin/07_install_wildduck.sh: line 45: /etc/wildduck/lmtp.toml: No such file or directory
cat: /etc/wildduck/wildduck.toml: No such file or directory
sed: can't read /etc/wildduck/wildduck.toml: No such file or directory
/home/admin/07_install_wildduck.sh: line 58: npm: command not found
chown: cannot access '/var/opt/wildduck.git': No such file or directory
Created symlink /etc/systemd/system/multi-user.target.wants/wildduck.service → /etc/systemd/system/wildduck.service.

-- Executing 08_install_haraka.sh subscript --
Removed /etc/systemd/system/multi-user.target.wants/haraka.service.
/home/admin/08_install_haraka.sh: line 23: git: command not found
/home/admin/08_install_haraka.sh: line 29: /var/opt/haraka-plugin-wildduck.git/hooks/update: No such file or directory
chmod: cannot access '/var/opt/haraka-plugin-wildduck.git/hooks/update': No such file or directory
/home/admin/08_install_haraka.sh: line 36: npm: command not found
/home/admin/08_install_haraka.sh: line 37: haraka: command not found
/home/admin/08_install_haraka.sh: line 38: cd: /opt/haraka: No such file or directory
/home/admin/08_install_haraka.sh: line 39: npm: command not found
/home/admin/08_install_haraka.sh: line 43: git: command not found
/home/admin/08_install_haraka.sh: line 46: npm: command not found
/home/admin/08_install_haraka.sh: line 48: cd: /opt/haraka: No such file or directory
mv: cannot stat 'config/plugins': No such file or directory
/home/admin/08_install_haraka.sh: line 51: config/databytes: No such file or directory
/home/admin/08_install_haraka.sh: line 52: config/me: No such file or directory
/home/admin/08_install_haraka.sh: line 53: config/smtpgreeting: No such file or directory
/home/admin/08_install_haraka.sh: line 67: config/plugins: No such file or directory
/home/admin/08_install_haraka.sh: line 70: config/tls.ini: No such file or directory
/home/admin/08_install_haraka.sh: line 94: config/rspamd.ini: No such file or directory
/home/admin/08_install_haraka.sh: line 99: config/clamd.ini: No such file or directory
cp: cannot stat 'plugins/wildduck/config/wildduck.yaml': No such file or directory
sed: can't read config/wildduck.yaml: No such file or directory
/home/admin/08_install_haraka.sh: line 120: config/smtp.ini: No such file or directory
chown: cannot access '/opt/haraka': No such file or directory
chown: cannot access '/var/opt/haraka-plugin-wildduck.git': No such file or directory
Created symlink /etc/systemd/system/multi-user.target.wants/haraka.service → /etc/systemd/system/haraka.service.

-- Executing 08_install_zone_mta.sh subscript --
Removed /etc/systemd/system/multi-user.target.wants/zone-mta.service.
/home/admin/09_install_zone_mta.sh: line 24: git: command not found
/home/admin/09_install_zone_mta.sh: line 25: git: command not found
/home/admin/00_install_global_functions_variables.sh: line 240: /var/opt/zone-mta.git/hooks/update: No such file or directory
chmod: cannot access '/var/opt/zone-mta.git/hooks/update': No such file or directory
/home/admin/09_install_zone_mta.sh: line 34: /var/opt/zonemta-wildduck.git/hooks/update: No such file or directory
chmod: cannot access '/var/opt/zonemta-wildduck.git/hooks/update': No such file or directory
/home/admin/09_install_zone_mta.sh: line 42: git: command not found
/home/admin/09_install_zone_mta.sh: line 45: git: command not found
cp: cannot stat '/opt/zone-mta/config': No such file or directory
sed: can't read /etc/zone-mta/interfaces/feeder.toml: No such file or directory
/home/admin/09_install_zone_mta.sh: line 50: /etc/zone-mta/dbs-production.toml: No such file or directory
cat: /etc/zone-mta/zonemta.toml: No such file or directory
/home/admin/09_install_zone_mta.sh: line 56: /etc/zone-mta/pools.toml: No such file or directory
/home/admin/09_install_zone_mta.sh: line 61: /etc/zone-mta/plugins/loop-breaker.toml: No such file or directory
/home/admin/09_install_zone_mta.sh: line 89: /etc/zone-mta/plugins/wildduck.toml: No such file or directory
/home/admin/09_install_zone_mta.sh: line 91: cd: /opt/zone-mta/keys: No such file or directory
Generating RSA private key, 1024 bit long modulus
....+++++
......................+++++
e is 65537 (0x010001)
writing RSA key
/home/admin/09_install_zone_mta.sh: line 103: node: command not found
/home/admin/09_install_zone_mta.sh: line 106: npm: command not found
/home/admin/09_install_zone_mta.sh: line 109: npm: command not found
chown: cannot access '/var/opt/zone-mta.git': No such file or directory
chown: cannot access '/var/opt/zonemta-wildduck.git': No such file or directory
Created symlink /etc/systemd/system/multi-user.target.wants/zone-mta.service → /etc/systemd/system/zone-mta.service.

-- Executing 10_install_wildduck_webmail.sh subscript --
Removed /etc/systemd/system/multi-user.target.wants/wildduck-webmail.service.
/home/admin/10_install_wildduck_webmail.sh: line 21: git: command not found
/home/admin/00_install_global_functions_variables.sh: line 252: /var/opt/wildduck-webmail.git/hooks/update: No such file or directory
chmod: cannot access '/var/opt/wildduck-webmail.git/hooks/update': No such file or directory
chmod: cannot access '/var/opt/wildduck-webmail.git/hooks/update': No such file or directory
/home/admin/10_install_wildduck_webmail.sh: line 32: git: command not found
cp: cannot stat '/opt/wildduck-webmail/config/default.toml': No such file or directory
sed: can't read /etc/wildduck/wildduck-webmail.toml: No such file or directory
chown: cannot access '/var/opt/wildduck-webmail.git': No such file or directory
sudo: npm: command not found
sudo: npm: command not found
Created symlink /etc/systemd/system/multi-user.target.wants/wildduck-webmail.service → /etc/systemd/system/wildduck-webmail.service.

-- Executing 11_install_nginx.sh subscript --
Generating a RSA private key
...+++++
....................................................................................................................................................+++++
writing new private key to 'privkey.pem'
-----
/home/admin/11_install_nginx.sh: line 59: /etc/nginx/sites-available/email.mydomain.com: No such file or directory
ln: failed to create symbolic link '/etc/nginx/sites-enabled/email.mydomain.com': No such file or directory
Failed to reload nginx.service: Unit nginx.service not found.

-- Executing 12_install_ufw_rules.sh subscript --
Skipping adding existing rule
Skipping adding existing rule (v6)
Skipping adding existing rule
Skipping adding existing rule (v6)
Skipping adding existing rule
Skipping adding existing rule (v6)
Skipping adding existing rule
Skipping adding existing rule (v6)
Skipping adding existing rule
Skipping adding existing rule (v6)
Skipping adding existing rule
Skipping adding existing rule (v6)
Skipping adding existing rule
Skipping adding existing rule (v6)
Firewall is active and enabled on system startup

-- Executing 13_install_ssl_certs.sh subscript --
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   705    0   705    0     0   8016      0 --:--:-- --:--:-- --:--:--  8103
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  184k  100  184k    0     0  1395k      0 --:--:-- --:--:-- --:--:-- 1400k
[Wed Jul  3 07:57:39 UTC 2019] Installing from online archive.
[Wed Jul  3 07:57:39 UTC 2019] Downloading https://github.com/Neilpang/acme.sh/archive/master.tar.gz
[Wed Jul  3 07:57:40 UTC 2019] Extracting master.tar.gz
[Wed Jul  3 07:57:40 UTC 2019] It is recommended to install socat first.
[Wed Jul  3 07:57:40 UTC 2019] We use socat for standalone server if you use standalone mode.
[Wed Jul  3 07:57:40 UTC 2019] If you don't use standalone mode, just ignore this warning.
[Wed Jul  3 07:57:40 UTC 2019] Installing to /root/.acme.sh
[Wed Jul  3 07:57:40 UTC 2019] Installed to /root/.acme.sh/acme.sh
[Wed Jul  3 07:57:40 UTC 2019] Installing alias to '/root/.bashrc'
[Wed Jul  3 07:57:40 UTC 2019] OK, Close and reopen your terminal to start using acme.sh
[Wed Jul  3 07:57:40 UTC 2019] Installing cron job
56 0 * * * "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null
[Wed Jul  3 07:57:40 UTC 2019] Good, bash is found, so change the shebang to use bash as preferred.
[Wed Jul  3 07:57:40 UTC 2019] OK
[Wed Jul  3 07:57:40 UTC 2019] Install success!
sed: can't read /etc/zone-mta/interfaces/feeder.toml: No such file or directory
/home/admin/13_install_ssl_certs.sh: line 15: /etc/zone-mta/interfaces/feeder.toml: No such file or directory
[Wed Jul  3 07:57:41 UTC 2019] Single domain='email.mydomain.com'
[Wed Jul  3 07:57:41 UTC 2019] Getting domain auth token for each domain
[Wed Jul  3 07:57:42 UTC 2019] Create new order error. Le_OrderFinalize not found. {
  "type": "urn:ietf:params:acme:error:rateLimited",
  "detail": "Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/",
  "status": 429
}
[Wed Jul  3 07:57:42 UTC 2019] Please add '--debug' or '--log' to check more details.
[Wed Jul  3 07:57:42 UTC 2019] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
Warning: Failed to generate certificates, using self-signed certs
/home/admin/13_install_ssl_certs.sh: line 74: /etc/nginx/sites-available/email.mydomain.com: No such file or directory
Failed to start nginx.service: Unit nginx.service not found.
Failed to reload nginx.service: Unit nginx.service not found.

-- Executing 14_install_start_services.sh subscript --
Failed to start mongod.service: Unit mongod.service not found.
Failed to start wildduck.service: Unit wildduck.service is not loaded properly: Invalid argument.
See system logs and 'systemctl status wildduck.service' for details.
Failed to reload nginx.service: Unit nginx.service not found.

-- Executing 15_install_deploy.sh subscript --
Waiting for the server to start up......................................^C

**Comment by W2AlharbiMe** [comment]
i have the same problem and i got the following output:
scripts output:

```
-- Executing 14_install_start_services.sh subscript --
Failed to start wildduck.service: Unit wildduck.service is not loaded properly: Invalid argument.
See system logs and 'systemctl status wildduck.service' for details.
```

`$ systemctl status wildduck.service`

```
● wildduck.service - WildDuck Mail Server
   Loaded: error (Reason: Invalid argument)
   Active: inactive (dead)

Jul 22 23:56:38 localhost systemd[1]: [/etc/systemd/system/wildduck.service:9] Executable path is not absolute, ignoring: server.js --config="/etc/wildduck/wildduck.toml"
Jul 22 23:56:38 localhost systemd[1]: wildduck.service: Service lacks both ExecStart= and ExecStop= setting. Refusing.
Jul 22 23:56:38 localhost systemd[1]: [/etc/systemd/system/wildduck.service:9] Executable path is not absolute, ignoring: server.js --config="/etc/wildduck/wildduck.toml"
Jul 22 23:56:38 localhost systemd[1]: wildduck.service: Service lacks both ExecStart= and ExecStop= setting. Refusing.
Jul 22 23:56:39 localhost systemd[1]: [/etc/systemd/system/wildduck.service:9] Executable path is not absolute, ignoring: server.js --config="/etc/wildduck/wildduck.toml"
Jul 22 23:56:39 localhost systemd[1]: wildduck.service: Service lacks both ExecStart= and ExecStop= setting. Refusing.
Jul 22 23:56:39 localhost systemd[1]: [/etc/systemd/system/wildduck.service:9] Executable path is not absolute, ignoring: server.js --config="/etc/wildduck/wildduck.toml"
Jul 22 23:56:39 localhost systemd[1]: wildduck.service: Service lacks both ExecStart= and ExecStop= setting. Refusing.
Jul 22 23:56:41 localhost systemd[1]: [/etc/systemd/system/wildduck.service:9] Executable path is not absolute, ignoring: server.js --config="/etc/wildduck/wildduck.toml"
Jul 22 23:56:41 localhost systemd[1]: wildduck.service: Service lacks both ExecStart= and ExecStop= setting. Refusing.
```

**Comment by W2AlharbiMe** [comment]
I have fixed the issue and it was from node && npm i tried to install them manually and also before running the scripts i configured my dns:
add A record to point to your server
add mx record to point to the A record 
here's how to install node && npm on linux:
https://github.com/nodesource/distributions/blob/master/README.md
good luck.
@lug-email

**Comment by louis-lau** [comment]
Is still still an issue with the latest install script?
