### ISSUE TITLE
can I use it only for IMAP server

### ISSUE THREAD

**Issue by bibudha** [nodemailer/wildduck#13]
Hello

I have done the SMTP server with haraka and save mail data in mysql. But can not able send data to other IMAP mail clients. So can I do it using wildduck ?

**Comment by bibudha** [comment]
Ok thanks for the answer. Do you have any solution for my problem ?

**Comment by andris9** [comment]
No. You could try to fork Wild Duck and change it to use your own backend for storage but that's it.

**Comment by kishoreannapureddy** [comment]
Not meaning to re-open this issue, but @andris9 I have looked at hoodiecrow for wanting to use a scriptable IMAP server. How evolved is Wildduck's IMAP code compared to hoodiecrow or imapper (https://github.com/deitch/imapper)? Are they stable compared to Wildduck's IMAP implementation? If not, how easy is stripping out IMAP part of Wildduck and making it scriptable like hoodiecrow/imapper?
