### ISSUE TITLE
Need help with documentation?

### ISSUE THREAD

**Issue by mrleedev** [nodemailer/wildduck#132]
I set up a fresh instance over the weekend and it went more or less smoothly. I discovered one or two things along the way that weren't immediately obvious (or I missed it).

- `sudo` isn't enough, you've gotta be root when installing.
- A 512MB VPS will result in a stalled setup.

Not so bad, but the application config came across as mostly opaque to me and in some places did not look to be secure by default. There wasn't enough information for me to understand how to configure this securely so I gave up, particularly because I wanted to host email just for me and not multiple users.

I would gladly help provide documentation for this with some assistance and pointers in the right direction.

**Comment by andris9** [comment]
More documentation would be awesome! There is a publicly editable [Wiki](https://github.com/nodemailer/wildduck/wiki) with some content (that might be outdated), feel free to edit/add anything you like.

Regarding notes:

* `sudo` - I think it should be possible, at least in theory, to install everything using sudo. Current setup script does not allow this for some environment variables issue. I usually start up all test environments from a clean setup where there even might not be any other users that root, so I haven't felt the need for `sudo` so far and thus haven't fixed the setup script.
* 512MB VPS is too small for WildDuck as you would install all components into a single machine. In production environment you would install all components into separate machines (MongoDB cluster, Redis replica set, WildDuck IMAP daemon, ZoneMTA MSA, Haraka MX etc). This is different than, for example, Dovecot, where you have no need for a separate database daemon as everything is stored into file system etc. and thus you need less RAM.
* Secure setup. You're right, the setup script is not very secure at all. Installation is made somewhat secure by blocking database access via firewall and setting database daemons to only bind to local interface. This blocks any external clients. As there is not password set to MongoDB or Redis then somehow getting access to these services would also mean access to all email content. In production you should obviously use authentication and also separate roles for different database tasks.

**Comment by rakshith-ravi** [comment]
@leemachin Are you still interested in helping out with documentation? I'd be happy to assist you in documenting how the code is structured. That, along with some help from Andris should give us a good documentation for new comers to contribute to the project.

**Comment by louis-lau** [comment]
Documentation is now on https://docs.wildduck.email. If you want to contribute to the docs you can press the `Edit on github` link in the top right to edit and open a Pull Request.
