### ISSUE TITLE
Real time syncing between Maildir (Dovecot) and Wildduck?

### ISSUE THREAD

**Issue by duyhotan2000** [nodemailer/wildduck#135]
Hello,

After some experiments, I was very interesting in Wildduck ideas and solutions for e-mail.
I had a mail server with Dovecot and Postfix running. I want to try Wildduck but still want to keep my current server for stability. Do we have anyway to sync Maildir and Wildduck database in real time?

**Comment by andris9** [comment]
There is no way for syncing maildir and wildduck in real time. If you want to import your existing maildir account to WildDuck you can use [the importer tool](https://github.com/nodemailer/import-maildir).
