### ISSUE TITLE
Using email aliase doesn't work

### ISSUE THREAD

**Issue by jsdev2018** [nodemailer/wildduck#137]
I have created new identities

/account/identities

however it just says: " Failed to create address"

**Comment by jsdev2018** [comment]
Is this a Harakra plugin for alias?

**Comment by andris9** [comment]
WildDuck addresses are not related to Haraka. Haraka only passes all email address handling to WildDuck.

If you see "Failed to create address" then you should also see an explanation of the error next to address field. For example the web client can not create general purpose addresses like "admin@domain" or "postmaster@domain", these must be created directly by using WildDuck API
