### ISSUE TITLE
How to log files in graylog?

### ISSUE THREAD

**Issue by Weldeasy** [nodemailer/wildduck#138]
Hello, I have a working graylog server, inputs created and tested with TCP, UDP and HTTP methods. All working.

But when I config Wildduck to enable logging, nothing appears.

Also i can't figure it out how to configure Haraka and Zone-MTA to log in graylog with gelf.

This is the wildduck.toml:

[log]   
                                                                                                                                       level="info"
                                                                                                                                               skipFetchLog=false # if true, then does not output individual * FETCH responses to log

authlogExpireDays=30
                                                                                                                                               [log.gelf]                                                                                                                                     

enabled=true

hostname=false   
                                                                                                                          component="wildduck"

[log.gelf.options]

graylogPort=12202    
                                                                                                                      graylogHostname="localhost"

connection="lan"

THANK YOU!

**Comment by andris9** [comment]
The configuration seems correct. Check your Graylog Inputs setting if there is a corresponding "Gelf UDP" input defined and started:

<img width="835" alt="Screenshot 2019-07-12 at 11 31 06" src="https://user-images.githubusercontent.com/132242/61114257-9eefa300-a498-11e9-853e-2864108b9c1e.png">

**Comment by Weldeasy** [comment]
I've reconfigured all and now looks like it's working! I thing I was using Gelf TCP.

Thank you!
