### ISSUE TITLE
Timeout to mongodb on mailbox deletion 

### ISSUE THREAD

**Issue by vitalvas** [nodemailer/wildduck#148]
Hello,

I have a large mailbox. In mailbox have over 200k mails.
The task starts more than a week - no result.
Could you help with this issue?

![image](https://user-images.githubusercontent.com/571747/64552360-c8fdfe00-d33f-11e9-97fe-be0964c7028f.png)

**Comment by vitalvas** [comment]
I see logs - task retried after some time. But after some time - task was failed with errors in screenshot. This happened more than a week.

For now. I see - collection with tasks is empty. User is not available from API. Messages were not deleted from the collections.

**Comment by andris9** [comment]
I think I understand what's the problem. There was a `updateMany()` command against MongoDB that tried to update all messages of a user at once. As there were so many messages then the command took so much time that connection timeout options kicked in.

I changed the user delete task to modify messages not at once but in batches of 2000.

By the way could you check if the not deleted messages in your database have `userDeleted` set to `true` or not? The delete task does not actually delete messages but mark these as expired (so it would be possible to recover if user was deleted accidentally). Actual deletion date is 2 weeks (assuming that `userDeleted` is `true`).

**Comment by vitalvas** [comment]
I checked - all user messages have `'userDeleted ': true`

**Comment by andris9** [comment]
I guess what happened was that `updateMany` only updated a subset of the messages and this continued by the retrying task until all messages were updated. Actual deletion happens on `rdate` value. The new version handles this better by updating messages in smaller batches and thus the connection should not timeout but it still does the exact same thing - just marks the messages for deletion in some future date.
