### ISSUE TITLE
Debian 10 support?

### ISSUE THREAD

**Issue by blackyzero** [nodemailer/wildduck#150]
Hello,

Thanks for great product.
Could you please make Wildduck support Debian 10?

Thanks a lot.

**Comment by louis-lau** [comment]
You can run Haraka, WildDuck, ZoneMTA on anything that supports nodejs.

**Comment by andris9** [comment]
WildDuck should run fine on any platform, including Debian, Windows, OSX etc. There are currently no plans to update the install script to get it working automatically on all these platforms as it is provided mostly for demo purposes. Install script is tested on Ubuntu 16.04 and Ubuntu 18.04 so getting it also running on Debian should be pretty easy (the only thing I can think of is the custom Redis PPA which may work only on Ubuntu but you can replace it by installing Redis manually yourself).

**Comment by blackyzero** [comment]
ok. got it. let me try on it.
thanks
