### ISSUE TITLE
After fresh install, questions?

### ISSUE THREAD

**Issue by blackyzero** [nodemailer/wildduck#151]
Hello,

Thanks for great product.

I have installed Wildduck on Ubuntu 18.04, it goes well. I can send and receive emails. There are few questions i would need your help.

1) How could i limit the public registration? As for now, user just goes to the URL or IP of Wildduck server, and able to create an account (same as demo page).

2) Is there any admin account (gui) which is used to manage all email accounts instead of using API from console? This would help me IT guy to manage to create new user account.

3) How could i add other domains (multi domain on same server)?
Ex: "abc1.com" which was used for installation (install script) for default domain 1.
"xyz2.com" is domain 2.
"domain3.com" is domain 3.

Thanks again.

**Comment by louis-lau** [comment]
1. In `/etc/wildduck/wildduck-webmail.toml` set `allowJoin=false`
1. Not as far as I'm aware. I'm currently building one, will let you know when it's finished.
1. WildDuck doesn't care about domains, Using the api you can add whatever you want. If you want to make the domain available in WildDuck webmail you can edit the domains array in `/etc/wildduck/wildduck-webmail.toml`

**Comment by blackyzero** [comment]
Thanks a lot, Louis!

1. Got it.

2. It's great to have this feature available on GUI control panel along with other features ex: spam, DKIM, forward, filter, ... for each domain and mail service monitoring status.

3. That's really good to hear it's possible. How about DKIM configuration?

Thank you.

**Comment by louis-lau** [comment]
That's the plan for the control panel! Currently you can configure DKIM using the API:
https://api.wildduck.email/#api-DKIM

**Comment by blackyzero** [comment]
thanks @louis-lau for this info, hope it will be released soon.

Regarding to 1. (disable web registration). It still doesn't work for me.
After changing "allowJoin=false"  in "/etc/wildduck/wildduck-webmail.to", i am still able to create new account using Wildduck web. Do i need to execute any command to take effect for this change?

Thank you.

**Comment by blackyzero** [comment]
i got it works, after restart the service wildduck.
I will test with multi domains soon

**Comment by imtiyaz-ideavate** [comment]
Hello @louis-lau, @blackyzero 

could you please help me to configure SMTP(zone-mta) over SSL? I run below command to test SMTP over SSL.

openssl s_client -showcerts -connect mail.example.com:465

but got below error.

140176357999040:error:0200206F:system library:connect:Connection refused:../crypto/bio/b_sock2.c:110:

140176357999040:error:2008A067:BIO routines:BIO_connect:connect error:../crypto/bio/b_sock2.c:111:
connect:errno=111

**Comment by andris9** [comment]
@imtiyaz-ideavate  ZoneMTA by default is only listening on port 587 using STARTTLS, so the command you would have to use would be:

```
$ openssl s_client -showcerts -starttls smtp -crlf -connect mail.example.com:587
```

**Comment by ukwuezeobinna** [comment]
> i got it works, after restart the service wildduck. I will test with multi domains soon

what command restarts wildduck and zone-mta and from what directory should this be run?

**Comment by louis-lau** [comment]
They are systems services. You can manage them with systemctl:

https://www.digitalocean.com/community/tutorials/how-to-use-systemctl-to-manage-systemd-services-and-units
