### ISSUE TITLE
Best way to update to latest version?

### ISSUE THREAD

**Issue by blackyzero** [nodemailer/wildduck#152]
Hello team,

What would be the best way to update to latest version?
Thank you.

**Comment by andris9** [comment]
Currently the only upgrade mechanism is by using Git.

```
$ git pull
$ npm install --production
$ systemctl restart wildduck
```

Most probably there will be system packages in the future, no estimate on that though.

**Comment by blackyzero** [comment]
thanks for your comment. But i am still not able to  make it works, cause i used installation script,
https://github.com/nodemailer/wildduck/tree/master/setup

Each service is located in folder /opt, and there is not able to use git to update.

**Comment by andris9** [comment]
The upgrade is a bit complicated but doable. In the server, in root home directory you should have a file that contains DNS information (DKIM, SPF etc) and it also contains information about upgrade locations. Basically you would have to set up local git repositories, pull changes from Github and then push to your server as git remote destination.

1. In your server add your ssh public key to `/home/deploy/.ssh/authorized_keys`

2. In your own machine, clone wildduck repository

```
$ git clone git@github.com:nodemailer/wildduck.git
$ cd wildduck
```

3. Register your server as remote repo (change `yourserver.com` with your actual server name, keep the user as `deploy`)

```
$ git remote add production deploy@yourserver.com:/var/opt/wildduck.git
```

4. From now on, to upgrade, pull latest changes from Github and push to production

```
$ git pull origin master
$ git push production master
```

This should be it. Git hook in the server takes care of upgrading npm packages etc.

PS. The server is composed from multiple components. You would also need to do the same for ZoneMTA and Haraka. Check the instructions file generated during install for all components.

**Comment by blackyzero** [comment]
Thanks a lot for your detail instruction.
For step 3, i don't use "wildduck.git" just "wildduck"

I have done two components wildduck and wildduck-webmail. 

I'd like to know what are the correct git repo for ZoneMTA and Haraka?

Thanks again.
