### ISSUE TITLE
Disable reserve username

### ISSUE THREAD

**Issue by blackyzero** [nodemailer/wildduck#154]
Hello,

How could i disable reserve username?
I am trying to register an new email account, but got error "social" is a reserved username"

And what are these reserve username?

Thank you.

**Comment by louis-lau** [comment]
https://github.com/nodemailer/wildduck-webmail/issues/2

**Comment by andris9** [comment]
WildDuck itself does not have any user-part restrictions in email addresses. There is a limitation in WildDuck Webmail as by default it allows open registration and most probably you do not want anonymous people claiming postmaster or hostmaster addresses.

**Comment by blackyzero** [comment]
thanks for your comments.
I can create "social"  user by using API, but not by web interface.

I checked the link from louis, there is no reserved "social" in  the list.
'abuse', 'admin', 'administrator', 'hostmaster', 'majordomo', 'postmaster', 'root', 'ssl-admin', 'webmaster'

**Comment by andris9** [comment]
You missed the role based addresses variable. You can find the entire list for it here: https://github.com/mixmaxhq/role-based-email-addresses/blob/master/index.js

**Comment by blackyzero** [comment]
perfect. It's clear now.
Thanks a lot for your great info
