### ISSUE TITLE
fail2ban integration

### ISSUE THREAD

**Issue by mhf-ir** [nodemailer/wildduck#155]
How can i block invalid ips try to connect ?

Such as webinterface, IMAP, POP3, SMTP or etc ?

https://www.stefan-seelmann.de/wiki/fail2ban#postfix-and-dovecot

**Comment by rqelibari** [comment]
You will need to create a configuration for each interface/service.

E.g. for protecting the SMTP authentication you will need to create a file `/etc/fail2ban/filter.d/zonemta.conf` and a `zonemta` section in the `/etc/fail2ban/jail.local` config file. See the `dovecot` example on the site: https://www.stefan-seelmann.de/wiki/fail2ban#postfix-and-dovecot

**Comment by rqelibari** [comment]
FYI: wildduck contains an [authentication rate limiter](https://github.com/nodemailer/wildduck/wiki/Security-implementation). This does not block the specific IP of an attacker but is already a good protection for hobby mail servers.

**Comment by mhf-ir** [comment]
Thanks, but I think for all of these, just add simple documentation here in project.

1. Add wildduck logs to output file.
2. Define fail2ban filter

As simple markdown will be enough.

**Comment by rqelibari** [comment]
Yes, that is a good idea. Depending on your installation configuration `wildduck` may be already logging to [`syslog`](https://en.wikipedia.org/wiki/Syslog). You should find all log output there.

Can you figure out the correct fail2ban configuration for `wildduck` and write a simple documentation text?

**Comment by mhf-ir** [comment]
First of all we need standard logging sample for fail2ban
Then define the filter:
Samples files are : https://github.com/fail2ban/fail2ban/tree/0.11/fail2ban/tests/files/logs

Somthing like https://brandur.org/logfmt will be good start point.
But in all layers such as SMTP, IMAP POP3 even HTTP could be applied.

**Comment by mhf-ir** [comment]
Of course fail2ban can parse any kind of logging cause many old legacy system not design logging for parsing and centerilze logs.

But logs just not for fail2ban, Stuff like https://fluentbit.io/ https://vector.dev/ also came for new centric log collector solution. Parsable logs is the best practices for any kind of stuff, better to be readable also like logfmt. But not very highly important but will be better if we respect new perspective for those concepts.

I think wildduck logs must Parsable and readable and all services must do the same, Also documentation for 3rd party services like ClamAV and RspamD will be awesome.

**Comment by andris9** [comment]
If WildDuck logs are not usable for fail2ban then there's always the option to modify log output, by adding new log rows etc.

**Comment by louis-lau** [comment]
> Thanks, but I think for all of these, just add simple documentation here in project.

If you'd like to contribute documentation you can press `Edit on Github` on https://docs.wildduck.email/.

> Stuff like https://fluentbit.io/ https://vector.dev/ also came for new centric log collector solution

Wildduck already supports GELF for centralized logging. 😁
