### ISSUE TITLE
Support for sharded cluster zones

### ISSUE THREAD

**Issue by louis-lau** [nodemailer/wildduck#156]
https://docs.mongodb.com/manual/tutorial/sharding-segmenting-data-by-location/

This would allow for faster reads/writes for a geo-distributed deployment. For this to work there would need to be a country field on every message/attachment, and use targeted reads.

Since I haven't deployed WildDuck in production or at large scale yet I'm not sure if this is actually worth the performance improvement over just accessing a Europe primary from the USA.

**Comment by andris9** [comment]
I've thought about it as well. The only sharded collection this would make sense for would be the message metadata collection. Attachments (that make up the majority of storage use) are deduplicated and not implicitly bound to any specific message / user. Being able to read message entires faster would give some gain for operations where attachments are not required (mostly IMAP / webmail message listing).

On the WD side this would mean adding a region field to users and setting this region for each of the messages of this user. Operationally you could then configure MongoDB to use this message region key for segmentation.

**Comment by andris9** [comment]
Now that I re-read the segmentation docs it seems that region key must be part of the sharding key. WildDuck uses a compound key of user:mailbox:uid as the shard key for messages. Adding a region into the index would be quite difficult by now.

**Comment by louis-lau** [comment]
I can see how that would be problematic given how many messages are usually stored. That's a shame. We may have to just do different deployments for different regions and have users connect to the right region. Or maybe use nginx mail proxy and route to the right server for a user?

Do you have any tips on migrating a user from one wildduck instance to another?

**Comment by andris9** [comment]
I guess you could use regular IMAP based export/import scripts. You can't just copy over database rows for messages because of attachment deduplication. Or write a API client script that downloads all messages and settings for a user via API and upload the same data to a different server.

**Comment by louis-lau** [comment]
Alright, that makes sense. Thank you! We'll have to see if the latency is noticable enough to warrant it.
