### ISSUE TITLE
New logo, better for (fav) icon

### ISSUE THREAD

**Issue by mhf-ir** [nodemailer/wildduck#158]
I think something like this would be better for new logo,  If you interested.

![wd_l13 svg](https://user-images.githubusercontent.com/1172526/67552191-6c9c4580-f717-11e9-9a5a-7ccbba810377.png)

**Comment by andris9** [comment]
@mhf-ir thanks! For the favicon you could create a PR against existing [favicon file](https://github.com/nodemailer/wildduck-webmail/blob/master/public/favicon.ico). Regarding project logo, I have plans to update design once a new 3rd party webmail project, that is currenlty in development, is released.

**Comment by louis-lau** [comment]
Off topic for this issue, but will that new webmail client be open source? I'm interested :grin:

**Comment by andris9** [comment]
@louis-lau The plans, as far as I know, are to open source it once it is "ready". It is not my project, so I can not give any ETAs. It already is semi public though, as anyone who signs up a web hosting package at zone.ee and creates an e-mail account can use the new web client at webmail.ee. It's a Laravel (that means PHP) + Vue.js app. Otherwise pretty similar functionality than the wildduck-webamail demo app has (except much better email composing/sending UX, multi language, signatures etc.). Here's a [screenshot](https://cloudup.com/cJ0JmXTOTkd) of my spam folder.

**Comment by louis-lau** [comment]
Looks good! I like the material design. Love that Zone will open source it (or plans to anyway). Sadly haven't been able to use WD in production yet. Slowly working on a control panel in my spare time. 
 https://github.com/louis-lau/DuckyPanel

**Comment by blackyzero** [comment]
that's very nice admin panel. 
Thanks @louis-lau

**Comment by ramiroaisen** [comment]
> @mhf-ir thanks! For the favicon you could create a PR against existing [favicon file](https://github.com/nodemailer/wildduck-webmail/blob/master/public/favicon.ico). Regarding project logo, I have plans to update design once a new 3rd party webmail project, that is currenlty in development, is released.

Hey im writing a webmail for wildduck too, is written in svelte and typescript once a i have a demo i let you know

**Comment by louis-lau** [comment]
Nice! Keep us updated 😁

**Comment by mhf-ir** [comment]
See sample of implementation: https://github.com/mhf-ir/wild-duck-graphic

**Comment by louis-lau** [comment]
It's not up to me to decide, but I like it!

**Comment by andris9** [comment]
Well, the 3rd party webmail project is still not moving and this logo surely looks better than the one there currently is (I paid $5 on fiverr.com for that logo, and got what I paid for) so we could replace the existing logo with this one indeed.

**Comment by mhf-ir** [comment]
@andris9 Should i send PR for logo?

**Comment by andris9** [comment]
@mhf-ir yes, this would be great 👍🏻
