### ISSUE TITLE
Fails to send email in gmail or different domains

### ISSUE THREAD

**Issue by refail** [nodemailer/wildduck#159]
Hello,
I installed wildduck in ubuntu 18.04 with quick installer. Everything installed correctly but now i can send emails only between users that i have created.
If i want to send an email in my gmail account it says "success" and put the email in the "sent mail" folder but don't send it.

Thank you in advance.

**Comment by elberthcorniell** [comment]
I have this issue too. I had a zone-mta error first but solved it with #109 . Now emails don't get out of outbox when I send them from Android's Gmail app, and in wild duck webmailer, mails are showed as sent but they don't reach the destination.

**Comment by ChaitanyaBhole** [comment]
I too have this type of issue. user1@example.com cannot send email to user2@gmail.com.

**Comment by elberthcorniell** [comment]
I solved this issue by following the instructions on domail.com-nameserver.txt on root directory

> MX
> --
> Add this MX record to the shield.do DNS zone:
> 
> domain.com. IN MX 5 mail.domain.com.
> 
> SPF
> ---
> Add this TXT record to the shield.do DNS zone:
> 
> domain.com. IN TXT "v=spf1 a:mail.domain.com domain.com ip4:10.0.0.1 ~all"
> 
> Or:
> domain.com. IN TXT "v=spf1 a:mail.domain.com ip4:10.0.0.1 ~all"
> domain.com. IN TXT "v=spf1 ip4:10.0.0.1 ~all"

**Comment by louis-lau** [comment]
Hi, is this still an issue? If so, we'll need more details such as zonemta logs.

**Comment by inayatu** [comment]
> Hi, is this still an issue? If so, we'll need more details such as zonemta logs.

Hey @louis-lau  Were you able to fix the issues? Found any work around?

**Comment by louis-lau** [comment]
I don't have any idea what the issue is, the info given is equivalent to "it doesn't work". Need ZoneMTA logs to help.

**Comment by deibertf** [comment]
I have the same issue. I did a fresh install, receiving works without a problem but sending mails to external domains is not working. Where do I find the logs you need to help?

**Comment by deibertf** [comment]
<pre>Aug 12 17:05:00 mail-customer-1 zone-mta[743]: info SMTP/feeder/743 CONNECTION id=zysxey7h4avpvvfj src=[77.247.110.122]:52684
Aug 12 17:05:27 mail-customer-1 zone-mta[744]: ERR! Sender/default/744[2] 17b3ab43e97000fb17.001 CONNFAIL domain=outlook.com local=mx01.serverdomain.com[0.0.0.0] remote=104.47.66.33:25 error=Network error when connecting to MX server outlook-com.olc.protection.outlook.com[104.47.66.33] for outlook.com: Connection timed out
Aug 12 17:05:27 mail-customer-1 zone-mta[744]: ERR! Sender/default/744[2] 17b3ab43e97000fb17.001 ERRCONNECT domain=outlook.com error=Network error when connecting to MX server outlook-com.olc.protection.outlook.com[104.47.59.161] for outlook.com: Connection timed out
Aug 12 17:05:27 mail-customer-1 zone-mta[744]: info Sender/default/744[2] 17b3ab43e97000fb17.001 DEFERRED[other] from=test@maildomain.de to=XXXXXXXXXX@outlook.com src= mx=outlook.com id=<8a03ef0f-6f25-6c76-982e-792b459e4187@maildomain.de> (450 Network error when connecting to MX server outlook-com.olc.protection.outlook.com[104.47.59.161] for outl>
Aug 12 17:06:20 mail-customer-1 zone-mta[744]: ERR! Sender/default/744[4] 17b3ab0f136000fb17.001 CONNFAIL domain=gmx.de local=mx01.serverdomain.com[0.0.0.0] remote=212.227.15.9:25 error=Network error when connecting to MX server mx00.emig.gmx.net[212.227.15.9] for gmx.de: Connection timed out
Aug 12 17:06:20 mail-customer-1 zone-mta[744]: ERR! Sender/default/744[4] 17b3ab0f136000fb17.001 ERRCONNECT domain=gmx.de error=Network error when connecting to MX server mx01.emig.gmx.net[212.227.17.5] for gmx.de: Connection timed out
Aug 12 17:06:20 mail-customer-1 zone-mta[744]: info Sender/default/744[4] 17b3ab0f136000fb17.001 DEFERRED[other] from=test@maildomain.de to=XXXXXXXXXX@gmx.de src= mx=gmx.de id=<f563836c-4812-20c3-5920-00888300666f@maildomain.de> (450 Network error when connecting to MX server mx01.emig.gmx.net[212.227.17.5] for gmx.de: Connection timed out)
Aug 12 17:07:05 mail-customer-1 zone-mta[744]: info Sender/default/744[1] 17b3ada00b30005a95.001 CONNECTING domain=mydomain.de port=25
Aug 12 17:09:16 mail-customer-1 zone-mta[744]: ERR! Sender/default/744[1] 17b3ada00b30005a95.001 CONNFAIL domain=mydomain.de local=mx01.serverdomain.com[0.0.0.0] remote=188.68.47.116:25 error=Network error when connecting to MX server mail.mydomain.de[188.68.47.116] for mydomain.de: Connection timed out
Aug 12 17:09:16 mail-customer-1 zone-mta[744]: ERR! Sender/default/744[1] 17b3ada00b30005a95.001 ERRCONNECT domain=mydomain.de error=Network error when connecting to MX server mail.mydomain.de[188.68.47.116] for mydomain.de: Connection timed out
Aug 12 17:09:16 mail-customer-1 zone-mta[744]: info Sender/default/744[1] 17b3ada00b30005a95.001 DEFERRED[other] from=test@maildomain.de to=XXXXXXXXXX@mydomain.de src= mx=mydomain.de id=<24ce42e7-dd0c-a1b5-eb9f-08a11b2795c7@maildomain.de> (450 Network error when connecting to MX server mail.mydomain.de[188.68.47.116] for mydomain.de: Connection ti>
Aug 12 17:09:59 mail-customer-1 zone-mta[743]: info SMTP/feeder/743 CONNECTION id=4bflqdwkfmrunz7z src=[77.247.110.122]:55914
Aug 12 17:14:58 mail-customer-1 zone-mta[743]: info SMTP/feeder/743 CONNECTION id=x2bm2jwhd6cu5p3z src=[77.247.110.122]:52688
Aug 12 17:17:17 mail-customer-1 zone-mta[744]: info Sender/default/744[1] 17b3ada00b30005a95.001 DEFERRED[other] from=test@maildomain.de to=XXXXXXXXXX@mydomain.de src= mx=mydomain.de id=<24ce42e7-dd0c-a1b5-eb9f-08a11b2795c7@maildomain.de> (450 Network error when connecting to MX server mail.mydomain.de[188.68.47.116] for mydomain.de: Connection ti>
Aug 12 17:19:56 mail-customer-1 zone-mta[743]: info SMTP/feeder/743 CONNECTION id=w5pvwl4rxyfxabac src=[77.247.110.122]:54081
</pre>

**Comment by louis-lau** [comment]
That probably means your hosting provider or ISP is blocking outbound port 25.

**Comment by deibertf** [comment]
> That probably means your hosting provider or ISP is blocking outbound port 25.

Thanks so much. This is indeed the issue. So simple yet so hard to find out.
![image](https://user-images.githubusercontent.com/24978665/129252704-35edff44-4f5a-4b3d-9fe4-05786a1ad5d6.png)

Thanks alot for your help!

**Comment by louis-lau** [comment]
Glad I could help! :)
