### ISSUE TITLE
Docker Container

### ISSUE THREAD

**Issue by doc-tongue** [nodemailer/wildduck#16]
- Have you wrapped this in a docker container?  I am trying but having networking issues.

**Comment by andris9** [comment]
Did you get it resolved? Was there anything worth noting in general or was it some configuration error?

**Comment by doc-tongue** [comment]
I did thank you.  I was missing make and g++ in my dockerfile.  I missed the errors during my build and it caused some unexpected results.  The optional dependancy @ronomon/crypto-async needed them.  They also made the image size jump from 50mb to 350.  I will run some more tests and when the image is stable will do a PR so users can have a quick docker option to fire up.

**Comment by FLYBYME** [comment]
How is this coming along?
