### ISSUE TITLE
ssh: Could not resolve hostname mail.****.com: Name or service not known

### ISSUE THREAD

**Issue by ihaveahurry** [nodemailer/wildduck#164]
"root@asd:/# git clone deploy@mail.[hidden].com:/var/opt/wildduck.git
Cloning into 'wildduck'...
ssh: Could not resolve hostname mail.[hidden].com: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists."

How do I fix this?

I copied the content from root/.ssh/authorized_keys to /home/deploy/.ssh/authorized_keys, so there should not be anything wrong with it. How do I check if the permissions are correct?

I added the correct DNS (TXT / MX) records, most of their names were "@" but one was "dec2019._domainkey".

The website / webmail does not work. I do not know how to setup the PTR records. I am using A VPS rent from a same service than the domain name. I have to automate everything, so record added by a support is not a choice.

I am using root account on terminal. I am using Ubuntu.

**Comment by andris9** [comment]
WildDuck requires some tinkering as it is designed for larger email systems. If you have a single VPS where you want to run a full featured email system, then much better alternatives would be [iRedMail](https://www.iredmail.org/) or [Mail-in-a-Box](https://mailinabox.email/).

**Comment by ihaveahurry** [comment]
> WildDuck requires some tinkering as it is designed for larger email systems. If you have a single VPS where you want to run a full featured email system, then much better alternatives would be [iRedMail](https://www.iredmail.org/) or [Mail-in-a-Box](https://mailinabox.email/).

I am setting up decentralized, autonomous peer-to-peer network so it will be open source but uses centralized anonymous/bulletproof hosting + later open source nodes hosted by anyone over the Internet.

It would mean even hundreds of servers, hundreds of domain names, thousands to tens of thousands of e-mail accounts so all of them are connected to each other through P2P / clustering.

I have to use NodeJS for now for a year or two.

I am testing / setting on this single machine currently. After this works, the script will purchase a new server with anonymous cryptos by withdrawing it from anonymous exchange account and then automatically install all packages and setup mail server etc. on it so the emails will be shared across the network, etc.

The whole network will be autonomous / automatic. I am programming this whole network alone and without large budget.

...

Can't you give any answer to this problem / are you just saying I should fix this myself without any support? I was using Windows Server previously with centralized mail services, but not I have to use Linux with own mail servers, so this environment is pretty new for me.

**Comment by ihaveahurry** [comment]
The domain service provider supports now manual PTR records, the problem was on their side.

**Comment by andris9** [comment]
I assumed from the fact that you did not figure out how to use Git URLs and DNS settings that you might not have enough experience to use something like WildDuck.

`git clone deploy@mail.[hidden].com:/var/opt/wildduck.git` assumes that there is a server with hostname `mail.[hidden].com`.  "Name or service not known" means that this hostname you try to use does not exist.

"@" is a common reference for main hostname in the DNS system, in your case it would probably mean either "[hidden].com" or "mail.[hidden].com". "dec2019._domainkey" is a subdomain for "@", so it would probably mean "dec2019._domainkey.[hidden].com" or "dec2019._domainkey.mail.[hidden].com"

**Comment by ihaveahurry** [comment]
All DNS settings are now correct, as "@" means the domain name so the domain name is not required and "dec2019._domainkey" the subdomain before it.

**Comment by ihaveahurry** [comment]
> "@" is a common reference for main hostname in the DNS system, in your case it would probably mean either "[hidden].com" or "mail.[hidden].com". "dec2019._domainkey" is a subdomain for "@", so it would probably mean "dec2019._domainkey.[hidden].com" or "dec2019._domainkey.mail.[hidden].com"

Yeah, I knew that already as I said on the first post: "I added the correct DNS (TXT / MX) records, most of their names were "@" but one was "dec2019._domainkey"."

> "git clone deploy@mail.[hidden].com:/var/opt/wildduck.git assumes that there is a server with hostname mail.[hidden].com. "Name or service not known" means that this hostname you try to use does not exist."

That I knew, too, because deploy is the folder in the server (mail.[hidden].com), and I would have asked about it without asking about PTR records if it was a problem to understand.

_

Actually, I was just asking : "Do you think the problem is in the PTR record and that's why the git clone does not work, or do you think it's in the permissions of that SSH file?"

Just learning this new environment.

I will test it now after adding that PTR record.

**Comment by louis-lau** [comment]
There would need to be an A record or a CNAME record on mail.[hidden].com, referring to the host you are trying to clone from. A PTR record does not come into play while using git. This question is more about git and DNS than about wildduck imo.

**Comment by ihaveahurry** [comment]
![dns](https://user-images.githubusercontent.com/58116174/70077531-aeb78180-1609-11ea-8ca9-48ba69cfef75.png)

**Comment by ihaveahurry** [comment]
![deploy](https://user-images.githubusercontent.com/58116174/70077715-0524c000-160a-11ea-8526-19a33edfdb34.png)

**Comment by ihaveahurry** [comment]
![dns](https://user-images.githubusercontent.com/58116174/70077806-2e455080-160a-11ea-8648-b57cb24a797c.png)

**Comment by ihaveahurry** [comment]
![dns2](https://user-images.githubusercontent.com/58116174/70078193-ea9f1680-160a-11ea-9c03-895b27012755.png)

**Comment by ihaveahurry** [comment]
![dns](https://user-images.githubusercontent.com/58116174/70078469-66995e80-160b-11ea-9496-5b5ca8def968.png)

**Comment by ihaveahurry** [comment]
![dns](https://user-images.githubusercontent.com/58116174/70078528-829d0000-160b-11ea-82e3-cc0c20e7f302.png)

**Comment by ihaveahurry** [comment]
Or should I just use the VPS's Reverse DNS instead on some of the records? I am not DNS + Linux Administration Expert, more experienced in programming and P2P.

**Comment by ihaveahurry** [comment]
Succesful. Thanks for @louis-lau for being professional. Very simple thing, lol, but when your thoughts are in a different universe, simple things become difficult. :)

**Comment by ihaveahurry** [comment]
Still the same error. When I visit mail.[hidden].com it says: "502 Bad Gateway". Now my VNC server does not work for some reason, dunno why, lol. I can ping the domain and receive all packages with correct IP. The DNS should be correct? Dunno if there is problem with the permissions of the SSH file or something.

**Comment by ihaveahurry** [comment]
Now the website / webmail works, but I still get that error:
"ssh: Could not resolve hostname mail.sgx-1254525.com: Name or service not known
fatal: Could not read from remote repository."

The DNS settings should be correct and SSH public key is correct.

**Comment by ihaveahurry** [comment]
https://www.upwork.com/ab/applicants/1201948391274110976/job-details

**Comment by louis-lau** [comment]
So.. What are you actually trying to accomplish here. You've told us the command that you're executing, but what is your end goal here? Why not just clone wildduck from github?

**Comment by ihaveahurry** [comment]
> So.. What are you actually trying to accomplish here. You've told us the command that you're executing, but what is your end goal here? Why not just clone wildduck from github?

I checked my (static) hostname, it is asd.

I am trying to do this:

 2. Clone application code
 $ git clone deploy@asd:/var/opt/wildduck.git
 $ git clone deploy@asd:/var/opt/zone-mta.git
 $ git clone deploy@asd:/var/opt/wildduck-webmail.git
 $ git clone deploy@asd:/var/opt/haraka-plugin-wildduck.git
 $ git clone deploy@asd/var/opt/zonemta-wildduck.git

3. After making a change in local copy deploy to server
 $ git push origin master
 (you might need to use -f when pushing first time)

------

But it gives me:
"root@asd:~# git clone deploy@asd:/var/opt/wildduck.git
Cloning into 'wildduck'...
deploy@asd: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists."

Even if all permissions are correct, SSH public key is correct (my VPS's SSH / same as root/.ssh/...), etc.

**Comment by louis-lau** [comment]
Ah, those instructions are from the deploy script. I see. Those are the instructions for cloning your existing install on another server. The format of the clone command in this case is like this: `[user@]host.xz:path/to/repo.git/`. So does the deploy user exist on the server you're trying to clone from? Is mail.sgx-1254525.com actually the server you want to clone from? Are all applications already installed and configured there?

Again, this is more of a git question.

**Comment by louis-lau** [comment]
I think it's obvious that most documentation has been made with sysadmins in mind. I'm not sure that's going to change anytime soon. As the project focus is large email systems a sysadmin is almost always involved.

**Comment by ihaveahurry** [comment]
> Ah, those instructions are from the deploy script. I see. Those are the instructions for cloning your existing install on another server (I assume). The format of the clone command in this case is like this: `[user@]host.xz:path/to/repo.git/`. So does the deploy user exist on the server you're trying to clone from? Is mail.****.com actually the server you want to clone from? Are all applications already installed and configured there?
> 
> Again, this is more of a git question.

Damn, told that domain as a mistake. (deleted my previous comment now)

This project is large email system related, but just decentralized and autonomous, but okey, I gotcha. I will just make a script which copies everything as that becomes so difficult, all users are made, but nothing works, etc.

For some kind of reason installing wildduck broke my vncserver, I have to think about it now.

The Wild Duck webmail does not receive or send any messages outside the server even if the port forwarding is correct, dunno why.

I can't use other servers and my backend is NodeJS, so I keep asking this forever until I get this working, as there is not other full email servers which I could easily connect to NodeJS, unless I use Postfix + Python, but that becomes too much hassle and learning as this package should work... there is just some dot somewhere which breaks the system, unless it is portforwarding / firewall related.

**Comment by louis-lau** [comment]
Any server will connect to NodeJS as you can use imap or smtp. For creating accounts they can offer an api, or work using files on the file system. Just like you create accounts on WildDuck using the API. I've said this before, using NodeJS in your application is not a reason to use a NodeJS mailserver.

**Comment by ihaveahurry** [comment]
> Any server will connect to NodeJS as you can use imap or smtp. For creating accounts they can offer an api, or work using files on the file system. Just like you create accounts on WildDuck using the API. I've said this before, using NodeJS in your application is not a reason to use a NodeJS mailserver.

Yeah, I know, but there does not seem to be any quick installer for Postfix or other mail servers like that to send and receive messages so they could be implemented Node.js quickly. Not interested to learn Postfix or other mail servers like that to setup a new e-mail account which receives an e-mail.

**Comment by ihaveahurry** [comment]
> Any server will connect to NodeJS as you can use imap or smtp. For creating accounts they can offer an api, or work using files on the file system. Just like you create accounts on WildDuck using the API. I've said this before, using NodeJS in your application is not a reason to use a NodeJS mailserver.

I have not used API on WildDuck currently, but the webmail. It does not work.
