### ISSUE TITLE
Mail sent using SMTP not counted in recipients counter

### ISSUE THREAD

**Issue by joyider** [nodemailer/wildduck#165]
Hello!

As far as I can see the counter for sent emails is not updated when you send emails using SMTP, but it does get updated when you send emails using the webclient.

The Doc states:

> "Recipient/forward limits assume that messages are sent using ZoneMTA with zonemta-wildduck plugin, otherwise the counters are not updated or checked."

Is there some config that we've missed or is there some issue with zonemta when it comes to the counters

Regards
AndréK

**Comment by andris9** [comment]
Counters are stored in Redis, so you have to use zonemta-wildduck and have it configured to use the same MongoDB and Redis configuration as the WildDuck main app itself.
