### ISSUE TITLE
redis error

### ISSUE THREAD

**Issue by furkankinyas** [nodemailer/wildduck#166]
Clean scripted install

Dec 09 13:59:14 mail wildduck-server[2322]: [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
Dec 09 13:59:14 mail wildduck-server[2322]:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1129:14)

**Comment by andris9** [comment]
Redis did not start. Depending on your VPS there might be some things that prevent Redis to work properly (ie. Apparmor conflicts). Try to get Redis working manually. And then make sure that Redis information in WildDuck config files are correct (/etc/wildduck/*.toml)

**Comment by furkankinyas** [comment]
how is auto start redis because when i reboot, dont start redis so i take this error

**Comment by andris9** [comment]
You should check Redis log (usually here: /var/log/redis/redis-server.log) and also Syslog (/var/log/syslog) to see why Redis does not start.
