### ISSUE TITLE
Generate a never-expiring access token 🕒

### ISSUE THREAD

**Issue by hamedbaatour** [nodemailer/wildduck#168]
is there any way to generate a never-expiring access token?

in `api.toml` it says that access token max lifetime is set in seconds and it defaults to 180 days but how can I generate a never-expiring access token or at least refresh the old access token through the API? 
thanks :)

https://github.com/nodemailer/wildduck/blob/15d3e95e65bcf61e9d8f4d12df33bc7944dfb5a4/config/api.toml#L25

**Comment by andris9** [comment]
Tokens generated via API are user account bound (token is valid for actions only related for the authenticated account) and always have a lifetime thus needing renewing after expiration. If you want to generate system tokens, that have different privileges, then you can create these via cli

```
$ ./bin/access-tokens --config="/path/to/server/config.toml" provision admin root
Generated access token for admin[root]:
3ab3a00ae63227673ab423b3be3afabe5e185b4c
```

In this case `--config="/etc/wildduck/wildduck.toml` points to server specific configuration file, "admin" is username for the token (this is not a user account but just a name to use in access logs etc) and "root" is role
