### ISSUE TITLE
smarthost for sending email

### ISSUE THREAD

**Issue by mleader1** [nodemailer/wildduck#169]
hi,

how can I setup an external smarthost for sending outgoing emails please (I went through manual installation so ZoneMTA not installed).

Many thanks!

**Comment by louis-lau** [comment]
WildDuck doesn't really handle outgoing mail. You need ZoneMTA with the WildDuck plugin for that. You can configure the default zone of ZoneMTA to relay it to external smtp.

**Comment by mleader1** [comment]
got it.  thx.
