### ISSUE TITLE
multi-tenant domains setup possible?

### ISSUE THREAD

**Issue by mleader1** [nodemailer/wildduck#170]
Hi,

I've seen domain alias setup available in the API but couldn't find any for multiple primary domain setup (i.e. multi-tenancy email accounts, such as sales@abc.com and sales@def.com ).

Is there a way to achieve this? If not, are there any plan for implementing such feature please?

Really love this mail server!

Cheers

**Comment by louis-lau** [comment]
In WildDuck an account is a single inbox, which you can add aliases to if needed. I've started developing an API on top of WildDuck that functions like you would want, but it's currently not finished and I wouldn't recommend using it.

https://github.com/louis-lau/DuckyAPI

**Comment by mleader1** [comment]
thanks @louis-lau  sorted - the domain alias can be created by configuring both "alias" and "domain" fields the same as the new domain.  

it works seamlessly.  :) a few more rounds of testing I'll then roll it out for a proper  sandbox.

**Comment by louis-lau** [comment]
Oh. Hahaha, I don't think I understood your question when I first read it. Glad you found the domain aliases
