### ISSUE TITLE
mail server can be replicated, backup

### ISSUE THREAD

**Issue by canbeup** [nodemailer/wildduck#171]
Can I ask for a specific configuration example? step by step for two servers? , how to backup a WildDuck Mail Server?

**Comment by louis-lau** [comment]
Can't really answer your first question, as it depends completely on your needs. Two seperate servers? Two servers sharing one mongodb? Two servers sharing a sharded mongodb cluster? I recommend you use the install script (https://github.com/nodemailer/wildduck/tree/master/setup) to get a feel of how WildDuck works, then you can start crafting your own setup and configuration based on your needs.

WildDuck stores everything important in mongodb, as you can read in the readme. So your question is actually "How do I backup mongodb?". That will also depend on if you plan to use mongodb sharding or not, I recommend you assess your own options depending on your setup.

So really the answer to this question is: it depends. Use the install script for an example setup.
