### ISSUE TITLE
[API] set unlimited usage quota for user 📫 

### ISSUE THREAD

**Issue by hamedbaatour** [nodemailer/wildduck#173]
how to remove any usage quota through the API? (docs doesn't mention anything about this)
the default limit is set to 1GB and I believe 150/hour limit for receiving emails but how can I remove those restrictions?
I know that I cloud set a ridiculously high number but is there a way to actually indicate "unlimited"
```
     "quota": {
        "allowed": 1073741824 // default
      },
```
thanks

**Comment by louis-lau** [comment]
As far as I can see this isn't possible at the moment. You _can_ change the default of 1GB to something else here: 
https://github.com/nodemailer/wildduck/blob/c3f2b8f3d370ceaef3a80cd3bcf0dff744bda312/config/default.toml#L14

**Comment by hamedbaatour** [comment]
@louis-lau thanks for the clarification.
