### ISSUE TITLE
How to configure external outbound relay?

### ISSUE THREAD

**Issue by figassis** [nodemailer/wildduck#174]
One of the main obstacles of running an email server is ending up on blacklists even when following recommended best practices. A solution is to use outgoing relay services like spamhero.com, but this requires configuring the smtp server to use an external server to relay messages. How would I go about doing that with wildduck? I can't find any hints here or on ZoneMTA.

**Comment by louis-lau** [comment]
Look at the example configuration of ZoneMTA:

https://github.com/zone-eu/zone-mta/blob/ed6fbece3cce0aff73b9046067a6a0d5905af43b/config/default.js#L381-L390

**Comment by figassis** [comment]
That's exactly what I needed. I was already down a rabbit hole trying to write a zonemta plugin. Thanks!
