### ISSUE TITLE
Clarify access control features

### ISSUE THREAD

**Issue by figassis** [nodemailer/wildduck#175]
So I now have a fully working deployment, with webmail and all the whistles. Amazing work! can't wait to start building on top of this, but have one question:

Is there any sort of RBAC built in? I can see in the API docs (https://api.wildduck.email/#api-Users-PostUser) that there is a status:regular_user, but that is simply a tag, not sure it has any effect. In fact, searching the code does not show that role anywhere except in the docs, so it looks like just a tag.

So how does one go about limiting access by role. It would be great allow roles such as system admin, domain admin (scoped to a specific domain) and regular user, as well as allow system, domain and user quotas.

I haven't tested if this is implemented, but just thought odd that I could not specify a user role when creating a user.

Cheers!

**Comment by louis-lau** [comment]
You can see 1 user as an inbox if you'd like. There are no admin users that allow managing multiple inboxes. `status:regular_user` is in the list of tags in the example. It is indeed just a tag, that you can read and write. It has no functionality in WildDuck itself.

I am currently working on an admin control panel/api in my free time, but it is unfinished. You can take a look on my GitHub profile.

**Comment by figassis** [comment]
I just looked a bit deeper and found in api.toml there's hardcoded access control, which includes this file: https://github.com/nodemailer/wildduck/blob/master/config/roles.json

Most of the access is based on whether you can CRUD any resource or your own. For a large scale service, we might want to add more granularity. An enterprise customer might want to buy a number of accounts and manage their own users.

@louis-lau I saw your admin api and interface yesterday, looks amazing, I'm planning on deploying today and seeing where I can contribute. Ideally I'll build a single docker based deployment that had wildduck, wildduck-webmail (or a better interface) and ducky admin.

**Comment by louis-lau** [comment]
Ah, right. I guess there are multiple roles for the API, but WildDuck currently doesn't have a concept of domain ownership. 

There is already a WildDuck docker image out there with everything in it. I personally would like every service separated so you can scale and distribute them independently, though that does lead to a more complicated setup. I plan to create docker images for duckypanel/api when I feel it's finished enough.

**Comment by andris9** [comment]
Yeah, the design has intentionally not included any access control. The API is private, it is not meant to be exposed directly to customers and thus any AC logic should be handled by the management application. 

Roles are there to prevent issues where via a bug or stolen credentials some application could get access to all data. So if you run a webmail client, then you need 2 roles - one for authentication (and nothing more) and one for regular user. If the user logs in via authentication role and gets assigned a user role token, then this user can not make requests on behalf of other users even if the webmail application is buggy.

For management UI you need to handle your own AC logic. Tags and metadata are there to help, so you could for example ad an "admin" tag to every admin user and then use this tag for filtering all admins. Tags and metadata are not visible or editable for "user" role users, so if a user logs in to webmail using a user role token, then it can not see or modify metadata assigned to himself even if a web client bug would allow setting it.

**Comment by louis-lau** [comment]
> Yeah, the design has intentionally not included any access control. The API is private, it is not meant to be exposed directly to customers and thus any AC logic should be handled by the management application.

I never even confirmed this, just assumed it from the way you designed the API. Which is the reason I started a separate project instead of contributing back to WD. Also TypeScript :grin:. The tags are really useful!
