### ISSUE TITLE
DKIM key tool long on route53

### ISSUE THREAD

**Issue by figassis** [nodemailer/wildduck#176]
Looks like wildduck generates a 408 character TXT string which route53 rejects as too long. Is there a solution?

**Comment by louis-lau** [comment]
DNS providers with a better UX do this for you, but you'll need to split it:
http://hack.limbicmedia.ca/how-to-split-dns-dkim-records-properly/

**Comment by figassis** [comment]
Ok, I also saw another issue recommending using 1024 bit keys, which are automatically shorter. Will also try that, and it it doesn't work, will split

**Comment by louis-lau** [comment]
That would also work, but keep in mind that 2048 bit will be more future proof. 1024 is secure right now, but you never know what the future will bring :wink:
