### ISSUE TITLE
Running Wildduck instances on multiple servers.

### ISSUE THREAD

**Issue by rqelibari** [nodemailer/wildduck#177]
Hi *,

I want to run two Wildduck instances on two different physical servers. The first one should be the main mail server and the second one should serve as a backup mail server, accepting mail in case the first mail server is down. Hence I want both servers to have identical data.
Does anyone know how to do this, especially regarding `mongodb` and `redis`? @andris9 do you have any suggestions on this one?
Any information is appreciated.

## What I already looked into
All mails are stored in the `mongodb` database, therefor the database has to be synchronized between both servers. I've figured out, that `mongodb` has a feature called [replication set](https://docs.mongodb.com/manual/replication/) that does exactly what I need.

I do not know what the corresponding concept is called for `redis` though or if I need to replicate the information in `redis` at all (haven't looked into the code yet).

**Comment by louis-lau** [comment]
Yep. Mongodb replica set and redis sentinel.

https://github.com/nodemailer/wildduck/blob/master/README.md#redis-sentinel

**Comment by louis-lau** [comment]
Keep in mind that you need at least three servers for a replica set. One of the doesn't have to store data, it can be an arbiter.

**Comment by louis-lau** [comment]
Keep in mind that you need at least three servers for a replica set. One of the doesn't have to store data, it can be an arbiter.

**Comment by andris9** [comment]
The easiest set up would be to use 3 servers and run entire stack on each one of these. Then configure MongoDB to use replica set setup over these 3 servers and also set up Redis to use Redis Sentinel (this also means that you would have to change mondogb and redis configuration settings in WildDuck config files). You do not have to use Sentinel, you can go with regular 1 master + 2 slaves setup but Sentinel gives you automatic failover - once Redis master goes down, sentinel promotes one of the slaves to became new master.

If you are running multiple servers with WildDuck then it does not matter which request goes to which server as long as all these instances share the same MongoDB and Redis config.

**Comment by rqelibari** [comment]
@louis-lau Thank you. Why would one need an arbiter in a two server setup? I read about arbiters, but assumed it is only needed to prevent even vote numbers.

@andris9 Thank you very much for the explanation on mongodb and Redis, especially the detail that Redis needs to be synchronized too. Is there any known setup with only two servers?

**Comment by andris9** [comment]
You need at least 3 instances of MongoDB for a replica set to work. You can actually run just 2 and it would work just as well but this means if either of these servers goes down, then the remaining one goes down as well as it does not have required quorum. You could always resolve these issues manually though by reconfiguring the cluster if you do not care about automatic failover and such.

**Comment by Weldeasy** [comment]
> @andris9 Thank you very much for the explanation on mongodb and Redis, especially the detail that Redis needs to be synchronized too. Is there any known setup with only two servers though?

You can install the arbiter on the same machine of the slave.

**Comment by andris9** [comment]
With 2 servers you could run Redis in a "normal" 1 master - 1 slave configuration without Sentinel and also 2 node MongoDB replica set (with or without arbiter). If one of these servers goes down then:

1. If the invalid server was running Redis Master, then configure Redis Slave to be new master (by running `REPLICAOF NO ONE` command in the former slave instance). Also modify WildDuck config files to use the new server as Redis host.
2. Unless you used MongoDB arbiter setup and the server with arbiter is still up then MongoDB goes down even if the remaining server was primary as it does not have enough quorum votes. So you would have to modify the replica set by removing the invalid instance from cluster configuration using `rs.remove()` command. Once you have a replica set with a single server then you have enough votes and the instance could become primary again.

**Comment by louis-lau** [comment]
> Why would one need an arbiter in a two server setup? I read about arbiters, but assumed it is only needed to prevent even vote numbers.

@rqelibari In order to hold an election, the nodes that remain online need to form a majority of the total nodes. 1/2 isn't a majority, 2/3 is :). To be honest I don't know the _why_ of it all, but I do know what works and what doesn't.

> You can install the arbiter on the same machine of the slave.

@Weldeasy That does defeat the point though. If that machine goes down only 1/3 nodes will be up, unable to hold an election.

**Comment by rqelibari** [comment]
Thank you all. I think @andris9 did explain the possible solutions to this issue very thoroughly.
I for myself will go use a three server setup to have automatic failover.
