### ISSUE TITLE
Ability to enable/disable entire domain and/or multiple users by query

### ISSUE THREAD

**Issue by figassis** [nodemailer/wildduck#178]
So one use case I'm working on is a multi tenant email service where users can signup to a main domain, but companies can signup to a custom domain, and then create users under that domain. Users have roles such as SuperAdmin, Admin, CompanyAdmin, DomainAdmin (since a company can have multiple domains). So it's important to be able to manage settings in batches, such as enable/disable all users for a domain, or for a company, or set domain wide limits. For now the most important is being able to enable/disable/suspend.

Now, the flow is pretty much disable company and then query the api for all users with that domain [page through if too many] and disable one by one.

This can be a hit on performance, or simply resource intensive if made async. Also, for a large dataset, results may take a while, so disabling a user may allow users to still access the system until their account is processed.

Is there a workaround for this or maybe I should contribute with some batch operations?

**Comment by figassis** [comment]
Yes, but can you batch update by tag?

**Comment by rqelibari** [comment]
No, the current API does not define a way to update a filtered list of users simultaneously. You have to retrieve a list of user ids and than update each user with a specific request.

**Comment by figassis** [comment]
And that is the issue, I have no problem getting a collection, its acting on that that becomes the problem. Imagine working on a million users one at a time, each time a domain admin makes a change.

**Comment by louis-lau** [comment]
Having the ability to update in bulk would be nice, as there would be less overhead. I suggest you or anyone that is willing to work on this submits a pull request :).

What I have done for bulk actions in the meantime is start a background task on the server that does the requests asynchronously in batches. It's not too bad this way.

**Comment by figassis** [comment]
Sure, haven’t had a time slot yet, but will definitely help out.
