### ISSUE TITLE
OpenAPI/Swagger specification

### ISSUE THREAD

**Issue by louis-lau** [nodemailer/wildduck#179]
Having an openapi specification would allow you or anyone else to generate api client libraries automatically: https://openapi-generator.tech/docs/generators.html. I've used this in my code for duckypanel and it's wonderful. You don't have to remember any urls, or response types, as it will generate types as well. You can pass the baseurl and access token once, and not bother with it in the rest of your code.

I've tried converting the apidoc documentation to openapi using [apidoc-swagger](https://www.npmjs.com/package/apidoc-swagger), but it doesn't support openapi 3 and the output contained thousands of errors.

What's your opinion about switching from apidoc to [swagger-jsdoc](https://www.npmjs.com/package/swagger-jsdoc)? You could provide a beautiful documentation page [like this](https://redocly.github.io/redoc/) to replace the generated apidoc as well. Of course this would mean rewriting a lot of stuff, but that could be a PR 😉

**Comment by andris9** [comment]
Actually I wanted to use OpenAPI at first because of the nicely generated documentation pages. I only went with apiDoc because it is basically JSDoc with some extra tags and I was already comfortable using JSDoc. I wouldn't mind replacing apiDoc with OpenAPI if it would mean accepting a PR 👍
