### ISSUE TITLE
TypeError: Cannot read property 'component' of undefined

### ISSUE THREAD

**Issue by Bodenhaltung** [nodemailer/wildduck#185]
I see in my logs an error when a mail recevied:

`Mar 08 15:10:04 mail haraka[891]: [CRIT] [CD90B52F-83E3-4A9D-A469-5760EA7BF9BC.1] [core] Plugin wildduck failed: TypeError: Cannot read property 'component' of undefined
Mar 08 15:10:04 mail haraka[891]:     at Plugin.plugin.loggelf (/opt/haraka/plugins/wildduck/index.js:94:43)
Mar 08 15:10:04 mail haraka[891]:     at Plugin.exports.hook_mail (/opt/haraka/plugins/wildduck/index.js:279:12)
Mar 08 15:10:04 mail haraka[891]:     at Object.plugins.run_next_hook (/opt/haraka/node_modules/Haraka/plugins.js:508:28)
Mar 08 15:10:04 mail haraka[891]:     at callback (/opt/haraka/node_modules/Haraka/plugins.js:466:32)
Mar 08 15:10:04 mail haraka[891]:     at Plugin.exports.return_results (/opt/haraka/node_modules/Haraka/plugins/spf.js:269:20)
Mar 08 15:10:04 mail haraka[891]:     at ch_cb (/opt/haraka/node_modules/Haraka/plugins/spf.js:210:16)
Mar 08 15:10:04 mail haraka[891]:     at mod_chain_caller (/opt/haraka/node_modules/Haraka/spf.js:294:28)
Mar 08 15:10:04 mail haraka[891]:     at mech_chain_caller (/opt/haraka/node_modules/Haraka/spf.js:317:28)
Mar 08 15:10:04 mail haraka[891]:     at /opt/haraka/node_modules/Haraka/spf.js:360:56
Mar 08 15:10:04 mail haraka[891]:     at mech_chain_caller (/opt/haraka/node_modules/Haraka/spf.js:317:28)
Mar 08 15:10:04 mail haraka[891]: [NOTICE] [CD90B52F-83E3-4A9D-A469-5760EA7BF9BC.1] [core] sender <xxxx@gmail.com> code=CONT msg=""
Mar 08 15:10:07 mail haraka[891]: [INFO] [CD90B52F-83E3-4A9D-A469-5760EA7BF9BC.1] [core]  hook=rcpt plugin=wildduck function=hook_rcpt params=<xxxx@xxxx.com> retval=DENYSOFT msg="Failed to process recipient, try again [ERRC02]"`

It is a fresh installation on Ubuntu 18.04.

**Comment by louis-lau** [comment]
Check the config of the haraka plugin. Sounds like you added the gelf config section, but have removed the component field. Unless a recent commit broke the default installation config, that would also be a possibility.

https://github.com/nodemailer/haraka-plugin-wildduck/blob/0627ed4db85953ab3a9604f5e5ea3698a6595f3b/config/wildduck.yaml#L68-L74

**Comment by louis-lau** [comment]
Never mind the above, looks like the plugin code was updated to prevent this 3 days ago, but the install script wasn't updated to pull the latest version. Let me just PR that :)
