### ISSUE TITLE
Improve documentation on local mail delivery

### ISSUE THREAD

**Issue by kiuka** [nodemailer/wildduck#192]
Hi,

I'm new to Wildduck and trying to setup my self hosted mail server from scratch (without using the installer script).

Maybe its only me, but it gave me hard time to find out how to delivery local mails. I'm using the packages which was in the documentation but neither of them mentioned that how does queue/lmtp plugin exactly deliver the email.

I just append the error log because maybe it will help others to find this topic:

[NOTICE] [-] [core] [outbound] Failed to get pool entry: Outbound connection error: Error: connect ECONNREFUSED 127.0.0.1:24

So the problem is that Wildduck listens on 2424 as default and queue/lmtp forwards to 24 by default which is not the 2424. I think either the default config should be changed to 24 or at least make it clear in the documentation (as well in the documentation of haraka-plugin-wildduck).

**Comment by andris9** [comment]
Actually you should disable LMTP both in WIldDuck and in Haraka and instead use [wildduck plugin for Haraka](https://github.com/nodemailer/haraka-plugin-wildduck) for local delivery. This is also what the setup scripts sets up. The plugin writes incoming messages directly to mail store.

**Comment by kiuka** [comment]
Then its even less clear:) On the page of the mentioned plugin it says I need the queue/lmtp which does not do local delivery only forward it to localhost:24.

Am I missing something?

**Comment by andris9** [comment]
Oh, that's seriously out of date, I'll fix the docs

**Comment by andris9** [comment]
Removed LMTP references from [README](https://github.com/nodemailer/haraka-plugin-wildduck/blob/master/README.md)

**Comment by kiuka** [comment]
Thank you, meanwhile I removed queue/lmtp and it works like a charm. Thanks for the hard work and the fast responses!:)
