### ISSUE TITLE
Detailed setup instructions for wildduck setup through Docker

### ISSUE THREAD

**Issue by SpoorthiPalakshaiah** [nodemailer/wildduck#194]
Hello, 
Can I get a detailed setup instructions for wildduck setup through docker.
![image](https://user-images.githubusercontent.com/43110794/78768888-32172400-79aa-11ea-87d7-3bbd7a789b17.png)
It says the server is listening on 127.0.0.1:8080 but I get site cannot be reached response

**Comment by rakshith-ravi** [comment]
Have you exposed the right ports from your docker container to the host?

cc @thebongy

**Comment by SpoorthiPalakshaiah** [comment]
Can I get the docker run command for setting up wildduck

**Comment by thebongy** [comment]
@SpoorthiPalakshaiah 
You can use the `-p` option with docker run to selectively publish container ports to ports on the host machine.

For example
```
docker run -p 8080:8080 -p 9993:9993 -p 9995:9995 -p 2424:2424 nodemailer/wildduck
```
Will expose ports 8080,9993,9995,2424 to the same ports on the host machine.

More information on docker's [documentation](https://docs.docker.com/engine/reference/run/#expose-incoming-ports)

For more config options for the wildduck docker image, have a look at the [wiki page on docker](https://github.com/nodemailer/wildduck/wiki/Docker)

**Comment by SpoorthiPalakshaiah** [comment]
I  have a mongo container running and I have all the three: mongo container, redis container and wildduck container in the same network. Still I get the following error,
![image](https://user-images.githubusercontent.com/43110794/78962229-8ab50100-7b11-11ea-84e0-39393458d116.png)

**Comment by thebongy** [comment]
Can you give the output of
```
docker network inspect <name of the docker network>
```
and provide more information on how the containers were run so I can reproduce the issue?

**Comment by SpoorthiPalakshaiah** [comment]
docker network inspect mail-net
![image](https://user-images.githubusercontent.com/43110794/78974096-e772e480-7b2e-11ea-9e9f-fc51647dd16b.png)
For running containers:
docker run -itd  --network mail-net --name local-mongo -p 27017:27017 mongo --> For mongo container
docker run -itd --network mail-net --name local-redis redis:alpine --> For redis container
docker run -it -p 8080:8080 -p 9993:9993 -p 9995:9995 -p 2424:2424 --network mail-net --name mail-server nodemailer/wildduck

**Comment by thebongy** [comment]
@SpoorthiPalakshaiah as described in the wiki, the wildduck container by default, is configured to connect to mongodb and redis on `localhost`.

Since in your use case, mongo runs on the hostname `local-mongo` and redis runs on the hostname `local-redis`, you must configure wildduck to connect to these instead of `localhost`.

Here is one method to configure the container to do so, by using the `CMD_ARGS` variable
```bash
docker run -it -p 8080:8080 -p 9993:9993 -p 9995:9995 -p 2424:2424 --network mail-net --name mail-server --env CMD_ARGS="--dbs.mongo=mongodb://local-mongo:27017 --dbs.redis=redis://local-redis:6379/3" nodemailer/wildduck
```

For more configuration options, have a look at the [wiki page on docker](https://github.com/nodemailer/wildduck/wiki/Docker)

**Comment by SpoorthiPalakshaiah** [comment]
But I'm getting empty response from 127.0.0.1:8080

**Comment by SpoorthiPalakshaiah** [comment]
![image](https://user-images.githubusercontent.com/43110794/78984818-d46b0f00-7b44-11ea-8df9-d462bf89e17c.png)
All servers are listening,
Now I tried to add user with command as 
`curl -i -XPOST http://localhost:8080/users \
-H 'Content-type: application/json' \
-d '{
  "username": "myuser",
  "password": "verysecret",
  "name": "John Doe",
  "address": "john.doe@example.com",
  "tags": [
    "status:regular_user",
    "subscription:business_big"
  ]
}'`
But I got error saying 
![image](https://user-images.githubusercontent.com/43110794/78984903-0e3c1580-7b45-11ea-9467-8b766d1491f6.png)

**Comment by thebongy** [comment]
@SpoorthiPalakshaiah It seems that the wildduck server is running on `127.0.0.1` (loopback address) inside the container, thus it isn't accessible from outside the container. You can configure wildduck to run  on `0.0.0.0` instead, to listen on all interfaces inside the container:

```bash
docker run -it -p 8080:8080 -p 9993:9993 -p 9995:9995 -p 2424:2424 --network mail-net --name mail-server --env CMD_ARGS="--dbs.mongo=mongodb://local-mongo:27017 --dbs.redis=redis://local-redis:6379/3 --api.host=0.0.0.0" nodemailer/wildduck
```

**Comment by SpoorthiPalakshaiah** [comment]
Thank you so much!! It works now.
