### ISSUE TITLE
Return consistent types in API responses

### ISSUE THREAD

**Issue by figassis** [nodemailer/wildduck#195]
Many fields in response objects such as Address return different types depending on whether a field is available or not. For example, and address will have the name field set to boolean false if the user has no name. This usually breaks integrations, especially for statically typed languages that rely on consistent response types.

My suggestion is to return an empty value of that type, such as an empty string.

**Comment by ramiroaisen** [comment]
> Many fields in response objects such as Address return different types depending on whether a field is available or not. For example, and address will have the name field set to boolean false if the user has no name. This usually breaks integrations, especially for statically typed languages that rely on consistent response types.
> 
> My suggestion is to return an empty value of that type, such as an empty string.

I rather change the false values to null values, null is the correct value for non-existing values
