### ISSUE TITLE
Api typescript definitions

### ISSUE THREAD

**Issue by ramiroaisen** [nodemailer/wildduck#197]
Hi!
Is somewhere available typescript definitions for the api
if not i can write them and make a PR,
I cant find the change stream definition in the api.wildduck.email page, where can i find it?

**Comment by louis-lau** [comment]
Seems like a duplicate of #179. API clients with typescript definitions could be generated if there was an OpenApi definition 😁.

**Comment by louis-lau** [comment]
Duplicate of #179

**Comment by louis-lau** [comment]
@ramiroaisen Wildduck now has an openapi spec. You can sue this spec to generate typescript definitions for the api :)
