### ISSUE TITLE
Centralized address book feature

### ISSUE THREAD

**Issue by SpoortiPalakshaiah** [nodemailer/wildduck#198]
Is there any centralized address book feature in wildduck so that by using wildduck as IMAP server we get same address book in every user's mail applications

**Comment by louis-lau** [comment]
You can't get contacts over imap. It's not a standard. You would need a carddav server.

**Comment by kesavkolla** [comment]
Is it possible to have a carddav server that can connect to wildduck database?

**Comment by louis-lau** [comment]
@kesavkolla What do you want to connect? The WildDuck database doesn't store contacts. If you want to connect authentication I know for example radicale supports IMAP as an authentication backend.

**Comment by kesavkolla** [comment]
@louis-lau wildduck has users.  Is users different from contacts?  I mean we can add few extra attributes like name and address then user becomes contact.  Am I missing anything?

**Comment by louis-lau** [comment]
Ah, I see what you mean. I mostly tend to think of WildDuck as an application with which multiple separate users interact, all having different contacts and not knowing each other. But I guess if you were using WildDuck in an organization this would make sense 😁. However, I'm not aware of any way to do this.

You do have to create the WildDuck user at some point though, why not add it to a shared caldav at the same time? :)

**Comment by louis-lau** [comment]
I can't see WildDuck implementing CalDav to serve users as contacts. However, if WildDuck ever integrates with LDAP (#105) that could be used as a backend for a CalDav server. You can subscribe to that issue if that's something you're interested in.
