### ISSUE TITLE
JMAP support

### ISSUE THREAD

**Issue by andris9** [nodemailer/wildduck#2]
I don't have time to work on this right now but [JMAP](http://jmap.io/) is something that probably should be considered. IMAP is not so great for web clients.

**Comment by andris9** [comment]
JMAP is completely off the table for now.

**Comment by alexanderadam** [comment]
> JMAP is completely off the table for now.

People who're looking for a mail server with JMAP support might have a look at [Stalwart mailserver](https://stalw.art/) then.

Apart from being very resource efficient (_it's written in :crab: Rust_) it also has many modern features (_it even supports [encryption at rest](https://stalw.art/docs/category/encryption/)_) and is [easy to install](https://stalw.art/docs/category/installation).

**Comment by andris9** [comment]
Stalwart and WildDuck have different goals. WildDuck is designed for environments with tens or hundreds of thousands of active users and hundreds of terabytes of stored emails. And to achieve this, a lot of corners have been cut. Rust is a better option for these kinds of server applications, but the majority of the load for real-life usage is not coming from effective command handling (where Rust shines better than Node) but from fetching the emails from the backend storage.

To illustrate, below is a screenshot of a production WildDuck setup for deduplicated attachments.

![Screenshot 2023-10-17 at 21 09 48](https://github.com/nodemailer/wildduck/assets/132242/a17bbeec-29dc-49a3-818f-71ff25e697e7)

**Comment by andris9** [comment]
Yeah, in any case, Stalwart is a good option. On the WildDuck’s homepage I suggest using Dovecot+Postfix but by now Stalwart would probably be a better option.
