### ISSUE TITLE
DKIM Body Hash Incorrect

### ISSUE THREAD

**Issue by grumpyguvner** [nodemailer/wildduck#200]
I realise that this is handled by ZoneMTA or the WildDuck plugin for the same however I am posting this issue here as I have used this projects ./install.sh script to install on a blank Ubuntu 18.04 server, created the DNS records per the deploy script and not made any modifications to any code or config files.

When I test my outgoing emails either using the webmail interface or the api I am getting the same DKIM verification error which is that the Body Hash is not as expected.

I have tried multipart and plain text emails with the same result.

Do you have any guidance on where I should be looking.

**Comment by grumpyguvner** [comment]
I have also tried this on a blank Ubuntu 16.04 server with them same result.

**Comment by andris9** [comment]
Is the DKIM body hash correct when you are using SMTP instead of API or is it always broken?

**Comment by grumpyguvner** [comment]
It was always broken using either SMTP or API. I am not sure which part was wrong but I fixed it by deleting the existing DKIM key then creating a new private key and DKIM record.

**Comment by grumpyguvner** [comment]
Sorry I just reread your message, I cannot remember whether I tried SMTP, I definitely sent emails via webmail and api.

**Comment by grumpyguvner** [comment]
For reference I was using mxtoolbox.com/deliverability to test the emails I sent.

**Comment by ExternalDatabase** [comment]
@andris9
Hi, I have the same issue (I use latest docker version of Wildduck) and I guess that problem may be caused by putting spaces between every 75 characters in DKIM Signature within b tag...
