### ISSUE TITLE
New Alternative Webmail Released

### ISSUE THREAD

**Issue by ramiroaisen** [nodemailer/wildduck#202]
Hello!
I recently release a webmail for wilddick mail server
You can see it and test it in [https://github.com/ramiroaisen/raven-webmail](https://github.com/ramiroaisen/raven-webmail)
cheers!

**Comment by louis-lau** [comment]
Cool! Screenshots? 👀 

I see you haven't yet changed the token on your public install though (https://github.com/ramiroaisen/goosy-webmail/issues/1). You'll also want to add the node_modules and dist folder to your gitignore. Those don't belong in git as they just slow down pulls and pushes, and clutter your commit history 😁 .

**Comment by ramiroaisen** [comment]
> Cool! Screenshots? 
> 
> I see you haven't yet changed the token on your public install though (https://github.com/ramiroaisen/goosy-webmail/issues/1). You'll also want to add the node_modules and dist folder to your gitignore. Those don't belong in git as they just slow down pulls and pushes, and clutter your commit history  .

Hey thanks, that's repo was suposed to be private, i already fix it thank you very much

**Comment by andris9** [comment]
Very cool 👍

**Comment by ramiroaisen** [comment]
> Very cool

have you tested it?

**Comment by ramiroaisen** [comment]
> Cool! Screenshots? 
I'm on it

**Comment by andris9** [comment]
> > Very cool
> 
> have you tested it?

Yes, it was very easy to get it up and running 👍 

<img width="1260" alt="Screenshot 2020-04-28 at 21 41 48" src="https://user-images.githubusercontent.com/132242/80524945-26ab8d00-8999-11ea-8d10-57087627f596.png">

**Comment by louis-lau** [comment]
Looks nice! Will test it later. @andris9 Maybe we could create a page with all WildDuck related projects?

**Comment by andris9** [comment]
>  @andris9 Maybe we could create a page with all WildDuck related projects?

Yeah sure, greta idea. There are multiple options to do this, not sure which way would be the best to go with:

1. to create a new [Wiki page](https://github.com/nodemailer/wildduck/wiki)
2. to add a list of projects to [README](https://github.com/nodemailer/wildduck/blob/master/README.md)
3. or to add a section to the [homepage](https://wildduck.email/) (homepage runs on WordPress)

**Comment by louis-lau** [comment]
The readme is already quite long, and it would be hard for anyone else to contribute to the homepage, so I guess wiki? Then again, it's not very easy to upload images to the wiki. Which would be nice for screenshots.

Seeing as the readme is already huge, could be an idea to split it up to nice documentation pages hosted on GitHub pages so everyone can still contribute. 

Or just the wiki heheh.

**Comment by louis-lau** [comment]
> nice documentation
Something like this: https://docsify.js.org/

**Comment by ramiroaisen** [comment]
If you give me a list of the projects i could create a page for them

**Comment by louis-lau** [comment]
Closing this as it's mentioned in the docs since #206. 😁
