### ISSUE TITLE
CPU over load issue

### ISSUE THREAD

**Issue by itree** [nodemailer/wildduck#205]
I have installed wildduck for about over a year now. Every now and then the CPU and network spikes that locks up server.  I can't even ssh in. And require a reboot.  Then everything goes back to normal for a while.  Any idea how I can debug this? 

Great project BTW.

It is running on debian stretch with 1 GB ram.

**Comment by andris9** [comment]
Are you running a year old version of WildDuck or have you recently upgraded? There have been several performance improvemts during the last year.

**Comment by itree** [comment]
Let me do a git pull.  Is there a upgrade guide I should follow?

**Comment by andris9** [comment]
You could try to run this the WildDuck code folder:

```
$ git remote add origin git://github.com/nodemailer/wildduck.git || true
$ git pull origin master
$ npm install --production
$ systemctl restart wildduck
```

**Comment by itree** [comment]
Thanks.  I was just wondering if I should check to the commit point

stated here: 
WILDDUCK_COMMIT="7f491802578a019a66e49c55a876ea59d8b5e3d9"

https://github.com/nodemailer/wildduck/blob/master/setup/01_install_commits.sh

**Comment by itree** [comment]
Also just FYI. I'm not using the mogodb 4.0, rather the default mongo that came with Debian stretch, wonder if that makes a difference.

**Comment by itree** [comment]
Ok, I did it a bit different. I first fetched the local bare git repo and then updated the wildduck install directory.  Then npm install --production

It is running now. Is there a way to check if I'm on the most currently version?

**Comment by itree** [comment]
Also I have made some changes to the code, should I issue a pull request?

**Comment by louis-lau** [comment]
> Is there a way to check if I'm on the most currently version?

It will tell you the version on startup, latest is currently 1.24.0.

> should I issue a pull request

If you think these changes would benefit everyone else, then yes! 😁

**Comment by andris9** [comment]
Run `git log` and compare it against latest commits [here](https://github.com/nodemailer/wildduck/commits/master). Should be more or less the same.

For PRs it depends about the changes. If it is a small fix then it probably gets merged fast. If it is a large and completely new feature then might not be merged if it is not aligned with current dev direction.

**Comment by itree** [comment]
the change is more along the line of checking existing user during registration for server using more than one domains. 



When there is more than one domain, if a exact username is used for the second domain it will say the user already exists when try to create a new account. 

So in this file:
https://github.com/nodemailer/wildduck/blob/master/lib/user-handler.js:1175
So i changed  username to address

The side effect is that when logging in the user must use the full address to log.  Not sure if that is relevant to other people.

**Comment by andris9** [comment]
The current username check is intentional. Usernames and addresses are loosely coupled, so username availability should not depend on if a similarly looking address exists or not. In fact in several WildDuck installations users even do not know their actual usernames, they use their email addresses instead of usernames to log in. In these systems username mirrors user's ID in the main customer database.

**Comment by itree** [comment]
Then how do we handle issues for when we have 

user1@example.com is registered

and when trying to register user1@example2.com it will say the username already exists. 

Shouldn't the verification for existing user be based on the email address instead of just the username? 

such as 
```
            existingUserData = await this.users.collection('users').findOne(
                {
                    address: data.address
                },
                {
                    projection: {
                        unameview: true
                    },
                    maxTimeMS: consts.DB_MAX_TIME_USERS
                }
            );

```

**Comment by itree** [comment]
I know this is an edge case, but how do you propose we handle server with more than one domain and want use the same username?

**Comment by louis-lau** [comment]
You can set the username separately from the address. I just randomly generate the usernames.

**Comment by itree** [comment]
@louis-lau you mean from wildduck-webmail ?  So randomly generate username if it already exists?

**Comment by louis-lau** [comment]
I'm not sure about wildduck-webmail, I don't use it to create the accounts. I mean using the api directly.

**Comment by itree** [comment]
Ok thanks.

**Comment by itree** [comment]
BTW, the server is now running on 1.24.0 

I'll keep it running for a bit see if the load is running normal.

**Comment by ramiroaisen** [comment]
> You can set the username separately from the address. I just randomly generate the usernames.

I'm just set the username equals to the address... is very simple

**Comment by louis-lau** [comment]
That works as well! I moved to randomly generated because I want to have the ability to change the address. If you have the address as the username you can still change the address, but you won't be able to use the old address in a new account as the username is then already taken. :grin:

**Comment by itree** [comment]
Hey guys, just FYI. I updated to 1.24.0.  

And the sever hung again after a few days. Any ideas? Where I shall look?

**Comment by louis-lau** [comment]
I guess the logs would be a good start: `journalctl -u wildduck`

**Comment by itree** [comment]
Yeah I did. Nothing out of ordinary. I'll keep my eyes on it.

**Comment by louis-lau** [comment]
Hey @itree, is this still happening?
