### ISSUE TITLE
Installation error!. Haraka

### ISSUE THREAD

**Issue by RexzZzY** [nodemailer/wildduck#209]
Having a issue while following scripted installation of wildduck on ubuntu server.
It fails to install haraka installation script

![Screenshot (78)](https://user-images.githubusercontent.com/49055800/81272940-cfc64780-906b-11ea-8b4b-825b22a6d696.png)

**Comment by andris9** [comment]
I've also seen this, Haraka for whatever reason tries to compile sqlite. If building it fails, the installation should still work even if it takes a lot of time.

**Comment by RexzZzY** [comment]
Yeah leave it for an hour like that, But nothing happened. So i terminated the connection myself

**Comment by panhna** [comment]
@RexzZzY cc @andris9 It's working fine for me. I got double error message but it's still successfully setup.
