### ISSUE TITLE
telnet wild.duck 25

### ISSUE THREAD

**Issue by gurumelo** [nodemailer/wildduck#21]
Hello, with the standard configuration + Haraka. You can send false emails, for example:
telnet wild.duck 25
MAIL FROM: juanito@wild.duck
RCPT TO: cat@wild.duck

or
MAIL FROM: juanito@moon.com
RCPT TO: cat@wild.duck

Thanks

**Comment by andris9** [comment]
I don't understand the issue. Wild Duck does not run on port 25. There is a LMTP compinent running on port 24 (or 2424) that accepts mail only for existing accounts

**Comment by gurumelo** [comment]
Haraka, sorry.
