### ISSUE TITLE
Api error codes for internacionalization

### ISSUE THREAD

**Issue by ramiroaisen** [nodemailer/wildduck#211]
Hi there!
Do you have a list of api error codes? (to generate user-facing messages that we can translate)
Thanks!

**Comment by andris9** [comment]
There is no list. A lot of errors are dynamic, so not easy to translate either. I've tried to attach a code value to each of the error responses so you could generate a translation based on that code, eg. in case of `UserNotFound` you could use "Provided user was not found" or something like that. Though there is not list for these codes either, you'd have to grep these from the code.

**Comment by louis-lau** [comment]
@andris9 Is this list not up to date? https://docs.wildduck.email/#/api-error-codes

**Comment by andris9** [comment]
I guess it more or less is up to date. I just forgot that this list exists 🙄

**Comment by ramiroaisen** [comment]
Yeah a saw that list right after posting this issue.. great!
