### ISSUE TITLE
Attachemnts not working in webmail with wildduck

### ISSUE THREAD

**Issue by mahesh-birajdar** [nodemailer/wildduck#212]
Hi 

   We are getting below error while downloading or viewing attachments from wilduck via webmail

  ```
code: "ResourceNotFound"
message: "//users/5ea66fafcf1da504f538/mailboxes/5ea66fafcf1da50/messages/9/attachments/ATT00001 does not exist"

info HTTP GET /webmail/5ea66fafcf1da5/attachment/10/ATT00001 404 133.275 ms - 165

```
can someone help on this?

**Comment by louis-lau** [comment]
Interesting how it's `//users` in the error message. Do you have a `/` at the end of the api url in the configuration of wildduck webmail? If so, remove it.

**Comment by mahesh-birajdar** [comment]
Thank you so much!! You are right. It works now. 

you hit the bull's eye :)

**Comment by louis-lau** [comment]
Great! 😁
