### ISSUE TITLE
Using different character for address labels

### ISSUE THREAD

**Issue by skerit** [nodemailer/wildduck#216]
I've used ASSP for years, and it actually let you configure which key you want to use for address labels. Instead of the default `+` I set it to `_`.
It really works great: nobody would ever strip those off and every e-mail input field accepts it.

Even though it's not a config in wildduck, I thought it would be trivial to change by just tweaking the regex in `lib/tools.js`

Here's my new regex:

```js
    if (removeLabel) {
        user = user.replace(/\_[^@]*$/, '');
    }
```

Easy! I even made sure the wildduck package in the haraka plugin AND the wildduck package in the zone-mta plugin would have the same tweak. 

Unfortunately, it doesn't work. I keep getting `550 5.1.1 No such user` responses from ZoneMTA.

Are there any other places where labels are checked?

**Comment by louis-lau** [comment]
Not sure if this fits your use case, but another option is to just create a user with this address: `johndoe_*@example.com`.

**Comment by skerit** [comment]
Thanks, I can use that as a workaround for now :)
But that makes me create quite a lot of forwarders per name & domain, and I'd like to know where else this filtering happens :P

**Comment by vid** [comment]
I have been using _ as separator for decades now since it is accepted so widely, and want to switch to Wildduck, so this would be hundreds if not thousands of addresses, and I'd have to continue creating new ones manually. Any way to support this feature as a configuration option? Thanks!
