### ISSUE TITLE
Filtering on custom headers

### ISSUE THREAD

**Issue by skerit** [nodemailer/wildduck#217]
Looking at the API documentation, I don't think it's possible to create a filter based on a custom header, right?

Is there a reason why it's not included in the API, even though the code seems to support it & the To/From/Subject/... filters get stored in a `headers` object in the database anyway?

I guess I could directly edit the database document and put a filter in? Although I don't think there's currently a way to only check for the *existence* of a header?

I'd like to create a separate folder where all my newsletters will end up. Filtering all the incoming mail that have a `List-Unsubscribe` header would actually do most of the work :)

**Comment by andris9** [comment]
Current filtering features are intentionally limited to keep it more or less compatible with message search as not all headers are indexed and thus not searchable from the datastore. Filtering is done against actual message, not database, so it would be possible to create any kind of filter. Right now for your problem the easiest way would be to create a filter for `listId` and use a single dot as the value as this should match most messages from mailing lists / newsletters

```json
{
  "query": {
    "listId": "."
  }
}
```

**Comment by skerit** [comment]
Good to know. I might try to code it in my fork.

Also, fyi: nearly half of the newsletters I receive don't have a `List-Id` header, only a `List-Unsubscribe` one 🤷
