### ISSUE TITLE
Feature Request: CalDav/CardDav Support

### ISSUE THREAD

**Issue by chinthakadeshapriya** [nodemailer/wildduck#218]
What is your plan for CalDav/CardDav integration

**Comment by andris9** [comment]
Currently there are no plans as these are pretty complex things to build directly into WildDuck.

**Comment by louis-lau** [comment]
You can use radicale with an IMAP authentication plugin: https://github.com/Unrud/RadicaleIMAP/blob/master/README.md

Or nextcloud with imap authentication: https://github.com/nextcloud/user_external#readme

Both will work as caldav/carddav servers.
