### ISSUE TITLE
How to extend user model?

### ISSUE THREAD

**Issue by kesavkolla** [nodemailer/wildduck#221]
I want to add some custom attributes to user collection to facilitate our organization needs.  Eg I want to add a OU attribute to track groups. How to effectively make this happen without breaking for code upgrades?

**Comment by louis-lau** [comment]
You can use tags for that, see the api documentation.

**Comment by andris9** [comment]
You can use `tags` for searchable values and `metadata` for arbitrary (but not searchable data)
