### ISSUE TITLE
rspamd interface ?

### ISSUE THREAD

**Issue by blackyzero** [nodemailer/wildduck#222]
Hello,

Is Wildduck using Rspamd?
If yes, how could i access it?

Thank you.

**Comment by andris9** [comment]
Haraka is using Rspamd. WildDuck uses rspamd output from Haraka like shown [here](https://github.com/nodemailer/haraka-plugin-wildduck/blob/master/index.js#L970)

**Comment by blackyzero** [comment]
thanks for this info.
