### ISSUE TITLE
Two installs in separate datacenters with just clustered mongodb

### ISSUE THREAD

**Issue by fcardona** [nodemailer/wildduck#223]
Hello. I've been using wildduck for some time now and it has been quite solid. Thank you for the great work.

I'm now thinking of installing a new version in another datacenter using install.sh. I then plan to cluster the mongodb databases but each instance of redis will be independent. Will this work or may it have some unintended consequences?

**Comment by andris9** [comment]
For clustering you need at least MongoDB instances. 2 works as well but it has no fault tolerance at all, if one server goes down then the other one stops working as well. Redis works with 2 inctanse setup when using 1 master + 1 slave configuration. If you want to use Redis Sentinel (that is automatic failover if Redis Master goes down), then you also need at least 3 instances to run the Sentinel daemon.

Regarding WildDuck all instances must use the same database configuration, that goes both for Mongo and Redis. You can only use separate Redis instances only if you disable IMAP.

For setup you can use the install script, then edit dbs.toml in /etc/wildduck and if using Haraka then also edit /opt/haraka/config/wildduck.yaml to set correct DB settings

**Comment by fcardona** [comment]
Thanks!
