### ISSUE TITLE
Threads collection is not cleaned up after user deletion

### ISSUE THREAD

**Issue by v-byte-cpu** [nodemailer/wildduck#224]
MongoDB Threads collection is not cleaned up after user deletion. Also I haven't found any deletes from this collection in source code.

**Comment by andris9** [comment]
Thread collection is time-capped. Entries auto-expire after 180 days of last change so when a user is deleted all threads get removed eventually.

**Comment by v-byte-cpu** [comment]
Can this period be configured ?
