### ISSUE TITLE
Limit message size

### ISSUE THREAD

**Issue by SpoortiPalakshaiah** [nodemailer/wildduck#226]
Is there any API or any way to limit message size?

**Comment by louis-lau** [comment]
For inbound messages with haraka:
https://github.com/haraka/Haraka/blob/master/config/databytes

For outbound messages with ZoneMTA:
https://github.com/zone-eu/zone-mta/blob/master/config/default.js#L204

**Comment by voxsoftware** [comment]
How edit after installed?

**Comment by SpoortiPalakshaiah** [comment]
> How edit after installed?

You can edit the specific files as mentioned above and restart the service or restart the containers.
