### ISSUE TITLE
2FA (OTP SMS)

### ISSUE THREAD

**Issue by zaidysf** [nodemailer/wildduck#227]
Hi, i just wondering about adding phone number for user registration, so it will be used to 2FA OTP SMS feature, maybe we can add 3rd party sms gateway (like twilio) or self-hosted sms gateway.

**Comment by andris9** [comment]
I would not add external service dependencies into WildDuck but you can manage this yourself by using [Custom 2FA](https://docs.wildduck.email/api/#api-TwoFactorAuth-EnableCustom2FA). This way you can mark users as having 2FA enabled (and thus disabling account password for IMAP/SMTP) but the actual implementation would be your own.
