### ISSUE TITLE
SSL error when sending message with SMTP

### ISSUE THREAD

**Issue by duyhotan2000** [nodemailer/wildduck#230]
Hi @andris9 ,

I have installed Wildduck on server and configured ZoneMTA with Let's encrypt certificate for SMTP TLS, but when sending email from Thunderbird, I got this error:
![image](https://user-images.githubusercontent.com/10768153/85971285-f9aa4380-b9f6-11ea-8398-9a584f4f4953.png)

I also checked the syslog and got them following error:
![image](https://user-images.githubusercontent.com/10768153/85971251-ded7cf00-b9f6-11ea-8dab-e574422f2439.png)

Please give me some clues.
Thank you!

**Comment by louis-lau** [comment]
Hey, sorry there hasn't been a response to this issue. Is this still an issue? I recommend opening an issue over at https://github.com/zone-eu/zone-mta instead.
