### ISSUE TITLE
When using install.sh from sudo, letsencrypt fails

### ISSUE THREAD

**Issue by mannyveloso** [nodemailer/wildduck#232]
When using install.sh on Ubuntu 18.04 and installing from sudo, letsencrypt setup fails because 13_install_ssl_certs.sh assumes acme.sh lives in /root instead of in ~.

Proposed:

change

/root

to

~/.acme.sh/acme.sh

**Comment by mannyveloso** [comment]
FYI, the current failure behavior is excellent, because it does stick a self-signed cert in there.

**Comment by andris9** [comment]
yes, this has been noted before. could you change the code, test if the installation process really works with the changes and make a PR?

**Comment by mannyveloso** [comment]
Pull request created. Tested on 18.04, works fine.

**Comment by andris9** [comment]
Thanks
