### ISSUE TITLE
Move email to archive

### ISSUE THREAD

**Issue by sandro971** [nodemailer/wildduck#234]
Hello.
I read the wildduck documentation and i have not found anything about how to move an email into archive collection.
May be i don't understand is fonctionality, but i see how to restore but not the reverse.
Anyone can help me ?
Thanks !

**Comment by andris9** [comment]
"archive" stores deleted emails. If you delete an email from webmail or from IMAP then it is not deleted permanently but moved to archive for some time. You can then restore the message until the archived message is permanently deleted.

**Comment by andris9** [comment]
You can think of the archive as a soft backup. It is difficult to make user specific backups from WildDuck so when a user asks to restore their emails that they have deleted then you can restore these messages from the archive. Messages are kept in the archive [25 days](https://github.com/nodemailer/wildduck/blob/a00be20f80ac90689d684105206f92914b882cff/lib/consts.js#L73) and are permanently deleted once that time is reached.

**Comment by sandro971** [comment]
Thanks ! It was one of my tracks.
