### ISSUE TITLE
Installing on kubernetes 

### ISSUE THREAD

**Issue by botzill** [nodemailer/wildduck#236]
Hi.

Does anyone have any guide on how to install this on Kubernetes? 

Thx a lot.

**Comment by louis-lau** [comment]
There's a docker container:
https://docs.wildduck.email/#/in-depth/docker

**Comment by louis-lau** [comment]
A docker container with an [example docker-compose file](https://github.com/nodemailer/wildduck/blob/master/docker-compose.yml) should be enough guidance to deploy wildduck in kubernetes. Though there's no actively published docker containers for haraka or zonemta, these would be needed for receiving and sending email. That however, are issues for haraka and zonemta.
