### ISSUE TITLE
I get "certificate not trusted"

### ISSUE THREAD

**Issue by botzill** [nodemailer/wildduck#237]
I installed it using the default `install.sh` script and default generated certificates I get in chrome:  certificate not trusted. 

Do I need to do other steps in order to make this work out of the box?

**Comment by andris9** [comment]
Could you check your installation log? Certificates are generated by Let's Encrypt using acme.sh and if anything fails (eg. ww is not accessible etc.) then self signed certs are used. You can also try to generate these certs manually by running the following as root:

```
~/.acme.sh/acme.sh --issue --nginx \
    -d "your.domain.name" \
    --key-file       /etc/wildduck/certs/privkey.pem  \
    --fullchain-file /etc/wildduck/certs/fullchain.pem \
    --reloadcmd     "/usr/local/bin/reload-services.sh" \
    --force
```

**Comment by hadpro24** [comment]
I 

> Could you check your installation log? Certificates are generated by Let's Encrypt using acme.sh and if anything fails (eg. ww is not accessible etc.) then self signed certs are used. You can also try to generate these certs manually by running the following as root:
> 
> ```
> ~/.acme.sh/acme.sh --issue --nginx \
>     -d "your.domain.name" \
>     --key-file       /etc/wildduck/certs/privkey.pem  \
>     --fullchain-file /etc/wildduck/certs/fullchain.pem \
>     --reloadcmd     "/usr/local/bin/reload-services.sh" \
>     --force
> ```

I make this command, but I still have this problem
