### ISSUE TITLE
Not able to set retention parameter for a mailbox

### ISSUE THREAD

**Issue by SpoortiPalakshaiah** [nodemailer/wildduck#239]
**Description:**

I wanted auto-purging of mails after specific amount of time (1 day); So, I tried to setup retention parameter for a mailbox; but I'm getting error while setting up a retention parameter.

**Steps to reproduce:**

`curl -i -XPUT https://<mail_api_url>/users/:user/mailboxes/:mailbox -H 'Content-type: application/json' -d '{"retention":86400000}'`

**Expected behavior:**

Retention parameter set for specific mailbox and working purge of mails.

**Actual behavior:**
 
Cannot set retention parameter

**Relevant error-response:**

```
{
  "error": "Mailbox update failed with code CANNOT"
}
```

**Comment by andris9** [comment]
Should be fixed in the latest commit.
