### ISSUE TITLE
Error could not find suitable formatter

### ISSUE THREAD

**Issue by MohammedAl-Mahdawi** [nodemailer/wildduck#24]
Hi,

Thank you so much for creating this amazing project, I hope I'll be able to help in the future.

After running `node server.js` I got unlimited number of errors like the following:

`{"name":"Wild Duck API","hostname":"Mohammed-Notebook","pid":31868,"level":40,"req":{"method":"GET","url":"/__webpack_hmr","headers":{"host":"localhost:8080","connection":"keep-alive","accept":"text/event-stream","cache-control":"no-cache","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36","referer":"http://localhost:8080/","accept-encoding":"gzip, deflate, br","accept-language":"en-US,en;q=0.8"},"remoteAddress":"127.0.0.1","remotePort":40726},"err":{"message":"could not find suitable formatter","name":"NotAcceptableError","stack":"NotAcceptableError: could not find suitable formatter\n    at ServerResponse.__send (/path/wildduck/node_modules/restify/lib/response.js:400:32)\n    at ServerResponse.send (/path/wildduck/node_modules/restify/lib/response.js:221:24)\n    at /path/wildduck/node_modules/restify/lib/server.js:788:17\n    at /path/wildduck/node_modules/restify/lib/server.js:1145:16\n    at Immediate.<anonymous> (/path/wildduck/node_modules/vasync/lib/vasync.js:175:30)\n    at runCallback (timers.js:785:20)\n    at tryOnImmediate (timers.js:747:5)\n    at processImmediate [as _immediateCallback] (timers.js:718:5)","code":"NotAcceptable"},"msg":"error retrieving formatter","time":"2017-10-12T13:09:07.255Z","v":0}`

They appear one after one on the terminal.

My operating system is Linux Mint 18.02 which is built on top of Ubuntu 16.04

How can I fix this issue please?

All the best,
Mohammed

**Comment by andris9** [comment]
Any idea why the log message includes "/__webpack_hmr"? Do you have some other process also listening on 8080?

**Comment by MohammedAl-Mahdawi** [comment]
Hello @andris9 ,

Thank you for the quick reply.

Yes, I have a webpack app listening on 8080 but I switched it off before running wildduck.

Regards,
Mohammed

**Comment by andris9** [comment]
Something seems to be trying to openwebpa k  event stream urls and the Wild Duck API does not know how to respond. Check that you do not have your webpack app open in some browser tab

**Comment by MohammedAl-Mahdawi** [comment]
WOW, you are awesome, you are right, the issue appeared because I have a browser tab opening on 8080.

I just closed it and the issue has gone away!

Thank you so much for your help.

So for any other one that faces this issue to fix it please close your app that listening on 8080 and any other browser tab that uses it.

**Comment by andris9** [comment]
Graeat! Maybe it was a mistake to use port 8080 for the API as it is quite common. Anyway you can also change the API port from the api settings.
