### ISSUE TITLE
Document system access token generation

### ISSUE THREAD

**Issue by figassis** [nodemailer/wildduck#240]
When I set up Wildduck the first time, I was able to set access tokens for different roles, but now I can't seem to find the docs that showed me to do that. Luckily I had saved a snipped and searched for it to find https://github.com/nodemailer/wildduck/blob/master/bin/access-tokens, which basically allows me to:

`/var/nodemailer/wildduck/bin/access-tokens --config="config.toml" provision NAME [root,webmail,manager,user,auth,...]`

There's also a closed issue #168 

I think this info is really important to anyone trying to build anything on top of wildduck, so would you mind adding this to the docs at docs.wildduck.email?

**Comment by andris9** [comment]
Good point. I've been building WildDuck mostly for a specific [web hosting service](https://www.zone.ee/en/) and keeping docs up to date has been lacking as I myself know what I've built and don't need docs for that. Fortunately there are people like louis-lau who have helped in this regard but still - there are lot of features left undocumented. I set up a page for roles [here](https://docs.wildduck.email/#/in-depth/roles). Not complete but at least it's something.
