### ISSUE TITLE
Infinite expunging of mailbox?

### ISSUE THREAD

**Issue by mannyveloso** [nodemailer/wildduck#241]
I've been messing around with mailboxes, and it seems as if wild duck gets into a loop thing to expunge a mailbox. My mailbox structure is:

* INBOX
** Manny SubBox
*** Kids
*** MannyBox2

When I click on the "Manny SubBox" in Apple Mail, the wild duck log shows WD trying to continuously expunge the "Manny SubBox" mailbox.

> Jul  7 19:54:59 mail wildduck-server[39387]: info IMAP [qjjvrmam5y3vuwrf] mveloso authenticated using PLAIN
Jul  7 19:54:59 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] New journal listener for 5efce66482a5bd3d0e7f1028 (mveloso)
Jul  7 19:54:59 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: * CAPABILITY IMAP4rev1 APPENDLIMIT=26214400 CHILDREN CONDSTORE ENABLE ID IDLE MOVE NAMESPACE QUOTA SPECIAL-USE UIDPLUS UNSELECT UNSELECT UTF8=ACCEPT XLIST
Jul  7 19:54:59 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: 3.34 OK mveloso authenticated
Jul  7 19:54:59 mail wildduck-server[39387]: sill IMAP [pqboyw6csbk5t26a] C: 15.33 IDLE
Jul  7 19:54:59 mail wildduck-server[39387]: sill IMAP [pqboyw6csbk5t26a] S: + idling
Jul  7 19:54:59 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] C: 4.34 CAPABILITY
Jul  7 19:54:59 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: * CAPABILITY IMAP4rev1 APPENDLIMIT=26214400 CHILDREN CONDSTORE ENABLE ID IDLE MOVE NAMESPACE QUOTA SPECIAL-USE UIDPLUS UNSELECT UNSELECT UTF8=ACCEPT XLIST
Jul  7 19:54:59 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: 4.34 OK CAPABILITY completed
Jul  7 19:55:24 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] C: 5.34 SELECT "(* 23B string *)" (CONDSTORE)
Jul  7 19:55:24 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] Opening "INBOX/Manny SubBox/Kids"
Jul  7 19:55:24 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: * FLAGS (\Answered \Flagged \Draft \Deleted \Seen)
Jul  7 19:55:24 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: * OK [PERMANENTFLAGS (\Answered \Flagged \Draft \Deleted \Seen \*)] Flags permitted
Jul  7 19:55:24 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: * OK [UIDVALIDITY 1593717282] UIDs valid
Jul  7 19:55:24 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: * 0 EXISTS
Jul  7 19:55:24 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: * 0 RECENT
Jul  7 19:55:24 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: * OK [UIDNEXT 1] Predicted next UID
Jul  7 19:55:24 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: 5.34 OK [READ-WRITE] SELECT completed, CONDSTORE is now enabled
Jul  7 19:55:24 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] C: 6.34 IDLE
Jul  7 19:55:24 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: + idling
Jul  7 19:55:25 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] C: <4 bytes of data>
Jul  7 19:55:25 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: 6.34 OK IDLE terminated
Jul  7 19:55:25 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] C: 7.34 SELECT "(* 28B string *)" (CONDSTORE)
Jul  7 19:55:25 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] Opening "INBOX/Manny SubBox/MannyBox2"
Jul  7 19:55:25 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: * FLAGS (\Answered \Flagged \Draft \Deleted \Seen)
Jul  7 19:55:25 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: * OK [PERMANENTFLAGS (\Answered \Flagged \Draft \Deleted \Seen \*)] Flags permitted
Jul  7 19:55:25 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: * OK [UIDVALIDITY 1593717217] UIDs valid
Jul  7 19:55:25 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: * 0 EXISTS
Jul  7 19:55:25 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: * 0 RECENT
Jul  7 19:55:25 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: * OK [UIDNEXT 1] Predicted next UID
Jul  7 19:55:25 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: 7.34 OK [READ-WRITE] SELECT completed, CONDSTORE is now enabled
Jul  7 19:55:25 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] C: 8.34 IDLE
Jul  7 19:55:25 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: + idling
Jul  7 19:55:25 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] C: <4 bytes of data>
Jul  7 19:55:25 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: 8.34 OK IDLE terminated
Jul  7 19:55:25 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] C: 9.34 SELECT "INBOX/Manny SubBox" (CONDSTORE)
Jul  7 19:55:25 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] Opening "INBOX/Manny SubBox"
Jul  7 19:55:25 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: * FLAGS (\Answered \Flagged \Draft \Deleted \Seen)
Jul  7 19:55:25 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: * OK [PERMANENTFLAGS (\Answered \Flagged \Draft \Deleted \Seen \*)] Flags permitted
Jul  7 19:55:25 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: * OK [UIDVALIDITY 1593717206] UIDs valid
Jul  7 19:55:25 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: * 0 EXISTS
Jul  7 19:55:25 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: * 0 RECENT
Jul  7 19:55:25 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: * OK [UIDNEXT 1] Predicted next UID
Jul  7 19:55:25 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: 9.34 OK [READ-WRITE] SELECT completed, CONDSTORE is now enabled
Jul  7 19:55:25 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] C: 10.34 IDLE
Jul  7 19:55:25 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: + idling
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] C: <4 bytes of data>
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: 10.34 OK IDLE terminated
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] C: 11.34 EXPUNGE
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] Deleting messages from "5efe31d682a5bd3d0e7f1047"
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: * 0 EXISTS
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: 11.34 OK EXPUNGE completed
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] C: 12.34 UNSELECT
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: 12.34 OK UNSELECT completed
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] C: 13.34 SELECT "INBOX/Manny SubBox" (CONDSTORE)
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] Opening "INBOX/Manny SubBox"
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: * FLAGS (\Answered \Flagged \Draft \Deleted \Seen)
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: * OK [PERMANENTFLAGS (\Answered \Flagged \Draft \Deleted \Seen \*)] Flags permitted
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: * OK [UIDVALIDITY 1593717206] UIDs valid
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: * 0 EXISTS
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: * 0 RECENT
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: * OK [UIDNEXT 1] Predicted next UID
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: 13.34 OK [READ-WRITE] SELECT completed, CONDSTORE is now enabled
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] C: 14.34 IDLE
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: + idling
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] C: <4 bytes of data>
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: 14.34 OK IDLE terminated
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] C: 15.34 EXPUNGE
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] Deleting messages from "5efe31d682a5bd3d0e7f1047"
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: * 0 EXISTS
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: 15.34 OK EXPUNGE completed
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] C: 16.34 UNSELECT
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: 16.34 OK UNSELECT completed
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] C: 17.34 SELECT "INBOX/Manny SubBox" (CONDSTORE)
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] Opening "INBOX/Manny SubBox"
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: * FLAGS (\Answered \Flagged \Draft \Deleted \Seen)
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: * OK [PERMANENTFLAGS (\Answered \Flagged \Draft \Deleted \Seen \*)] Flags permitted
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: * OK [UIDVALIDITY 1593717206] UIDs valid
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: * 0 EXISTS
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: * 0 RECENT
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: * OK [UIDNEXT 1] Predicted next UID
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: 17.34 OK [READ-WRITE] SELECT completed, CONDSTORE is now enabled
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] C: 18.34 IDLE
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: + idling
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] C: <4 bytes of data>
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: 18.34 OK IDLE terminated
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] C: 19.34 EXPUNGE
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] Deleting messages from "5efe31d682a5bd3d0e7f1047"
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: * 0 EXISTS
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: 19.34 OK EXPUNGE completed
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] C: 20.34 UNSELECT
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: 20.34 OK UNSELECT completed
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] C: 21.34 SELECT "INBOX/Manny SubBox" (CONDSTORE)
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] Opening "INBOX/Manny SubBox"
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: * FLAGS (\Answered \Flagged \Draft \Deleted \Seen)
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: * OK [PERMANENTFLAGS (\Answered \Flagged \Draft \Deleted \Seen \*)] Flags permitted
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: * OK [UIDVALIDITY 1593717206] UIDs valid
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: * 0 EXISTS
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: * 0 RECENT
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: * OK [UIDNEXT 1] Predicted next UID
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: 21.34 OK [READ-WRITE] SELECT completed, CONDSTORE is now enabled
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] C: 22.34 IDLE
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: + idling
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] C: <4 bytes of data>
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: 22.34 OK IDLE terminated
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] C: 23.34 EXPUNGE
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] Deleting messages from "5efe31d682a5bd3d0e7f1047"
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: * 0 EXISTS
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: 23.34 OK EXPUNGE completed
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] C: 24.34 UNSELECT
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: 24.34 OK UNSELECT completed
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] C: 25.34 SELECT "INBOX/Manny SubBox" (CONDSTORE)
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] Opening "INBOX/Manny SubBox"
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: * FLAGS (\Answered \Flagged \Draft \Deleted \Seen)
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: * OK [PERMANENTFLAGS (\Answered \Flagged \Draft \Deleted \Seen \*)] Flags permitted
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: * OK [UIDVALIDITY 1593717206] UIDs valid
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: * 0 EXISTS
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: * 0 RECENT
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: * OK [UIDNEXT 1] Predicted next UID
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: 25.34 OK [READ-WRITE] SELECT completed, CONDSTORE is now enabled
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] C: 26.34 IDLE
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: + idling
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] C: <4 bytes of data>
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: 26.34 OK IDLE terminated
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] C: 27.34 EXPUNGE
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] Deleting messages from "5efe31d682a5bd3d0e7f1047"
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: * 0 EXISTS
Jul  7 19:55:28 mail wildduck-server[39387]: sill IMAP [qjjvrmam5y3vuwrf] S: 27.34 OK EXPUNGE completed

**Comment by mannyveloso** [comment]
Actually, I can't tell if this is a bug in Apple Mail or WildDuck. I'll try to repro on a clean mailbox.

**Comment by mannyveloso** [comment]
This apparently is a bug in Mac OS Mail. if you click on the top-level mailbox (the Inbox in the mail UI) mail apparently sends a stream of expunge commands on the mailbox below the INBOX.

**Comment by mannyveloso** [comment]
Just rebuilt with this mailbox hierarchy
INBOX
- SubBox1
-- SubBox2
-- SubBox3
and it happens on Mac OS X mail. 

Jul  7 20:40:31 mail wildduck-server[39541]: info IMAP [asy7yarkx64mz7cm] name      : Mac OS X Mail
Jul  7 20:40:31 mail wildduck-server[39541]: info IMAP [asy7yarkx64mz7cm] version   : 13.4 (3608.80.23.2.2)
Jul  7 20:40:31 mail wildduck-server[39541]: info IMAP [asy7yarkx64mz7cm] os        : Mac OS X
Jul  7 20:40:31 mail wildduck-server[39541]: info IMAP [asy7yarkx64mz7cm] os-version: 10.15.5 (19F101)
Jul  7 20:40:31 mail wildduck-server[39541]: info IMAP [asy7yarkx64mz7cm] vendor    : Apple Inc.

**Comment by mannyveloso** [comment]
Actually, I'll examine the network traces to see. It could be that WD is sending back a reply that mail doesn't like?

**Comment by titanism** [comment]
This is an actual bug in WildDuck, see #850
