### ISSUE TITLE
User creation during migration slows down to 47s after ~300 users

### ISSUE THREAD

**Issue by figassis** [nodemailer/wildduck#246]
I'm not sure if it's my setup or if anyone experienced this, but I during a migration of around 400 users, I noticed creating users started getting slower, and now, at around the 300 user mark, POST and PUT /users takes around 47+ seconds.

I'm running all this in k8s, but my mongo instance is external to the cluster and looks pretty snappy. Has anyone experienced this?

**Comment by louis-lau** [comment]
What are the wildduck logs like? What's the number of wildduck processes? Have you tried upping the number of processes? :)

**Comment by figassis** [comment]
nvm, the unixcrypt for sha512 is just slow, and some of my hashes have 70k rounds. Found the culprit by temporarily passing a sha256 hash for the same user, which got processed pretty quickly

**Comment by louis-lau** [comment]
Ah, that makes sense. Probably just add a bit of a delay in your loop adding users then :)

**Comment by figassis** [comment]
Quick question though, when creating users, the `await hashes.compare('whatever', data.password);` seems a bit unnecessary since it's basically guaranteed to always return false, and no crypto library will actually throw an exception, we're throwing it ourselves in the switch statement. So would it not be speedier and equally robust to simply run the switch and return a boolean to determine if we support a specific format?

**Comment by louis-lau** [comment]
Where is this? You can link specific lines on github 😁

**Comment by figassis** [comment]
https://github.com/nodemailer/wildduck/blob/master/lib/user-handler.js#L1269

**Comment by louis-lau** [comment]
I think you may be right, but not sure. Andris will probably know :)
