### ISSUE TITLE
messages with nodemailer are not saved in the database

### ISSUE THREAD

**Issue by victorriba** [nodemailer/wildduck#248]
```
	let transporter = nodemailer.createTransport({
		host: "webmail.wildduck.com",
		port: 587,
		secure: false,
		auth: {
			user: 'username',
			pass: 'password',
		},
	});
```
if I send from wildduck webmailer or thunderbird the messages are save on messages table
but if I send from a server with nodemailer the messages are sent but they are not saved in the database

can help me please? thanks

**Comment by andris9** [comment]
This is because email account client like Thunderbird uploads sent message through IMAP to "Sent Mail" folder. Nodemailer is just a SMTP client, it does not use IMAP. This is the same for most email servers, except Gmail, where SMTP messages are automatically added to IMAP as well.

**Comment by victorriba** [comment]
okk @andris9  I understand, thanks for your prompt reply
