### ISSUE TITLE
SpamAssassin & ClamAV with Wild Duck?

### ISSUE THREAD

**Issue by MohammedAl-Mahdawi** [nodemailer/wildduck#25]
Hi,

Can we use SpamAssassin & ClamAV with Wild Duck?
If the answer is no, is there any alternatives?

Kind Regards,
Mohammed

**Comment by andris9** [comment]
WildDuck does not act as MX and thus don’t provide support for these things. Instead you should use Haraka with the WildDuck plugin https://github.com/nodemailer/haraka-plugin-wildduck

**Comment by MohammedAl-Mahdawi** [comment]
@andris9 Thank you

**Comment by niftylettuce** [comment]
This might be helpful https://github.com/niftylettuce/forward-email
