### ISSUE TITLE
Problem to use mongodb server remote

### ISSUE THREAD

**Issue by Bianconiglio** [nodemailer/wildduck#250]
hi,
i have install wildduck-server with script in ubuntu 18 and with mongodb in localhost all working good.

Now i want use my remote mongodb server with username and password.

i have create database in remote mongodb and i have do a dump from localhost and restore in remote mongodb server.

in wildduck/config/default.toml in section [dbs] i have enable  @include "dbs.toml"

and in file dbs.toml i have change the connection string default to mongo="mongodb://username:password@server:27017/wildduck"

when restart wildduck service in log file i have:

wildduck-server[4532]: ERR! Db Failed to setup database connection

how can change mongodb database from localhost to remote?

**Comment by louis-lau** [comment]
Should work fine. Make sure your external mongodb is actually reachable from the server that wildduck is on. Try logging in with the mongo command line client.

**Comment by Bianconiglio** [comment]
yes mongodb remote work fine and in command line with mongo --host=remoteserver -u username -p password  work fine, there is not problem

**Comment by Bianconiglio** [comment]
now i have try again and if i remove #  from @include "dbs.toml" inside default.toml and restart daemon i have this problem 

vmi427935 wildduck-server[5872]: [/opt/wildduck/config/default.toml] /opt/wildduck/config/default.toml: Expected "#", "'", "[", "\"", "\n", "\r", [ \t] or [A-Za-z0-9_\-] but "@" found.

**Comment by louis-lau** [comment]
Yeah, don't do that 😁. `dbs.toml` is already included by default, with the `#`.

**Comment by louis-lau** [comment]
Keep in mind with that connection url it's using the `wildduck` database as the authentication source. Have you added the user in the wildduck database? Or in the admin database (I think this may be the case). What I meant with my previous suggestion is to actually use the same connection url with the mongo client, not something else.

**Comment by Bianconiglio** [comment]
ok this understand about @include ..

in default dbs.toml there is this dmongodb connection:
mongo="mongodb://127.0.0.1:27017/wildduck"

in remote server i have create database wildduck but in new mongodb connection i have put username and password of user of mongodb remote like:

mongo="mongodb://username:password@remoteserver:27017/wildduck"

in admin of remote server i dont have create other user or one user for wildduck

**Comment by louis-lau** [comment]
Mongodb users are linked to a specific database. Where did you create the user? In the admin database?

**Comment by Bianconiglio** [comment]
the username and pasword who i use is in admin database and have grant like admin

**Comment by louis-lau** [comment]
In that case try `mongodb://username:password@remoteserver:27017/wildduck?authSource=admin`

**Comment by Bianconiglio** [comment]
i have follow your example mongodb://username:password@remoteserver:27017/wildduck?authSource=admin

when i restart daemon waiting and after write:

 wildduck-server[7701]:   _error: 'connect ECONNREFUSED 127.0.0.1:27017',
 wildduck-server[7701]:   _name: 'MongoServerSelectionError',
 wildduck-server[7701]:   facility: 'wildduck',
 wildduck-server[7701]:   host: 'server',
 wildduck-server[7701]:   timestamp: 1596496952.402,
 wildduck-server[7701]:   _component: 'wildduck'
 wildduck-server[7701]: }

**Comment by louis-lau** [comment]
Hmm, that's weird. No idea how that would happen. Unless you've done something odd with your configuration?

**Comment by Bianconiglio** [comment]
i have only touch the mongodb connection string but if i remove my connection string for remote mongodb server and i put default connection string for localhost all work good

**Comment by Bianconiglio** [comment]
i have check local mongodb and there is wildduck and zone-mta but i have only export wildduck possible is the problem

**Comment by Bianconiglio** [comment]
i have find solution i have modify wrong config file i have try in begin to modify config file in /opt/wildduck/config and /opt/wilduck-webmail/config but  i must modify config in /etc/wildduck/ if i change mongodb connection of remote server and restart service work good.
