### ISSUE TITLE
Problem to receive email

### ISSUE THREAD

**Issue by Bianconiglio** [nodemailer/wildduck#251]
hi,
i have problem to receive email, for send email all work good.

provider not put limitation on port because first time when i have installed wildduck in this machine i can receive and send email.

Now with this new installation i can send email and people receive in correct way but i dont receive nothing and from account who i send there is not message.

wildduck receive email on port 25? which service use for listen on port?

i have try from remote machine to do telnet server 25 but not work

firewall have port 25 open

**Comment by louis-lau** [comment]
Inbound is handled by haraka with the haraka-wildduck plugin. It needs to use the same database as wildduck.

**Comment by Bianconiglio** [comment]
yes i see the connection string but i must change in /opt/haraka/plugin or in other place?

**Comment by louis-lau** [comment]
Yeah, there should be fine.

**Comment by Bianconiglio** [comment]
ok thank you so much i try

**Comment by Bianconiglio** [comment]
if understand correct haraka use for incoming email port 24 but port 24 accept only incoming request from localhost it's normal?

**Comment by louis-lau** [comment]
No, port 25.

**Comment by Bianconiglio** [comment]
if i check service and port on linux machine with command ss -l port 25 i dont see i se only in localhost port 24 and in plugin i have chnage connection string to mongodb remote.

i have check log of haraka there is no error only one warn

[WARN] [-] [core] smtp.ini.nodes unset, using 1

**Comment by louis-lau** [comment]
Is the haraka service actually started?

**Comment by Bianconiglio** [comment]
yes started and i solve problem, problem it's connection string i have modify string in /opt/haraka/plugin/wildduck/ but dont work and i find another file of config the same of plugin under haraka in another directory, i have modify the second file who i find and after restar service all work good. 

Thank you for help, but i want ask if you known, why there is so many file of configuration with the same content in different part ? for example in haraka there is config file under /opt/haraka/plugin/wildduck but the same file is in another place under haraka, same file same content. I dont understand why in different part and the same i find for wildduck and wildduck-webmail some file of configuration in /opt/wildduck/config /opt/wildduck-webmail/config but the same in /etc/wildduck

Thank you for help

**Comment by andris9** [comment]
WildDuck has default configuration and server specific configuration that are merged together (if a specific config value is not set in server config then default config is used). Usually you should never touch the default config files.

So if you have installed WildDuck using the default install script then the config file locations are the following:

* **WildDuck IMAP/POP3/API**: /etc/wildduck/wildduck.toml
* **WildDuck IMAP/POP3/API**: /etc/wildduck/wildduck-webmail.toml
* **ZoneMTA**: /etc/zone-mta/zonemta.toml
* **Haraka**: /opt/haraka/config/wildduck.yaml

Each config file can include another config file using the `# @include "path` directive.

WildDuck and ZoneMTA share the database config file (/etc/wildduck/dbs.toml), Haraka has a separate setup as it uses a different config loader than other components.

**Comment by andris9** [comment]
Here's a schema how config file nesting works using the `#include` directive

![pic1](https://user-images.githubusercontent.com/132242/89398846-4ed62500-d71a-11ea-86da-bf7bb95014af.jpg)

**Comment by Bianconiglio** [comment]
thank you so much for information and compliment for platform it's very cool
