### ISSUE TITLE
Constant hostname always os.hostname()

### ISSUE THREAD

**Issue by manalejandro** [nodemailer/wildduck#252]
Make this [constant](https://github.com/nodemailer/wildduck/blob/master/lib/maildropper.js#L10) configurable please, don't always use the machine name, thanks

**Comment by andris9** [comment]
Machine name is only used as a fallback if `From` address is empty, so normally it is not used.

**Comment by manalejandro** [comment]
It is used as HELO argument when make connection to the SMTP, we are using docker and it is not a FQDN domain, please reconsider it. Thanks

**Comment by andris9** [comment]
SMTP connections are not handled by WildDuck but ZoneMta. See the ZoneMta pool config file to set the hostname (/etc/zone-mta/pools.toml)
