### ISSUE TITLE
Block unencrypted connections on SMTP

### ISSUE THREAD

**Issue by imtiyaz-ideavate** [nodemailer/wildduck#253]
Hello @andris9,

Thank you for sharing such a great product....!!

Currently, I found that **SMTP(Zone-MTA)** is allowing unencrypted connections. Could you please help me with the **configuration file and the flag** which I can update to disallow any unencrypted connections on SMTP.

**Comment by louis-lau** [comment]
Do you want to block insecure smtp on submission (client to ZoneMTA) or on transmission (ZoneMTA to another mail server)?

In the future you should create ZoneMTA issues in the ZoneMTA repository :)

**Comment by Reechik8760** [comment]
Hi Louis -- what Imtiyaz and I are specifically looking for is to set the configuration file to enable STARTTLS such that all SMTP communications are encrypted.

**Comment by louis-lau** [comment]
For submission you can simply use TLS on port 465 to enforce it. For transmission, there's a plugin hook (`sender:tlserror`) that gets called when STARTTLS to the mx fails. If you pass an error there to next() I think it will make the message bounce.

**Comment by imtiyaz-ideavate** [comment]
@louis-lau : Thank you for your valuable suggestion, it was really very helpful to fix my issue.
