### ISSUE TITLE
Roadmap for adoption of Ubuntu 20.04

### ISSUE THREAD

**Issue by Reechik8760** [nodemailer/wildduck#254]
@andris9 and team -- thank you for building such a wonderful product. 

What's your roadmap to support current releases of Ubuntu such as 20.04 LTS?

Thanks!

**Comment by louis-lau** [comment]
WildDuck supports any operating system that can run nodejs, mongodb, and redis. While the installation script may not have been tested yet on 20.04, it might just work fine.

Have you tested the installation script and did you encounter any issues?

**Comment by Reechik8760** [comment]
We are in the process of testing it out now -- will be in touch shortly.

**Comment by andris9** [comment]
Current quick installation script should work with Ubuntu versions from 16.04 to 20.04.

**Comment by imtiyaz-ideavate** [comment]
@andris9 and @louis-lau 

Thanks for your response to the above query.

I tested the installation script on Ubuntu 20.04 and it works great without any additional steps.

**Comment by louis-lau** [comment]
Thanks! Added this to the docs.
