### ISSUE TITLE
Cannot authenticate to mail client

### ISSUE THREAD

**Issue by zaidysf** [nodemailer/wildduck#255]
Hi, i am just having an issue about asp, i cannot login to my mail server, can i know which fields that required to be able login to mail client? i tried to download osx/ios config file, still not able to login. i got this issue only after i added one more identity for specific email account.

**Comment by louis-lau** [comment]
Just the username, or one of the addresses for that user. And the app password as the password with or without spaces.

**Comment by zaidysf** [comment]
thank you for fast response, i am able to login now, issue on my default mail address.
one thing, how to enable ssl for outgoing mail? i've tried to register new profile on iOS and everything works fine except ssl status for outgoing mail is "no"

**Comment by louis-lau** [comment]
No idea about profiles, but ZoneMTA supports both TLS on port 465 and STARTTLS on port 587.

**Comment by louis-lau** [comment]
For mobileconfig profiles you may need to play with these config lines:
https://github.com/nodemailer/wildduck/blob/977c36a0d545cc3731654c17ac6692523f68e994/config/default.toml#L90-L94

**Comment by louis-lau** [comment]
@zaidysf HAve you resolved this? If so, please close the issue 😁
