### ISSUE TITLE
Haraka plugin for incoming email doesn't work when install with different domain and hostname

### ISSUE THREAD

**Issue by ckmd** [nodemailer/wildduck#259]
Hello, thanks for build this great mail server.

I already follow the instruction to setup the wildduck mail, and found a issues when I run the command below
`$ ./install.sh mydomain.com mail.mydomain.com`
if I define the mydomain.com same with mail.mydomain.com, the zone-mta for outbond SMTP and haraka for inbound SMTP work well without problem.
but when I define the mydomain different with mail.mydomain.com, the zone-mta for outbund SMTP works well, but the haraka for inbound SMTP doesn't work (proven by reply email from sender, that message couldn't be delivered to username@mydomain.com because the remote server is misconfigured. see technical below for more information).
do I miss some configuration ? please help me and thanks in advance

**Comment by ckmd** [comment]
Thank you very much for your insight, I already setup the mx record, spf, dkim, and dmarc. Now my mail server running well as I want.

**Comment by louis-lau** [comment]
Nice! 😁
