### ISSUE TITLE
Pipe filter to other scripts/applications/services

### ISSUE THREAD

**Issue by MohammedAl-Mahdawi** [nodemailer/wildduck#26]
Hi,

Is Wild Duck have a pipe filter? I cant find such thing in the documentation.
If the answer is no then is it possible to extend the filter feature to use pipes to other scripts/applications/services using plugins for example?

Kind Regards,
Mohammed

**Comment by andris9** [comment]
Could you elaborate a bit what do you mean? Maybe some examples? Existing filtering allows to forward messages to email addresses and also upload as files to HTTP URLs

**Comment by MohammedAl-Mahdawi** [comment]
@andris9 Thank you for your reply.

For example, say I have a PHP script or another node service running on the same server then using the pipe filter(as I imagine it, you can name it another thing) I can pipe all the incoming messages to that script/service then that script/service decide what Wild Duck should do with the message, for example, tell Wild Duck to move the message to a specific folder.

All the best,
Mohammed

**Comment by andris9** [comment]
Could this be done in Haraka as well? You could set a routing header and then filter by that header in WildDuck? Currently it is not possible to create filters based on arbitrary headers but it wouldn't be difficult to add.

So in Haraka you would so something like this:

```
// make sure that senders do not set your routing header
transaction.remove_header('X-My-Routing-Key'); 
...
// send message directly to trahs
transaction.add_header('X-My-Routing-Key', 'Trash');
```

and then in the WildDuck create a filter to send all messages where X-My-Routing-Key=Trash straight to Deleted Messages folder.

**Comment by MohammedAl-Mahdawi** [comment]
Hi @andris9 

Thank you for your reply.

Yes, I think no problem if Haraka will take care of it, and in WildDuck we can set such filter per email address.

Warm Regards,
Mohammed
