### ISSUE TITLE
feature request - generic webhook

### ISSUE THREAD

**Issue by mleader1** [nodemailer/wildduck#261]
Hi,

We've been testing Wildduck internally for about 6 months and really loved it.  Whilst our main goal is integrate the mail service into our internal system, we do require lots of 'triggers', will that be an easy job to simply add a very simple webhook mechanism with the following:

We have already got most of the functionality available through RESTful API.  Can we:
1. Create a simple table to register a set of external endpoints (for use in events)
2. For each action related API endpoint (such as user created, address updated, domain created etc. etc) post the JSON result to the registered endpoint

For step 1 - it can be a simple endpoint set for creating and deleting endpoints

For step 2 - as a progress of the development, we can firstly make all APIs to always trigger the webhook endpoints (therefore the registered endpoints are like 'catch-all' type endpoint listening to all events). And then gradually to open up functionality allowing each endpoint to be limited to various events.

**Benefits:**   That opens the door for all sorts of possibilities and make the Wildduck much more flexible for any integration that others may want to achieve.  

The above is just point of suggestion.  Shame I'm not a NodeJs developer otherwise I could've contributed!

Cheers

**Comment by andris9** [comment]
I agree, webhooks would make a lot of sense. I recently built webhook support for my other IMAP related project [IMAP API](https://imapapi.com), I'll see if I can reuse it somehow.

**Comment by andris9** [comment]
First draft of webhooks is now available. You need to have the latest version from git installed to use it.

You can find the API documentation [here](https://docs.wildduck.email/api/#api-Webhooks) and available event types [here](https://github.com/nodemailer/wildduck/blob/master/lib/events.js#L11-L39)
