### ISSUE TITLE
email sending issue

### ISSUE THREAD

**Issue by codemagician45** [nodemailer/wildduck#264]
I installed wildduck email server and tested all apis
dealing with user, address, are working well... (I installed manually like this: https://docs.wildduck.email/#/general/install?id=manual-install)
But after I create domain and create user with that domain, I cant send message to gmail or other emails with created new email.
Domain is alive now
Please help me how can I submit message

**Comment by louis-lau** [comment]
Wildduck is an IMAP/POP3 server. It has LMTP support, but it's not what you'd generally use as it's quite basic.

If you intend to have a fully functional email server you'd use haraka with the wildduck plugin for inbound, and zonemta with the wildduck plugin for outbound. Additionally use the rspamd plugin in haraka for spam filtering. Please take a look at the "Additional software" section in the docs.

The setup script installs all of this for you.

**Comment by classy-dev** [comment]
Thank you for your kind teaching me.
well... can you explain more detail how to install haraka, zonemta, rspamd plugins after manual install like me?
And also can provide link for "Additional Software"?

**Comment by classy-dev** [comment]
Thanks for your kind explain, let me try to install those plugins and let me know you again
Thanks again

**Comment by classy-dev** [comment]
Hello, louis-lau
Can you help me again?
I was facing this part. https://docs.wildduck.email/#/additional-software/wildduck-mta

I was going to install 3 things:
https://github.com/zone-eu/zone-mta
https://github.com/nodemailer/zonemta-wildduck
https://github.com/nodemailer/wildduck-mta

I installed zone-mta-template first
but I cant install zonemta-wildduck and this is error

loadDep:wildduck → get    ▀ ╢██████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
npm ERR! Linux 5.3.0-1028-aws
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "zonemta-wildduck" "--save"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/npm-debug.log

how can I fix it? and after zonemta install how can I use this plug in wildduck platform for sending email to other domain?
Thanks

**Comment by louis-lau** [comment]
Update your npm:
https://github.com/npm/cli/issues/681#issuecomment-573854123

**Comment by classy-dev** [comment]
Thanks.
I fixed it and may I ask another question?
After install zonemta-wildduck and wildduck-mta, I can see config.example.toml and wildduck-mta.toml
They are the same in content

1. First question
So For using zonemta-wildduck plugin in the wildduck, then I need to install zonemta-wildduck plugin inside the wildduck and should configuration? Or I need to use wildduck-mta for wildduck?

2, Second question
------------------ here 'example.com' is domain where wildduck is installed?--------
------------------ what I need to change else for my own configuration?------------
# plugins/wildduck.toml
["modules/zonemta-wildduck"]
enabled=["receiver", "sender"]

# to which SMTP interfaces this plugin applies to. Use "*" for all interfaces
interfaces=["feeder"]

# optional hostname to be used in headers
# defaults to os.hostname()
hostname="example.com"

# How long to keep auth records in log
authlogExpireDays=30


disableUploads=false # if true then messages are not uploaded to Sent Mail folder
uploadAll=false # if false then messages from Outlook are not uploaded to Sent Mail folder

# SRS settings for forwarded emails
# ---------------------------------

["modules/zonemta-wildduck".srs]
    # Handle rewriting of forwarded emails. If false then SRS is not used
    # Only affect messages that have interface set to "forwarder"
    enabled=true

    # SRS secret value. Must be the same as in the MX side
    secret="secret value"

    # SRS domain, must resolve back to MX
    rewriteDomain="example.com"

# DKIM Settings
# -------------

["modules/zonemta-wildduck".dkim]
    # If true then also adds a signature for the outbound domain
    signTransportDomain=false

    # If set then decrypt encrypted DKIM keys using this password
    #secret="a secret cat"

    # Cipher to use to decrypt encrypted DKIM keys
    #cipher="aes192"


["modules/zonemta-wildduck".gelf]
    enabled=false
    component="mta"

    ["modules/zonemta-wildduck".gelf.options]
        graylogPort=12201
        graylogHostname='127.0.0.1'
        connection='lan'

-----------------------------------------------------
many thanks 👍

**Comment by louis-lau** [comment]
Hey @classy-dev, please use code blocks to make your config snippet readable:
https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks

As for your fist question, you seem to have misunderstood. wildduck-mta = ZoneMTA with the zonemta-wildduck plugin. That's all.

**Comment by classy-dev** [comment]
"wildduck-mta = ZoneMTA with the zonemta-wildduck plugin" what does this mean in the real application?
```
# plugins/wildduck.toml
["modules/zonemta-wildduck"]
enabled=["receiver", "sender"]

# to which SMTP interfaces this plugin applies to. Use "*" for all interfaces
interfaces=["feeder"]

# optional hostname to be used in headers
# defaults to os.hostname()
hostname="example.com"

# How long to keep auth records in log
authlogExpireDays=30


disableUploads=false # if true then messages are not uploaded to Sent Mail folder
uploadAll=false # if false then messages from Outlook are not uploaded to Sent Mail folder

# SRS settings for forwarded emails
# ---------------------------------

["modules/zonemta-wildduck".srs]
    # Handle rewriting of forwarded emails. If false then SRS is not used
    # Only affect messages that have interface set to "forwarder"
    enabled=true

    # SRS secret value. Must be the same as in the MX side
    secret="secret value"

    # SRS domain, must resolve back to MX
    rewriteDomain="example.com"

# DKIM Settings
# -------------

["modules/zonemta-wildduck".dkim]
    # If true then also adds a signature for the outbound domain
    signTransportDomain=false

    # If set then decrypt encrypted DKIM keys using this password
    #secret="a secret cat"

    # Cipher to use to decrypt encrypted DKIM keys
    #cipher="aes192"


["modules/zonemta-wildduck".gelf]
    enabled=false
    component="mta"

    ["modules/zonemta-wildduck".gelf.options]
        graylogPort=12201
        graylogHostname='127.0.0.1'
        connection='lan'

```

**Comment by louis-lau** [comment]
What are you asking when you say "what does this mean"? It means that wildduck-mta is simply a template. In reality it's ZoneMTA with the zonemta-wildduck plugin installed. So when you say you've installed both wildduck-mta and zonemta-wildduck you've made a mistake somewhere. Because wildduck-mta already has zonemta-wildduck installed. Just like stated on the docs page: https://docs.wildduck.email/#/additional-software/wildduck-mta

> here 'example.com' is domain where wildduck is installed?

Where haraka is installed, I think.

**Comment by classy-dev** [comment]
_"1. First question
So For using zonemta-wildduck plugin in the wildduck, then I need to install zonemta-wildduck plugin inside the wildduck and should configuration? Or I need to use wildduck-mta for wildduck?"_

I have mentioned before, I installed wildduck on my server and finished api by documentation.
To send email by wildduck, I need to install zonemta-wildduck plugin inside wildduck and should make configuration?
Or I need to install wildduck-mta inside wildduck?
---------
This is what I want to know

**Comment by louis-lau** [comment]
Nothing goes inside wildduck. Wildduck only handles imapand pop3. Zonemta is a seperate application. Haraka is a seperate application.

You use the wildduck-zonemta plugin to connect zonemta with wildduck. You use the haraka-wildduck plugin to connect haraka with wildduck.

wildduck-zonemta is a plugin for zonemta.
haraka-wildduck is a plugin for haraka.

wildduck-mta = zonemta + wildduck-zonemta

haraka = inbound smtp
zonemta =outbound smtp

**Comment by classy-dev** [comment]
So to use wildduck zonemta plugin, after install https://github.com/nodemailer/zonemta-wildduck
and change domain simply in the  config.example.toml, then I can send email correctly in the wildduck, do you think?

**Comment by louis-lau** [comment]
You would move the example config of the plugin to `config/plugins/wildduck.toml` in the zonemta template. After configuring zonemta correctly you should be able to send email.

**Comment by classy-dev** [comment]
Ok, let me try
Many thanks again :)
