### ISSUE TITLE
User enumeration using apiUser/getLoggedUsers

### ISSUE THREAD

**Issue by Reechik8760** [nodemailer/wildduck#265]
Is there a configuration or best practice available from wildduck to address the problem of user enumeration when making direct API calls via /apiUser/getLoggedUsers

We have implemented a captcha on the front end, but that has not addressed this issue.

**Comment by louis-lau** [comment]
> /apiUser/getLoggedUsers

What do you mean exactly? That's not an api endpoint in wildduck as far as I know.

**Comment by Reechik8760** [comment]
My apologies, I made a mistake. Please disregard.
