### ISSUE TITLE
Install script fails on Debian 10!

### ISSUE THREAD

**Issue by PontusTideman** [nodemailer/wildduck#268]
Spinned up a brand new Debian 10 droplet this morning, but the scripts fails to install on Debian 10.

`Cannot write to '-' (Broken pipe).`

`Err:10 http://repo.mongodb.org/apt/ubuntu buster/mongodb-org/4.2 Release       
  404  Not Found [IP: 2600:9000:2062:6c00:1e:e933:9800:93a1 80]`

`Err:4 https://deb.nodesource.com/node_14.x buster InRelease 
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 1655A0AB68576280
Err:5 http://rspamd.com/apt-stable buster InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY FFA232EDBF21E25E
Reading package lists... Done    
E: The repository 'http://repo.mongodb.org/apt/ubuntu buster/mongodb-org/4.2 Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
N: Repository 'http://deb.debian.org/debian buster InRelease' changed its 'Version' value from '10.5' to '10.6'
W: GPG error: https://deb.nodesource.com/node_14.x buster InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 1655A0AB68576280
E: The repository 'https://deb.nodesource.com/node_14.x buster InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://rspamd.com/apt-stable buster InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY FFA232EDBF21E25E
E: The repository 'http://rspamd.com/apt-stable buster InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
/root/04_install_import_keys.sh: line 47: apt-add-repository: command not found`

`/root/00_install_global_functions_variables.sh: line 240: /var/opt/wildduck.git/hooks/update: No such file or directory
chmod: cannot access '/var/opt/wildduck.git/hooks/update': No such file or directory
/root/07_install_wildduck.sh: line 32: git: command not found
cp: cannot stat '/opt/wildduck/config': No such file or directory
mv: cannot stat '/etc/wildduck/default.toml': No such file or directory
sed: can't read /opt/wildduck/emails/00-example.json: No such file or directory
sed: can't read /etc/wildduck/imap.toml: No such file or directory
sed: can't read /etc/wildduck/pop3.toml: No such file or directory
/root/07_install_wildduck.sh: line 45: /etc/wildduck/lmtp.toml: No such file or directory
cat: /etc/wildduck/wildduck.toml: No such file or directory
sed: can't read /etc/wildduck/wildduck.toml: No such file or directory
sed: can't read /etc/wildduck/sender.toml: No such file or directory
/root/07_install_wildduck.sh: line 59: npm: command not found
chown: cannot access '/var/opt/wildduck.git': No such file or directory`

And much much more... Do you want me to fix this with a PR?

**Comment by andris9** [comment]
Install script is supposed to run on Ubuntu only as this is the platform I use for testing. If you could manage to get it working for Debian as well (without breaking support for Ubuntu 16.xx-20.xx) then it would be great and I'd happily merge that.

**Comment by PontusTideman** [comment]
Sure, I can check if I can solve it. 👍
