### ISSUE TITLE
Best practice to add new domains?

### ISSUE THREAD

**Issue by PontusTideman** [nodemailer/wildduck#269]
First, I've searched the issues and also Google to find the solution, but no specific solution has been provided with a hands on?

Just, use this script or add in the domain array.

`    # allowed domains for new addresses
    domains=["localhost"]`

Yes, but how? Have tried some solutions, and all ends up with a bad gateway for the main domain.
When added 2 rows with domains=, it ended up with domainA,domainB.

**Comment by louis-lau** [comment]
I'm not sure what you mean. You should be aware that wildduck has no restriction on domains at all. Using the api you can add whatever address you want.

The "create new account" form in wildduck webmail is limited to the domains specified in that config variable.

**Comment by andris9** [comment]
WildDuck does not care about domain names. The domain array is needed only by the webmail to limit domains for signed up accounts. Ie. there is no point allowing to sign up using gmail.com when WildDuck MX server is not able to receive emails for that address.

<img width="595" alt="Screenshot 2020-10-08 at 12 44 23" src="https://user-images.githubusercontent.com/132242/95442499-1f36d980-0964-11eb-8be0-42bbac4d774e.png">

If you are adding accounts via API directly, then you can use any domains you like, as long as the DNS MX records point to that WildDuck server.

For the webmail component, here's how it is defined for webmail.wildduck.email (config file location is`/etc/wildduck/wildduck-webmail.toml`):

```toml
[service]
    domains=["wildduck.email", "уайлддак.орг", "wildduckg4hslfia.onion", "3yu6fhi3j5g3sqb3p343rdufvjam42hqs7p7xptujl4bx6y3y2ykcvyd.onion"]
```

PS. About config files. If you used the installation script then all config files reside in /etc/wildduck. Values from these files are merged with the default config files in the code directory (/opt/wildduck/config). So do not edit files in /opt, only edit these in /etc

**Comment by PontusTideman** [comment]
Cheers!

This is exactly what I was looking for. 👍
