### ISSUE TITLE
Forward existing email addresses

### ISSUE THREAD

**Issue by figassis** [nodemailer/wildduck#270]
While building an email service, I get many requests to forward incoming email to old addresses, like gmail, because they're used to the UI. So I noticed that in WD you can only create new forwarded addresses, not update existing ones to forward incoming mail to a target address.

I haven't looked at the code for that yet, but off the bat, is this something you could consider implementing or is there a reason an address can't be both forwarded and deliver mail locally?

Thanks!

**Comment by louis-lau** [comment]
Sure you can, just set `targets` on the user: https://docs.wildduck.email/api/#api-Users-PutUser

You can also create a filter which forwards email.

**Comment by figassis** [comment]
Hi, that's amazing. Not sure how I overlooked that, thanks! However, I hit a snag, which might have more to do with my setup, not sure.

When sending email to a user with a @gmail.com target, the server gets the message, but the target does not. Gives a `Could not find a valid Account ID` error. I'm not sure what that refers to, since I expect the target to not be valid within wildduck, but to be valid within gmail. Also, it does seem like WD has connected to gmail, and the error comes after? So is this a gmail error, if so, why would it attempt to check if the original sender is valid in my server?

```bash
CONNECTING domain=gmail.com port=587
CONNECTED domain=gmail.com mx=my.relay.net[123.123.123.123] src=myserver[10.200.135.63]
REJECTED[block] from=sender@email.com[SRS0=26b4=DR=email.com=sender@wildduckserver.com] to=target@gmail.com src=10.200.135.63 mx=my.relay.net[123.123.123.123] id=<4503d673-af01-4439-acf5-32ca81d10a4c@email.com> (550 5.7.1 Could not find a valid Account ID (0) for the given domain(wildduckserver.com) (id: 5Edj7G))
```

**Comment by figassis** [comment]
I think this is more related to my relay server. Just tested with a target on the same WD server and got the same error. I think the spam filter is checking if the sender is valid in my server. So nvm, the forwarding seems to work, just need to see if I can configure the relay server better.

**Comment by louis-lau** [comment]
> mx=my.relay.net

Yeah that error seems to be coming from your relay server.
