### ISSUE TITLE
Threading like gmail

### ISSUE THREAD

**Issue by imtiyaz-ideavate** [nodemailer/wildduck#275]
@andris9 Thank you for sharing such a great product.

Please advise me on how I can achieve the threading the same way as Gmail is doing. Gmail shows the thread of an email as a separate tile from Sendbox and Inbox.

**Comment by louis-lau** [comment]
When [getting a message](https://docs.wildduck.email/api/#api-Messages-GetMessage) it has a property `thread`, you can then use that thread id to [search for messages](https://docs.wildduck.email/api/#api-Messages-GetMessagesSearch) that are in the same thread.
