### ISSUE TITLE
How to migrate to another mail server to wildduck mail server ?

### ISSUE THREAD

**Issue by ckmd** [nodemailer/wildduck#276]
Hello,

I already installed wildduck mail server and succesfully try it to send and receive email to another mail domain. but previously in my community already use another mail server (zimbra and iredmail), my question is how to migrate the whole data from previously mail server (zimbra and iredmail) to this new wildduck mail server ? do i just copy the database or there is another way ?

thanks in advance

**Comment by louis-lau** [comment]
Someone already wrote a basic migration guide: https://docs.wildduck.email/#/general/migration-guide

**Comment by louis-lau** [comment]
Basically, recreate all your users using the api, or wildduck webmail. Then migrate like you would any other imap server with something like imapsync or mbsync, or use the [import-maildir](https://github.com/nodemailer/import-maildir) tool if your current server uses maildir.

The same is true if you want to migrate any imap server. Recreate accounts and migrate the emails.

**Comment by ckmd** [comment]
> Basically, recreate all your users using the api, or wildduck webmail. Then migrate like you would any other imap server with something like imapsync or mbsync, or use the [import-maildir](https://github.com/nodemailer/import-maildir) tool if your current server uses maildir.
> 
> The same is true if you want to migrate from any imap server to any other imap server. Recreate accounts and migrate the emails.

thanks for your answer, so i have to recreate the accounts manually before migrate the mail data right ?
but how when I use iredmail, there are multiple level of account (global, admin, and user) then migrate it to wildduck. does wildduck also support multiple level of account also ? because when i check the api documentation in mydomain/api/swagger, wildduck only support one level of account (user only). please cmiiw

thanks in advance

**Comment by louis-lau** [comment]
> does wildduck also support multiple level of account also

Wildduck itself does not have an administration panel. So yes, there are only users/email accounts.

> when i check the api documentation in mydomain/api/swagger

Wildduck does not have an openapi/swagger spec so I'm not sure what you're referring to.
