### ISSUE TITLE
AWS migration done - ZoneMTA is not receiving inputs from Wildduck

### ISSUE THREAD

**Issue by lindaravindran1612** [nodemailer/wildduck#285]
We recently migrated our EC2 instances to a new AWS account and both ZoneMTA and Wildduck are on one EC2 instance. When we action out from the UI for a reset password request. Wildduck is working and shows 200 but no message sent to zonemta. Please help correct this issue

#Wildduck 
#109 
#zonemta

**Comment by louis-lau** [comment]
You seem to have opened 2 issues, closing this one.
