### ISSUE TITLE
AWS migration done - ZoneMTA is not receiving inputs from Wildduck

### ISSUE THREAD

**Issue by lindaravindran1612** [nodemailer/wildduck#286]
We recently to the AMI from our older EC2 which has zonemta and wildduck to a new AWS account - new machine with this AMI and restarted both ZoneMTA and Wildduck. We have also changed the Mongodb details. 
When we are trying to send an email, wildduck is acknowledging that request and sending 200 response but its not calling zoneMTA (no log is coming inside zoneMTA service which is running in the new instance, however the logs get generated in the older instance).
We have not changed any ip address/domain anywhere. Do we need to change the ip address to make it work
Please help!

#Wildduck 
#109 
#zonemta

**Comment by andris9** [comment]
Make sure that both wildduck and zonemta are using the same database settings. Wildduck does not communicate with zonemta directly, it writes messages to outbound queue in the db and zonmta picks messages from that database for delivery.

**Comment by lindaravindran1612** [comment]
They are connected to the same DB. But wild duck is not writing to the DB. How do we resolve this @andris9 

> Make sure that both wildduck and zonemta are using the same database settings. Wildduck does not communicate with zonemta directly, it writes messages to outbound queue in the db and zonmta picks messages from that database for delivery.

**Comment by andris9** [comment]
Well it writes that data somewhere, otherwise you’d get an error. Try to figure out if these messages are written for example to a different database server or different name or different database collection.

**Comment by lindaravindran1612** [comment]
Hi @andris9 , now we have mapped wildduck and zonemta to the same database. wildduck writes correctly to our mongodb but we are getting an error on zonemta. enclosing the error. please advise!
![image](https://user-images.githubusercontent.com/33597432/99362403-7754ea00-28d9-11eb-8d39-1d3a373a158c.png)

**Comment by louis-lau** [comment]
It says it can't reach the mx. Have you requested port 25 already?

https://aws.amazon.com/premiumsupport/knowledge-center/ec2-port-25-throttle/

**Comment by lindaravindran1612** [comment]
port 25 is open

**Comment by louis-lau** [comment]
Try `curl -v smtp://gmail-smtp-in.l.google.com`, just to be sure.

**Comment by chenchunaidu** [comment]
@louis-lau @andris9 
we opened port 25 but now we are getting other error
"The IP you're using to send mail is not authorized to send email directly to our servers. Please use the SMTP relay at your service provider instead. Learn more at https://support.google.com/mail/?p=NotAuthorizedError k184si7802718pgc.151 - gsmtp)"

**Comment by louis-lau** [comment]
That isn't an issue with wildduck. Try reading the linked article.

> The determination of whether or not an IP address is authorized to send mail is made by the ISP that provides you with the IP address.

So I guess contact Amazon?

**Comment by lindaravindran1612** [comment]
Hi @louis-lau @andris9 we are having great trouble configuring the google smtp on wildduck and zonemta. We got the port opened for the ip by AWS and added the google smtp details 
host name: smtp-relay.gmail.com and ports: 25 
also tried port 587 however its still giving us the same issue of ip not recognised and aws mentioned that our mails are still going through the MX records instead of smtp.
Please let us know where exactly are these details to be entered in wildduck and zonemta for it to work correctly using the smtp relay.

**Comment by andris9** [comment]
When sending from AWS you have to use Elastic IP's and also request sending limit removal and set PTR records using this [form](https://aws-portal.amazon.com/gp/aws/html-forms-controller/contactus/ec2-email-limit-rdns-request) for these IP addresses.
