### ISSUE TITLE
Prevent user send spam

### ISSUE THREAD

**Issue by Bianconiglio** [nodemailer/wildduck#290]
HI,
there is some system for prevent user send spam with wildduck server?

I have decrease the forwards limit for prevent user send massive email but other system for prevent?

**Comment by louis-lau** [comment]
For smtp? Yes, you can connect zonemta to an rspamd instance:
https://github.com/zone-eu/zone-mta/blob/6a8d9c35c565316879c22a7496c60843eca6ee5a/config/default.js#L101-L111

**Comment by Bianconiglio** [comment]
thank you for answer, it's possibile do this configuration only in zone-mta versione 1.1 or it's possible do in version 1.0 too?

**Comment by louis-lau** [comment]
1.0 was a beta release, last released 1 aug 2017. The current version is 2.3.3.

Are you sure you're on 1.0? And if so, why?

**Comment by Bianconiglio** [comment]
sorry you have right my zone-mta is 2.3.0. but i dont have file default.js in etc/zone-mta/config or in /opt/zone-mta/config i can just create the file and restart zone-mta?

**Comment by v-byte-cpu** [comment]
It is linked to https://github.com/zone-eu/zone-mta/issues/237

**Comment by Bianconiglio** [comment]
I tried to implement rspamd in zone-mta to block users we spam others but the standard zone-mta configuration is different from what is installed with wildduck. Do you need to create a specific plugin for wildduck?
