### ISSUE TITLE
Joi.ip not validating ip correctly

### ISSUE THREAD

**Issue by zero245** [nodemailer/wildduck#293]
The current master will fail if installed as it is. 
if I changed the Joi.ip validation to max 255 it will work

  8 const sessIPSchema1 = Joi.string()
  9     .ip({
 10         version: ['ipv4', 'ipv6'],
 11         cidr: 'forbidden'
 12     })
 13     .label('Client IP');

---
const sessIPSchema = Joi.string().max(255).label('Client IP');

Could be the install script need to be changed as it may not be getting the correct ip.  However either just want to file this here for now.

**Comment by andris9** [comment]
What's the IP that fails? Could it be that you use IPv6 interface and convert IPv4 addresses to pseudo IPv6, eg. `ffff::127.0.0.1` or something like that?

**Comment by zero245** [comment]
it is possible. However, it is currently hard to inspect the instance. I can also post this on Joi.

**Comment by zero245** [comment]
I'm using accessToken so ip validation is not necessary.

**Comment by zero245** [comment]
is there a config to turn off ip validation?

**Comment by andris9** [comment]
The current behaviour is correct one, there is nothing wrong with Joi, pseudo IPv6 IP addresses are not valid addresses and should fail. You should provide valid IP address or not use any addresses at all.

**Comment by andris9** [comment]
If the IP is provided by wildduck-webmail then edit /etc/wildduck/wildduck-webmail.toml and in the [www] block change `host=false` to `host="0.0.0.0"` which disables IPv6

**Comment by zero245** [comment]
ok thanks Andris.

**Comment by zero245** [comment]
Just FYI here is the ip. 

erver[6966]: info Gelf {"short_message":"WILDDUCK HTTP [POST /authenticate] FAILED","_remote_ip":"127.0.0.1",

**Comment by zero245** [comment]
Just FYI, changing the config file has no effect. I just leave the ip as how I changed it for now to get it working.
