### ISSUE TITLE
reset password api return 405

### ISSUE THREAD

**Issue by zero245** [nodemailer/wildduck#294]
http://docs.wildduck.email/api/#operation/resetUserPassword

calling this returns 

(node:12689) UnhandledPromiseRejectionWarning: HTTPError: Response code 405 (Method Not Allowed)

This method ran just fine. Are there other steps need to enable password reset for a user.  Auth token is set. 
http://docs.wildduck.email/api/#operation/getUsers

**Comment by andris9** [comment]
How do you call this method? I tried it and it seems to work

```
curl -XPOST "http://localhost:8080/users/5eb233c09dedc083791986bb/password/reset" -H 'content-type: application/json' -d '{
>     "ip": "127.0.0.1"
> }'
{
  "success": true,
  "password": "ZrQG9jVZGEfR",
  "validAfter": "2020-11-22T20:50:23.450Z"
}
```

**Comment by zero245** [comment]
I was trying got. However, I can see that it is got config issue. Feel free to close this ticket.
