### ISSUE TITLE
setup advice

### ISSUE THREAD

**Issue by DuredhelFinceleb** [nodemailer/wildduck#295]
Hi,

First I must say that I'm totally incompetent with MongoDb having never used it...
I've looked into MongoDb doc and so far I'm a bit overwhelmed.
I hope I don't have to become a MongoDB specialist to use WildDuck, I just don't have the resources for that at the moment.

I want to ensure that there's always a server up for the domains: I know that SMTP servers are supposed to retry sending emails if they have no answer but I want that to happen only in case of major issue at my hosting provider
For "simple" server unavailibity, I want to have an other server able to keep on serving the domains

So I'll either go for 2 servers behind a load-balancer or for 2 publics servers & 2 MX records with the same priority (or just 1 MX record pointing to 2 A records)
My intention is to use the install script on both servers.
I understand that WildDuck is stateless, so both servers can serve the same domains right away
But of course, I guess I need their respective MongoDBs to be in sync somehow otherwise users won't ever see all of thier mails at once.
How would you do that?

**Comment by louis-lau** [comment]
You do need some mongodb knowledge in order to create a high availability cluster. MongoDB calls it a replica set. You will need a minimum of 3 servers. Only 2 of them need to hold the actual data, the third can be a cheap vps.

I suggest you read through this: https://docs.mongodb.com/manual/replication/
Knowledge of mongodb also comes in handy when you have issues, but that's the

**Comment by louis-lau** [comment]
> My intention is to use the install script on both servers.

I read over this. Out of the box that will set up 2 completely seperate nodes. After running the install script you'd have to alter the mongodb configuration and create a replica set. Then alter the mongodb urls in all application configs to point to the mongodb replica set.

The nodes will also need to be configured to use the same redis databases. Redis can be made highly available with redis sentinel.

**Comment by DuredhelFinceleb** [comment]
> Out of the box that will set up 2 completely seperate nodes.

I suspected as much. But at least a lot of the heavy lifting will be done with the scripts, won't it?

OK then I'll have a good look at the replica documentation. Thanks for telling me I'll need 3 servers, I had missed that info.
I guess all 3 servers have to be in the same vlan so I'll have to go for the load-balancer option
Just in case: can I start with 1 server and later on add replication? Or do replicas have to be set up from the start?

is redis sentinel installed by the script?

**Comment by louis-lau** [comment]
> But at least a lot of the heavy lifting will be done with the scripts, won't it?

Exactly!

> can I start with 1 server and later on add replication? 

Yes, luckily mongodb has a lot of documentation. See here : https://docs.mongodb.com/manual/tutorial/convert-standalone-to-replica-set/
You may also want to read the tutorial for setting up a replica set to get more context.

> is redis sentinel installed by the script?

No, the script is for a single node setup. I personally don't have experience with redis sentinel, but here's the config section for wildduck:
https://github.com/nodemailer/wildduck/blob/1e1417cedb621b9539bf73b067812c6421d13ffe/config/dbs.toml#L34-L47

**Comment by DuredhelFinceleb** [comment]
Thanks a lot for your help!
