### ISSUE TITLE
EUPL

### ISSUE THREAD

**Issue by zero245** [nodemailer/wildduck#296]
Hi, this is more a general question regarding the license that wildduck is release under.  
EUPL?  

I know that EUPL is compatible with GPL. Just wonder if these part of the GPL:
https://www.gnu.org/licenses/gpl-faq.html#InternalDistribution

also hold true for wildduck? We are making some internal changes to the code. It will be only used for internal.

**Comment by andris9** [comment]
I can’t give license advice, you have to figure out the details yourself. Good overview of EUPL can be found here: https://choosealicense.com/licenses/eupl-1.2/
