### ISSUE TITLE
open ports

### ISSUE THREAD

**Issue by DuredhelFinceleb** [nodemailer/wildduck#297]
Hi !

Regarding port 80, I've noticed that closing it breaks the install script when it installs let's encrypt certs
I've opened it & proceeded with installation.
Now can I close it again or does it need to stay open for the certs renewal script?

How do I open port 465 (SMPT SSL) ?. I know it's deprecated but it's still widely used plus there are still organizations which blocks 587

I'm not sure how to enable both IMAP secured on 993 & IMAP STARTTLS on 143
Now really stressed about it though as I still haven't seen a network blocking 993

Can port 25 be safely closed or does it need to stay opened?

**Comment by louis-lau** [comment]
> does it need to stay open for the certs renewal script

Yes, I believe whatever is installed with the setup script uses let's encrypts HTTP challenge. So port 80 needs to be open.

> How do I open port 465 (SMPT SSL)

In `/etc/zone-mta/interfaces/` you'll find `feeder.toml`. It contains the config for the default feeder. You can create a second feeder, for example `feeder2.toml` with configuration for port 465 with implicit TLS instead of STARTTLS. However, there is the following notice in the default config: 
```toml
# set to true to start in TLS mode if using port 465
# this probably does not work as TLS support with 465 in ZoneMTA is a bit buggy
secure=false
```
This was added 3 years ago, I'm not sure if this is still the case. @andris9 may know.

> I know it's deprecated

While the port assignment was revoked shortly after it's introduction, it's recently been reassigned, and it's actually now recommended over port 587 with STARTTLS. See [RFC 8314](https://tools.ietf.org/html/rfc8314).

> enable both IMAP secured on 993 & IMAP STARTTLS on 143

You can add more interfaces to `/etc/wildduck/imap.toml`. However, STARTTLS isn't widely used for IMAP and POP3. I see no reason to offer it.

> Can port 25 be safely closed or does it need to stay opened?

Only if you don't plan to recieve any email. Port 25 is used for email transmission, so it must be open if you want to receive emails. In this setup it can't be used for email submission.

**Comment by DuredhelFinceleb** [comment]
OK then I'll left port 80 opened
Will try to see if I can allow just let's encrypt requests and redirect everything else to 443. Or else, if I can get the let's encrypt scripts work with https

As for port 465, I've look into the config file you pointed and saw the warning about zone-mta & TLS on 465 ==> I'll leave this aside for the moment.

For STARTTLS and IMAP, you're right and I won't bother with it 🙂 

As for port 25, I naively thought that SMTP server could communicate with one another using 465 or 587. So it's still 25 then: OK I'll keep it opened

Thanks again for your help
I'm about to connect a second domain to my setup, guess I'll need Ducky Panel soon 🙂

**Comment by andris9** [comment]
I _think_ that using 465 should be fine by now. I did fix some issues with it but I have not used it in actual production.

**Comment by DuredhelFinceleb** [comment]
Thanks.
I'm going to try and activate it

**Comment by louis-lau** [comment]
> As for port 25, I naively thought that SMTP server could communicate with one another using 465 or 587.

Understandable! But those ports are only for submitting emails to an MSA. Keep in mind that STARTTLS is also used on port 25, if both ends support it.

**Comment by DuredhelFinceleb** [comment]
> Thanks.
> I'm going to try and activate it

hmm... fail
first I could not get both 465 & 587 at the same time
I added a feeder2.toml in /etc/zone-mta/interfaces as suggested and restarted both zone-mta & wildduck (well killed the processes as they auto-restart. Could not find a cleaner way. Does this use pm2?)
Upon restart whatever I do I only get either 465 or 587, I guess it depends on which interface conf file is read first

anyway, I've end up trying with just my feeder2.toml to test 465
`[feeder]
enabled=true
processes=1
maxSize=31457280
host="0.0.0.0"
port=465
authentication=true
maxRecipients=1000
starttls=false
secure=true`

I've also updated /etc/zone-mta/plugins/wildduck.toml so that interfaces is set to ["feeder2"]
Changed Thunderbird SMTP conf from 587-STARTTLS to 465-SSL/TLS
Thunderbird connects to the server but gets stuck trying to send the mail and ends up says there's a timeout
Looked at the logs for both wildduck-server & zone-mta and did not see any errors

Well, going back to 587 now.
As for 465, guess I'll cross that bridge when I come to it.

**Comment by DuredhelFinceleb** [comment]
About port 80, yes it has to stay open (unless you're OK with doing DNS-01challenges)
It is possible to change nginx config to redirect all requests to 443 save those used by acme.sh
```
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name  _;
    root /var/www/html;
    location /.well-known/acme-challenge/ {
       try_files $uri =404;
    }
    location / {
        return 301 https://$host$request_uri;
    }
}
```

Refer to this for a full discussion [https://community.letsencrypt.org/t/renewing-via-port-443/106771/3](url)

**Comment by DuredhelFinceleb** [comment]
About port 465, got it working! 😄 

Setup instructions starting for install script (for Ubuntu 20.04 LTS) as root
* ufw allow 465/tcp
* cd /etc/zone-mta/interfaces
* cp feeder.toml feeder_465.toml
* edit feeder_465.toml:
** [feeder] >> [feeder_465]
** port=587 >> port=465
** starttls=true >> starttls=false
** secure=false >> secure=true
* cd /etc/zone-mta/plugins
* edit wildduck.toml
** interfaces=["feeder"] >> interfaces=["feeder", "feeder_465"]
* systemctl restart zone-mta
