### ISSUE TITLE
Arm64 Arm32 Docker Support

### ISSUE THREAD

**Issue by tmassey** [nodemailer/wildduck#298]
I am very interested in this project as it addresses some needs in my startup. However my Entire Datacenter right now is a Docker Swarm Cluster running on Raspberry Pi's. I realize that's not considered enterprise; however from a developer perspective this is a pretty cheep setup but I would love for your wildduck system compiled for Arm64 and I can help with that and supply a docker file. I could fork and do this on my own but I really think it would be best to share that with your community.

**Comment by louis-lau** [comment]
Currently builds are being done on docker hub. Which doesn't seem to be capable of multi-arch. So the build process would have to be done in something like a github workflow.

It's also worth noting that there's no published docker image for haraka, only a community made dockerfile that's not officially supported. Zone-mta currently has no dockerfile. And rspamd doesn't publish a docker image themselves either.

I hope it will some day be possible to pull the complete wildduck stack from docker hub, but it currently isn't.

**Comment by andris9** [comment]
@tmassey  I don't think that WildDuck requires any ARM specific compilation. Once you get Node running in ARM, then WildDuck should work as well as it is 100% javascript.

**Comment by louis-lau** [comment]
I just released [WildDuck: dockerized](https://github.com/nodemailer/wildduck-dockerized). Currently only amd64, but it uses github actions to build zonemta, haraka, and rspamd. I should be able to duplicate this setup to the wildduck and wildduck-webmail repositories, and get arm builds going :).

> I don't think that WildDuck requires any ARM specific compilation

But the underlying docker image does sadly.

**Comment by kornate** [comment]
Hi Louis. Any movement on arch64 support for the main image and webmail? I'm trying to get dockerised WD running on Amazon Linux 2 Arch64. Thanks for all the hard work!

**Comment by louis-lau** [comment]
Hi @kornate, I still plan on doing it, and some other things like better TLS and config management. I'm just so busy right now.

**Comment by AriaFantom** [comment]
Hey is there any Update on ARM system ?? If any place you are facing problems i might see to it

**Comment by psschand16** [comment]
any update on this?
