### ISSUE TITLE
Ability to use other storing method

### ISSUE THREAD

**Issue by ben221199** [nodemailer/wildduck#299]
Hello all,

At the moment all the mails are stored in MongoDB.
However, that is not the software I want to use for storing my mails.
In my situation I use a MySQL server (and that isn't MongoDB obviously).

Also I don't want to use MySQL directly.
I have my own REST API ([JSON:API](https://jsonapi.org)) that manages all the resources, permissions, etc.
I want Wildduck to use my API as storing method.
Will be there something like this be possible in the future?

Thanks in advance

**Comment by ben221199** [comment]
I also use the REST API for authentication.

**Comment by andris9** [comment]
MongoDB is kind of a hard requirement for WildDuck. if you want to use SQL then an alternative would be https://www.dbmail.org/
