### ISSUE TITLE
Wild Duck IMAP LDAP application password broken.

### ISSUE THREAD

**Issue by jtagcat** [nodemailer/wildduck#301]
Unable to set up Thunderbird to interact with Wild Duck Mail.
Used information from /help
App password from /account/security/asps

The password didn’t work. With spaces, or without spaces. Server settings were found ok.

Additional: While copying server settings, or password, it is padded with a space. This probably shouldn’t be the case (ofc I tried removing the spaces as well).

![image](https://user-images.githubusercontent.com/38327267/103164607-94000e00-4805-11eb-8b73-1f291f149ce5.png)

**Comment by jtagcat** [comment]
Downstream issue: https://git.k-space.ee/k-space/overnode-cluster/issues/87

**Comment by louis-lau** [comment]
Try troubleshooting with curl:
```shell
curl -v imaps://webmail.wildduck.email -u "username:password"
```

Wildduck accepts ASPs with it without spaces, so that shouldn't matter :)
