### ISSUE TITLE
Issue while updating wildduck to latest version

### ISSUE THREAD

**Issue by SpoortiPalakshaiah** [nodemailer/wildduck#302]
Hello,
We are using wildduck commits in our Dockerfile and we update the wildduck using Commit ID;
When we try to update wildduck from `v1.28.1` to latest `v1.31.4` using Commit ID `38f4220521842c464f8b26a08acb4ddbbfa58158 ` we are facing the error
```
/opt/wildduck/node_modules/standard-as-callback/built/index.js:6
        throw e;
        ^
TypeError: Cannot read property 'enabled' of undefined
    at Object.module.exports.start (/opt/wildduck/webhooks.js:75:26)
    at /opt/wildduck/worker.js:33:18
    at start (/opt/wildduck/tasks.js:117:16)
    at /opt/wildduck/tasks.js:169:20
    at /opt/wildduck/node_modules/ioredfour/lib/ioredfour.js:131:13
    at tryCatcher (/opt/wildduck/node_modules/standard-as-callback/built/utils.js:11:23)
    at /opt/wildduck/node_modules/standard-as-callback/built/index.js:19:49
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
info App Worker 30136 died
```

**Comment by louis-lau** [comment]
I don't think this is an issue with wildduck. But an issue with your Dockerfile. From your comment I assume you're not using the official Dockerfile?

**Comment by SpoortiPalakshaiah** [comment]
yes @louis-lau we are using the customized dockerfile, this is the file that we used to create the container
```
FROM ubuntu
# Install software
RUN apt-get update && apt-get install -y dumb-init  nodejs
ARG user=wildduck
ARG group=wildduck
ARG uid=1000
ARG gid=1000
ARG WILDDUCK_HOME=/opt/wildduck
ARG WILDDUCK_COMMIT="38f4220521842c464f8b26a08acb4ddbbfa58158"
RUN mkdir -p $WILDDUCK_HOME \
        && chown ${uid}:${gid} $WILDDUCK_HOME \
        && groupadd -g ${gid} ${group} \
        && useradd -d "$WILDDUCK_HOME" -u ${uid} -g ${gid} -m -s /bin/bash ${user} \
        && cd /var/opt && git clone --bare git://github.com/nodemailer/wildduck.git \
        && git --git-dir=/var/opt/wildduck.git --work-tree=/opt/wildduck checkout "$WILDDUCK_COMMIT" \
        && cd /opt/wildduck && npm install --unsafe-perm --production
WORKDIR $WILDDUCK_HOME
VOLUME $WILDDUCK_HOME
```

**Comment by louis-lau** [comment]
I was wrong, your Dockerfile looks fine :)

Looks like the webhooks section needs to be in the config section:
https://github.com/nodemailer/wildduck/blob/da8f5bc7d5b9cdd77be55a76c178a62d92a8593f/config/default.toml#L96

I'll submit a fix PR.

**Comment by Vinutha-Garimella** [comment]
@louis-lau  we will wait for your update thanks for the quick reply

**Comment by louis-lau** [comment]
I submitted the PR. in the meantime you can just add the webhooks section to your config, and you won't get any errors. :)

**Comment by Vinutha-Garimella** [comment]
@SpoortiPalakshaiah  thank you for posting the issue, you saved us the time. :-)
