### ISSUE TITLE
/addresses API giving error as Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by SpoortiPalakshaiah** [nodemailer/wildduck#304]
Hello, We updated the wildduck to v1.31.4 recently;
And after updating to this version; we are facing error as 

`http Error GET /addresses?accessToken=<secret_token> sess=- user=root error="TypeError: Cannot read property 'toString' of undefined\n    at /opt/wildduck/lib/api/addresses.js:191:48\n    at Array.map (<anonymous>)\n    at /opt/wildduck/lib/api/addresses.js:186:50\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async /opt/wildduck/lib/tools.js:501:13"`

And we are not able to list the addresses;

**Comment by andris9** [comment]
Should be fixed in v1.32.0, let me know if the issue still occurs

**Comment by SpoortiPalakshaiah** [comment]
@andris9  what is the commit id that has to be used to update the wildduck version to v1.32.0, I still see the old commit id in `wildduck/setup/01_install_commits.sh` 
should I use this commit id `4853d04b799104c0e1eb8806f08d845f040658da`

**Comment by andris9** [comment]
yes, that's the correct one. I also updated the commit hash in the setup file.

**Comment by SpoortiPalakshaiah** [comment]
Hello @andris9 , After updating the wildduck version to 1.32.0; 
When we use /addresses/forwarded/<address>, we are getting response with ID as
`"id": {
    "_bsontype": "ObjectID",
    "id": {
      "type": "Buffer",
      "data": [
        95,
        221,
        142,
        151,
        226,
        0,
        156,
        0,
        217,
        13,
        18,
        249
      ]
    }
  }`
  
  We were getting it as String previously; Also, in the docs `https://docs.wildduck.email/api/#operation/getForwardedAddress` the response for id is String; but we are getting Buffer object;

**Comment by andris9** [comment]
Fixed the bug and released v1.32.1
