### ISSUE TITLE
spf: sending host was not verified

### ISSUE THREAD

**Issue by DuredhelFinceleb** [nodemailer/wildduck#305]
Hi, not sure if this is a wildduck issue, a haraka issue , a DNS config issue or even an issue at all.
Correct me if necessary.

I've used the install script to setup wildduck
Hence for spf I've go this
`myfirstdomain.com IN TXT v=spf1 a:mail.myfirstdomain.com a:myfirstdomain.com ip4:12.34.56.78 ~all`

Then I've added a new domain : myseconddomain.com
And I've reused the same config for spf
`myseconddomain.com IN TXT v=spf1 a:mail.myfirstdomain.com a:myfirstdomain.com ip4:12.34.56.78 ~all`

When I send mail from myfirstdomain.com to myseconddomain.com in wildduck-webmail I can see the hint "Mailed by: sending host was not verified"
I've got the same result if I send mail from myseconddomain.com to myfirstdomain.com
Is this normal? Maybe this is because wildduck is both sender & receiver here and thus does not need to make this control?
Or did I got it wrong with the spf configs?

**Comment by andris9** [comment]
Use an external service Mail Tester to see if in general everything is set up properly. If you are sending from the same machine then you might have some funky routing issues, eg. like sening from/to 127.0.0.1 or via AWS private interface that are not included in the SPF record.
