### ISSUE TITLE
Too little document information

### ISSUE THREAD

**Issue by jet10000** [nodemailer/wildduck#307]
After wasting a long time, it was not configured correctly, the docker version of wildduck. The document information is too little.

**Comment by louis-lau** [comment]
Please let us know what information you would like to see. Ironically, your issue lacks information. 😁

**Comment by louis-lau** [comment]
Even though You haven't given any more information, I think this has been solved now with wildduck: dockerized:
https://github.com/nodemailer/wildduck-dockerized
