### ISSUE TITLE
Network error when connecting to MX server

### ISSUE THREAD

**Issue by umutyil** [nodemailer/wildduck#309]
Hi,

I installed Wildduck via install.sh to a fresh Ubuntu 20.04 server. I can receive emails from outer world but I cannot send any emails. I checked wildduck server logs and it seems everything is ok wildduck wise. Then I checked zone-mta logs and I saw the below error. 

_Jan 21 08:05:04 ***** zone-mta[98371]: ERR! Sender/default/98371[4] 17723d5528f00026b5.001 CONNFAIL domain=gmail.com local=mail.*****.io[0.0.0.0] remote=74.125.28.26:25 error=Network error when connecting to MX server alt3.gmail-smtp-in.l.google.com[74.125.28.26] for gmail.com: Connection timed out_

I checked and there is no firewall in front of the server, and all the ports are open.
What am I missing here? Is there a setting to enable this?

Thanks in advance for the help.

Best

**Comment by louis-lau** [comment]
> there is no firewall in front of the server

If there wasn't any firewall you would be able to reach alt3.gmail-smtp-in.l.google.com. A lot of server providers block outbound port 25 to avoid spammers. Most if the time you can request removal of the block.

**Comment by umutyil** [comment]
I am managing my own server so it is not related to a server provider :D Is this be a problem with ISP?

**Comment by louis-lau** [comment]
In that case your ISP, yes. Unless you have a business subscription it's unlikely they will even consider opening port 25.

Closing this issue as it's clearly a network issue and not an issue will wildduck or zonemta 😁

**Comment by umutyil** [comment]
Thanks for the help Louis :D

**Comment by louis-lau** [comment]
Glad I could help! Good luck with your ISP. If they don't want to open port 25 you can configure an external relay by adding this to your zone config for zonemta:

https://github.com/zone-eu/zone-mta/blob/862e3347a38deeecb39a4a90f13a9e73f482f886/config/default.js#L395-L404
