### ISSUE TITLE
wildduck update best practices?

### ISSUE THREAD

**Issue by DuredhelFinceleb** [nodemailer/wildduck#318]
OK, stupid question I guess but can't figure it out: how do you properly update Wild Duck?

so far on my server I did this
git --git-dir=/var/opt/wildduck.git --work-tree=/opt/wildduck checkout master
git --git-dir=/var/opt/wildduck.git --work-tree=/opt/wildduck fetch
git --git-dir=/var/opt/wildduck.git --work-tree=/opt/wildduck pull

at this point I could see the new commits since 1.31.4 in my VSCode using my cloned repo made with user "deploy"

what bothers me here is I could not find a way to fetch & pull without checking out first to master > this changes the files in /opt/wildduck, obviously I can't do that in production...

second thing that I could not find: I expected to be able to just fetch/pull using VSCode with the "deploy" clone without having to touch anything on the server
also tried to connect VSCode directly to /opt/wildduck using ssh remote connection but could not figure out how to pass the --git-dir & --work-tree arguments so VSCode was unable to run git
>> I'm certainly not knowledgable enough with git here, I understand this is not a git help forum so feel free to igonre me on this 

other question: what is the current stable version?
I've seen commits named "vX.YY.Z" but they don't have tags
For now I've just went back to 1.31.4 : 
git --git-dir=/var/opt/wildduck.git --work-tree=/opt/wildduck checkout "v1.31.4"

**Comment by louis-lau** [comment]
Though I'm not sure on the exact update process with a setup scripted install (I'm sure andris will chime in), I do know that all versions of wildduck do have tags.

Current latest:
https://github.com/nodemailer/wildduck/tree/v1.32.3

**Comment by DuredhelFinceleb** [comment]
OK great, for some reason I do not see them in VSCode
I'm going to checkout this version right away in my DEV envrionment 😄

**Comment by DuredhelFinceleb** [comment]
hmm.. or I'll wait for Andris input before doing that
I've jsut seen there are packages updates, if that breaks things in the repo I don't have time right now to fix them
Think I'd better have a proper & secure update process before touching anything

**Comment by dumprop** [comment]
Also interesting this for docker

**Comment by louis-lau** [comment]
@dumprop The same as with any docker-compose file:

```shell
cd wildduck-dockerized
docker-compose pull
docker-compose up -d
```

Stuff like this is why people like docker 😁

**Comment by dumprop** [comment]
> @dumprop The same as with any docker-compose file:
> 
> ```shell
> cd wildduck-dockerized
> docker-compose pull
> docker-compose up -d
> ```
> 
> Stuff like this is why people like docker 😁

Yes. So then it compatible w/ [watchtower](https://github.com/containrrr/watchtower) ? Currently, I use mailcow and it not so easy (incompatible w/ watchtower, but updating easy too, but need some manual job to run sh script)

**Comment by louis-lau** [comment]
I don't see why not. I've used watchtower for home use as well with some other docker stuff.

I wouldn't recommend any form of automatic updating in production though. Better to be there if anything goes wrong.

**Comment by DuredhelFinceleb** [comment]
@andris9 

Hi, how would you update the apps from a setup scripted install?

I was thinknig of something like this:
```
systemctl stop wildduck
cd /opt/wildduck
git --git-dir=/var/opt/wildduck.git --work-tree=/opt/wildduck checkout "vx.yy.z"
git --git-dir=/var/opt/wildduck.git --work-tree=/opt/wildduck fetch
git --git-dir=/var/opt/wildduck.git --work-tree=/opt/wildduck pull
npm i
systemctl start wildduck
```
Repeat sequence for wildduck-webmail, zome-mta, haraka and DuckyAPI
In case of failure, rollback would just be to repeat the sequence use the correct version tag/branch

What's your take on this?

**Comment by andris9** [comment]
Yes, you can do it like this. I would use `npm install --production` instead of plain `npm install` though as installing all the dev tools takes a lot of time and these are not needed.

In production we do not run git or npm in the production servers. Instead we have a build server where we basically just `git pull` from Github, `npm install --production`, then compress the resulting folder into tar.gz and upload it to application server. In the app server we then replace the application folder with the files from the compressed folder.

**Comment by DuredhelFinceleb** [comment]
Thanks a lot for your input!
I understand the bit about not having/using git, npm or any dev tool for that matter on a prod server
Since I'll be using the install script on my PROD server, git & npm will be there anyway so...

**Comment by DuredhelFinceleb** [comment]
about the plugins for haraka & zone-mta, I see that the install script deploys them along with their master applications, not with Wild Duck.
So should I do the same when updating, for example always updating the haraka-plugin when (and only when) updating haraka?
Or should I not do this & instead ensure I can update the plugins independantly from their master apps?

**Comment by louis-lau** [comment]
The plugins are for integrating wildduck with those applications. So if the plugins behavior changes, it's most likely because something in wildduck changed. They can and should be independently updated :).

**Comment by DuredhelFinceleb** [comment]
That's what I suspected. Thanks!

**Comment by tobsowo** [comment]
@DuredhelFinceleb please can you share process for updating Haraka, Zone MTA, Webmail?
