### ISSUE TITLE
Rate limit exceeded error

### ISSUE THREAD

**Issue by SpoortiPalakshaiah** [nodemailer/wildduck#319]
Hello,

I'm getting rate limit error as
`The user you are trying to contact is receiving mail at a rate that\nprevents additional messages from being delivered. Please resend your\nmessage at a later time. If the user is able to receive mail at that\ntime, your message will be delivered`

I've increased the receivedMax limit; But still getting the same error. The limits for the user is as follows:
`"limits": {
    "quota": {
      "allowed": 32212254720,
      "used": 23280155663
    },
    "recipients": {
      "allowed": 2000,
      "used": 0,
      "ttl": false
    },
    "forwards": {
      "allowed": 2000,
      "used": 0,
      "ttl": false
    },
    "received": {
      "allowed": 100000000000000,
      "used": 0,
      "ttl": false
    },
    "imapUpload": {
      "allowed": 10485760000,
      "used": 0,
      "ttl": false
    },
    "imapDownload": {
      "allowed": 10485760000,
      "used": 0,
      "ttl": false
    },
    "pop3Download": {
      "allowed": 10485760000,
      "used": 0,
      "ttl": false
    },
    "pop3MaxMessages": {
      "allowed": 250
    },
    "imapMaxConnections": {
      "allowed": 15,
      "used": 0
    }
  }`

**Comment by andris9** [comment]
You can increae `receivedMax` value with [updateUser](https://docs.wildduck.email/api/#operation/updateUser)

**Comment by andris9** [comment]
Is this the user's actual email or some kind of forwarding?

**Comment by SpoortiPalakshaiah** [comment]
It's not actual email; All the incoming and outgoing mails of the server are stored in this;
But this email is created as actual email account;
