### ISSUE TITLE
Too much source usage

### ISSUE THREAD

**Issue by furkankinyas** [nodemailer/wildduck#320]
![FireShot Capture 033](https://user-images.githubusercontent.com/769893/108818323-3f40ff80-75ca-11eb-82d1-4f6a8a63dffc.png)

At times, the use of resources has increased tremendously.

Server Ubuntu 20.04 (LTS) x64
wildduck: 1.28.1

**Comment by andris9** [comment]
How much RAM does the server have? CPU usage usually goes up once RAM is exhausted

**Comment by furkankinyas** [comment]
1 vCPU
1GB memory / 25GB Disk

**Comment by furkankinyas** [comment]
disk I/O 1Gb/s why so much

**Comment by andris9** [comment]
You should consider moving MongoDB into a separate server or increase RAM. Disk IO is probably Mongo moving cached pages from disk to RAM.
