### ISSUE TITLE
dkim 

### ISSUE THREAD

**Issue by yarosdev** [nodemailer/wildduck#323]
I have enabled dkim sign but it does not sign

mail server is mail.domain.com and email address is user@domain.com

![image](https://user-images.githubusercontent.com/6161950/110817449-f9a45800-8294-11eb-8813-6b24745be983.png)

Could you help?

**Comment by louis-lau** [comment]
Because this doesn't seem to have anything to do with the docker setup of wildduck, I've moved your issue to the correct place.

Have you enabled dkim for the domain?
https://docs.wildduck.email/api/#operation/updateDkimKey

**Comment by andris9** [comment]
You also need to register a DKIM key through the [API](https://docs.wildduck.email/api/#operation/updateDkimKey).

**Comment by yarosdev** [comment]
I have created dkim with API and registered its value in dns, but few minutes ago mongo database has been dropped suddenly

**Comment by yarosdev** [comment]
1. created DKIM via API
![image](https://user-images.githubusercontent.com/6161950/110825491-c5349a00-829c-11eb-921c-e9cc7b46886a.png)
2. created DNS record
![image](https://user-images.githubusercontent.com/6161950/110825541-d41b4c80-829c-11eb-8eff-c0a1878b037e.png)
3. checking DKIM via mxtoolbox
![image](https://user-images.githubusercontent.com/6161950/110825695-ff05a080-829c-11eb-8442-4cb85da9396c.png)
4. sending email from user@mydevtest.tk to gmail, gmail not recognizes DKIM

Maybe it is due to different mail server domain, mail.mydevtest.tk?

**Comment by andris9** [comment]
Yes, the domain needs to be exact match. Add an additional key through the API for each domain, or alternatively use the match-all domain placeholder “*”

**Comment by yarosdev** [comment]
I have also created dkim for mail.mydevtest.tk but nothing changed, I am confused

**Comment by yarosdev** [comment]
/config/zone-mta/plugins/wildduck.toml

![image](https://user-images.githubusercontent.com/6161950/110841722-f0c08000-82ae-11eb-810f-9d1911cbffb2.png)

do I need to set it to "true" also?

**Comment by yarosdev** [comment]
Could you help? pls

**Comment by andris9** [comment]
`signTransportomain=true` in `wildduck.toml` config file means that WildDuck looks for DKIM key for the current sending domain that is set in the `IP pool config`. If there is a stored key for that domain (or key for `"*"`), then it will be used, otherwise not.

**Comment by yarosdev** [comment]
Just to clarify, using api http://docs.wildduck.email/api/#operation/updateDkimKey it is not enough to work also I need to specify this in IP pool config at zonemta-wildduck?

**Comment by louis-lau** [comment]
@andris9 So even with `signTransportdomain=false` dkim should be signed for the sending domain right? Just not the domain in the ip pool config.

**Comment by louis-lau** [comment]
@yarosdev You could try using https://www.mail-tester.com/ and sharing the result url.

**Comment by yarosdev** [comment]
@louis-lau https://www.mail-tester.com/test-s99ruobg9

**Comment by andris9** [comment]
`signTransportdomain` is an additional signature and does not replace main signature, so it is not mandatory to use it. By default you should get a signature for the From address domain but in addition to that you can also add a signature for the HELO domain of the MTA server.

For example you are sending as "user@blurdybloop.com" and the MTA server hostname is "mail.blurdybloop.com".

1. `signTransportdomain=false` and you have a DKIM key for "blurdybloop.com":

```
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=blurdybloop.com;...
```

2. `signTransportdomain=true` and you have a DKIM keys for "blurdybloop.com" and "mail.blurdybloop.com" (or DKIM key for `"*"`):

```
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=blurdybloop.com;...
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=mail.blurdybloop.com;...
```

If DKIM key can not be found for `blurdybloop.com` then that signature is not added, also if there is not key for `mail.blurdybloop.com` then that signature is also not added.

**Comment by andris9** [comment]
> @louis-lau https://www.mail-tester.com/test-s99ruobg9

Change your [pool config](https://github.com/zone-eu/zone-mta-template/blob/a905d22064f2d5bcec5d946144c0c6974e96d60f/config/pools.toml#L10) and replace `mail.mydevtest.tk` with `static.133.160.90.157.clients.your-server.de`. Also ad a DKIM key for that domain. The domain name must match the PTR record of your IP (157.90.160.133).

Also check if WildDuck plugin is even enabled. If it is not then you might end up with an open relay (try authenticating against your SMTP server with random username/password)

**Comment by louis-lau** [comment]
I'd change your reverse dns to mail.mydevtest.tk instead, I know that that's an option with Hetzner for both their dedi's and VMs.

> Also check if WildDuck plugin is even enabled

If it's not I have done something very wrong with the default wildduck-dockerized config, I assume @yarosdev is using that anyway.

**Comment by yarosdev** [comment]
@louis-lau Yes I am using wildduck-dockerized

**Comment by yarosdev** [comment]
Guessing :)
![image](https://user-images.githubusercontent.com/6161950/110942856-18612800-8343-11eb-8c87-3365f6bbe454.png)

**Comment by louis-lau** [comment]
This is the line that enables the plugin in zonemta:
https://github.com/nodemailer/wildduck-dockerized/blob/9f85a9cdb8740588851c187dc3a6218475cf6b28/default-config/zone-mta/plugins/wildduck.toml#L2

**Comment by yarosdev** [comment]
["modules/zonemta-wildduck"]
enabled=["receiver", "sender", "dkim"] ? :)

**Comment by andris9** [comment]
Well, even if you have it enabled but things are not working as they should then maybe the plugin is not loaded. Easy test would be this (you want to see `535 Authentication failed`) :

```
$ openssl s_client -starttls smtp -crlf -connect mail.example.com:587
EHLO localhost
AUTH PLAIN dGVzdAB0ZXN0AHRlc3RwYXNz
```

**Comment by yarosdev** [comment]
> Well, even if you have it enabled but things are not working as they should then maybe the plugin is not loaded. Easy test would be this (you want to see `535 Authentication failed`) :
> 
> ```
> $ openssl s_client -starttls smtp -crlf -connect mail.example.com:587
> EHLO localhost
> AUTH PLAIN dGVzdAB0ZXN0AHRlc3RwYXNz
> ```

It was your test?
![image](https://user-images.githubusercontent.com/6161950/110943750-409d5680-8344-11eb-8c85-f6a482146ab7.png)

**Comment by yarosdev** [comment]
> Well, even if you have it enabled but things are not working as they should then maybe the plugin is not loaded. Easy test would be this (you want to see `535 Authentication failed`) :
> 
> ```
> $ openssl s_client -starttls smtp -crlf -connect mail.example.com:587
> EHLO localhost
> AUTH PLAIN dGVzdAB0ZXN0AHRlc3RwYXNz
> ```
didn't find starttls in server response, try anyway...

![image](https://user-images.githubusercontent.com/6161950/110944648-66772b00-8345-11eb-8b6c-10cc62d03d57.png)

**Comment by yarosdev** [comment]
> If it's not I have done something very wrong with the default wildduck-dockerized config, I assume @yarosdev is using that anyway.

Could you help to solve the issue with wildduck-dockerized config?

**Comment by yarosdev** [comment]
STARTTLS not supported by wildduck-dockerized

**Comment by JamesCartar** [comment]
I run into the same problem and i fix it by removing `@zone-eu/` prefix in `config-generated/config-generated/zone-mta/plugins/wildduck.toml` and i put the `dkim` in the enabled array at the top of the file
