### ISSUE TITLE
Is it possible to disable redis?

### ISSUE THREAD

**Issue by littleplus** [nodemailer/wildduck#324]
I use different redis instance for different wildduck instances, and find that I could not retrieve the mail by IMAP from A wildduck instance while B wildduck instance receive mail. And I also find that I could retrieve the mail after A wildduck instance receive new mails.

I think it's caused by different redis instances, so could I disable redis completely for wildduck or IMAP only?

**Comment by andris9** [comment]
You must share the same Redis between all WildDuck instances as Redis is used to relay event notifications between instances.
