### ISSUE TITLE
How do I receive emails?

### ISSUE THREAD

**Issue by widevel** [nodemailer/wildduck#325]
Hello. I have installed wildduck but I can't find how to activate the SMTP server in your configuration files. How am I supposed to receive emails? Do I have to install a separate SMTP server? 

Thanks and best regards

**Comment by louis-lau** [comment]
Please see the docs:
https://docs.wildduck.email/#/general/install

> WildDuck itself is only an IMAP and POP3 server, with simple LMTP support if needed. However, because of its integration with ZoneMTA and Haraka, it can function as a complete mail server. Below are instructions for installing a complete mail server, or only WildDuck itself.
