### ISSUE TITLE
DKIM Wildcard/Subdomains

### ISSUE THREAD

**Issue by yarosdev** [nodemailer/wildduck#326]
According to API description:

> Use "*" as a special value that will be used for domains that do not have their own DKIM key set
> http://docs.wildduck.email/api/#operation/updateDkimKey

But RFC says that it is not possible to handle wildcard with DKIM records.

> https://tools.ietf.org/html/rfc5617#section-6.3

So question is, how to tell wildduck to use primary domain DKIM? I mean if I send email from user@sub.example.com using mail server mail.example.com so that email should be signed using DKIM for example.com

Thank you for your attention!

**Comment by andris9** [comment]
Nothing to do with RFC. When you send a mail through WildDuck then in the DKIM signing step it looks at the From address domain name and tries to find a matching DKIM key from the DB. If not such key was found it tries to find a key that has `"*"` set as the domain instead. If it still can't find anything then it skips signing. When generating `DKIM-Signature` header then the domain name comes from the From address and is not the DB domain.

**Comment by yarosdev** [comment]
Yes, but how does dns record should look like for such "*" domain?

**Comment by louis-lau** [comment]
You would add multiple dns records, with the same content.
