### ISSUE TITLE
Pluggable storage ?

### ISSUE THREAD

**Issue by robbiehanson** [nodemailer/wildduck#33]
I understand that wildduck is "opinionated". However, is there any chance you'll be supporting pluggable storage in the future?

I notice that other projects (based on your work) have sprung up specifically to address this concern: [imapper](https://github.com/deitch/imapper)

We're keen to use wildduck. But pluggable authentication and pluggable storage are requirements I don't think we'd be able to work around.

**Comment by andris9** [comment]
Pluggable authentication is doable. I'm experimenting with a plugin system for Wild Duck and authentication is just a call that takes an username and a password as an input and should yield with an user ID. It does get more complicated with the SMTP plugin as it performs authentication directly against the database but I guess it wouldn't be difficult to edit it in a way to perform auth against a Wild Duck server and not against the database.

Pluggable storage is another story. It would be possible to use a custom storage for attachments (Wild Duck separates attachments from the message), as all it requires is an object store. In fact the current [attachment store](https://github.com/nodemailer/wildduck/blob/master/lib/attachments/gridstore-storage.js) is already organised as kind of a plugin as it is decoupled from the rest of the code and could just as well store the attachments to S3 for example.

Pluggable message store is much more difficult to do though. The number one goal for Wild Duck is scalability, so I have spent a lot of time evaluating different storage options and have done a lot of MongoDB specific tuning. There is nothing in there too MongoDB specific though that could not be replaced with something else even if the replacement would be a huge task but as a sole developer my time resources are extremely limited and if something does not get me closer to my own goals, then I can not work on it.

If it's not the actual store that you care about but want to build something very specific, for example an encrypted message store or dynamic message store where the IMAP mailbox would be a front end to something else, then I guess that the best bet would be to take the code from [imap-core folder](https://github.com/nodemailer/wildduck/tree/master/imap-core) and build in top of that. [Here's a minimal IMAP server](https://github.com/nodemailer/wildduck/blob/master/imap-core/test/test-server.js) built on top of the core. You could take that example server and build your custom logic on top of it.

**Comment by andris9** [comment]
Just for the reference, to get the test server running:

```
$ git clone git://github.com/nodemailer/wildduck.git
$ cd wildduck
$ npm install --production
$ node -e 'require("./imap-core/test/test-server.js")({secure:true}).listen(9993)'
```

and then from another tab

```
$ openssl s_client -crlf -connect localhost:9993
> * OK wildduck ready
```

You can then use usernamer 'testuser' and password 'pass' to log in:

    a login testuser pass
    > a OK testuser authenticated

and from there use standard IMAP commands to open the INBOX and fetch/append messages

    a select inbox
    > server response
    a fetch 1:* (UID FLAGS BODY.PEEK[])
    > server response
