### ISSUE TITLE
wildcard autofiltering

### ISSUE THREAD

**Issue by DuredhelFinceleb** [nodemailer/wildduck#334]
Is it possible to have mail sent to a wildcard address be auto delivered into a folder named after the wildcard?

=> if a user has a *me@domain address and receives an email on hey.me@domain, the email would be delivered into the "hey" folder of the user's mailbox (with the options of having the folder created if nor existing)

**Comment by andris9** [comment]
This is currently not possible. It would probably require some kind of scripting or plugin capabilities in WildDuck so you could create a custom setup for it as it's hard to see as a general feature.

**Comment by DuredhelFinceleb** [comment]
OK I'll look into this when I have time.
Maybe there are some events that couls trigger a webhook? Webhooks might not be the best way to do this though

**Comment by andris9** [comment]
Incoming emails are actually processed by Haraka and Haraka already has an existing plugin system, WildDuck email handling is also nothing more than a Haraka plugin. So maybe there should be a way to let other Haraka plugins to somehow interact with the Haraka WildDuck plugin that stores the message. I have to test a bit with that.
