### ISSUE TITLE
fail2ban setup

### ISSUE THREAD

**Issue by DuredhelFinceleb** [nodemailer/wildduck#335]
Not sure it goes here, could not find an other place.
For anyone that would find this useful 🙂 

fail2ban setup on Ubuntu 20.04 LTS
Using the scripted install, not sure how it applies for dockerized version but that should not be too different

Create a /etc/fail2ban/jail.d/custom.conf
In the default section, add the IPs that should never be blocked then your standard settings for findtime, bantime & maxretry
Personnally I use these:
```
[DEFAULT]
ignoreip = 127.0.0.0/8 <my public IP> <any IP you need here>
findtime = 1h
bantime = 7d
maxretry = 3
```

Then add this section for wildduck
```
[wildduck]
enabled  = true
port     = 993,995
filter   = wildduck
logpath  = /var/log/wildduck-server/wildduck-server.log
```

Then create /etc/fail2ban/filter.d/wildduck.conf
```
[INCLUDES]
before = common.conf

[Definition]
failregex = \[AUTHFAIL\] .*"_ip":"<HOST>"
ignoreregex =
```

And restart fail2ban.

**Comment by andris9** [comment]
That's good to know 👍  Maybe you could add this as a page somewhere in the WildDuck [documentation](https://github.com/nodemailer/wildduck/tree/master/docs)?

**Comment by DuredhelFinceleb** [comment]
Sure!
How do I do that though? Your link points to a github repo
I've never contributed to a github project, are there resources I should read first?
I'm asking because I have some small modifications to wildduck-webmail I'd like to submit

**Comment by andris9** [comment]
Maybe add a section to this [document](https://github.com/nodemailer/wildduck/blob/master/docs/in-depth/operating-wildduck.md)? Anything on that page ends up [here](https://docs.wildduck.email/#/in-depth/operating-wildduck)

**Comment by DuredhelFinceleb** [comment]
OK so I've made my very first github contrilb 🙂 
If I've followed the instructions correctly, you should have received a PR with the document updated.

**Comment by andris9** [comment]
Thanks! You can see the updated documentation [here](https://docs.wildduck.email/#/in-depth/operating-wildduck?id=fail2ban-setup) (might need page refresh)

**Comment by oviliz** [comment]
@DuredhelFinceleb , in the wildduck.conf file we refer to a common.conf file (`before = common.conf`). Should that be instead the custom.conf file we create before or is actually correct?
https://github.com/nodemailer/wildduck/blame/master/docs/in-depth/operating-wildduck.md#L133
