### ISSUE TITLE
Documentation: Thread implementation

### ISSUE THREAD

**Issue by Vanellope-Von-Schweetz** [nodemailer/wildduck#338]
Hello,
Thank you for developing Wildduck!
I've been looking everywhere in the documentation, but there an information I cannot find.
Messages seem to be given a thread which you can use to query and filter. But I can't figure out how this thread ID is attributed. What does define a message thread in Wildduck?
Thank you very much.

**Comment by louis-lau** [comment]
Here's the code for it:
https://github.com/nodemailer/wildduck/blob/master/lib/message-handler.js#L1353-L1415

I'm not the one that wrote it and I've only looked over it for a second, so I don't know all the details. But seems the thread id is based on the subject, and one of the following headers: `Message-ID`, `In-Reply-To`, `Thread-Index`, `References`.

**Comment by andris9** [comment]
Threading in WildDuck is similar to the REFERENCES threading algorithm [described here](https://datatracker.ietf.org/doc/html/rfc5256#page-7) (but not the same as you can see from @louis-lau's comment)
