### ISSUE TITLE
Fix Redis start-up and ZoneMTA connection failure

### ISSUE THREAD

**Issue by N1ghteyes** [nodemailer/wildduck#340]
Feel free to kill this if its not appropriate to add the issue in this way.

[For Ubuntu 18.04]

This is a record of a combined issue we ran into while trying to bring wildduck back online over a server reboot. The issue manifested itself as a failer of ZoneMTA to connect to Redis on boot, as detailed here: [#339](https://github.com/nodemailer/wildduck/issues/339)

It looks like the wildduck install script (for VPS, not Docker) fails to do two things. First, Redis is not added to startup - To fix that, we do:

`systemd: systemctl enable /lib/systemd/system/redis-server.service`

Next, the service reference to Redis in the zone-mta.service file is incorrect.

`nano /etc/systemd/system/zone-mta.service`

And alter the following:

```
...
After=mongod.service redis.service
....
```

to

```
...
After=mongod.service redis-server.service
....
```

After which, restart the Daemon 
`systemctl daemon-reload`

And then reboot to check it works. All going well, you will now be safe(r) from random restarts, droplet resizes (on DO) or other outage events

I'll push a PR with install fixes if i can, just looking into what needs changing.

**Comment by louis-lau** [comment]
There have been some issues about redis indeed. I quickly looked into the setup script once, and I think it did actually enable redis on startup. It could very well be that the service name changed to `redis-server` at some point. It could also be that it's different between ubuntu versions, that may need to be checked so it can be accounted for in the setup script.

If you could submit a PR that'd be great!

**Comment by louis-lau** [comment]
> definitely did not add Redis

Seems you're correct. I can't find any `enable redis` command in the setup scripts. I must be confusing it with something else.

> PR wise I'm stacked for time

No worries, we all are 😅.
