### ISSUE TITLE
scripted install fails - attached are updated files to exexute install.sh

### ISSUE THREAD

**Issue by ymir1v** [nodemailer/wildduck#341]
The scripted install fails - i made following changes to fix it:

01_install_commits.sh
(updated versions for mongodb and haraka - without these updated version settings the install will fail since repos for the old versions are not available anymore!)
```
MONGODB="4.4"
HARAKA_VERSION="2.8.27"
```

04_install_import_keys.sh
(disable workaround on mongodb on ubuntu focal - since this version is now available) 
```
# focal is supported as of 2021-06-14!
#if [ "$MONGORELEASE" = "focal" ]; then
  # Ubuntu 20 is not yet supported (as of 2020-07-01), fallback to 18
  # MONGORELEASE="bionic"
#fi

# use redis team repo
add-apt-repository -y ppa:redislabs/redis
# apt-add-repository -y ppa:chris-lea/redis-server
```

06_install_enable_services.sh
(probably required due to repo change?)
```
$SYSTEMCTL_PATH enable redis-server.service
```

11_install_nginx.sh
(maybe this not required if nginx is installed from the ubuntu repo - just to be sure all directories exist)
```
# create nginx config dirs - if missing
if [[ ! -d /etc/nginx/sites-available ]]; then
    mkdir -p /etc/nginx/sites-available
fi
if [[ ! -d /etc/nginx/sites-enabled ]]; then
    mkdir -p /etc/nginx/sites-enabled
fi
```

12_install_ufw_rules.sh
(optional - this reads the specified sshd port from the sshd_config file instead of using statically port 22)
```
_var_sshd_port="$(cat /etc/ssh/sshd_config|grep -i -E ^port|cut -f2 -d' ')"
if [[ $_var_sshd_port == "" ]]; then
    _var_sshd_port=22
fi

#### UFW ####
ufw allow $_var_sshd_port/tcp
```

14_install_start_services.sh
(again this is probably required due to repo change?)
```
$SYSTEMCTL_PATH start redis
```

[ubuntu-wildduck.zip](https://github.com/nodemailer/wildduck/files/6712255/ubuntu-wildduck.zip)

**Comment by louis-lau** [comment]
Hi @ymir1v, thanks for contributing! Could you create a pull request with these changes?
