### ISSUE TITLE
Fetchmail and EXPUNGE responding with `* id EXISTS` rather than `* id EXPUNGE`

### ISSUE THREAD

**Issue by moll** [nodemailer/wildduck#343]
Hey,

I noticed this on the Estonian ISP Zone's IMAP servers which should be running WildDuck.
I, via Fetchmail, am seeing something weird after `EXPUNGE`. WildDuck seems to respond with `* id EXISTS`, rather than `* id EXPUNGE` after invoking `EXPUNGE`. My reading of [RFC 3501](https://datatracker.ietf.org/doc/html/rfc3501#section-6.4.3) says that the mail server is supposed to respond with a list of emails expunged. The particular email that's reported as `EXISTS` was just set `\Seen` and `\Deleted`.

This is what `fetchmail --verbose` reports:

```
fetchmail: IMAP> A0009 STORE 1 +FLAGS (\Seen \Deleted)
fetchmail: IMAP< * 1 FETCH (FLAGS (\Seen \Deleted))
fetchmail: IMAP< A0009 OK STORE completed
fetchmail: IMAP> A0010 EXPUNGE
fetchmail: IMAP< * 1 EXISTS
fetchmail: IMAP< A0010 OK EXPUNGE completed
fetchmail: mail expunge mismatch (0 actual != 1 expected)
```

Do you have any idea what's going on?

Thanks!

**Comment by andris9** [comment]
Will investigate. My first guess about what happens there is that deleting the message takes so much time (deletion in IMAP is an asynchronous process) that it is still not completed by the time EXPUNGE is executed. WildDuck starts deleting messages in the background once \Deleted flag is added to a message and EXPUNGE is more like a no-op that lists the results. The servers in question store about 100TB of emails and adding new emails is fast and easy but deleting anything is quite troublesome.

**Comment by andris9** [comment]
Can confirm. When expunge is issued then deletion is still in progress. Asking for updates a bit later results in actual expunge results. I guess I need to implement some kind of locking that waits until processing is finished

1. after opening the folder, there is 11392 emails

```
* 11392 EXISTS
```

Trying to delete the latest message seems to do nothing (still 11392 messages in folder)

```
a store 11392 +flags (\Deleted)
a expunge
* 11392 FETCH (FLAGS (\Seen \Deleted))
a OK STORE completed
* 11392 EXISTS
a OK EXPUNGE completed
```

Polling for updates after few seconds finally shows the updates

```
a noop
* 11392 EXPUNGE
* 11391 EXISTS
a OK Nothing done
```

This behavior is not correct. Not showing untagged EXPUNGE responses is actually fine (deleting is async and there are a lot of things that might trigger the deletion process) but the unchanged EXISTS response is completely wrong.

**Comment by andris9** [comment]
Disabled auto deletion as it caused some async race condition issues (eg. messages were already being deleted but the process was not finished yet, so previous message count was reported).

```
...
* 11670 EXISTS
...
A STORE 1 +FLAGS (\Deleted)
B EXPUNGE
* 1 FETCH (FLAGS (\Seen \Deleted))
A OK STORE completed
* 1 EXPUNGE
* 11669 EXISTS
B OK EXPUNGE completed
```
