### ISSUE TITLE
API Token overview

### ISSUE THREAD

**Issue by her-finn** [nodemailer/wildduck#344]
Hi, I am currently looking for a way to display all current access tokens.

Is there perhaps a script that is currently not yet documented?

Regards

**Comment by louis-lau** [comment]
I don't think there's currently such an endpoint. I assume you want to list active webmail sessions with an option to invalidate them, or something similar?

**Comment by her-finn** [comment]
No, im planning multiple services, with connection to the wildduck api. Every service gets his own (root-)Access Token. in a few years i will no longer have an overview of which (root) api keys are available. So I want to display all the keys that I have created with the access-tokens script

**Comment by andris9** [comment]
Currently there is no API endpoint for this. Tokens are stored in Redis and currently the only way to list these would be by running the following Redis command (you probably have to run `SELECT 3` first to open the correct DB):

```
KEYS tn:token:*
```

In production you should never run the KEYS command though as it is synchronous and it has to scan the entire keyspace so while Redis is doing the listing no other Redis command can be executed. It would be better to use [SCAN](https://redis.io/commands/scan)  command.

**Comment by andris9** [comment]
If you want to get the owner of a token then you can do it with the following command:

```
HGET tn:token:123345 user
> username
```

**Comment by her-finn** [comment]
Thanks! 
The command I was looking for was just
 ```
 SELECT 3
 KEYS tn:*
```
This returns:
```
1) "tn:token:xxx"
2) "tn:token:xxx"
3) "tn:user:app1"
4) "tn:token:xxx"
5) "tn:token:xxx"
6) "tn:user:app2"
7) "tn:token:xxx"
```
I think the tn:user:username is the name that i entered in the access-tokens script, and the tokens below it are the hashes of the generated access tokens. Right?

**Comment by her-finn** [comment]
Update:

I have now managed to display the tokens with users with a Redis Explorer.

Can you perhaps tell me the command with which I can display the table shown below on the console?

Thank you!

![image](https://user-images.githubusercontent.com/58078450/128643462-458424da-5438-43b8-85e8-fca10bcbec4a.png)

**Comment by andris9** [comment]
You get the same info in cli by running `HGETALL tn:token:....`
`s` is signature, so it is not a secret. Whenever you use an access token the data of the token are compared against the signature to see if token has been modified or not (eg. someone having access to Redis would update token from a unprivileged role to root).
