### ISSUE TITLE
Mistake in the API documentation

### ISSUE THREAD

**Issue by her-finn** [nodemailer/wildduck#345]
Hi, there is an error in storage in the API documentation: When uploading a file, it says that the file should be uploaded in the body parameter. In reality, the parameter is called content.

![wd_is_api](https://user-images.githubusercontent.com/58078450/127777592-e51ce274-fd5d-4ea8-809f-caf02b0695de.png)

**Comment by louis-lau** [comment]
Hi, could you send a pull request to correct it?
The schema you mention is here:
https://github.com/nodemailer/wildduck/blob/master/docs/api/openapi.yml#L1994-L2001

**Comment by her-finn** [comment]
Done :)
