### ISSUE TITLE
TypeError: Cannot read property 'agent' of undefined

### ISSUE THREAD

**Issue by SpoortiPalakshaiah** [nodemailer/wildduck#350]
Hello, 
We are using wildduck commits in our Dockerfile and we update the wildduck using Commit ID;
When we try to update wildduck from v1.31.4 to latest v1.34.0 using Commit ID `702292120f65b1a7c7e30738cf540c3ad0d1d80b` we are facing the error
```
/opt/wildduck/acme.js:57
    if (!config.acme.agent.enabled) {
                     ^

TypeError: Cannot read property 'agent' of undefined
    at module.exports (/opt/wildduck/acme.js:57:22)
    at /opt/wildduck/worker.js:72:29
    at Server.<anonymous> (/opt/wildduck/api.js:538:9)
    at Object.onceWrapper (events.js:519:28)
    at Server.emit (events.js:412:35)
    at emitListeningNT (net.js:1354:10)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
info App Worker 10593 died
```
This is our Dockerfile
```
FROM ubuntu
# Install software
RUN apt-get update && apt-get install -y dumb-init  nodejs
ARG user=wildduck
ARG group=wildduck
ARG uid=1000
ARG gid=1000
ARG WILDDUCK_HOME=/opt/wildduck
ARG WILDDUCK_COMMIT="38f4220521842c464f8b26a08acb4ddbbfa58158"
RUN mkdir -p $WILDDUCK_HOME \
        && chown ${uid}:${gid} $WILDDUCK_HOME \
        && groupadd -g ${gid} ${group} \
        && useradd -d "$WILDDUCK_HOME" -u ${uid} -g ${gid} -m -s /bin/bash ${user} \
        && cd /var/opt && git clone --bare git://github.com/nodemailer/wildduck.git \
        && git --git-dir=/var/opt/wildduck.git --work-tree=/opt/wildduck checkout "$WILDDUCK_COMMIT" \
        && cd /opt/wildduck && npm install --unsafe-perm --production
WORKDIR $WILDDUCK_HOME
VOLUME $WILDDUCK_HOME

```
It gives no error when I get into the container and execute 
`node /opt/wildduck/acme.js`

**Comment by andris9** [comment]
In general the config system for WildDuck assumes that your own config is merged with the default config. In your case what happens is that you do not merge the config and only use your own config files so you must make sure that you keep your config files in sync with the default ones.

Your config is missing the `[acme]` block ([see here](https://github.com/nodemailer/wildduck/blob/9422d02373732ee4ccd7e3139d8fa84b58ad6044/config/default.toml#L83-L84) and [here](https://github.com/nodemailer/wildduck/blob/master/config/acme.toml)).
