### ISSUE TITLE
Multiple domains

### ISSUE THREAD

**Issue by rolfen** [nodemailer/wildduck#36]
I cannot figure out how to handle multiple domains. It seems that WildDuck assumes that all users and hosted email addresses will be using the same domain suffix (`@mydomain.com`).

I also want to be handling mail for `myotherdomain.com`.

Do I need to do another installation of wildduck?

**Comment by andris9** [comment]
When creating users via API specify the address argument as well. If it is not set then WildDuck defaults to username@defaultDomain.
