### ISSUE TITLE
[Docker] New commits and tags don't appear on Docker Hub

### ISSUE THREAD

**Issue by IndeedNotJames** [nodemailer/wildduck#361]
Hi :)

The original Dockerfile has been added as part of PR #180 (early 2020) together with the Docker Hub Autobuild integration in the PR comments in the very same PR: https://github.com/nodemailer/wildduck/pull/180#issuecomment-592939878

Last _git tag_ tagged as [`nodemailer/wildduck:v1.34.0`](https://hub.docker.com/layers/nodemailer/wildduck/v1.34.0/images/sha256-41383c448b1cdf4d817a1def9771db96af256e8e01c009b27ef2743da75eef23) [July 5, 2021]
Last _commit_ tagged as [`nodemailer/wildduck:latest`](https://hub.docker.com/layers/nodemailer/wildduck/latest/images/sha256-19d55e8d64fcfe3ff646377cc4ecbb5447096af46b4196b8599c482c56f3cc3e) is https://github.com/nodemailer/wildduck/commit/864fa8d8b61b6cb3fa2e80f16f1c2c03f36ef35f [July 5, 2021]

There has been no commit between July 5 and August 1[^1]. So to me, it looks like this org/repo could be affected by the change Docker Hub made on June 18, 2021 impacting free tiers on Docker Hub, assuming there has been some unmentioned grace period:

> [...] so today we are disappointed to announce that we will be discontinuing Autobuilds on the free tier starting from June 18, 2021.[^2] 

There are two main ways I can think of to solve this:
1. WildDuck could try to apply as part of the [Docker Open Source Program](https://www.docker.com/community/open-source/application) to fully restore the Autobuild service for free
1. Build the Docker image using a ci like GitHub Actions and automatically push to Docker Hub (or some equivalent like the integrated GitHub Container registry[^3])

I would love to help :)

[^1]: https://github.com/nodemailer/wildduck/compare/v1.34.0...v1.35.0
[^2]: https://www.docker.com/blog/changes-to-docker-hub-autobuilds/
[^3]: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry

**Comment by IndeedNotJames** [comment]
Is [andris9/wildduck](https://hub.docker.com/r/andris9/wildduck) on Docker Hub considered the new official Docker image? :)

**Comment by andris9** [comment]
@IndeedNotJames It's the temporary official image. Docker Hub stopped autobuilds for free accounts and I happened to have a personal paid account. Long term goal is to move to Github actions to build those images.

**Comment by NicolaiSchmid** [comment]
I think this can be closed now

**Comment by IndeedNotJames** [comment]
I wasn't aware of #382!
Thank you so much @NicolaiSchmid :heart:

**Comment by NicolaiSchmid** [comment]
You're welcome. I only created the PR when I stumbled upon this issue
