### ISSUE TITLE
Error with install script

### ISSUE THREAD

**Issue by brinnington** [nodemailer/wildduck#363]
Hi,

The WildDuck Installer README.md says, "The install script is self contained, you can upload to your server and start it as root. It fetches all required files from Github."

But that seems to me to be incorrect.

On a blank VPS, using the install script, I got these errors:

./root/15_install_deploy.sh: line 114: curl: command not found
ERROR: lsof is not installed.
/root/06_install_enable_services.sh: line 10: pwgen: command not found
/root/06_install_enable_services.sh: line 19: node: command not found
/root/07_install_wildduck.sh: line 22: git: command not found
/root/12_install_ufw_rules.sh: line 14: ufw: command not found

The result is:

Failed to start nginx.service: Unit nginx.service not found.
Failed to reload nginx.service: Unit nginx.service not found.
-- Executing 14_install_start_services.sh subscript --
Failed to start mongod.service: Unit mongod.service not found.
Failed to start redis.service: Unit redis.service not found.
Failed to start wildduck.service: Unit wildduck.service has a bad unit file setting.
See system logs and 'systemctl status wildduck.service' for details.
Failed to reload nginx.service: Unit nginx.service not found.

It seems to me that there is an error in the first command:

wget -O - https://raw.githubusercontent.com/nodemailer/wildduck/master/setup/get_install.sh | bash

And whatever the error is, it causes the second command to stumble and fail in some areas.

Do you know what is wrong and is there an easy solution?

Best,

Bob

**Comment by Berndinox** [comment]
Hy,

Some parts from here were not installed:
https://github.com/nodemailer/wildduck/blob/master/setup/05_install_packages.sh

Curl ist not part of the install Script, those i would.

1) create empty server 
2) install curl
3) runn install script
