### ISSUE TITLE
Account namespace "notifications" is indicated as reserved, though not indicated in accounts.js

### ISSUE THREAD

**Issue by lexparsimonet** [nodemailer/wildduck#364]
As the title states, the account namespace for "notifications" cannot be utilized, as WildDuck `/accounts/create` indicates that "notifications" is a reserved name. This is not configured anywhere in the WildDuck codebase (that I am able to ascertain), yet is still restricted. 

I am unsure if this is a bug, or if this is a feature, but would like to determine where this is defined, as it is not included in `!config.service.enableSpecial` in `accounts.js`.

**Comment by louis-lau** [comment]
`/accounts/create` is not a wildduck API endpoint. Are you sure you're not looking at wildduck-webmail? I know it has such a setting.

**Comment by lexparsimonet** [comment]
Observant you are. Thanks for correcting me on this - https://github.com/nodemailer/wildduck-webmail/blob/master/routes/account.js line #177.  I assumed familiarity with WildDuck might be sufficient across repositories to determine what is happening with this. 

The parameter for 'notifications' as a 'Special' account name I am unable to locate. I will open an issue in the appropriate location.

Thanks again.

**Comment by louis-lau** [comment]
> familiarity with WildDuck might be sufficient across repositories to determine what is happening with this.

It's a reasonable assumption haha. I just wanted to clarify ;). I see what you mean now, just looking at it from my phone I'm not entirely sure either to be honest.

**Comment by louis-lau** [comment]
Just looked into it from my PC, wildduck-webmail is using this library to match against: [role-based-email-addresses](https://github.com/mixmaxhq/role-based-email-addresses). `notifications` is in that list :)
