### ISSUE TITLE
Thunderbird Setup

### ISSUE THREAD

**Issue by ukwuezeobinna** [nodemailer/wildduck#367]
Wildduck is successfully installed using the Scripted install.

Are there additional configurations needed to make Wildduck work on Thunderbird? I can't seem to get it to work.

**Comment by louis-lau** [comment]
Hey @ukwuezeobinna,

Nope. Let us know exactly waht you tried and what didn't work, maybe we can help

**Comment by ukwuezeobinna** [comment]
Hi @louis-lau

This is what I have tried. 2factor is not enabled. I have also tried creating an app password and that didn't work.

![Uploading Screenshot from 2021-12-15 05-45-53.png…]()

**Comment by louis-lau** [comment]
Seems the image didn't upload. What error do you get?

**Comment by ukwuezeobinna** [comment]
![Screenshot from 2021-12-15 05-45-53](https://user-images.githubusercontent.com/852830/146154245-0a66a9c7-67b8-46fe-9882-63cdc90e8781.png)

Error message: unable to log in at server. Probably wrong configuration, username or password.

**Comment by louis-lau** [comment]
Config looks good to me, but I can't check for sure without knowing the real server name.
