### ISSUE TITLE
Sending a message in the api?

### ISSUE THREAD

**Issue by mattmcsparran** [nodemailer/wildduck#37]
I apologize if this isn't the place to put this, and if I'm just not understanding exactly what this does, but is there anything in the API that can be used to send a new email from a user?

Like, if I had an application with a dashboard where I wanted to be able to send emails directly from the application, without having to use wildduck's webmail (if there even is one), or if I wanted to use a custom webmail.

Again, sorry if this isn't the right place for my question. I've looked through the API documentation as well as some of the source code and was unable to find anything.

**Comment by andris9** [comment]
I haven't yet created the sending API as I haven't figured out all the details regarding Drafts. I guess I could slip in a simple sending endpoint though without the Drafts stuff, similar to how autoreplies and message forwarding is handled.

**Comment by mattmcsparran** [comment]
I can take a look and see if I can figure out a decent draft solution. How difficult would it be to put the sending endpoint in?

**Comment by andris9** [comment]
By drafts I mean keeping compatibility with desktop clients, so you could start a draft for example in Outlook and continue editing it via the API and vice versa. There are a lot of moving parts in it, so I haven’t wanted to rush it.

Adding a simple sending endpoint with no draft system would be fairly easy, I’ll look into it in the coming days.

**Comment by mattmcsparran** [comment]
I know that you meant by drafts haha. Sounds good though. Let me know if I can help in any way

**Comment by andris9** [comment]
I created a preliminary submission API, see docs [here](https://api.wildduck.email/#api-Submission). It assumes that you are running WildDuck with ZoneMTA as set up by the [install script](https://github.com/nodemailer/wildduck/tree/master/setup). Message is delivered to destination and uploaded to Sent Mail folder.
