### ISSUE TITLE
Make acme optional?

### ISSUE THREAD

**Issue by nahsi** [nodemailer/wildduck#371]
I'm using mTLS provided by [Consul service mesh](https://www.consul.io/docs/connect) .
So I don't provide certificates to wildduck and I don't need any automatically generated certificates.

This error repeats in logs:
```ERR! Tasks Failed running recurring ACME checks. error=command findAndModify requires authentication```

**Comment by andris9** [comment]
This is a regular check that looks if there are any ACME certs to update. If you do not have any such certs then it does nothing. If that task is failing with `findAndModify requires authentication` then you probably have issues with other things as well as WildDuck is not able to perform database queries.
