### ISSUE TITLE
Email search

### ISSUE THREAD

**Issue by junleus** [nodemailer/wildduck#374]
I am BCC all domain e-mail into a signle  wildduck mailbox, 731k emails at this time. 

when I search a gernal key work, got timeout.

**Comment by junleus** [comment]
mailbox quote
![image](https://user-images.githubusercontent.com/37057723/148814557-8548d41b-4bdd-48fa-9bd3-bcf495e1df0c.png)

**Comment by andris9** [comment]
Usually what happens is that MongoDB can not fit all its indexes to memory and has to read data from disk. Make sure that you have enough memory available for MongoDB so that all indexes would fit into RAM.

**Comment by junleus** [comment]
Thank you Andris, 
do I need manual create indexes?   

> db.collection.totalIndexSize()
0

**Comment by junleus** [comment]
thank you Andris.

**Comment by junleus** [comment]
671k emails and 225GB in single mailbox, check the search working.
