### ISSUE TITLE
how to modify acme.sh config to do DNS challenge

### ISSUE THREAD

**Issue by jhayesdev** [nodemailer/wildduck#375]
Due to my particular network architecture, forwarding port 80/443 through the same subdomain I'm using for my MTA services is not possible.

I am having trouble even _locating_ the ACME script that would be responsible for certificate renewals or if one exists, but I was able to bodge the installer (/opt/wildduck/setup/13_install_ssl_certs.sh) to issue a cert by DNS.

Does the server renew the cert with this script? If so I'm probably fine now, but if I've missed something (and I likely have), please point me in the right direction!

Thanks

**Comment by louis-lau** [comment]
I found some docs for you:
https://github.com/acmesh-official/acme.sh/wiki/dnsapi

> Does the server renew the cert with this script

According to the acme.sh readme:

> The installer will perform 3 actions:
> 
> 1. Create and copy `acme.sh` to your home dir (`$HOME`): `~/.acme.sh/`.
> All certs will be placed in this folder too.
> 2. Create alias for: `acme.sh=~/.acme.sh/acme.sh`.
> 3. Create daily cron job to check and renew the certs if needed.
> 
> Cron entry example:
> 
> ```bash
> 0 0 * * * "/home/user/.acme.sh"/acme.sh --cron --home "/home/user/.acme.sh" > /dev/null
> ```

**Comment by jhayesdev** [comment]
Ahhhh, that's where it is. That clears everything up, and it does appear that the settings I used when I modified and ran the installer have been preserved and a cron job created as described. Thanks for pouring light on this, I was having a bit of a mental impasse.

**Comment by louis-lau** [comment]
Glad to hear it 😁
