### ISSUE TITLE
pools.toml setting

### ISSUE THREAD

**Issue by junleus** [nodemailer/wildduck#376]
Please advice the pools setting,

I am trying to seutp 2 zone-mta into the pools,both **shared the same mongodb**,**redis are using their own.**

 sent 8 emails, 4 emails got 

"_response":"450 Network error when connecting to MX server s9.email.com[1.2.3.4] for email.com: Cannot assign requested address"

pools.toml

[[default]]
address="192.168.1.151"
name="email_131.email.com"

[[default]]
address="192.168.1.153"
name="email_133.email.com"

**Comment by louis-lau** [comment]
Does the host actually have network interfaces zone-mta can bind to for those ips? Seeing the error, I'm guessing not. :)

**Comment by junleus** [comment]
yes, both of then have public IP by outbound NAT. either one working good without pools.

**Comment by junleus** [comment]
I just figure out the pools IP need put into  the same zone-mta vm, but I put it into 2 vm.

**Comment by louis-lau** [comment]
You can also configure 2 VMs, but in that case you shouldn't add both ips to both configs. Only add the ips that that specific instance has. Also make your you set a different instance id in their configs.

**Comment by louis-lau** [comment]
Yes, that's what I meant to say. In case it wasn't clear :)
