### ISSUE TITLE
create a user alias

### ISSUE THREAD

**Issue by Bianconiglio** [nodemailer/wildduck#379]
Hi,
is it possible to add a domain alias to a user?

I saw that it is possible to add an identity to a user but I didn't understand how to add an alias.

let me explain:

my server has two domains configured: mydomain.org and mydomain.com

I created the info user for mydomain.org but if I wanted to receive emails about the user for the mydomain.com domain and then create an alias info@mydomain.com to info@mydomain.org

How can it be done?

the info user already exists and was created with the mydomain.org domain

**Comment by louis-lau** [comment]
Just add another address to the user. That's an alias.

**Comment by Bianconiglio** [comment]
but I cannot create another user info@mydomain.com the info user already exists and is associated with mydomain.org

**Comment by Bianconiglio** [comment]
I would like the info user to receive mail from mydomain.org and from mydomain.com

**Comment by louis-lau** [comment]
Yes, that's what adding an address to the user does. A single user can have multiple addresses.
