### ISSUE TITLE
zonemta time issue

### ISSUE THREAD

**Issue by smile-tommy** [nodemailer/wildduck#385]
For the zonemta,the default bounce time is 48 hours,it is too long.
const ttlMinutes = [
    5 /* 5 */, 7 /* 12 */, 8 /* 20 */, 25 /* 45 */, 75 /* 2h */, 120 /* 4h */, 240 /* 8h */, 240 /* 12h */, 240 /* 16h */, 240 /* 20h */, 240 /* 24h */,
   240 /* 28h */, 240 /* 32h */, 240 /* 36h */, 240 /* 40h */, 240 /* 44h */, 240 /* 48h */
];

I have changed to be as below and restart the server,but after 10 hours,i still not get the bounce emails.
const ttlMinutes = [ 
     3 /* 3 */, 
     5 /* 5 */, 
     6 /* 6 */ 
];

**Comment by louis-lau** [comment]
It would make more sense to open this issue in the zone-mta repository.

Postfix defers for 5 days by default. 48 hours is actually relatively short. Why do you think 48 hours is too long?

**Comment by smile-tommy** [comment]
let the sender know the sending issue is import,for axample,you are sending a bidding rate for the company,there is dead time in 6 hours.
The sender sent the email,but never get warming message,after 48 hours,he get the bounce email,and the bidding time is over,and your company lost the opportunity!!
