### ISSUE TITLE
Server busy, too many connections.

### ISSUE THREAD

**Issue by ukwuezeobinna** [nodemailer/wildduck#399]
When I try to send an email from Thunderbird, I get this error message,

"Sending of the message failed.
An error occurred while sending mail: Outgoing server (SMTP) error. The server responded:  Server busy, too many connections."

The message is then saved in the draft folder. Anyone know why this is happening?

**Comment by louis-lau** [comment]
`Server busy, too many connections` isn't a message that zonemta gives. Are you sure you've configured thunderbird to connect to zonemta? As far as I can see that message is given by the ProxSMTP and ClamSMTP smtp proxies.

**Comment by ukwuezeobinna** [comment]
"Are you sure you've configured thunderbird to connect to zonemta?"
I used the install script, are there additional configurations that needs to be done?

I am using AWS SES for email delivery.

**Comment by louis-lau** [comment]
There shouldn't be. How did you configure thunderbird, and how are you using AWS SES?

**Comment by ukwuezeobinna** [comment]
I am using AWS SES for email delivery.

![Screenshot from 2022-05-24 10-53-49](https://user-images.githubusercontent.com/852830/170027355-ad4f1461-ac8b-4c2e-b2fe-84610cac718a.png)

**Comment by ukwuezeobinna** [comment]
This doesn't seem to happen on webmail.

**Comment by ukwuezeobinna** [comment]
> Hmm. Are you sure the port is open?
> 
> ```
> ❯ curl smtp://mail.chimso.xyz:587 -v --max-time 10
> *   Trying 44.204.183.169:587...
> * TCP_NODELAY set
> * Connection timed out after 10001 milliseconds
> * Closing connection 0
> curl: (28) Connection timed out after 10001 milliseconds
> ```

It is now.

curl smtp://mail.chimso.xyz:587 -v --max-time 10
* Rebuilt URL to: smtp://mail.chimso.xyz:587/
*   Trying 44.204.183.169...
* TCP_NODELAY set
* Connected to mail.chimso.xyz (44.204.183.169) port 587 (#0)
< 421 Server busy, too many connections
* Got unexpected smtp-server response: 421
* Closing connection 0
curl: (8) Got unexpected smtp-server response: 421

**Comment by ukwuezeobinna** [comment]
Maybe I should contact AWS Support for this.

**Comment by louis-lau** [comment]
Maybe you have another smtp server running on your vps? The response doesn't match zonemta.

Yours:
```
❯ curl smtp://mail.chimso.xyz:587 -v --max-time 10
*   Trying 54.90.56.81:587...
* TCP_NODELAY set
* Connected to mail.chimso.xyz (54.90.56.81) port 587 (#0)
< 220 mail.chimso.xyz ESMTP
> EHLO DESKTOP-A8IKKT7
< 250-mail.chimso.xyz
< 250-PIPELINING
< 250-SIZE 11534336
< 250-ETRN
< 250-STARTTLS
< 250-ENHANCEDSTATUSCODES
< 250-8BITMIME
< 250-DSN
< 250 CHUNKING
> HELP
< 502 5.5.2 Error: command not recognized
* Command failed: 502
> QUIT
< 221 2.0.0 Bye
* Closing connection 0
```

zonemta:
```
❯ curl smtp://localhost:587 -v --max-time 10
*   Trying 127.0.0.1:587...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 587 (#0)
< 220 86fef3d70a39 ESMTP Welcome to feeder! [zone-mta/2.4.3]
> EHLO DESKTOP-A8IKKT7
< 250-86fef3d70a39 Nice to meet you, [172.18.0.1]
< 250-PIPELINING
< 250-8BITMIME
< 250-SMTPUTF8
< 250-AUTH LOGIN PLAIN
< 250 SIZE 31457280
> HELP
< 214 See https://tools.ietf.org/html/rfc5321 for details
214 See https://tools.ietf.org/html/rfc5321 for details
* Connection #0 to host localhost left intact
```

**Comment by louis-lau** [comment]
Depending on the new server it may come with an smtp server installed.
