### ISSUE TITLE
Missing new releases

### ISSUE THREAD

**Issue by randrusiak** [nodemailer/wildduck#401]
As I wrote in [one of the issues](https://github.com/nodemailer/wildduck/issues/381#issuecomment-1139446305), I'm considering the wildduck as an email server for my internal project. I'm going to run wildduck on the top of Kubernetes so I rely on the wildduck-dockerized project. Almost everything works great, but I'm worried that the last proper (semver) release is from November 2021.

I can help with containerization and proper releasing stuff, but I want to know whether @andris9 has a plan to standardize the releasing process.
Do you have the willingness to use semantic versioning (or other standardized practice) and maintain a changelog in the future?

**Comment by randrusiak** [comment]
I understand, so I hope you will find time to prepare for the next versioned release. 
Although you treat wildduck as an internal project, you need to know that it brings a lot of value to the community.  So I keep fingers crossed for further development. :)

**Comment by ukwuezeobinna** [comment]
I'm also considering using wildduck for our users at chimso.xyz and docker will be amazing.
