### ISSUE TITLE
procedure for the renewal of certificates

### ISSUE THREAD

**Issue by Bianconiglio** [nodemailer/wildduck#418]
Hi, 
i wanted to know what is the correct procedure to renew the certificates that are used for zone-mta and haraka with the services of imap and smtp. Is it enough to update the certificates in / etc / wildduck / certs or do I have to consider others in different places as well? there is a procedure to follow like with the command

~ / .acme.sh / acme.sh --set-default-ca --server letsencrypt --issue --nginx -d "domainname.com" --key-file /etc/wildduck/certs/privkey.pem - -fullchain-file /etc/wildduck/certs/fullchain.pem --reloadcmd "/usr/local/bin/reload-services.sh" --force

thanks for the support.

**Comment by louis-lau** [comment]
The setup script configures a cronjob to renew them, you don't need to do anything.
