### ISSUE TITLE
Emails are not being sent

### ISSUE THREAD

**Issue by ukwuezeobinna** [nodemailer/wildduck#419]
I installed WildDuck using the Easy Install Script. I can receive emails very well but outgoing emails are not being sent or delivered. How do i troubleshoot this.

 I reached out to my hosting provider(hetzner.com/) and below is their response.

"For our cloud servers the ports 25 and 465 are blocked. But Port 587 is still open. If this port doesn't work either, the problem probably relates to your mail server configuration. However, we do not offer software support for cloud servers."

I will appreciate any help.

URL: https://chimso.xyz

**Comment by louis-lau** [comment]
You need port 25 to send email.

**Comment by ukwuezeobinna** [comment]
Ok, thanks.

**Comment by ukwuezeobinna** [comment]
Can I change the port used for sending emails?

**Comment by andris9** [comment]
If your server provider does not unblock port 25, you can not send mail.

I don't have experience with Hetzner, but other providers usually unblock it if you have a history with them and can justify why you need unblocking (e.g. you are running your company's email server on their premises, etc.).

**Comment by ukwuezeobinna** [comment]
This has been solved. Thanks everyone.
