### ISSUE TITLE
Does wildduck support multiple domains?

### ISSUE THREAD

**Issue by fcardona** [nodemailer/wildduck#42]
I see that wildduck supports domain aliases but does it support multiple domains? If it doesn't out of the box is it possible to have multiple instances of wildduck use the same redis and mongodb?

btw, awesome work!

**Comment by andris9** [comment]
WildDuck is domain name agnostic, if you set up an address for whatever domain then WildDuck accepts messages for it. There is a default domain that is only used when you create users without specifying address, otherwise it is not needed
