### ISSUE TITLE
API not following OpenAPI specification: previousCursor

### ISSUE THREAD

**Issue by rqelibari** [nodemailer/wildduck#422]
The [Wildduck OpenAPI specification](http://docs.wildduck.email/api/openapi.yml) states, that previousCursor shall be a string (e.g. in GetAddressesResponse scheme on line 3901) and yet Wildduck seems to return a boolean some of the times.

**Comment by louis-lau** [comment]
You're right, it should be string or false. I'd prefer null or just undefined tbh, but it's currently implemented to return false if it doesn't exist. If you can fix the spec I'll accept the PR, otherwise someone will do it some other time :).

**Comment by rqelibari** [comment]
@louis-lau How did you write the file when you first committed it (commit [70e0d11](https://github.com/nodemailer/wildduck/commit/70e0d11b005763a195bd512a787d5478b774bcd7?diff=unified)). Did you use tooling to generate it or did you write it up manually?
