### ISSUE TITLE
AutoDiscover / Autoconfig

### ISSUE THREAD

**Issue by vaelu** [nodemailer/wildduck#426]
It would be a really nice feature if WildDuck would support AutoDiscover (Microsoft) and Autoconfig (Mozilla) features by default, so setting up new mail accounts in clients would be easier.

Reference:
https://learn.microsoft.com/en-us/exchange/architecture/client-access/autodiscover
https://wiki.mozilla.org/Thunderbird:Autoconfiguration

**Comment by louis-lau** [comment]
It's been a while since I looked into this, but I think setting up auto discover is done by setting DNS records and/or by server specific files over http. I'm not entirely sure how adding this to wildduck would work, as the domains http and DNS are out of its control. Do you have an idea of how this would function?

**Comment by vaelu** [comment]
It has been a while for me too. I helped Plesk team with integrating it, it's a really irritating and complex thing. Plesk dropped support for some Outlook clients since they all work a bit different from version to version (see https://talk.plesk.com/threads/autodiscover-not-working-properly-on-outlook.356682/page-2#post-893215).

However, the process is something like this:

1. Outlook makes a request to the root domain of the user’s email address to find configuration info (e.g. `https://example.com/autodiscover/autodiscover.xml`)
2. Outlook makes a request to the autodiscover subdomain of the user’s email address to find configuration info (e.g. `https://autodiscover.example.com/autodiscover/autodiscover.xml`)
3. Outlook makes a request to the domain’s root DNS to see if any SRV records exist that point to a host that holds configuration info

There is the possibility to deliver a .xml file which holds the correct information (e.g. like this: https://serverfault.com/questions/244660/is-there-a-way-to-use-the-autodiscover-feature-without-exchange).

Would it be possible to do this on the root domain of wildduck webmail? I think in most cases it's the same domain where the email server runs. And when not, you can create an SRV record to point to the webmail/autodiscover domain. @louis-lau

**Comment by louis-lau** [comment]
If I have louis@example.com, usually my webmail wouldn't be hosted on example.com or autodiscover.example.com. so I'm not quite sure adding this to the webmail would actually make sense. Wouldn't it make more sense to just add the file as a static file to the webhosting of example.com?

I can see it making sense for something like Plesk, as in many cases the web hosting for the root domain wi be on the same server.

**Comment by louis-lau** [comment]
Sorry, I read over your SRV record suggestion :). I would personally just use that php script. I personally don't see a reason for it to integrate with wildduck. It doesn't use any data from wildduck and could be completely standalone. Or it could just be a static file the business uploads to their webhosting

**Comment by vaelu** [comment]
I get your point, it might not make sense since wildduck is more likely to be used at bigger companies/ISPs.

When you have louis@example.com, I thought of something like adding the SRV record to the example.com domain, which then points to the mail server, where the webmail is located.

But I think I will just build a general solution for it, where my web servers redirect all requests to autodiscover.xml to a general site, because managing these SRV is a pain when you don't control DNS.
