### ISSUE TITLE
Shared folders

### ISSUE THREAD

**Issue by ariep** [nodemailer/wildduck#427]
Does WildDuck support anything resembling shared IMAP folders or mailboxes? So a group of users would all have access to some specified IMAP folders -- see [dovecot](https://doc.dovecot.org/configuration_manual/shared_mailboxes/shared_mailboxes/#user-shared-mailboxes) for example. I did not find any reference to something like that in the API documentation. If it's not supported now, would it be easy or likely to be added?

**Comment by louis-lau** [comment]
Currently not, but it's a feature I'd want eventually as well. There is an ACL spec for IMAP that we would likely want to implement for this feature, but it might not be a necessity. Ideally there would also be multiple permission levels for shared mailboxes.

I'm not entirely sure how much work it would be to allow the most basic level of sharing without IMAP ACL or permission levels. I do think it would affect a lot of endpoints and imap commands.

**Comment by SaiCode-OTH** [comment]
is there any update?
