### ISSUE TITLE
Invalid DKIM Generated

### ISSUE THREAD

**Issue by DJCoolDev** [nodemailer/wildduck#430]
I can receive and send mails without any issues. However when testing my score with https://www.mail-tester.com I recognized that the dkim I generated over the API seems to be invalid. How is this possible and what did I do wrong?
DKIM DNS Value (generated by the API)
`v=DKIM1;t=s;p=MIIBCgKCAQEAvMd8IngZiQs4J+Aa3dS4KBkQtnQWUiz0nVrjP5XIYOXwzxsUSqlj+UeKqGKJixd1ZxS5i+1q36RlU9lL7UtX3YkOVtQQkW9Xx3rjQ+1ejJcVzbUkyNzSm2BcK/q6SEKDZS28KVUWP0ObhSkJnLrX7ScndOLCSSeTQVreGYmsUXEezw3SKTZrUJxOIOI6/A7qgL0ctiihSVRjYjE1LsVQ970IUE3cAGm/r0U3omyA9teZvXV/rAZ+PQkqiY1z/81isV5l+SgDjMtKM0GWszfe62m3Aem9+zOizcGMispzef8N0f3FYmdhSs3yHAMMinZJl9ALq1C4LDoQi1cKo3KcxQIDAQAB`
Thanks for your help

**Comment by loickal** [comment]
same issue here, did you manage to solve it? @DJCoolDev

**Comment by andris9** [comment]
Make sure your WildDuck version (specifically zonemta-wildduck plugin) is up to date. Some older versions calculated the signature invalidly
