### ISSUE TITLE
about filters process

### ISSUE THREAD

**Issue by fnpac** [nodemailer/wildduck#44]
https://github.com/nodemailer/wildduck/blob/029aeecc233af54bf9170570d87c2e1695fad922/lib/filter-handler.js#L268

the action ( that key === 'forward' or key === 'targetUrl') of the first filter in forEach , will not be processed in the following logic , why ?

**Comment by andris9** [comment]
I think the first `if(!filterActions...` is dead code and can be removed as `filterActions` is always set by that point.

Or do you have some issues with filters where filters are not used properly?

**Comment by fnpac** [comment]
i think you should remove `if(!filterActions...` . if not the first action's `forward` and `targetUrl` will not be processed.

Thank you for resolving my confusion, if there are other questions, I will send again
