### ISSUE TITLE
VPS sizing (send only)?

### ISSUE THREAD

**Issue by Sjoerd82** [nodemailer/wildduck#445]
Hi I'm currently hosting a site on a small VPS (CentOS 8, 1GB RAM, 1 vCPU x E3/E5) and like to be able to send out transactional emails to my users.

Not too keen on vendor lock-in, I started looking at hosting it myself. Started looking at Postal (Docker image); this scared me a bit as it strongly advices 4GB RAM and 2 CPU's!

How resource-heavy is WildDuck expected to be? Can it be run on a small VPS like mine, next to a website? This does not strictly require a docker setup right? Also, I do not need to _receive_ any emails, so a lot of acompaying tools may not be required. This may scale back the resource usage as well?

Thanks,
Sjoerd

**Comment by andris9** [comment]
WildDuck requires RAM and CPU to run MongoDB. If you do not have a lot of system resources available you might want to go with Dovecot+Postfix setup instead, for example by using https://mailinabox.email

**Comment by Sjoerd82** [comment]
Wow, fast reply 👍. What WildDuck brings to the table is an HTTP API; you don't get that with a Dovecot+Postfix setup.

The HTTP API makes sending email out from a (browser) app a breeze (ie. just an axios/fetch POST to https://wildduck.myhost.com/users/{user}/submit. 

_Alternatively_, my server already exposes a REST API on top of Postgres, I could call a stored procedure / watch a table and use a commandline tool postfix/sendmail (does that still exist?) to send email.

In both cases the server needs a smtp server, the WildDuck approach seems more "wholesome". Am I correct in understanding that the MongoDB takes up most of the resources?

Maybe I'll just give that docker a try on my local machine..

**Comment by louis-lau** [comment]
If you only need to send email, sending with smtp from a webapp backend is just as easy with libraries available for any language.

**Comment by mcolak** [comment]
Please close the issue. Actually this is not an issue this is support case you can use discord channel

**Comment by Sjoerd82** [comment]
Thanks for the info. As my app has grown, I'm currently moving everything into docker images, and will again reconsider Wildduck (Dockerized).
