### ISSUE TITLE
confusion about the responses

### ISSUE THREAD

**Issue by fnpac** [nodemailer/wildduck#45]
https://github.com/nodemailer/wildduck/blob/604e9232f9b2d838425fc480c3b5fcad2b76159a/lmtp.js#L146

rfc2033 desc :

Even if there were multiple successful RCPT commands giving the same forward-path, there must be one reply for each successful RCPT command.

---

this code block is for this ?  think you for your answer.

**Comment by andris9** [comment]
yes, in case of LMTP all RCPT TO calls require a response after message is processed. If you make 5 RCPT TO calls, then you must get 5 responses in the same order afterwards

**Comment by andris9** [comment]
By the way, I'm currently working on a Haraka plugin for Wild Duck that does not require LMTP anymore, so Haraka would run the filtering and forwarding directly and also store the message to message store instead of queueing to for LMTP.
