### ISSUE TITLE
Adding meta data on 'Submit a Message for Delivery' does not work

### ISSUE THREAD

**Issue by WeebNetsu** [nodemailer/wildduck#459]
When I add meta data to 'Upload Message' (/users/{user}/mailboxes/{mailbox}/messages), it works without an issue, however when I try to do the same with 'Submit a Message for Delivery' (/users/{user}/submit) the meta data never gets added to the message, here is an example of the structure of the body data on request:
```
{
                html: emailBody,
                subject,
                text: emailBody,
                bcc: (filteredToEmails as string[]).map(email => ({
                    address: email,
                })),
                meta: {
                    meetingId: meeting._id,
                },
            },
```

I've also tried using `metaData` instead of `meta`. I get no errors, but on retrieval of all the messages using 'List messages in a Mailbox' (/users/{user}/mailboxes/{mailbox}/messages), messages sent using 'Submit a Message for Delivery'  does not include any meta data, but 'Upload Message' messages that was later sent does include the meta data that was given.

I did notice in the code you actually parse metaData on 'Upload Message': https://github.com/nodemailer/wildduck/blob/fd8b65b11f433d28d15ccb8ef6d9c142fed12a4f/lib/api/messages.js#L1584
And you do not on 'Submit a Message for Delivery', does that mean we are supposed to only supply meta data on drafting, then to send the draft?

**Comment by louis-lau** [comment]
The api docs don't mention any metadata property for the "Submit a Message for Delivery" endpoint. That endpoint only sends the email that already exists on the server, and moves it to the sent folder right? What metadata could be added to that action?

**Comment by louis-lau** [comment]
Sorry I'm dumb, was thinking of "Submit draft for delivery". You're right. Either the docs or the functionality is wrong for that endpoint in that case.
