### ISSUE TITLE
Wild Duck Installer does not enable pop3

### ISSUE THREAD

**Issue by fcardona** [nodemailer/wildduck#46]
After a clean install using the Wild Duck Installer there doesn't seem to be any pop3 server listening on port 995.

**Comment by andris9** [comment]
This is now fixed. There was a pop3 server running but it was using port 9110 and it was not using tls. you can either change the pop3 server settings in /etc/wildduck/pop3.toml where you should change the port to 995 and secure to true. Additionally check that the port is allowed by firewall (ufw allow 995)

**Comment by fcardona** [comment]
Thanks.
