### ISSUE TITLE
Outbound not working

### ISSUE THREAD

**Issue by lambrohan** [nodemailer/wildduck#463]
OS -Ubuntu 20.04.4 LTS x86_64
Installed Via  startup script

`
Jun 10 11:03:18 smtp zone-mta[1154]: ERR! Sender/default/1154[1] id=undefined 188a463934d0003f2f.001 CONNFAIL domain=gmail.com local=smtp.example.in[0.0.0.0] remote=142.250.153.27:25 error=Network error when connecting to MX server alt4.gmail-smtp-in.l.google.com[142.250.153.27] for gmail.com: Connection timed out
`

`
Jun 10 11:03:18 smtp zone-mta[1154]: ERR! Sender/default/1154[1] id=undefined 188a463934d0003f2f.001 ERRCONNECT domain=gmail.com error=Network error when connecting to MX server gmail-smtp-in.l.google.com[142.251.16.27] for gmail.com: Connection timed out
`

**Comment by louis-lau** [comment]
The error is pretty clear. Check with your provider if they're not blocking port 25.

**Comment by lambrohan** [comment]
@louis-lau 
![image](https://github.com/nodemailer/wildduck/assets/30184825/b8826cac-734f-4771-8b46-e77f2297440b)

**Comment by louis-lau** [comment]
That's not nessecarily necessarily. Try telnetting in and manually submitting an email if you really want to test for yourself.

**Comment by lambrohan** [comment]
okay, thanks :pray:
