### ISSUE TITLE
Better message updater

### ISSUE THREAD

**Issue by WeebNetsu** [nodemailer/wildduck#464]
Endpoint: `https://api.wildduck.email/users/{user}/mailboxes/{mailbox}/messages` or `https://api.wildduck.email/users/{user}/mailboxes/{mailbox}/messages/{message}/message` (available, but not shown in docs)

Issue: We can only update very specific fields of a message, such as moveTo, seen, flagged, draft, expires, metaData, but it does not allow us to update the subject, text, html, from, to etc.

I would very much appreciate it if we could have an update that can allow us to update an existing message (in drafts) with a simple endpoint call, as of now we need to work around it in a very tedious manner

**Comment by andris9** [comment]
Emails are immutable, you can never edit any email content, only metadata that is not part of the rfc822 message. So modifying message flags is OK, modifying the subject line is not.

**Comment by WeebNetsu** [comment]
I understand, but when an email is saved as a draft, then it is saved so you can continue working on it later? It is saved to be updated in the future, maybe we can have an update endpoint that generates a new email, and carries over the email we are updatings data, then just returns the new email ID and deletes the old one (on request)?

**Comment by louis-lau** [comment]
The way to currently do it is to create a new draft, and delete the old one. The only disadvantage is that it's 2 requests, but otherwise the current situation is already the one you're describing :)

**Comment by WeebNetsu** [comment]
However, if you have attachments attached to a draft, there is no easy way to get those attachments to the new draft, due to the message attachments just having the "ATT---" ID and not their ID in the database to get their content, implementing an endpoint that does that whole new draft creation for you could boost the developer experience when using the API

**Comment by louis-lau** [comment]
There is! Just add them as files (https://docs.wildduck.email/api/#operation/uploadFile) and put their ids in the `files` string array. This is specifically made for not having to upload attachments every time while saving drafts.

> Storage allows easier attachment handling when composing Draft messages. Instead of uploading the attachmnent with every draft update, you store the attachment to the Storage and then link stored file for the Draft.

**Comment by WeebNetsu** [comment]
> There is! Just add them as files (https://docs.wildduck.email/api/#operation/uploadFile) and put their ids in the `files` string array. This is specifically made for not having to upload attachments every time while saving drafts.
> 
> > Storage allows easier attachment handling when composing Draft messages. Instead of uploading the attachmnent with every draft update, you store the attachment to the Storage and then link stored file for the Draft.

Ohhh! Thanks so much, that makes more sense!
