### ISSUE TITLE
clearNotificationListener not defined

### ISSUE THREAD

**Issue by esellier** [nodemailer/wildduck#466]
https://github.com/nodemailer/wildduck/blob/d59eb0058dfe3c0608272e468c8d4dbc6c8ddcf9/imap-core/lib/imap-command.js#LL396C24-L396C24

It should be `this.connection.clearNotificationListener`

**Comment by andris9** [comment]
Thanks! Fixed it with https://github.com/nodemailer/wildduck/commit/5a9f584c74e2849f99a302610921fb485a60f44b
