### ISSUE TITLE
Allow to query for specific file info

### ISSUE THREAD

**Issue by WeebNetsu** [nodemailer/wildduck#468]
Currently we have 2 endpoints, `/users/{user}/storage`, which get all the files stored on the user account and `/users/{user}/storage/{file}`, which downloads a specific file. It would be great have an endpoint like so `/users/{user}/storage/{file}/info` that can be used to get a specific files data (like name and size) from the database or to update `/users/{user}/storage` to allow us to search for a file via its ID as well in the query paramenter (which only does a partial match of a file name).

Currently my way of getting around this is to just call `/users/{user}/storage` and to just pagination-search (call the endpoint again with the next cursor) until I find the file that matches the ID I have. This method however will in the long run, as users upload more files, take longer to run and become more expensive as well. Is there potentially a better way to do this, or can we maybe add one of the above specified solutions?

Referenced Endpoints:
https://docs.wildduck.email/api/#operation/getFiles
https://docs.wildduck.email/api/#operation/getFile

**Comment by andris9** [comment]
The initial assumption was that you'd delete the stored files as soon as you don't need these anymore (once the draft has been sent). But if you don't delete, then yes, the current approach is quite cumbersome. I think the `{file}/info` would be better than the other proposed method.
