### ISSUE TITLE
Feature Request: Mailbox size option when requesting single mailbox information via API

### ISSUE THREAD

**Issue by tfrancois** [nodemailer/wildduck#469]
Currently, when requesting information for a single targeted mailbox via the [API](https://docs.wildduck.email/api/#operation/getMailbox), there is no option to include size calculation as there is when all mailboxes are requested for a user.  Any chance this feature can be added - this is especially useful when wanting to retrieve Inbox folder size without having to query all mailboxes for a given user.  Thanks!

**Comment by andris9** [comment]
WildDuck precalculates the generic used storage number. For anything more specific you would have to use aggregation queries that are super slow so this is not very feasible. Aggregations are OK for background tasks but not for regular API queries.

**Comment by tfrancois** [comment]
Thank you for reply @andris9.  But I guess I'm wondering - sorry if I'm not clear - how the size storage is provided when querying all user folder/mailbox list (via sizes query param) but not available when only requesting an individual mailbox.  Why not just make this same query param available so that the entire list does not have to be requested.  Again sorry for confusion if I'm missing something.
