### ISSUE TITLE
Not able to create custom setting using the settings API.

### ISSUE THREAD

**Issue by tfrancois** [nodemailer/wildduck#470]
Hi, it appears from the API documentation that custom settings can be defined via the [/settings](https://docs.wildduck.email/api/#operation/createSetting) api.  This is further confirmed by the settings list response having a custom flag/property.  But when I try to create a custom setting, I get this error:

`'"key" must be one of [const:archive:time, const:max:storage, const:max:recipients, const:max:rcpt_to, const:max:forwards, const:authlog:time, const:autoreply:interval, const:asp:limit, const:max:imap:download, const:max:pop3:download, const:max:imap:upload, const:max:filters]'`

Additionally, on a side note, exactly how do you format a filter string when performing a /GET settings API call please?  No matter what I try the settings list always returns the full list.

Sorry in advance if I'm misunderstanding this functionality - thank you!

**Comment by louis-lau** [comment]
The api is for setting settings for wildduck, not for storing your own custom settings :)

https://docs.wildduck.email/#/in-depth/default-values

**Comment by tfrancois** [comment]
Thanks for the reply - understood.
