### ISSUE TITLE
Any way to include List-ID when using GET /users/{user}/mailboxes/{mailbox}/messages API?

### ISSUE THREAD

**Issue by tfrancois** [nodemailer/wildduck#472]
I have a critical need to have the list-id included in the output for messages when listing messages in a mailbox.  Currently the paged results does not have that available and I would rather NOT have to make round trips to the server for each record in the results array just to retrieve this info.  In the message information API, this is located in: list.id.name.  I could try to make the change in source code directly, but terrified my changes would be lost when I apply any updates.  PLEASE HELP @andris9.  It's an urgent need and I would be willing to pay you for your time to implement this.  Please let me know.  Thanks!

**Comment by tfrancois** [comment]
I found where to make the change and it actually very quick - just never created a Pull Request before or done a fork - and the change is so simple I think all of that would be overkill for 1 line of code.

The change needs to occur in /lib/api/message.js:

I added the following 1-liner:
`listId: parsedHeader['list-id'] || null,`

Added to line 3130 in the let response = { ... } object, right after messageId = ...

Any way this can please be added permanently to the codebase so future releases include it please?  Thank you @andris9 .

**Comment by andris9** [comment]
I used a slightly different approach in the latest master branch. You can use `?includeHeaders=List-ID` GET argument to make WildDuck include the requested header values in the `headers` response property.

```
curl "http://localhost:7003/users/USER/mailboxes/FOLDER/messages?includeHeaders=Message-ID,Return-Path"
{
  "success": true,
  "total": 2,
  "page": 1,
  "previousCursor": false,
  "nextCursor": false,
  "specialUse": null,
  "results": [
    {
      "id": 2,
      "mailbox": "FOLDER",
      ...,
      "headers": {
        "message-id": "<1892a040b970003b95@xn--80addjzccu7a0a.xn--p1ai>",
        "return-path": "<info@xn--80addjzccu7a0a.xn--p1ai>"
      }
      ...
```

**Comment by tfrancois** [comment]
Andris - this IS OUTSTANDING! Thank you for your reply sir.
