### ISSUE TITLE
for if else

### ISSUE THREAD

**Issue by fnpac** [nodemailer/wildduck#48]
https://github.com/nodemailer/wildduck/blob/cca4a9adc4a1ef98c5fe07ddd4de43bd233b784e/lib/message-splitter.js#L67

why not use `or` in `if` , and the `if (pr1 === 0x0a)` is for what ?  thx for reply.

**Comment by andris9** [comment]
Messages might have lines that end with `<CR><LF>` (the correct way) or by `<LF>` (invalid but sometimes used). This code tries to detect which line ending was used
