### ISSUE TITLE
how can i get the right license

### ISSUE THREAD

**Issue by julywind** [nodemailer/wildduck#49]
hi sir, 
I want to use your code in my own private project,  how can i get the right license? 
Can we have a talk？ I just send a chat invitation to you on google+.

**Comment by julywind** [comment]
sorry,I sent the chat invitation to you on hangouts.(https://hangouts.google.com/)

**Comment by andris9** [comment]
For now you have to go with the EUPL license. I have no plans to change it, there are also other dependencies like ZoneMTA where I do not own the license, so i can't change it.
