### ISSUE TITLE
Feature request: Some way to filter messages by "flag".

### ISSUE THREAD

**Issue by D33M0N** [nodemailer/wildduck#494]
Some way to toggle "flag" visibility.
on = Hide everything that is not flagged;
off = normal.

**Comment by D33M0N** [comment]
What exactly am I supposed to to write into the search field? just writing `flagged: true` does nothing at all.

**Comment by louis-lau** [comment]
Wildduck doesn't have a search field, just an api where you can call the search endpoint. Is this an issue meant for wildduck-webmail? I can transfer it if you want.

**Comment by louis-lau** [comment]
Also, in the case of wildduck-webmail, I believe there's a "starred" section on the left that already does just that.

**Comment by D33M0N** [comment]
> Wildduck doesn't have a search field, just an api where you can call the search endpoint. Is this an issue meant for wildduck-webmail? I can transfer it if you want.

yes.

> Also, in the case of wildduck-webmail, I believe there's a "starred" section on the left that already does just that.

no.
![image](https://github.com/nodemailer/wildduck/assets/15782020/4b6305d7-2510-4e71-a556-d21bcbc29b1a)

**Comment by louis-lau** [comment]
That's zone webmail. It uses wildduck as a backend, but is otherwise completely separate from this project. Wildduck has the capability, it's upon the developers of zone webmail to implement this. Is their webmail even open source? I'm not sure why you came to this project looking for help instead of contacting Zone.

**Comment by andris9** [comment]
+1 to what Louis said - if you are using WildDuck API, then use `flagged=true` ([docs](https://docs.wildduck.email/api/#operation/searchMessages)). If you need help with using the webmail client as a end user then this is the wrong place for it.
