### ISSUE TITLE
Is it possible to forward copies of outgoing messages?

### ISSUE THREAD

**Issue by Access-deny** [nodemailer/wildduck#499]
Hello!
Is it possible to send copies of outgoing (automatically, without CC) emails (from the web interface and generally sent by any available methods, any outgoing, but in a way that is configurable)?
The filter From (myuser@server) does not send outgoing messages to the address specified in forward. In this case, the incoming filter works and redirects as indicated.
I need any outgoing message from the self user address to be redirected to any other addresses (like a filter in Exim - if $sender_address is myuser@server or $h_from is myuser@server then unseen deliver anyemail@anyserver).
Thank you.

**Comment by Access-deny** [comment]
Since there is no answer, then, as I understand it, this is too stupid question or the wrong question :).
@andris9, can you help? I need to be able to send copies of outgoing ones if this is indicated in the filter. Do I need to write a custom plugin for this? Custom plugin for zome-mta or wildduck? (For example, using the wildduck api you configure a filter from (current mail address) to (some address). The plugin retrieves these addresses from the filter (from mongoDB) and somehow sends a copy to them when sending mail. Just how?
Or is there some simpler option? What do you think?

**Comment by andris9** [comment]
You could write a ZoneMTA plugin, but this would only apply to messages sent over SMTP. All emails sent via API/webmail bypass ZoneMTA plugins that add emails to the queue. But, in general, WildDuck is not designed to work this way. If you need access to sent emails, then you can use the auditing feature https://docs.wildduck.email/#/additional-software/auditing
