### ISSUE TITLE
Dead cycle

### ISSUE THREAD

**Issue by fnpac** [nodemailer/wildduck#50]
https://github.com/nodemailer/wildduck/blob/571dbc0babdc9009ffbcc47a539798048f7ab1cf/lib/maildropper.js#L106

if user `A` forward is Null,
this line will forward to A self, is this will gets dead cycle? 

As autoreply has `Auto-Submitted` (and so on) headers to break  dead cycle.

what about forward logic ? thx

**Comment by andris9** [comment]
If user does not have forwarding addresses set, then forwarder is never invoked and this line is never reached.

If there's an infinite loop of forwarding, then it is immediately stopped by `X-Zone-Loop` header that is added to the message.

**Comment by fnpac** [comment]
this code is for what? why not callback immediately?

**Comment by andris9** [comment]
Messages can be sent in two ways:

1. by using the `targets` array. This is needed when using special settings like forwarding the same message to next relay etc. If `targets` is set then `to` array is used for SMTP envelope but not for MX DNS resolving
2. by using the `to` array. This is "normal" delivery, for example when invoking the [submission API call](https://api.wildduck.email/#api-Submission-PostSubmit). Addresses from `to` array are used to resolve MX DNS addresses.

The code checks if you had special delivery settings set in the `targets` array (case 1) and if not then proceeds as it would be a "normal" message (case 2)

**Comment by fnpac** [comment]
this code just for autoreply because of autoreply does not have `targets` array , right ?

**Comment by andris9** [comment]
submit does not use targets also. compare [submit](https://github.com/nodemailer/wildduck/blob/b48382b8cc962800d267400afc78a4f1b2efd9a5/lib/api/submit.js#L345-L352) (no targets, just `to`) with [forward](https://github.com/nodemailer/wildduck/blob/571dbc0babdc9009ffbcc47a539798048f7ab1cf/lib/forward.js#L4-L14) (has targets)

**Comment by fnpac** [comment]
I have not touched the api module, as you said above, 
I understand as `autoreply` and `submmit` are same that all of them do not have `targets ` , they just have `to`, right ?

**Comment by andris9** [comment]
yes, these are "normal" emails and thus do not need any special settings like it is with forwarded messages.

btw. are you planning to use WildDuck as an actual email server or are you just interested of how it works?

**Comment by fnpac** [comment]
WildDuck is so beautiful, i want to use WildDuck as an actual email server, and i am very interested in how it works, i want to learn more about it and give it some contribution as possible. 

btx, thinks for your help.

**Comment by andris9** [comment]
Thanks ☺️

I hope the code is not too difficult to understand. I've been working on it alone and thus have not paid too much attention on code comments or explaining why or what something actually does.
