### ISSUE TITLE
\wildduck\config\default.toml: Expected "\n" but "_" found.

### ISSUE THREAD

**Issue by 0xbalazstoth** [nodemailer/wildduck#507]
By following the docs: [https://docs.wildduck.email/#/general/install?id=wildduck-only](url)
Running with this code as suggested:
- `node server.js`

Got this error:
- `\wildduck\config\default.toml: Expected "\n" but "_" found.`

**Did not modified anything, just followed the wildduck only installation instructions.**

**Comment by andris9** [comment]
I can't reproduce it. Followed the same steps and WildDuck started without errors. Besides, there is not a single `_` character in default.toml 🤔

**Comment by 0xbalazstoth** [comment]
@andris9 What should I do?

**Comment by louis-lau** [comment]
Seeing the `\`, it looks like a Windows path. Maybe it has to do with CRLF line endings? Git does a conversion on Windows by default.

**Comment by 0xbalazstoth** [comment]
Yeah, I'm using Windows 10.

**Comment by bogvak** [comment]
Just in case someone else will search for the same issues, indeed it's up to file endings. 
So you should care that manifest with configmaps should has LF line ending.
