### ISSUE TITLE
Remove `server.notifier` requirement (make it conditional if `server.notifier` is detected)

### ISSUE THREAD

**Issue by titanism** [nodemailer/wildduck#509]
It appears that `server.notifier` is actually used, despite a comment asking if it was:

<https://github.com/nodemailer/wildduck/blob/6e0b95102f681678882210df0c941c23973393b6/imap.js#L130-L132>

If the `server.notifier` property is not available, then an uncaught exception will occur here (and possibly elsewhere):

```sh
TypeError: Cannot read properties of undefined (reading 'addListener')
    at IMAPConnection.setupNotificationListener (/Users/user/Projects/web/node_modules/.pnpm/wildduck@1.40.0/node_modules/wildduck/imap-core/lib/imap-connection.js:620:31)
    at /Users/user/Projects/web/node_modules/.pnpm/wildduck@1.40.0/node_modules/wildduck/imap-core/lib/commands/login.js:131:22
```

**Comment by andris9** [comment]
No, it is not about webhooks. The `notifier` object enables communication between different sessions. If an email is marked as `\Seen` in one session, then the session manager uses the notifier to notify other sessions about that change. This info will then be pushed to the client. The in-memory test notifier is a simple implementation that only allows creating sessions inside the same process, but in the case of WildDuck, different sessions can be even in different servers in different data centres.
