### ISSUE TITLE
Users can create infinite mailboxes

### ISSUE THREAD

**Issue by titanism** [nodemailer/wildduck#512]
Hi @andris9 just sharing that we looked at on the handler for `onCreate` and don't see that it prohibits users from creating an infinite amount of mailboxes nor does it check the user's current quota.

**Comment by andris9** [comment]
Yeah, all these limits are implementation-specific. The test server instance uses Arrays, and you have to consider issues like running out of memory if the array grows too large, but WildDuck itself stores mailboxes as database entries, and these are not hard-capped like Maildir folders, where you need to count inode values. There probably should be some sanity check limit, though. Maybe as well 10k like Gmail, or 100k, I'll add this to our JIRA backlog (WildDuck development happens mostly off-Github).
