### ISSUE TITLE
Message handler not taking into consideration mailbox flags

### ISSUE THREAD

**Issue by titanism** [nodemailer/wildduck#514]
Not sure if this is intended @andris9 but the `add` function here might want to take into consideration the `specialUse` of `mailboxData` if it was `'\\Deleted'`.  Not sure if your search stuff does something different but just filing this so I don't forget.  Sorry if this is overkill!

```diff
-                                    if (!flags.includes('\\Deleted')) {
+                                    if (!flags.includes('\\Deleted') && mailboxData.specialUse !== '\\Deleted')) {
                                        messageData.searchable = true;
                                    }
```

**Comment by andris9** [comment]
`\Deleted` message flag has special meaning. It is not a classifying information but a technical flag - this email will be immediatelly deleted once EXPUNGE or CLOSE command is invoked. Sometimes mail clients delay that operation to allow to “undo” deleting a message, but the messsage should already be hidden from listings etc.
