### ISSUE TITLE
Message handler not deleting newly created thread in rollback function

### ISSUE THREAD

**Issue by titanism** [nodemailer/wildduck#515]
Just noticed that if a thread was newly created and if a rollback occurred (e.g. an error) in the message handler add/create then the thread was not deleted/cleaned up.  Assuming this is because a parallel request (or simultaneous retry) could be made and we don't want to delete that newly created thread ID reference in that case if it was used in parallel.

<https://github.com/nodemailer/wildduck/blob/be900691dab73f126b9429a8d6da2c43739f3f16/lib/message-handler.js#L480-L496>

**Comment by andris9** [comment]
Threads are never cleaned up, these expire over time to reclaim space. It is basically a hash of message-id values.
