### ISSUE TITLE
Feature request: Ability to pass custom resolver for `dns.reverse`

### ISSUE THREAD

**Issue by titanism** [nodemailer/wildduck#516]
We would love to be able to use our project [Tangerine](https://github.com/forwardemail/tangerine) instead of the default `dns` module which is used in IMAP connection.  Using Tangerine ensures consistency in reverse lookups across all of our servers (using DNS over HTTPS with Redis caching).

```js
imap-core/lib/imap-connection.js
8:const dns = require('dns');
192:            dns.reverse(this.remoteAddress, reverseCb);
```

<https://github.com/nodemailer/wildduck/blob/be900691dab73f126b9429a8d6da2c43739f3f16/imap-core/lib/imap-connection.js#L192>

**Comment by andris9** [comment]
You could try to implement this yourself and create a PR where you would pass Tangerine as an alternative resolver. DoH will not be used by default in WildDuck. DoH is good for consumers but not for distributed data centre applications. You will lose all OS and DC level caching, custom resolving configuration/routing and optimizations. Additionally, when you are running thousands of DNS queries per second like a large WildDuck cluster does, then you start hitting throttling limits even with Cloudflare DoH.

The main WildDuck cluster that drives the development needs for WildDuck consists of several server racks of physical servers in different data centres, so it has different requirements than a smaller installation with few VPS servers has. WildDuck and ZoneMTA have all process-level DNS optimizations (eg. ZoneMTA can cache DNS results in Redis) turned off in production and only rely on OS/DC level configuration, which is specifically tuned for the cluster.
