### ISSUE TITLE
Question about Attachment's fields (disposition and hash)

### ISSUE THREAD

**Issue by EitanBoskovitz** [nodemailer/wildduck#519]
Hey,
I think there might be a gap in my understanding of the API regarding attachments,
When I use the upload message endpoint ([https://api.wildduck.email](https://api.wildduck.email/users/%7Buser%7D/mailboxes/%7Bmailbox%7D/messages)[/users/{user}/mailboxes/{mailbox}/messages](https://api.wildduck.email/users/%7Buser%7D/mailboxes/%7Bmailbox%7D/messages))
I pass these two attachments like so:
`[
  {
    content: "https://s3.amazonaws.com/bm-s-user-images/eml/ZWl0YW4uYkBpbmxhYnMubWU_/56dee8f0-85d5-4af3-bbdf-b8f2a75ee2f8.att",
    filename: "b64stringExample.txt",
    contentType: "text/plain",
    cid: undefined,
  },
  {
    content: "https://s3.amazonaws.com/bm-s-user-images/eml/ZWl0YW4uYkBpbmxhYnMubWU_/3d99bee8-4e2f-4289-8e90-bbd17e8eccf9.att",
    filename: undefined,
    contentType: "image/png",
    cid: "ii_085481134851274310",
  },
]
`

The first object is an attachment I added to a mail, and the second object is an inline photo I added into the mail body.

When I get the message from wildduck using the Request Message information endpoint ([https://api.wildduck.email](https://api.wildduck.email/users/%7Buser%7D/mailboxes/%7Bmailbox%7D/messages/%7Bmessage%7D)[/users/{user}/mailboxes/{mailbox}/messages/{message}](https://api.wildduck.email/users/%7Buser%7D/mailboxes/%7Bmailbox%7D/messages/%7Bmessage%7D)),

I get these two attachment objects:
`[
  {
    id: "ATT00001",
    filename: "b64stringExample.txt",
    contentType: "text/plain",
    disposition: "attachment",
    transferEncoding: "base64",
    related: false,
    sizeKb: 1,
    size: 110,
  },
  {
    id: "ATT00002",
    filename: "attachment-2.png",
    contentType: "image/png",
    disposition: "attachment",
    transferEncoding: "base64",
    related: false,
    sizeKb: 1,
    size: 110,
  },
]`

1. Is passing the cid in the attachment sufficient for wildduck to classify it with inline disposition? or will I also need to pass the HTML?
2. I'm not getting back the hash field for the attachment, Am i missing something that I should've added?

Thanks in advance for any help provided

**Comment by andris9** [comment]
When you upload an email, it gets compiled into a rfc822 formatted eml file. When you fetch message details, that email gets parsed into a JSON structure. So, the input and output will differ somewhat.

When uploading the email, use the `cid` URLs to reference embedded images.
```
"html": "...<img src=\"cid:unique-value@example\">...",
"attachments": [
  {
    "cid": "unique-value@example"
  }
]
```

When you download the email, you will see a different image element in the HTML, though:
```
<img src="attachment:ATT00002">
```
and you should replace it with the attachment with id ATT00002

**Comment by EitanBoskovitz** [comment]
Thank you for the explanation about cid, it was clear and helpful :)
