### ISSUE TITLE
Feature request: onStatus handler could use parallel countDocument request for performance improvement

### ISSUE THREAD

**Issue by titanism** [nodemailer/wildduck#529]
Right now the `countDocuments` queries occur in series, however they could occur in parallel for better performance response time (and more accuracy):

<https://github.com/nodemailer/wildduck/blob/fed3d93f7f2530d468accbbac09ef6195920b28e/lib/handlers/on-status.js#L33-L52>

**Comment by andris9** [comment]
STATUS is a background command, no user ever sees or expects its output. So this approach makes it slightly slower but reduces strain on the DB.
