### ISSUE TITLE
let's encrypt integration

### ISSUE THREAD

**Issue by cookiengineer** [nodemailer/wildduck#53]
Hey there,

I've been trying out wildduck locally - and so far this seems like exactly what I need: a modern email server that can be extended and customized.

However, regarding security: Is there a way to integrate let's encrypt auto signing for domains with wildduck?

If not, where would I start in the codebase and what would be the necessary steps to do this?

Thanks in advice.

**Comment by andris9** [comment]
If you install WildDuck using the [install script](https://github.com/nodemailer/wildduck/tree/master/setup) then it automatically sets up Lets Encrypt certificates and also renews these periodically.
