### ISSUE TITLE
Bug: onSearch handler has `returned` variable which causes early return and timeout (callback invocation is expected)

### ISSUE THREAD

**Issue by titanism** [nodemailer/wildduck#531]
The following code causes a function to return when it should instead invoke a callback:

<https://github.com/nodemailer/wildduck/blob/fed3d93f7f2530d468accbbac09ef6195920b28e/lib/handlers/on-search.js#L330-L332>

This should instead be changed to:

```diff
            if (returned) {
-                return;
+                return callback(new Error('Can not make requested search query'));
            }
```

**Comment by andris9** [comment]
There would usually be about 3-4 search terms, so while it would be more optimal, it wouldn't really change anything if the loop is stopped earlier.
