### ISSUE TITLE
Feature: IMAP4rev2 support

### ISSUE THREAD

**Issue by titanism** [nodemailer/wildduck#534]
Currently IMAP4rev1 is only supported, and IMAP4rev2 and [JMAP](https://github.com/nodemailer/wildduck/issues/2) would be nice addons.

Ref: <https://gist.github.com/nevans/8ef449da0786f9d1cc7c8324a288dd9b> (nice table)

**Comment by louis-lau** [comment]
> Although IMAP4rev2 is still being drafted, looking at the extensions that it includes can be used to prioritize adding the most useful capabilities to an IMAP4rev1 client or server.

I think this is pretty much the current situation? I feel like a feature request for a specific standard that's useful might be more helpful.
