### ISSUE TITLE
Bug: Messages not showing when appended to sent folder due to `ignore`

### ISSUE THREAD

**Issue by titanism** [nodemailer/wildduck#537]
This could just be a local issue or something, but I think that when a new message is appended to the Sent Folder it shouldn't be ignored by the local session (e.g. when you send an outbound SMTP message in a client like Thunderbird and then it gets appended to the Sent Folder).  Otherwise it doesn't show in the sent folder unless you completely close and re-open the client for LIST and FETCH to occur.

<https://github.com/nodemailer/wildduck/blob/73acc42cd19af0e9fd0703d5306838f7ac5c9f17/lib/message-handler.js#L554>

This line should be commented out (at least when I tested it locally it works properly when I commented it out).

**Comment by andris9** [comment]
Hmm, in this case, I don't actually remember anymore why the limitation is in place. Just removing it might fix this specific situation but break something else 🤔
