### ISSUE TITLE
Bug: `tls` now supports `dhparam: 'auto'`

### ISSUE THREAD

**Issue by titanism** [nodemailer/wildduck#541]
Right now it's hard-coded to read a path string, and doesn't support `'auto'`:

<https://github.com/nodemailer/wildduck/blob/917e029a90aaad3fa6b95100ea05de5e4495c4e7/lib/certs.js#L53-L55>

<img width="857" alt="Screen Shot 2023-10-19 at 11 18 27 AM" src="https://github.com/nodemailer/wildduck/assets/101466223/4cd6ff3b-30b0-4650-b203-3880e261a880">

Available since node v18.16.0+, you can set `dhparam: 'auto'` for sensible defaults for Perfect Forward Secrecy:

<https://nodejs.org/api/tls.html#perfect-forward-secrecy>

**Comment by andris9** [comment]
I wouldn't classify this as a bug. WildDuck follows the common pattern where you specify the dhparam file you have generater with the openssl command. It's the same as in Nginx and many other server applications. Tbh, in email, with ancient legacy client applications, it's a wonder if the client can even use DHE. Many clients can't even use SNI.
