### ISSUE TITLE
problems with the install script

### ISSUE THREAD

**Issue by himbeere** [nodemailer/wildduck#55]
Hello.

Thanks for your cool software!

Ran into two problems. First letsencrypt cert is not created. Error message:

```
[Sat Jan 27 11:10:25 CET 2018] Install success!
./install.sh: line 565: /root/.acme.sh/acme.sh: No such file or directory
Warning: Failed to generate certificates, using self-signed certs
```

Second problem: /webmail/send gives me currently 502. Error message:

```
2018/01/27 11:12:32 [error] 19000#19000: *231 upstream prematurely closed connection while reading response header from upstream, client: myip, server: mydomainname, request: "GET /webmail/send HTTP/2.0", upstream: "http://127.0.0.1:3000/webmail/send", host: "mydomainname"
```

Any ideas where i should start to debug? It's a clean ubuntu 16.04 machine.

thanks and cheers

**Comment by himbeere** [comment]
Seems wildduck is crashing.

```
Jan 27 12:17:01 ubuntu CRON[6901]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Jan 27 12:18:20 ubuntu node[6458]: http API GET /users/5a6c4c1d9b5ea73c59058a8b/addresses 200 2ms
Jan 27 12:18:20 ubuntu node[6458]: http API GET /users/5a6c4c1d9b5ea73c59058a8b/mailboxes?counters=true 200 3ms
Jan 27 12:18:20 ubuntu node[6880]: /opt/wildduck-webmail/routes/webmail.js:105
Jan 27 12:18:20 ubuntu node[6880]:                 if (messageData.meta && messageData.meta.reference) {
Jan 27 12:18:20 ubuntu node[6880]:                                 ^
Jan 27 12:18:20 ubuntu node[6880]: TypeError: Cannot read property 'meta' of undefined
Jan 27 12:18:20 ubuntu node[6880]:     at getMessageData (/opt/wildduck-webmail/routes/webmail.js:105:33)
Jan 27 12:18:20 ubuntu node[6880]:     at getMessageData (/opt/wildduck-webmail/routes/webmail.js:95:24)
Jan 27 12:18:20 ubuntu node[6880]:     at apiClient.mailboxes.list (/opt/wildduck-webmail/routes/webmail.js:98:13)
Jan 27 12:18:20 ubuntu node[6880]:     at _exec (/opt/wildduck-webmail/lib/api-client.js:162:24)
Jan 27 12:18:20 ubuntu node[6880]:     at req.push (/opt/wildduck-webmail/lib/api-client.js:329:16)
Jan 27 12:18:20 ubuntu node[6880]:     at parseResponse (/opt/wildduck-webmail/node_modules/restify-clients/lib/JsonClient.js:105:9)
Jan 27 12:18:20 ubuntu node[6880]:     at IncomingMessage.done (/opt/wildduck-webmail/node_modules/restify-clients/lib/StringClient.js:207:13)
Jan 27 12:18:20 ubuntu node[6880]:     at Object.onceWrapper (events.js:313:30)
Jan 27 12:18:20 ubuntu node[6880]:     at emitNone (events.js:111:20)
Jan 27 12:18:20 ubuntu node[6880]:     at IncomingMessage.emit (events.js:208:7)
Jan 27 12:18:20 ubuntu node[6880]:     at endReadableNT (_stream_readable.js:1055:12)
Jan 27 12:18:20 ubuntu node[6880]:     at _combinedTickCallback (internal/process/next_tick.js:138:11)
Jan 27 12:18:20 ubuntu node[6880]:     at process._tickCallback (internal/process/next_tick.js:180:9)
Jan 27 12:18:20 ubuntu systemd[1]: wildduck-webmail.service: Main process exited, code=exited, status=1/FAILURE
Jan 27 12:18:20 ubuntu systemd[1]: wildduck-webmail.service: Unit entered failed state.
Jan 27 12:18:20 ubuntu systemd[1]: wildduck-webmail.service: Failed with result 'exit-code'.
Jan 27 12:18:20 ubuntu systemd[1]: wildduck-webmail.service: Service hold-off time over, scheduling restart.
Jan 27 12:18:20 ubuntu systemd[1]: Stopped Wildduck Webmail.
Jan 27 12:18:20 ubuntu systemd[1]: Started Wildduck Webmail.
Jan 27 12:18:21 ubuntu node[6937]: info Express WWW server listening on port 3000
```

**Comment by andris9** [comment]
Yeah, this is a problem that should be fixed by now. I did forgot to update install script to reflect the changes though. Currently testing the changes.

**Comment by andris9** [comment]
Not sure about the acme part though. It should install fine in most cases :S

**Comment by himbeere** [comment]
Hi @andris9 

Thanks for your quick answer. Ok. I'll try to run the install script again. 

The acme thing is caused by running the install script with sudo. If i execute it as "real" root it works.

**Comment by andris9** [comment]
I verified that the updated install script works. Not sure about how to handle the acme thing. Did everything else work when running with sudo? I guess it installs acme to the home of actual user and not to /root

**Comment by himbeere** [comment]
>I guess it installs acme to the home of actual user and not to /root

Right.

The install script works now. Thank you very much.

May I add another question? How am i supposed to make updates of the software? Uh and another, okay, that is two questions. Can i prevent anonymous users from register themself an email address?

thanks again.

**Comment by andris9** [comment]
* To prevent additional signups edit /etc/wildduck/wildduck-webmail.toml and set the allowJoin value to false. This disables account creation page and thus signups.
* Updates are not very streamlined yet. It is possible via git though:
  1. You would have to add your ssh key to /home/deploy/.ssh/authorized_keys
  2. Next check out locally the part of the app you want to manage (you can find the remote repository urls from hostname-nameserver.txt). For example if you want to manage the web interface and your hostname is example.com then you would run `git clone deploy@example.com:/var/opt/wildduck-webmail.git`
  3. Then navigate to the local git repo (`cd wildduck-webmail`)
  4. Now you can link it with the master repo `git remote add upstream git://github.com/nodemailer/wildduck-webmail.git`
  5. Pull the updates from upstream `git pull upstream master`
  6. Push the updates to your own server `git push origin master` (you may need to use -f first time)

I hope to get a better update magament in the future once the code base is stable enough so I can start making packages. For now it is too inconvenient.

**Comment by himbeere** [comment]
Hi @andris9 

Any progress regarding updates? Do I still need to do it with git?

thanks and cheers
