### ISSUE TITLE
Bug: `CHECK` command not working properly (should not error if authenticated)

### ISSUE THREAD

**Issue by titanism** [nodemailer/wildduck#556]
Connection state should be either "Authenticated" or "Selected".

Right now if you try to use `himalaya` and run `himalaya account sync` you will get an error with any WildDuck server (it will not sync _any_ messages) due to this.

Submitting a PR shortly.

**Comment by andris9** [comment]
CHECK and CLOSE are only valid in the Selected state, see https://datatracker.ietf.org/doc/html/rfc3501#section-6.4

In these cases it is best to compare other implementations - for example, how do Gmail/MS365 etc IMAP servers respond if you try to use the non-standard approach, in this case if you would run these commands in an Authenticated state. If other implementations follow the spec, then WildDuck should do so as well. I’m on the phone right now so I can’t check this myself.

**Comment by andris9** [comment]
I just checked with Gmail, and it returns `BAD CLOSE not allowed now.` This is also what is defined in the spec, so there is no reason to allow these commands. On the other hand, it might be a symptom of some other issue. Why does the client library think that it is in the selected state? Maybe WildDuck closed the folder prematurely? You can check this by going through the IMAP commands processed by WildDuck and checking manually if the client should be in the Selected or in the Authenticated state at the time the CLOSE command was issued.
