### ISSUE TITLE
Bug: Case for `date` for `term.key` missing in `onSearch` function

### ISSUE THREAD

**Issue by titanism** [nodemailer/wildduck#560]
Right now the only two keys related to date supported for search are `internaldate` and `headerdate`.  If you are using `imap-flow` to search a mailbox, then the date key is not supported:

```js
  // dates
  for (const key of [
    'before',
    'on',
    'since',
    'sentBefore',
    'sentOn',
    'sentSince'
  ]) {
    await imapFlow.search({ [key]: new Date(Date.now() + 10000) });
  }
```

Ref: <https://github.com/nodemailer/wildduck/blob/ea24b9328b6984db841de86309f1712f100acb97/lib/handlers/on-search.js#L204-L288>

**Comment by andris9** [comment]
Did you check your implementation against [rfc3501#6.4.4](https://datatracker.ietf.org/doc/html/rfc3501#section-6.4.4)? It is pretty specific on how to compare dates when searching.

**Comment by andris9** [comment]
Oh, I see it now, instead of `case 'headerdate':` there should be `case 'date':` and this would fix the senton/sentsince/sentbefore queries. No-one really uses these, and IMAP search in general, is extremely unreliable, so clients usually use as simple search queries as possible.
