### ISSUE TITLE
Bug: Content encoding is incorrect

### ISSUE THREAD

**Issue by titanism** [nodemailer/wildduck#563]
```eml
Message-ID: <6767f034-bbc1-4086-bced-cd65088eb574@test.net>
Date: Sun, 26 Nov 2023 02:21:11 -0600
MIME-Version: 1.0
User-Agent: Mozilla Thunderbird Beta
From: test <test@test.net>
Subject: test
To: test@test.com
Content-Language: en-US
X-Mozilla-Draft-Info: internal/draft; vcard=0; receipt=0; DSN=0; uuencode=0;
 attachmentreminder=0; deliveryformat=0
X-Identity-Key: id1
Fcc: imap://test%test.net@imap.test.net/Sent Mail
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: 8bit

<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  </head>
  <body>
    <p>Hey!</p>
    <p>This is a test!</p>
    <p>To show that double line spacing is causing encoding issues with
      WildDuck.  Yo.</p>
    <p><br>
    </p>
    <p>OK<br>
    </p>
  </body>
</html>


```

Rendering incorrectly in Thunderbird:

<img width="638" alt="Screen Shot 2023-11-26 at 2 21 38 AM" src="https://github.com/nodemailer/wildduck/assets/101466223/92ce256b-e339-40a1-aa5c-06f19e6d7c44">

When you send the message, the double space is encoded as `ï¿½ `:

<img width="493" alt="Screen Shot 2023-11-26 at 2 28 30 AM" src="https://github.com/nodemailer/wildduck/assets/101466223/a08a50d9-38d0-4264-956d-1f24aea28bf8">

Not sure if this is WildDuck specific, but putting this in here for now until I figure out what is going on.

**Comment by andris9** [comment]
See https://github.com/titanism/wildduck/commit/a8fbe83960f1fa8dd7e827896a8c8630ec10c449#commitcomment-134660563

**Comment by louis-lau** [comment]
I'll tag it as a bug, shouldn't go stale again.

**Comment by andris9** [comment]
I can not verify this issue. This might be an issue with your specific setup because you are not using WildDuck itself but the core modules.

<img width="750" alt="Screenshot 2024-05-30 at 10 18 46" src="https://github.com/nodemailer/wildduck/assets/132242/19b1374f-a399-4836-9712-cc538521e40d">
