### ISSUE TITLE
Redis server Failed

### ISSUE THREAD

**Issue by Manishjodhani** [nodemailer/wildduck#57]
Hi 
i used install.sh
then it failed at redis server
Job for redis-server.service failed because a configured resource limit was exceeded. See "systemctl status redis-server.service" and "journalctl -xe" for details.
invoke-rc.d: initscript redis-server, action "start" failed.
● redis-server.service - Advanced key-value store
   Loaded: loaded (/lib/systemd/system/redis-server.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: resources) since Wed 2018-01-31 06:15:16 EST; 4ms ago
     Docs: http://redis.io/documentation,
           man:redis-server(1)
  Process: 4693 ExecStopPost=/bin/run-parts --verbose /etc/redis/redis-server.post-down.d (code=exited, status=0/SUCCESS)
  Process: 4689 ExecStop=/bin/kill -s TERM $MAINPID (code=exited, status=0/SUCCESS)
  Process: 4683 ExecStop=/bin/run-parts --verbose /etc/redis/redis-server.pre-down.d (code=exited, status=0/SUCCESS)
  Process: 4679 ExecStartPost=/bin/run-parts --verbose /etc/redis/redis-server.post-up.d (code=exited, status=0/SUCCESS)
  Process: 4675 ExecStart=/usr/bin/redis-server /etc/redis/redis.conf (code=exited, status=0/SUCCESS)
  Process: 4669 ExecStartPre=/bin/run-parts --verbose /etc/redis/redis-server.pre-up.d (code=exited, status=0/SUCCESS)

Jan 31 06:15:16 vps166879 systemd[1]: Failed to start Advanced key-value store.
Jan 31 06:15:16 vps166879 systemd[1]: redis-server.service: Unit entered failed state.
Jan 31 06:15:16 vps166879 systemd[1]: redis-server.service: Failed with result 'r...'.
Hint: Some lines were ellipsized, use -l to show in full.
dpkg: error processing package redis-server (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 redis-server

please help me

**Comment by andris9** [comment]
As the logs say you need more resources. Or if you are using some linux hardening tools like apparmor or similar, then check that you are limiting applications

**Comment by n0mer** [comment]
i had this issue because RDB ver 8 was not supported:

```
4531:M 10 Jul 14:51:54.368 # Can't handle RDB format version 8
4531:M 10 Jul 14:51:54.368 # Fatal error loading the DB: Invalid argument. Exiting.
```

So sometimes this error is NOT caused by hardening tools.
