### ISSUE TITLE
Mail thread

### ISSUE THREAD

**Issue by Tannyll** [nodemailer/wildduck#579]
Mail thread structure is not working. This feature is very important, if there is no thread, there is no mail.

**Comment by andris9** [comment]
Can you elaborate?

**Comment by Tannyll** [comment]
Of course: "https://api.wildduck.email/users/{user}/mailboxes/{mailbox}/{mailbox}/messages/{message}" How can I pull the messageId values from the reference array in the object from the method?

**Comment by louis-lau** [comment]
What?

**Comment by louis-lau** [comment]
It's still not entirely clear to me what you mean. But do you mean you want to find all messages in the same thread?

You can do that here by searching for the thread id:
http://docs.wildduck.email/api/#operation/searchMessages
