### ISSUE TITLE
install script is installing wildduck 1.39.14

### ISSUE THREAD

**Issue by true2thepen** [nodemailer/wildduck#586]
The current install script(Dec 23,2023) is installing wildduck 1.39.14 instead of 1.41.3. The commit for 1.39.14 is 38d80e49b2c4502aa7c873de6c2acdc2986835ce and for 1.41.3 is 89dd3cf861ffa23918acc16ba0ce0ae894604b62.

Wildduck_ZoneMTA installing version is 1.32.2; latest is 1.32.6.
ZoneMTA installing version is 3.6.6; latest is 3.70.
Wildduck_Haraka version is 1.37.13; latest is 5.8.2.

Webmail commit is from Aug 21; latest is from Oct 2.

Haraka installed is the latest at 3.0.2.

@andris9 should the install script be installing the latest versions? If not the latest, then which versions?

**Comment by andris9** [comment]
Upgraded to latest commits. This process is manual so it might be often out of date
