### ISSUE TITLE
Socket Hung up

### ISSUE THREAD

**Issue by sankath** [nodemailer/wildduck#59]
While Submitting the message using ReplyAll snippet in message payload, getting Socket Hung up error and message is not delivered.

Please let us know what is the issue.

**Comment by andris9** [comment]
Can you check syslog for any errors? Socket Hung up probably means that the app throws an exception of some kind.

**Comment by sankath** [comment]
@andris9  After increasing socket count, we did not get this error. But Reply To using Send API endpoint is not working, it is giving me successful response with queid:false. Reply Message is getting lost. 

@andris9 - is it known issue or can you help us. We are struck to use Wildduck in our product.
