### ISSUE TITLE
GET /users/{user}/search or.query parameter bug

### ISSUE THREAD

**Issue by leonidiy2000** [nodemailer/wildduck#592]
Looks like there is an issue with the or.query parameter. If it is included, it returns 
```
{
    "error": "\"$search\" had the wrong type. Expected string, found null",
    "code": 14
}
```

Upon a bit of research looks like the issue is in wildduck/lib/prepare-search-filter.js file, line 65
```
orQuery.push({ $text: { $search: query } });
```
should actually be 
```
orQuery.push({ $text: { $search: orTerms.query } });
```

**Comment by andris9** [comment]
Thanks!
