### ISSUE TITLE
Threading doesn't account for prefixes some mail systems or clients add

### ISSUE THREAD

**Issue by louis-lau** [nodemailer/wildduck#603]
Found this amusing and annoying example of a thread being split unnecessarily.

![image](https://github.com/nodemailer/wildduck/assets/1346804/b6a07eff-4085-4cb0-af5d-57f5cd6e8eef)

Various mail systems or clients seem to add additional square bracket tags indicating external messages etc, or additional "re:" after that. It would be nice if we could ignore those prefixes when threading.

Just filing this issue for now, may look at it myself later and submit a PR.

**Comment by andris9** [comment]
The subject line is normalized for threading [here](https://github.com/nodemailer/wildduck/blob/76d0e8f9e29c09b60129d3c8bacfc1db64328c73/lib/message-handler.js#L1455-L1473) with `removePrefix=true` option. Basically, it just removes any `Re:` or `Fwd:` prefixes

**Comment by louis-lau** [comment]
Ah thanks, that makes it almost no effort for me to adjust. PR incoming
