### ISSUE TITLE
Deleting hidden mailbox

### ISSUE THREAD

**Issue by leonidiy2000** [nodemailer/wildduck#604]
Not sure why, but deleting a hidden mailbox returns an error DisallowedMailboxMethod, like deleting Inbox or special use mailboxes. Is it done on purpose or can be changed? Now to delete such mailbox I have to first update it to !hidden and only then can delete, which is 2 db calls instead of 1, not super optimal.

**Comment by andris9** [comment]
Hidden mailbox folders can not be modified. You can not delete or rename such a folder. If you want to delete it, then yes, you would have to unhide it first.
