### ISSUE TITLE
Upgrade to latest Version

### ISSUE THREAD

**Issue by vijay-thakur** [nodemailer/wildduck#61]
Hi,
Installed Wildduck a month ago. Now I want to upgrade to latest one. So How can I upgrade ? I have installed wildduck using the install script a month ago. Please guide me.

**Comment by andris9** [comment]
The upgrade process is not easy. I guess the best option would be just reinstall everything (but keep the database)

**Comment by ezra-obiwale** [comment]
We have to find a way to make it easy to upgrade.
