### ISSUE TITLE
Network Error Connecting to MX Server Most of the Time.

### ISSUE THREAD

**Issue by vijay-thakur** [nodemailer/wildduck#62]
Whenever we are trying to send email reply through API it always throwing this ERROR "Network Error Connecting to MX Server and Connection timed out" but if we do same reply through any email client its working Even I have tried to resend theough zoneMTA webadmin then also its working. I have seen in syslog that when the api hits to reply at that time first it tries to connect port 25.  So My question is can we change this port to some other port like 2525. I hare read some blogs and it said if many hits comes to port 25 then it starts giving time-out. Please reply.

**Comment by andris9** [comment]
If some messages go through port 25 and some do not then you are most probably being rate limited by your hosting provider. When sending mail to external servers you can only use port 25.
