### ISSUE TITLE
Question on support for `SORT (DATE) US-ASCII ALL` command

### ISSUE THREAD

**Issue by titanism** [nodemailer/wildduck#622]
The command `SORT (DATE) US-ASCII ALL` does not seem to be supported right now.  Are there any plans to add this?

**Comment by andris9** [comment]
There are no plans to add support for [RFC5256](https://datatracker.ietf.org/doc/html/rfc5256). It is not possible to support only a specific sort operator, WildDuck would have to support them all and the current indexing is already strained enough, so you would get “out of memory” responses when sorting any larger mail account.
