### ISSUE TITLE
QNAP

### ISSUE THREAD

**Issue by cypriotxx** [nodemailer/wildduck#63]
hi there,
is there any chance we can install this on QNAP ?

how do we go about this please ?

we can give tv access if needed .. 

thank you

**Comment by andris9** [comment]
Do you have a QNAP NAS in home or office and you want to install WildDuck on it? I don’t know how apps are installed to QNAP. Basically you need to have Nodejs, Redis and MongoDB on that device in order to use WildDuck

**Comment by cypriotxx** [comment]
Nodejs and MongoDB yes but i cant see Redis on the app lists here , thats a
shame


Thank you so much
Regards

**Comment by cypriotxx** [comment]
this REDIS probably possible to compile from source ?


Thank you so much
Regards

**Comment by cypriotxx** [comment]
any chance you can check the machine over teamviewer to see if we can use
WildDuck, i am sure so many will be interested too if it would work :)


Thank you so much
Regards

**Comment by andris9** [comment]
sorry, you have to get it working yourself. If you have node 6+, MongoDB and Redis running then you should be fine.
