### ISSUE TITLE
Bug: `TypeError: connection._server.options.SNICallback is not a function`

### ISSUE THREAD

**Issue by titanism** [nodemailer/wildduck#635]
Despite setting a default `SNICallback` function, it is being binded and/or used on the wrong object (typo perhaps).

```sh
TypeError: connection._server.options.SNICallback is not a function
    at TLSSocket.SNICallback [as _SNICallback] (/usr/src/app/node_modules/.pnpm/wildduck@1.41.0/node_modules/wildduck/imap-core/lib/commands/starttls.js:42:40)
    at TLSWrap.loadSNI [as oncertcb] (node:_tls_wrap:220:9) 
```

<https://github.com/nodemailer/wildduck/blob/aa60ef93fec943718a5a1fa03494526162cbabed/imap-core/lib/commands/starttls.js#L42>

The function is being invoked from `connection._server.options.SNICallback` however the default `SNICallback` function is being binded to `this.options.SNICallback`, not `this.server.options` as per this:

<https://github.com/nodemailer/wildduck/blob/aa60ef93fec943718a5a1fa03494526162cbabed/imap-core/lib/imap-server.js#L413-L419>

When you start in insecure mode, e.g. port `113`, and if you use a client like Apple Mail and accidentally enable STARTTLS, an uncaught exception / error will be thrown as per above.

This most likely needs fixed for both IMAP and POP3 implementations.

Thanks to @shaunwarman for the find 🙏

**Comment by andris9** [comment]
This bug seems only to be triggered if you create a custom IMAP/POP3 server, not when running WildDuck. The reason for the bug is that the default SNICallback is only defined when the server is using TLS, should be the reverse. WildDuck always defines this method and as such the default is never called and the bug is not triggered.

**Comment by andris9** [comment]
WildDuck seems to work fine. Additionally, there are some changes planned around SNI in the near future, as using SNI will become more important. So no plans to address your issue for now as it does not actually concern the usage of WildDuck.

**Comment by andris9** [comment]
The server assumes that SNICallback is set. This is an internal API, and WildDuck uses SNICallback. In future releases, the SNI will become the default anyway, so it is OK to assume that SNICallback is always set.
