### ISSUE TITLE
login page as start page

### ISSUE THREAD

**Issue by himbeere** [nodemailer/wildduck#64]
Hello.

How am I supposed to change the start page? I prefer to see the login page when connecting to https://mydomain.tld instead of the info page. Should I adjust nginx?

Uh, and again. Thank you for your work.

cheers
t.

**Comment by gurugeek** [comment]
you can just navigate to /opt/wildduck-webmail/routes and modify the index.js as you wish

**Comment by himbeere** [comment]
ah, cool. thanks @gurugeek.
