### ISSUE TITLE
metaData field is stored as json string in mongo documents

### ISSUE THREAD

**Issue by Mesmon** [nodemailer/wildduck#646]
It seems that metaDataValidator converts metaData input objects to string and as a result that's what saved in the mongo document.

**Comment by andris9** [comment]
This behavior is intentional. Storing user data as an object is extremely risky so WildDuck stores it as a string.

**Comment by Mesmon** [comment]
@andris9 Thanks for the quick response! Could you please elaborate or refer me to a source of information about this matter? My use case is that I need to have a field for indexing and querying by it - is it a good solution to just add a field to the users collection?

**Comment by andris9** [comment]
The `metaData` field allows the user to set arbitrary object values. Unless this data is heavily filtered (which it is not), the user can use Mongo-specific syntax that would, at best, fail the insertion and, at worst, be a security risk. Simplest example: if you use a dot in the key name (valid in JSON object), the insertion will fail.
