### ISSUE TITLE
Send from different IPs

### ISSUE THREAD

**Issue by yasseribrahim740** [nodemailer/wildduck#649]
Hello, i'm using wildduck mail server as docker and i want to use more than one server with more IPs and use all this servers as one but with different IPs

**Comment by louis-lau** [comment]
All wildduck services are designed for that, they're effectively stateless. So good plan, let us know if you have any questions we can answer or if you have an issue.

**Comment by yasseribrahim740** [comment]
How can I apply this while using this Dockerized repository
https://github.com/astzweig/docker-wildduck
