### ISSUE TITLE
documentation for setup

### ISSUE THREAD

**Issue by gurugeek** [nodemailer/wildduck#65]
First of all a big THANK YOU for creating WildDuck ! is truly amazing and the setup worked just fine.
Just some minor issues for the documentation perhaps:
a) I managed to set signup to false. Perhaps there should be a way to have an admin to add emails ? I think I would need to turn it on again if I want to create another account but turnitin on would allow others to register too. Is any way to allow just a super user to create accounts ?

b) not sure from the instructions at https://github.com/nodemailer/wildduck/tree/master/setup how to change the index page.  I did manage to restart it by killing the process on port 3000 but perhaps there should be some minimal instructions on how to stop/restart the server.
Thanks again!

**Comment by gurugeek** [comment]
I sort of figured all out :)

**Comment by uditb** [comment]
Hi @gurugeek 
I am trying to setup WildDuck mail using the script. The first step I am going with is using the below command on AWS EC2 instance- 
(run as root)

$ wget -O - https://raw.githubusercontent.com/nodemailer/wildduck/master/setup/get_install.sh | bash
$ ./install.sh myowndomain.com mail.myowndomain.com

The second step is to set up the domain after successful installation 

I am able to SignUp and SignIn. But I am not able to send and receive emails. 

Could you please help me with the steps you have followed to set it up?
