### ISSUE TITLE
Webmail not accessible 

### ISSUE THREAD

**Issue by dreamspag** [nodemailer/wildduck#657]
I followed the instructions and ran install.sh .
Also did dns setup

Still not able to access https://mail.domainname.com/ 

What is missing

**Comment by louis-lau** [comment]
No idea, too little info or investigation on your part. Check logs, check ports, etc.

**Comment by dreamspag** [comment]
info Express WWW server listening on port 3000
 info HTTP #033[0mGET / #033[32m200#033[0m 63.629 ms - 13948#033[0m

**Comment by louis-lau** [comment]
Sorry, can conclude anything from that. I'd probably check if the port is actually open to the internet and if nginx is running correctly.
