### ISSUE TITLE
sending with Multi ips

### ISSUE THREAD

**Issue by yasseribrahim740** [nodemailer/wildduck#658]
Hello, i have wildduck mailserver running as docker on vps and i want to scale it up and use another server how to configure it to send mails from two IPs of VPS
i use this docker compose
https://github.com/astzweig/docker-wildduck

**Comment by louis-lau** [comment]
Duplicate of #649 

You want a customized setup guide for hosting a docker image not created by the maintainers of this repo. You'll need to hire a professional for this if it's not within your skillset.

Again, if you have any specific questions feel free to ask! "How do I do the entire setup" is not something we can answer without spending a lot of voluntary time we don't have.
