### ISSUE TITLE
IMAP did not working on port 143 

### ISSUE THREAD

**Issue by Manishjodhani** [nodemailer/wildduck#66]
Hi,
IMAP is working properly  on 993 SSL
but when i used IMAP on port 143  unsecured 
Then it's not working
Thanks in advance

**Comment by Manishjodhani** [comment]
Any one can has solved this problem....????

**Comment by andris9** [comment]
Check that `secure` option is `false` (https://github.com/nodemailer/wildduck/blob/4582f8e08cce6e6a400b61034061ef1f9bef20d1/config/imap.toml#L8) and that your firewall allows port 143

**Comment by Manishjodhani** [comment]
yes i have done that but still not working
