### ISSUE TITLE
Catch-all wildcard address definition via API

### ISSUE THREAD

**Issue by gminogiannis** [nodemailer/wildduck#665]
According to the [documentation](https://github.com/nodemailer/wildduck/blob/v1.23.5/docs/api_data.json), we may create a catch-all address for a given user account by executing something similar to the below:
```
curl -ski -X POST "http://$HOST:$PORT/users/$USER/addresses" \
-H "Content-Type: application/json" \
-d '{"address": "wildcard@example.com", "allowWildcard": true}'
```

When we are sending an email to the primary address ( i.e. `wildcard@example.com` ) , everything works as expected.
Nevertheless, when we are sending an email to an arbitrary address ( e.g. `foo@example.com` ), then we get an error `550 5.1.1 No such user`

Is that normal ? Are we missing any steps ?

---

P.S: The aforementioned curl command gets HTTP 200 and - apparently - successfully creates the requested address.

**Comment by louis-lau** [comment]
https://docs.wildduck.email/api/#operation/createUserAddress

allowWildcard:

> If true then address value can be in the form of \*@example.com, \*suffix@example.com and username@\*, otherwise using \* is not allowed. Static suffix can be up to 32 characters long.

**Comment by gminogiannis** [comment]
@louis-lau isn't the curl command I posted before compatible with the documentation?
