### ISSUE TITLE
Daily limit on self hosted instance [RateLimitedError]

### ISSUE THREAD

**Issue by WeebNetsu** [nodemailer/wildduck#669]
We are self hosting our Wildduck API, our website requires us to send users email notifications, and as such we may send over 10000 unique emails a day if required... Why is there a daily limit if it is self hosted? Is there a way remove this limit?

**Comment by WeebNetsu** [comment]
Here is a bit more info after digging
```
"limits": {
        "quota": {
            "allowed": 1073741824,
            "used": 555977365
        },
        "recipients": {
            "allowed": 2000,
            "used": 317,
            "ttl": 81288
        },
        ```

( https://docs.wildduck.email/api/#operation/getUser )
Recipients allowed is 2000? Could this be causing the issue?

**Comment by louis-lau** [comment]
Yes, wildduck has limits built in, because it's built for people and people need limits in case of account compromise.

You can set the user limits yourself.

**Comment by WeebNetsu** [comment]
After digging we found solutions, thank you for your response
