### ISSUE TITLE
Why not use smtp-server as Inbound SMTP??

### ISSUE THREAD

**Issue by eqfox** [nodemailer/wildduck#67]
Why not use smtp-server as Inbound SMTP??

**Comment by andris9** [comment]
Haraka has all the needed extensions that smtp-server is missing (dkim, spf verification etc)

**Comment by andris9** [comment]
If you want to use smtp-server then run the included LMTP in smtp mode on port 25

**Comment by ramiroaisen** [comment]
@andris9 How can we run the LMPT in smtp mode?

**Comment by louis-lau** [comment]
Check the example config.
https://github.com/nodemailer/wildduck/blob/master/config/lmtp.toml
