### ISSUE TITLE
Pass date with new message

### ISSUE THREAD

**Issue by leonidiy2000** [nodemailer/wildduck#674]
Hi everyone.
Is there a way to pass a date when uploading a new message (except as a metadata field)? I need to pass a certain date from the past, so it is stored on the message object (idate, hdate, rdate are created on the go and don't work for me).
This endpoint https://docs.wildduck.email/api/#operation/getMessage seem to have a 'date' field in the response, which is explained as 'Date string from header', but when I save a message with this header:
    {
      "key": "date",
      "value": "2024-04-14T13:33:08.437"
    }
the date field on fetch is still the time of the message being saved.

**Comment by louis-lau** [comment]
I think the docs here are wrong or outdated. Looking at the code you should just be able to give a date property directly, which sets the header for you.

hdate is the header date, and only created on the unless specified.
