### ISSUE TITLE
pass some extra keys when sending email 

### ISSUE THREAD

**Issue by imtiyaz-ideavate** [nodemailer/wildduck#677]
Hello @andris9 

I want to pass some extra keys when sending email so that it can be received at receiver end. I used the **meta** key to add my custom field but it is not working. 

The file path I am updating into : **/lib/api/submit.js**

![Screenshot from 2024-04-24 11-14-12](https://github.com/nodemailer/wildduck/assets/19643788/1254cd81-99eb-4235-8bd4-9ca7a1df13be)

**Comment by louis-lau** [comment]
Anything you need to transfer to someone else needs to be able to happen over SMTP. Which means you should set a custom header instead :)

**Comment by imtiyaz-ideavate** [comment]
Thank you @louis-lau for the valuable suggestion, it really helped.
