### ISSUE TITLE
Notify user when their quota was reached

### ISSUE THREAD

**Issue by WeebNetsu** [nodemailer/wildduck#683]
One of our mailboxes have become full, and suddenly our emails were no longer in our "sent" mailbox, even though they were being sent - after checking the logs, we found out our mailbox was full, and when checking it, we see the quota got reached.

Maybe throw an error or alternatively send an email to the inbox of the email every time they send an email to notify them their quota has been reached, or even hold the outgoing emails while the quota is full (because how do I know if an email was sent if it does not appear in my sent mailbox - best to then not send any email?)

**Comment by louis-lau** [comment]
Email clients send over SMTP, then upload a copy over IMAP to the sent folder after they've sent it. The client would have gotten an error when uploading over IMAP, I guess it didn't show it to you? Wildduck isn't in control of wether an email goes into the sent folder and when, the client is.

I'm assuming IMAP/SMTP cliënt here as you didn't give any details. It could be different if using the api.

**Comment by andris9** [comment]
Usually, users discover quite soon that their quota is full by not receiving any new emails anymore.

**Comment by WeebNetsu** [comment]
> I'm assuming IMAP/SMTP client here as you didn't give any details. It could be different if using the api.

Yes, we are using the API, thus why we thought maybe showing something other than
> users discover quite soon that their quota is full by not receiving any new emails anymore.
May be best, since most users won't understand why their emails aren't working and will probably not even know they had a quota, and those using the API may not know about the limit until they reach it either, as there is no explicit mention of it in the docs, other than some output explanations, from what I remember
