### ISSUE TITLE
DKIM enabled by default?

### ISSUE THREAD

**Issue by UnKnoWn-Consortium** [nodemailer/wildduck#70]
Hello, 

Thank you for your hard work in creating and maintaining such a modern email server. 

I would like to know if DKIM is enabled by default. I have checked the install.sh script and there are indeed sections for generating and deploying a DKIM key. The resultant $domain_name-nameserver.txt does include a DKIM TXT record which I have properly added to my DNS. And calling the Wildduck DKIM API also returns the DKIM key generated. 

However, there is no trace of the DKIM-Signature header in emails I sent via the Wildduck Webmail panel for testing. Do I need to enable it or do something to have DKIM working?

Thank you again for your help.

**Comment by UnKnoWn-Consortium** [comment]
I have finally had some time to look into the code. It appears I have figured out the culprit of this issue. 

The problem is with this: 
https://github.com/nodemailer/wildduck/blob/a0f3aa30c96817ecfc1a89e692353b0fec50fb77/lib/dkim-handler.js#L134

As [any 12-byte long string is a valid ObjectId](https://github.com/mongodb/js-bson/issues/112) for MongoDB, any domain name long enough will be regarded as valid and thus casted to an ObjectId and used in the `_id` field of the query. This is in stark contrast with how the DKIM API endpoint works.

**Comment by andris9** [comment]
That’s a good catch, it means that all the places where I use ObjectID.isValid() are affected 😦

**Comment by UnKnoWn-Consortium** [comment]
There are 6 occurrences in 4 files. Still manageable I guess.

**Comment by UnKnoWn-Consortium** [comment]
@andris9 

I have checked how the DkimHandler class is used among `wildduck` and `zonemta-wildduck`. I have become a little bit hesitant on how I should approach the bug fix. Currently, the `get` and `del` method in the class have the same pattern of accepting a `domain` parameter which is subject to checking by `ObjectID.isValid` and it is where the problem lies. 

I can spot the class in two locations, [`lib/api/dkim.js`](https://github.com/nodemailer/wildduck/blob/master/lib/api/dkim.js)  in `wildduck` and [`index.js`](https://github.com/nodemailer/zonemta-wildduck/blob/master/index.js)  in `zonemta-wildduck`. 

In `wildduck`, the class is used for the API GET and DELETE handlers for `/dkim/:dkim` where, as stated in the example usage, the parameter `dkim` is expected to be a string of a MongoDB generated ObjectId. 

In `zonemta-wildduck`, however, it is wrapped in a local function and used for appending DKIM keys for outgoing messages. The parameter submitted is expected to be a string of a domain name. 

The duality of this parameter makes it difficult to accommodate both unless we implement or bring in a npm package on validating whether the input is a [MongoDB generated ObjectId](https://docs.mongodb.com/manual/reference/bson-types/#objectid) and build the query accordingly. 

In this case, we can normalize the `get` and `del` methods of the DkimHandler class to handle the `domain` parameter like how its `set` method handles the `options` parameter. If one wants to get or delete a DKIM key by its MongoDB generated ObjectId, one can call the method in this way, `DkimHandler.get({ _id: <MongoDB_ObjectId>, ... })`. On the other hand, if one wants to use a domain name in the query, it can be done like this: `DkimHandler.get({ domain: <Domain_Name>, ... })`. Such breaking change is still affordable at the current state because the DkimHandler class is not so widely used as to render refactors/retrofits outright impossible. 

Or we can use an `$or` operator in query like this `{ $or: [ { _id: domain }, { domain: domain }`. Such change should have the least impact on the established APIs and handlers. 

What do you think?

**Comment by andris9** [comment]
Yeah, this doesn't sound right at all. I'll take a look and refactor it to something saner, most probably to use the { _id:''} vs { domain:'' } approach.

**Comment by andris9** [comment]
I published v1.1.0 of WildDuck with the changes in DKIM get/del handling that should fix your issue.
