### ISSUE TITLE
PTR Record

### ISSUE THREAD

**Issue by dawnn07** [nodemailer/wildduck#701]
I have a question about ptr record 

Make sure that your public IP has a PTR record set to mail.demo.online.
If your hosting provider does not allow you to set PTR records but has
assigned their own hostname, then edit /etc/zone-mta/pools.toml and replace
the hostname mail.lubanlock.online with the actual hostname of this server.

Anyone i already add record ptr but still not work
![image](https://github.com/nodemailer/wildduck/assets/114931139/0ad713c8-a4e7-4c82-9bca-e5438ea5c361)

**Comment by louis-lau** [comment]
Ptr is set by the owner of the ip. If the owner of the ip doesn't have an interface to set it, you'll need to ask them.

You should probably read a little more about reverse dns. For the ip behind mail.lubanlock.online, the rdns/ptr is currently static.cmcti.vn
