### ISSUE TITLE
Feat: Add safeguard to `EXPUNGE` to only delete messages in Trash/Junk (with `\Deleted` flag)

### ISSUE THREAD

**Issue by titanism** [nodemailer/wildduck#702]
It may be worthwhile to add a safeguard here to prevent message deletion unless they are in the Trash/Junk folder:

<https://github.com/nodemailer/wildduck/blob/a68725d312b2c1f8684a182531f5dfdfd5ee8e3e/lib/handlers/on-expunge.js#L39-L46>

Feel free to close this otherwise.

**Comment by louis-lau** [comment]
That feels pretty non-standard to me. Expunge can be run on all folders with any standard IMAP implementation.
