### ISSUE TITLE
Bug in `FETCH` causing `data` to be `false` when `selected.uidList` is inaccurate due to `GETQUOTAROOT` not updating `uidList` and `modifyIndex` on `session.selected` object

### ISSUE THREAD

**Issue by titanism** [nodemailer/wildduck#708]
Right now the only time that `session.selected.uidList` gets updated is via `OPEN`.

However not all email clients (e.g. Thunderbird) will send an `OPEN` each time the user opens the mailbox.

Instead, they often do `GETQUOTAROOT` on a particular folder, or simply call `FETCH`.

<https://github.com/nodemailer/wildduck/blob/a68725d312b2c1f8684a182531f5dfdfd5ee8e3e/lib/handlers/on-fetch.js#L248-L251>

This code here will cause messages to not get rendered when they are attempted to be fetched.

An example that you can reproduce is to create a bunch of messages in IMAP, move them to Sent Mail, and then right click on them in Sent Mail and copy them to INBOX.  Then click on your INBOX, and the messages will not be there.  You can reproduce this in Thunderbird.

cc @andris9

**Comment by andris9** [comment]
GETQUOTAROOT and FETCH do not modify the active sequence index. You need to call IDLE or NOOP, etc, to update it. If a message is added to a mailbox folder and you call GETQUOTAROOT then the message is still "not there" and should not be. The message appears only after you call one of the commands that is allowed to update the index.
