### ISSUE TITLE
`tools.checkRangeQuery` returning inaccurate data in `MOVE` due to invalid/outdated `this.selected.uidList`

### ISSUE THREAD

**Issue by titanism** [nodemailer/wildduck#710]
If the `uidList` in `session.selected` is out of date, and a `MOVE` command is processed, then there is a potential edge case where the _wrong_ messages are moved due to the message range being returned is invalid, and therefore a `$gte` and `$lte` query is made.  I think that instead of using `tools.getRangeQuery` it should instead simply use `$in`.

Additionally, a client can send a `MOVE` command when the mailbox they're moving for seems to not be selected, and we do not check this in the code right now it seems (e.g. `path` needs to be checked against `session.selected.path`):

```diff
path = imapTools.normalizeMailbox(path, !this.acceptUTF8Enabled);
                                                                       
if (!path) {
    return callback(new Error('Invalid mailbox argument for ' + cmd));
}

+if (path !== this.selected.path) return callback(new Error('Path does not match to selected mailbox path'));
```

<https://github.com/nodemailer/wildduck/blob/a68725d312b2c1f8684a182531f5dfdfd5ee8e3e/imap-core/lib/commands/move.js#L42>

<https://github.com/nodemailer/wildduck/blob/a68725d312b2c1f8684a182531f5dfdfd5ee8e3e/lib/tools.js#L41-L46>

```sh
> require('wildduck/lib/tools').checkRangeQuery([ 4, 2, 3])
{ '$in': [ 4, 2, 3 ] }
> require('wildduck/lib/tools').checkRangeQuery([ 1, 2, 3])
{ '$gte': 1, '$lte': 3 }
```

<https://github.com/nodemailer/wildduck/blob/a68725d312b2c1f8684a182531f5dfdfd5ee8e3e/lib/message-handler.js#L845>

```diff
                       let cursor = this.database
                            .collection('messages')
                            .find({
                                mailbox: mailboxData._id,
-                                uid: options.messageQuery ? options.messageQuery : tools.checkRangeQuery(options.messages)
+                                uid: options.messageQuery ? options.messageQuery : { $in: options.messages }
                            })
                            // ordering is needed for IMAP UIDPLUS results
                            .sort({ uid: 1 });
```

**Comment by andris9** [comment]
The server can not use an updated UID list unless the server has propagated the changes to the client first. Until the changes have been sent to the client, the old UID list is still valid and must be used. The client is not moving the actual emails, but the emails that match the UID list known to the client.

**Comment by andris9** [comment]
UID is a sequential number that starts from 1 so there are always emails with the same UID in different folders.

**Comment by andris9** [comment]
The query is _mailbox id of the currently selected folder AND list of UIDs_. How can it move messages from another folder? The _path_ argument is target folder, not source folder
