### ISSUE TITLE
Adding same email under multiple user profile

### ISSUE THREAD

**Issue by imtiyaz-ideavate** [nodemailer/wildduck#715]
Hello @andris9 

Suppose I have an email address **some_email@example.com** and want to add this email under **users/:user1** and **users/:user2** profile. So that when a user types the email in compose box, it shows the added emails as suggestion.

I used below API to achieve above usecase, but it allows me to attach the email with only one user profile. When trying to add the same email under user2 profile, it says **This email address already exists**. 

https://docs.wildduck.email/api/#operation/postusersuseraddresses

Any idea, how can I achieve this ?

**Comment by andris9** [comment]
If you add an address to a user, then it means that the added address becomes the address of the user (a single user can have multiple addresses). If anyone sends an email to that address, the email ends up in the user's Inbox.

**Comment by imtiyaz-ideavate** [comment]
So it means the new added address will work as an alias for a user.
