### ISSUE TITLE
Should `asctime` pad with leading 0 for the day?

### ISSUE THREAD

**Issue by titanism** [nodemailer/wildduck#722]
e.g. https://github.com/nodemailer/wildduck/blob/49bd5015c188079e3a265c0873178e805f84ca2e/lib/mbox-stream.js#L192

```diff
-    res.push((day.length < 2 ? ' ' : '') + day);
+    res.push((day.length < 2 ? '0' : '') + day);
```

To mirror other implementations such as Dovecot/Thunderbird, e.g. <https://github.com/thunderbird/import-export-tools-ng/commit/39474c6397139f3f9586e27b282844c58b6b83b2>

**Comment by andris9** [comment]
Asctime uses space-padding instead of zero-padding.
