### ISSUE TITLE
Can we get Thread ID in EXISTS event?

### ISSUE THREAD

**Issue by HimanshuGuptaIdeavate** [nodemailer/wildduck#734]
Hi @andris9 

Can we get the thread ID in EXISTS event when a receiver receives a new mail or a threaded mail? Right now I am getting 

```
{
    command: 'EXISTS',
    mailbox: 'xxxxxxxxxxxxxxxxxx',
    message: 'xxxxxxxxxxxxxxxxxx',
    uid: 4XX
}
```

But I also need the thread ID here in the above Response. Is it possible?

**Comment by louis-lau** [comment]
I added that in #439 about 2 years ago. Are you using an older version? Wildduck-dockerized is not up to date, it hasn't been maintained very well (by me)

**Comment by HimanshuGuptaIdeavate** [comment]
@louis-lau I am not using the Wildduck-dockerized version, I am using https://github.com/nodemailer/wildduck

**Comment by louis-lau** [comment]
Then you should be getting the thread id, since about 2 years.

**Comment by HimanshuGuptaIdeavate** [comment]
@louis-lau @andris9 

I had setup wildduck email server using the script mentioned below. How can I get the updates as the new changes are continuously being pushed by you.

https://github.com/nodemailer/wildduck/tree/master/setup

**Comment by HimanshuGuptaIdeavate** [comment]
> @louis-lau @andris9
> 
> I had setup wildduck email server using the script mentioned below. How can I get the updates as the new changes are continuously being pushed by you.
> 
> https://github.com/nodemailer/wildduck/tree/master/setup

Hi @louis-lau @andris9 Could you help me on this?
