### ISSUE TITLE
Standalone IMAP Server Library?

### ISSUE THREAD

**Issue by jordanbancino** [nodemailer/wildduck#745]
I found [nodemailer/smtp-server](https://github.com/nodemailer/smtp-server), which appears to be a standalone NodeJS library for implementing a custom SMTP server. I was wondering if there is an equivalent standalone library for IMAP. I see that Wildduck appears to implement IMAP, but I am interested in only the IMAP protocol part; I would like to implement my own backend.

Is this possible with Wildduck? If not, would it be feasible to break out the IMAP protocol functionality into its own standalone package?

Otherwise, are the any alternative Node packages that implement just the IMAP protocol and allow developers to hook into it like `smtp-server`?

**Comment by andris9** [comment]
IMAP protocol is so much more complex that it is really hard to provide a simple server library. Some people have used the underlying IMAP server from WildDuck for it. You can find an example IMAP server implementation on top of the WIldDuck IMAP core from [here](https://github.com/nodemailer/wildduck/blob/master/imap-core/test/test-server.js) (it's a standalone server implementation that provides a test server for automated tests)

**Comment by jordanbancino** [comment]
Very well, I understand.

The test server looks pretty close to what I want, so I will take a look and see if it will work for my needs.

Thank you for the timely response.
