### ISSUE TITLE
Bug: Attachment magic number grows incredibly large for PGP encrypted messages

### ISSUE THREAD

**Issue by titanism** [nodemailer/wildduck#750]
While this example is from SQLite, the same most likely occurs for MongoDB:

As you can see, the `magic` number column value is `3900112079`.

<img width="1192" alt="Screen Shot 2024-10-28 at 7 50 11 PM" src="https://github.com/user-attachments/assets/e34882db-fe8e-4479-a030-a597dc48ed62">

The `body` value is simply `Version: 1\r\n`:

```sh
> Buffer.from('56657273696f6e3a20310d0a', 'hex')
<Buffer 56 65 72 73 69 6f 6e 3a 20 31 0d 0a>
> Buffer.from('56657273696f6e3a20310d0a', 'hex').toString()
'Version: 1\r\n'
```

**Comment by andris9** [comment]
Yes, this is normal. The max number is 9007199254740991 (safe integer limit)
