### ISSUE TITLE
Changes required for local mail delivery

### ISSUE THREAD

**Issue by HimanshuGuptaIdeavate** [nodemailer/wildduck#754]
Hi @andris9 
I have setup the wildduck system to my local network i.e. intranet using a scripted version of installation [https://github.com/nodemailer/wildduck/tree/master/setup], What changes are required for local mail delivery?

**Comment by mayur-mku** [comment]
If you want to receive new emails, then the easiest way would be to send one from console using [this script](https://gist.github.com/andris9/059aee46f6f14064d97e77764a06e0dd). Replace wildduck.email and port 25 with your localhost settings (eg. host:localhost port:2525). The script then connects to your test MX server and tries to send an email to it.

If you want to send and receive emails locally from wildduck-webmail interface, then use "localtest.me" as your address domain and make sure that your local test MX is listening on port 25. "localtest.me" resolves to 127.0.0.1, so your emails should be delivered to 127.0.0.1:25

> Hi @andris9 I have setup the wildduck system to my local network i.e. intranet using a scripted version of installation [https://github.com/nodemailer/wildduck/tree/master/setup], What changes are required for local mail delivery?

**Comment by louis-lau** [comment]
By local mail delivery, do you mean that all email should go back to the MX and should never be sent externally? Can you clarify what you mean exactly?

**Comment by HimanshuGuptaIdeavate** [comment]
Yes @louis-lau  I want exactly the same thing. 

We are running Wildduck in the intranet and we do not want to send emails outside the intranet.

**Comment by louis-lau** [comment]
Just set zone-mta to always deliver to localhost port 25:
https://github.com/zone-eu/zone-mta-template/blob/0df73a3946eae0964a166b3015d3ed558d9d024f/config/zones/default.toml#L10

**Comment by HimanshuGuptaIdeavate** [comment]
Hi @louis-lau 
Thanks so much for the guidance it was really helpful.
