### ISSUE TITLE
550 message too big!

### ISSUE THREAD

**Issue by arafat-khan-mindruby** [nodemailer/wildduck#762]
Hi @louis-lau  , When I am trying to send a mail with attachment of 22 mb, I am getting error of "550 Message too big!".
I am sending mail locally.

Delivery to the following recipient failed permanently:
private@localtest.me

Technical details of permanent failure:

550 Message too big!
![Screenshot from 2024-12-08 22-35-41](https://github.com/user-attachments/assets/3c4de958-eb31-4d2d-af0c-7eef8ad7e509)

**Comment by louis-lau** [comment]
Harakas max message size is configured here I think.

https://github.com/haraka/Haraka/blob/3fe38b592c19507efaf8f946c9cc48602e1b742c/config/databytes

**Comment by louis-lau** [comment]
For more information about harakas configuration, you can read these docs:
https://haraka.github.io/core/CoreConfig

**Comment by arafat-khan-mindruby** [comment]
Hi @louis-lau ,
Thank you very much for your guidance!
