### ISSUE TITLE
How to Create Label

### ISSUE THREAD

**Issue by iaaxindev** [nodemailer/wildduck#763]
Hi
I've searched all APIs but am unable to create labels. how can i implement the same.

**Comment by louis-lau** [comment]
Labels are currently not something that's implemented in wildduck.

**Comment by louis-lau** [comment]
I've been wanting to implement it as well.

They'd have to be stored as custom IMAP keywords. There would have to be separate endpoints to manage which keywords get exposed as labels in the api. You should be able to filter messages by labels. There's also a need for counters, so we know how many unread emails each label has, this would work similarly to the mailbox unseen counters. 

That's all I've thought out so far. I've been wanting to do this for a long time, but I just don't ever seem to get around to it. I'm not comfortable enough in the wildduck codebase to write a more specific guide than that.

Maybe @andris9 can chime in if everything I said is accurate and aligns with his views of the project, or perhaps he can give more specific pointers than I can.

**Comment by andris9** [comment]
Well, yeah, labels are out of scope. You can use regular message flags as labels and then search all messages that have the specific flag set to emulate labels.
