### ISSUE TITLE
How to access archived folder through api

### ISSUE THREAD

**Issue by iaaxindev** [nodemailer/wildduck#765]
i am unable to access archived folder through API . How can i access archived folder through API

**Comment by louis-lau** [comment]
Can you explain what you mean by archived folder?

**Comment by louis-lau** [comment]
You can't currently list those, only restore all messages that were deleted between a date range. They will be restored to a specially created mailbox, where the user can sort out the messages they want to restore.

**Comment by louis-lau** [comment]
Actually, I'm wrong. You can just list them.

https://docs.wildduck.email/api/#operation/archived
