### ISSUE TITLE
Is it possible to move a message directly to the archived folder?

### ISSUE THREAD

**Issue by iaaxindev** [nodemailer/wildduck#766]
Is it possible to move a message directly to the archived folder?
Some use cases require this feature.

_Originally posted by @iaaxindev in https://github.com/nodemailer/wildduck/issues/765#issuecomment-2526738847_

**Comment by louis-lau** [comment]
There is no archived folder. The archive is where deleted messages go for 14 days.

If you just want an archived folder for a user, create a mailbox and move messages to that mailbox.
