### ISSUE TITLE
Is there a reason why the username can't be an email address?

### ISSUE THREAD

**Issue by fcardona** [nodemailer/wildduck#77]
I see here https://github.com/nodemailer/wildduck/blob/master/lib/api/users.js#L353 that wildduck doesn't allow @ as part of the username.

I want to migrate some email accounts to wildduck and would like to avoid reissuing usernames. But the user accounts in the current email system use the full email address as the username.

Is there technical reason why @ is not allowed?

**Comment by andris9** [comment]
I have wanted to separate users and email addresses/identities but other than that there are no technical restrictions. Allowing emails as usernames would mostly require changing the input validation handlers

**Comment by andris9** [comment]
Could you try the latest v1.2.0? I removed the username formatting requirements, so an email address could be used.

**Comment by fcardona** [comment]
Okay, thanks. I was thinking of doing a quick pull request for it but you beat me to it. :) Thanks again!
