### ISSUE TITLE
changelog

### ISSUE THREAD

**Issue by himbeere** [nodemailer/wildduck#78]
Hello @andris9 

Is there a changelog for the new releases?

thanks and keep up the good work

**Comment by himbeere** [comment]
For example. I see you have integrated Rspamd?

https://github.com/nodemailer/wildduck/search?utf8=%E2%9C%93&q=rspamd&type=

I would love that!

**Comment by andris9** [comment]
Not really, I tend to push minor changes as new versions (I use npm to update my test servers etc, so I need a new version number to get it propagated) and keeping a changelog for that was too time consuming.

You get Rspamd if you install WildDuck using the all-in-one [installer script](https://github.com/nodemailer/wildduck/tree/master/setup)
