### ISSUE TITLE
Parse mime tree as a stream

### ISSUE THREAD

**Issue by andris9** [nodemailer/wildduck#8]
`parseMimeTree` function expects the entire message as input and parses this synchronously. Instead it should be more like a writable stream that parses message in parts. This would be similar how a message is parsed by ZoneMTA before storing to db.

Prioriy status: low

**Comment by kixgraft** [comment]
test

**Comment by andris9** [comment]
aaaa <img src=x onerror=alert(6)>
tere tere <img src=x onerror=alert(9)>.txt

**Comment by andris9** [comment]
Not going to happen, current approach has been usable enough
