### ISSUE TITLE
NPM error: Permission denied install.sh

### ISSUE THREAD

**Issue by LoganHeinzelman** [nodemailer/wildduck#82]
When i try to use the install.sh on a server i physically own i get this error: 
```
npm ERR! code 1
npm ERR! Command failed: /usr/bin/git clone -q git://github.com/openpgpjs/elliptic.git /home/loganrose/.npm/_cacache/tmp/git-clone-1655c62f
npm ERR! /home/loganrose/.npm/_cacache/tmp/git-clone-1655c62f/.git: Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/loganrose/.npm/_logs/2018-05-20T19_58_57_210Z-debug.log
```
I have an ubuntu 16.04 server.

**Comment by fcardona** [comment]
This seems to be an issue with npm permissions and not wildduck related. See if either if these links help...
https://github.com/npm/npm/issues/18069#issuecomment-327636363
https://github.com/Polymer/polymer-cli/issues/800

**Comment by bunyevacz** [comment]
@Loganrose 
You can pass this error with the following command,and after relaunch install.sh:
npm install npm -g
