### ISSUE TITLE
nginx.service is not active, cannot reload.

### ISSUE THREAD

**Issue by bunyevacz** [nodemailer/wildduck#83]
The main problem with install.sh, it is monolithic, so if it stops it can't be restarted without error.
For me it stopped with git clone timeout.
Can this install.sh chopped up into chunks? 
a) import all the keys
b) install prerequisites
c) test running processes
d) install program a, b, c, etc.

I fixed the install.sh, with the following modification:
```
$SYSTEMCTL_PATH reload nginx
```
modified to:
```
$SYSTEMCTL_PATH start nginx
$SYSTEMCTL_PATH reload nginx
```

at install.sh:600:
https://github.com/nodemailer/wildduck/blob/734a6b974856237d4fdf2ac87e8222bbc4ac2165/setup/install.sh#L600

After this modification, I successfully installed the bundle, and it is working (webmail, mailserver, etc).

Is pull request welcome for breaking install.sh to multiple file? 
I believe it would help troubleshooting, if installation is unsuccesful.

**Comment by andris9** [comment]
Yeah, definitely, if you can think you can make the install script better, then it's all welcomed. I just hacked the current script together, it's not anything too great.

**Comment by bunyevacz** [comment]
Hi,

I have created a pull request:
https://github.com/nodemailer/wildduck/pull/84

I tried to be minimally intrusive, it is basically your script
choped up into smaller sections. So when it breaks, it is
easier to see where exactly.
It is tested on ubuntu 16.04.4.

There are still room for improvement:
- create certs, dkim (especially dkim! I have a dkim signature mismatch on all outbound emails), 
as separate files, so it can be modified after the installation (add the dkim cert afterwards, 
regenerate it with install.sh)
- use sudo instead of root

So I still want to break out these things (acme.sh, dkim signature, etc) into self contained 
subscript, so it can be launched separately. 

I hope you like the pull request. There are some unused shell functions, for 
password request. It will be needed once the install.sh can be launched without root.
(and asks for the user password, and issue sudo commands).

With the current root method the main problem that many dirs are created with root:root 
owner in the users $HOME directory...

**Comment by andris9** [comment]
Btw I updated the commit hashes as the Wildduck version listed in install script handled incoming message rate limiting invalidly. If you already use the older version then you might want to upgrade haraka-plugin-wildduck and flush Redis as otherwise all users get rate limited sooner or later for their incoming email.

**Comment by bunyevacz** [comment]
As I use kvm servers. Maybe it would be easier, just to install everything from ground up.
But dont know how to migrate data yet.

I need definietly look into upgrading. And how it should be done. Any suggestions?

**Comment by andris9** [comment]
You can update code via git. For example if you want to upgrade wildduck in /opt/wildduck to 538da537ca3cef0bbd714da70085cfd4cc734b49 then run the following commands:

```
(root) $ sudo su deploy
(deploy) $ cd /var/opt/wildduck.git
(deploy) $ git fetch origin 538da537ca3cef0bbd714da70085cfd4cc734b49
(deploy) $ git --git-dir=/var/opt/wildduck.git --work-tree=/opt/wildduck checkout 538da537ca3cef0bbd714da70085cfd4cc734b49
(deploy) $ exit
(root) $ systemctl restart wildduck
```

**Comment by bunyevacz** [comment]
something like this?:
```
Jun  8 15:09:47 mail zone-mta[1202]: info Sender/default/1360[3] 163df7203c70003521.001 DEFERRED[recipient] 
from=no-reply@microsoft.com to=jlajlp@awe.com src=0.0.0.0 
dst=mail.awe.com[192.168.10.10] id=<a85d2dc1-0b1a-475d-bd17-d4d21f932477@BL2FFO11FD018.protection.gbl> 
(450-4.2.1 The user you are trying to contact is receiving mail at a rate 
that prevents additional messages from being delivered. 
Please resend your message at a later time. If the user is able to receive mail at that time, 
your message will be delivered.)
```
I thought it is this `haraka-plugin-wildduck` commit causing problem:
https://github.com/nodemailer/haraka-plugin-wildduck/commit/05b08074371e7e3b836088cfe3c225735fe377ea

But this looks like a zone-mta error to me. And message (indeed) do not reach the inbox.
Also the hook_script seems to not executing right (in original install.sh either). 
I'm investigating...

In /opt dir, I have
```
haraka
wildduck
wildduck-webmail
zone-mta
```

While in install script `hook_script` function should create a `haraka.git` dir.
This is the code:
https://github.com/nodemailer/wildduck/blob/6c02b5bc8ebfb33f2e4e08336d9e343a75b16772/setup/00_install_variables.sh#L245-L254

I think line 253 is bogus:
```
 chmod +x "/var/opt/$1.git/hooks/update"
```

I just blindly copied this function. I have a hard time grasping how the update process is supposed to work. 
Could you please explain a bit what hook_script should be doing exactly?

Also why there is `var/opt/haraka` and `/var/opt/haraka.git` in your example?

I think its rtfm time for me.

**Comment by bunyevacz** [comment]
Oh, some git-fu is required:
```
(deploy) $ git fetch origin 538da537ca3cef0bbd714da70085cfd4cc734b49
```

It is zone-mta, but this is the error:
```
deploy@mail:/var/opt/zone-mta.git$ git branch -vv
* (HEAD detached at b991592) b991592 bumped zmta
  master f5f6a80 bumped allowd messages
deploy@mail:/var/opt/zone-mta.git$ git fetch origin f5f6a80
fatal: Couldn't find remote ref f5f6a80
```

I'm googling...

**Comment by bunyevacz** [comment]
I think this issue can be closed. The setup script is chopped up, and the wiki page has some up to date updating info.
