### ISSUE TITLE
generated domain-nameserver.txt and spf

### ISSUE THREAD

**Issue by bunyevacz** [nodemailer/wildduck#85]
Seems like the spf record generated in 
mydomain.com-nameserver.txt is not correct.

Currently generates this:
`mydomain.com. IN TXT "v=spf1 a:mydomain.com ~all"`

However normally the company website (mydomain.com) and the mailserver (mail.mydomain.com) resides on different servers.
So I think the correct solution would be:
`mydomain.com. IN TXT "v=spf1 a:[HOSTNAME] ip4:[PUBLIC IP ADDRESS] ~all"`

Ie. 
`mydomain.com. IN TXT "v=spf1 a:mail.mydomain.com ip4:11.11.11.11 ~all"`

If you agree, I would create a pull request modifying the install script.
Or maybe we could spit out all the variations. 
Currently I use:
`mydomain.com. IN TXT "v=spf1 a:mydomain.com a:mail.mydomain.com ip4:11.11.11.11 ~all"`
(so the main website can also send email, as a separate server. It is outbound only, and mostly confirmation emails)

**Comment by andris9** [comment]
Yes, this seems like incorrect. The earlier versions of the install scruipt did not allow using separate domain and hostname, so when I added the hostname support I forgot to updated SPF settings accordingly. PR would be great

**Comment by bunyevacz** [comment]
This pull request closes this issue:
https://github.com/nodemailer/wildduck/pull/88

**Comment by bunyevacz** [comment]
Pull request got merged. We can close this issue.
