### ISSUE TITLE
Statistics for user account

### ISSUE THREAD

**Issue by bunyevacz** [nodemailer/wildduck#89]
Despite of having installed the newest wildduck-haraka plugin with the 150message/hour quota fix, 
some of my user accounts get disabled:
```
Jun 12 09:44:05 mail haraka[1177]: [NOTICE] [94809DF0-873C-4139-9D3C-7F267772E370.3] 
  [core] sender <whoami@gmail.com> code=CONT msg=""
Jun 12 09:44:05 mail haraka[1177]: [INFO] [94809DF0-873C-4139-9D3C-7F267772E370.3] 
  [core]  hook=rcpt plugin=wildduck function=hook_rcpt params=<myuser@awesomeness.com> retval=DENYSOFT msg="[object Object]"
Jun 12 09:44:05 mail haraka[1177]: [NOTICE] [94809DF0-873C-4139-9D3C-7F267772E370.3] 
  [core] recipient <myuser@awesomeness.com> code=DENYSOFT msg="[object Object]" sender=whoami@gmail.com
```

Reading through the api documentation:
https://api.wildduck.email/#api-Mailboxes-GetMailbox

There are no statistics or metric queries. Which is rather vital imho for debugging.
So I would like to request a statistics for received and send messages for hour/day/month.

The API could simply extend the get user request:
```
GET https://api.wildduck.email/users/:id
```
and in the response have some additional fields:
```
"metrics": {
    "hourly": "142",
    "daily": "1230",
    "monthly: "15632",
    "lastUpdated: "2018-06-08T11:19:10.911Z"
 },
```

The issue (quote reached) is especially annoying, since it persists across reboots, and config file 
editing (`/opt/haraka/plugins/wildduck/config/wildduck.yaml`).
(inside of `redis-cli` a `flushall` is required)

Any comments?

**Comment by andris9** [comment]
yeah, there are several internal counters that should probably be exposed, i'll look into that

**Comment by andris9** [comment]
Published v1.2.1 that exposes additional counters in the `limits` section. In general the limits section shows how much resorces can be used, how much are used so far and finally, seconds until the counter resets for this limit type.

If you have a very large number as the ttl for received (should not be more than 3600) then it means your haraka config still has the old value. Check /opt/haraka/config/wildduck.yaml and change "limits.windowSize" to 3600. Once you have done that flush Redis contents to clear the cached values (or if you do not want to reset all coutners to 0 in Redis, find and delete "rl:rcpt:userid").

```
  "limits": {
    "quota": {
      "allowed": 1073741824,
      "used": 17127
    },
    "recipients": {
      "allowed": 50,
      "used": 0,
      "ttl": false
    },
    "forwards": {
      "allowed": 50,
      "used": 0,
      "ttl": false
    },
    "received": {
      "allowed": 150, // this number is currently hardcoded as there is no easy way to read data from Haraka config files
      "used": 2,
      "ttl": 3593
    },
    "imapUpload": {
      "allowed": 10485760000,
      "used": 0,
      "ttl": false
    },
    "imapDownload": {
      "allowed": 10485760000,
      "used": 9575,
      "ttl": 85532
    },
    "pop3Download": {
      "allowed": 10485760000,
      "used": 0,
      "ttl": false
    }
  }
```

**Comment by andris9** [comment]
I'm not sure about the metrics though. In ZoneMTA I use [Prometheus](https://github.com/zone-eu/zone-mta/#metrics-for-prometheus) but this exposes aggregated stats (how many messages sent in total) not by user (how many messages sent from a specific address), so the same approach might not be feasible.

I think the most sane approach would be to expose ever growing counters next to the limits, so you could feed this info to some time-series database that would calculate details like daily/weekly etc by itself.

**Comment by bunyevacz** [comment]
Correct me if I got it wrong:

Incoming emails (from the internet, eg. gmail):
```
internet -> server:25 (haraka) -> haraka-wildduck -> wildduck -> mongodb
```

Sending emails (from smtp clients, eg. outlook, thunderbird):
```
outlook -> server:587 (zone-mta/SMTP-TLS) -> internet
```
also outlook puts it into 'sent folders' and synchronize it via IMAP:
```
outlook -> server:993 (wildduck/IMAP-SSL) -> mongodb
```

Sending emails via webmail:
```
wildduck-webmail -> wildduck -> zone-mta -> internet
                            |-> mongodb
```

Receiving email via IMAP (folder synchronization from old account's .pst file via outlook):
outlook -> server:993 (wildduck/IMAP-SSL) -> mongodb

Receiving 'sent folder' emails via IMAP:
same as above.

Viewing email via webmail:
```
wildduck-webmail->wildduck->mongodb
```

In this setup, I believe each element should provide metrics, what it is handling.
In this case wildduck should provide IMAP events, incoming smtp events.
It should not collect metrics for outbound smtp emails, if it is happened outside of wildduck (ie. outlook sent mail through port 587, and *did not* copied the email via IMAP).
Normally it gets notified the same event via IMAP. Or if it was sent via a command line daemon (eg: bulk email, confirmation email, intranet business management software) then wildduck is out of luck, it is not his job.

I believe for *debugging* purpose each service should collect metrics from events which happened through itself.
No need to collect smtp events from zone-mta. 

I hope we are on the same page:) Thoughts?

**Comment by andris9** [comment]
So there are no cumulative/aggregated metrics available and it would be difficult to add it as it would require time-series data handling which WildDuck currently lacks (and most probably should not have anyway) but there are multiple options to listen to changes in the system, so you could add this information to a real time-series database

**Comment by bunyevacz** [comment]
> Published v1.2.1 that exposes additional counters in the limits section. I
In your recent commit, you shuffled git commit hashes, and they are incorrect.
https://github.com/nodemailer/wildduck/commit/a2581c5e1cdfa19191645ee2ce56c8c36d3389c1

I also wrote as comment in the commit message, what shuffled around.
Can you please correct it? It is unbuildable atm from vanilla checkout.

> In general yes, only that Haraka pushes messages to mongodb directly and does not connect to the WildDuck daemon process

Incoming emails (from the internet, eg. gmail):
```
internet -> server:25 (haraka) -> haraka-wildduck -> wildduck -> mongodb
```

So this is incorrect, it is simply:
```
internet -> server:25 (haraka) -> haraka-wildduck -> mongodb
(haraka-wildduck also checks valid email addresses against wildduck)
```

Right?

**Comment by bunyevacz** [comment]
Ok, I love your statistics commit.

My usecase:
I'm uploading users' emails to this mail server. I use `isync` (`mbsync`) for outlook .ost file.
I'm also using outlook itself for .pst files (sadly no .ost support from outlook).

One user account is 28GiB, and I'm testing it on a dummy account (with `mbsync`), and I see the statistics updating:
```
 "imapUpload": {
      "allowed": 10485760000,
      "used": 97204310,
      "ttl": 86320
    },
    "imapDownload": {
      "allowed": 10485760000,
      "used": 142700,
      "ttl": 86315
    },
```

So I can track if it hangs because of limit hitting. 
(outlook provides absolutely no information about the progress).

At least I can see on the server. Still testing. It is a major migration for me.

Btw, massive imap uploads a real resource hog on the server. wildduck-webmail loose (ECONNRESET) many clicks because of wildduck heavy working.  Dunno if its worth debugging.

**Comment by andris9** [comment]
If you have more than 1 CPU available, then you could try to increase the `processes` configuration option (defaults to 1) in /etc/wildduck/wildduck.toml, otherwise WildDuck does everything using just a single blocking thread which does not perform well under load.

**Comment by bunyevacz** [comment]
Oh, that should be included in install.sh!

I think a safe bet would be 1 by default, but more cpu is used, then 2. We can finetune later.
For detection, I'll use `nproc --all`, which is part of `coreutils` package, so should be installed.

Relevant stackoverflow thread:
https://unix.stackexchange.com/questions/218074/how-to-know-number-of-cores-of-a-system-in-linux

What do you think? If ok, then I'll prepare a pull request this evening.

**Comment by andris9** [comment]
Yeah, in production this value should be larger than 1 even if you have only 1 cpu available (if one process has problems then you still have another one available for serving requests), so changing it would make sense.

If you have node already available then you can use it to get cpu count even if coreutils etc is not available:

```
$ node -e 'console.log(os.cpus().length)'
8
$ nproc --all
8
```

**Comment by bunyevacz** [comment]
So this would be fine?:

```node -e 'console.log(Math.max(os.cpus().length,2))'```

So cpucount, but 2 at the minimum ?

**Comment by andris9** [comment]
Maybe some max value as well, for example I use servers with 64 CPUs and I dont't want to run 64 processes:

```
#!/bin/bash
PRC_MIN=2
PRC_MAX=15
PRC=`node -e "console.log(Math.min(Math.max(os.cpus().length,$PRC_MIN),$PRC_MAX))"`
echo $PRC
```

**Comment by bunyevacz** [comment]
When I raise the upload limit (I hit the 10GiB/24h limit while importing), I also need to flush the redis database. (`redis-cli flushall`)

Would be nice if wildduck would update the relevant redis information.
```
curl -i -XPUT http://localhost:8080/users/5bxxxxxxxxx83   -H 'Content-type: application/json'   -d '{"imapMaxUpload": "104857883830"}'
```

**Comment by andris9** [comment]
Good idea, added this to latest commit - if a counter key value is modified for an user then the according counter in Redis is reset. So in your case if you change imapMaxUpload  for an userthen the counter is reset to 0
