### ISSUE TITLE
Re-built messages are not exact copies of the originals

### ISSUE THREAD

**Issue by andris9** [nodemailer/wildduck#9]
When rebuilding rfc822 messages from serialized message data then the output is not always 100% exact copy of the original. Message builder moves all empty lines between multipart boundaries (end of one subtree and continuation of next) to the beginning of the body. For most messages it's not an issue because email clients usually do not put extra empty lines between the boundary lines but sometimes it happens

Status low. This is probably related to #8 and these should be resolved together with a better message parser.

**Comment by pvagner** [comment]
Is this severe enough to cause dkim verification failures?
i.e. If I receive a message and let wildDuck forward it to a different system could dkim verification fail there for example if white spaces get stripped out from the body part?

**Comment by andris9** [comment]
Forwarded messages are not affected. It only affects some (not all) messages that are received and stored to the system. If you try to verify DKIM for such stored message (for example download the message via IMAP and feed it to some verifier) then verification might fail.

**Comment by andris9** [comment]
I'd say that this is now intended behaviour. WildDuck decodes base64 encoded attachments and later re-encodes these which sometimes results in data loss in mime format (mostly related to line breaks in unexpected positions).
