### ISSUE TITLE
Some documentation

### ISSUE THREAD

**Issue by bunyevacz** [nodemailer/wildduck#90]
I would like to write some documentation regarding:
updating (git commit), detailed in  issue #83:
https://github.com/nodemailer/wildduck/issues/83

I constantly check how it needs to be done.

And also I would like a migration howto. It is not strictly wildduck related, but really handy.
It is mainly regarding outlook .pst/.,ost files, isync, maildir creation, and also tracking on wildduck 
the progress via command line (curl).

Is Updating.md and migration.howto.md is appropriate in the root directory?
Looks like docs/ dir is a complete web project for the api documentation.

Bests,

**Comment by andris9** [comment]
Yeah, the docs folder is for API docs but you could use the [Github Wiki for WildDuck](https://github.com/nodemailer/wildduck/wiki) which should be editable for everyone.

Currently there are some outdated stuff in the Wiki like out-of-date API docs (at first I used wiki to document API methods) and IRC Server docs (there used to be an IRC server built in that used WildDuck mail accounts for authentication but I removed it as it was really out of scope)

**Comment by bunyevacz** [comment]
> Yeah, the docs folder is for API docs but you could use the Github Wiki for WildDuck which should be 
> editable for everyone.

It is not editable for everyone. There is no edit button, and if I click on the "6 revisions" on the main wiki page, there is a `New page` button, and I get an error message:
` You do not have permission to update this wiki. `

I assume a mini tutorial is needed for me:(

**Comment by andris9** [comment]
Oh, sorry, I had limited editing to admins only (i guess it's the default). It should be ditable for everyone now.

**Comment by bunyevacz** [comment]
Thank you. 

I started to working on two subpage:
* [Administrating wildduck via command line](https://github.com/nodemailer/wildduck/wiki/Administrating-wildduck-via-command-line)
* [How to update wildduck from git](https://github.com/nodemailer/wildduck/wiki/Updating-wildduck-via-git)

Tell me what you think, or it is appropriate for the wiki, or out of scope.
I think mentioning the wiki in the beginning of README.md file would be really nice.

**Comment by andris9** [comment]
Awesome, just create a PR if you want to add links to README or to add the command file

**Comment by unixfox** [comment]
Hi @bunyevacz I'm interested in your migration documentation because I want to migrate from mailcow to wildduck.
Can you give me some tips to perform a migration to wildduck?

**Comment by bunyevacz** [comment]
Hi @unixfox, I never wrote the migration document, I need to recollect what I did.
But the basic idea was to install wildduck (via the setup), and sync the email boxes with isync.
I have migrated from exchange (and outlook .pst files).  So I first needed to convert .pst to maildir format (pst-utils package, `readpst` command).

I have just written a migration document:
https://github.com/nodemailer/wildduck/wiki/migration-guide

It is rather crude, but hopefully it will get you started.

**Comment by andris9** [comment]
For easier import from maildir based systems I created a tool to import emails directly from maildir to WildDuck. This allows to skip any IMAP based syncing etc. See the tool [here](https://github.com/nodemailer/import-maildir)

**Comment by bunyevacz** [comment]
@andris9 

For me the biggest bug I ended up with when migrated over to wildduck was:
Somehow the local domain name from all email address (me@mydomain.com, myothercollegue@mydomain.com) ended with only the name without domain (me, myothercollegue).

Maybe it is somehow an outlook bug (.pst fileformat). But right now it is just too hard to search for email address, because all local email address are invalid in past emails.

Would be nice to be able to rewrite all email address in the past emails, to correct this information loss.

**Comment by andris9** [comment]
@bunyevacz That's strange, I don't see how the domain part would be lost. Could you provide an example .pst file? eg something that does not have anything confidential in it?

**Comment by bunyevacz** [comment]
@andris9 
There were two migration paths:
1. outlook itself syncronized through imap (but it usually hangs with larger accounts)
2. export from outlook as .pst, convert pst->imap (readpst), synchronize imap with wildduck (isync).

Let me check where the domain name got lost at which exact step. Gimme a week for this sadly. 
I will report back here.
