### ISSUE TITLE
Invalid DKIM Key

### ISSUE THREAD

**Issue by nizulzaim** [nodemailer/wildduck#93]
Hi, Thank you with nice application/package

I have follow your instruction from the installation script very well. Let say i have to IP address which IP1 is pointing to web server of company and IP2 is pointing  to mail server which is both setup as A record already.

Then, I run the installation script using

./install.sh devsign.my mail.devsign.my

However,

After already done setup TXT and MX as instruct, the web apps show available domain to be select is @mail.devsign.my instead of @devsign.my

Also, when i run `systemctl status zone-mta`. this following error show up:

```
Jul 01 17:54:23 mail.devsign.my zone-mta[10472]: info Sender/default/10489[2] 16456e2945b0002f53.001 CONNECTING domain=gmail.com port=25
Jul 01 17:54:23 mail.devsign.my zone-mta[10472]: info Sender/default/10489[3] 16456e629820002f53.001 CONNECTING domain=gmail.com port=25
Jul 01 17:54:23 mail.devsign.my zone-mta[10472]: info Sender/default/10489[4] 16456ea663c0002f53.001 CONNECTING domain=gmail.com port=25
Jul 01 17:54:23 mail.devsign.my zone-mta[10472]: ERR! DKIM 16456e2945b0002f53.001 DBFAIL Failed loading DKIM key "mail.devsign.my". Invalid or unknown DKIM key
Jul 01 17:54:23 mail.devsign.my zone-mta[10472]: info Sender/default/10489[5] 16456f781ae0002f53.001 CONNECTING domain=gmail.com port=25
Jul 01 17:54:23 mail.devsign.my zone-mta[10472]: ERR! DKIM 16456e629820002f53.001 DBFAIL Failed loading DKIM key "mail.devsign.my". Invalid or unknown DKIM key
Jul 01 17:54:23 mail.devsign.my zone-mta[10472]: ERR! DKIM 16456ea663c0002f53.001 DBFAIL Failed loading DKIM key "mail.devsign.my". Invalid or unknown DKIM key
Jul 01 17:54:24 mail.devsign.my zone-mta[10472]: info Sender/bounces/10511 [d9b2565cedd24d118da6] Starting sending for bounces
Jul 01 17:54:26 mail.devsign.my zone-mta[10472]: ERR! Plugins Failed loading plugin file <plugins/srs>: Cannot find module '/opt/zone-mta/plugins/srs'
Jul 01 17:54:26 mail.devsign.my zone-mta[10472]: ERR! Plugins Failed loading plugin file <plugins/srs>: Cannot find module '/opt/zone-mta/plugins/srs'
```

I have run this from clean server about 3 times already and still this issue show up. Hope you can help me on this. Thank you.

**Comment by fcardona** [comment]
I haven't used the latest install.sh so I'm not sure if it supports the creation of multiple domains. However, you can add a new DKIM yourself using the API...
https://api.wildduck.email/#api-DKIM-PostDkim

**Comment by andris9** [comment]
This should be fixed in latest version
