### ISSUE TITLE
13_install_ssl_certs.sh: acme.sh installed into incorrect location

### ISSUE THREAD

**Issue by robbiehanson** [nodemailer/wildduck#96]
This may be entirely my fault. But I will submit that it may also be a common source of frustration for those running the install scripts.

When I installed wildduck, most everything seemed to install OK, except the TLS certs. The source of the problem seems to be that the path (on my machine) is `/home/robbie/.acme.sh/acme.sh` as opposed to the hard-coded path of `/root/.acme.sh/acme.sh` that the script assumes. Of course, this stems from the fact that I ran the install script as `sudo`, as opposed to running it as root.

Perhaps we could make the install script a little smarter to account for this ?

**Comment by bunyevacz** [comment]
seems like the solution is rather simple:

```
22c22
< /root/.acme.sh/acme.sh --issue --nginx \
---
> $HOME/.acme.sh/acme.sh --issue --nginx \
```

The [install script][0] installs to the `$HOME` directory, so it seems like a safe modification:

```
DEFAULT_INSTALL_HOME="$HOME/.$PROJECT_NAME"
```

[0]: https://raw.githubusercontent.com/Neilpang/acme.sh/master/acme.sh
