### ISSUE TITLE
Haraka as outbound SMTP

### ISSUE THREAD

**Issue by lcts** [nodemailer/wildduck#98]
Hi,
I'm working on an auth plugin for Haraka that checks user credentials (instead of just mail addresses like the current one) against Wildduck for SMTP submission, and was wondering whether there was a specific reason not to use Haraka as outbound SMTP in Wildduck? Is there any interest in porting the wildduck-zonemta-plugin to Haraka?

**Comment by andris9** [comment]
Using Haraka as outbound does not work with WildDuck message queueing, you would need ZoneMTA in between. WildDuck writes message information to (potentially distributed) MongoDB, so ZoneMTA can read that info and update it (in case soft bounces happen etc). Haraka reads its queue from the file system.

**Comment by CheyenneForbes** [comment]
@andris9 What about with plugins like this that allows queuing to MongoDB? [https://github.com/Helpmonks/haraka-plugin-mongodb](https://github.com/Helpmonks/haraka-plugin-mongodb)

**Comment by louis-lau** [comment]
> This plugin will store incoming emails (including bounces, etc.) in MongoDB and store all attachments on the disk. Additionally, it can also be used to store all results for outgoing emails.

Doesn't seem like that plugin will make haraka store its actual outbound queue in mongodb. I'm not sure that haraka's plugin structure would even allow this.

**Comment by CheyenneForbes** [comment]
Based on [this](https://github.com/haraka/Haraka/issues/1753#issuecomment-270518511) comment from a Haraka core member, my assumption is its allowed by the plugin structure (recently?)

**Comment by louis-lau** [comment]
That is again for inbound emails, not for storing an outbound queue.

> How to save the incoming mails to lets say a mysql database
