### ISSUE TITLE
How to delivered Junk to Inbox??

### ISSUE THREAD

**Issue by Manishjodhani** [nodemailer/wildduck#99]
Hi,
Wildduck is one of the best email server i ever used.
Is that possible to move all junk mails to inbox or i don't want junk folder in this.?
I try to select mails and move to inbox but it not working.
If i select more then 15 mails it will not move and when i select 10 mails then it will moved.
Is there any limit in move mails?Or i can increase the limit ?

**Comment by andris9** [comment]
Is this happening in an IMAP client or in the webmail demo client?

**Comment by Manishjodhani** [comment]
You mean to say this file config/imap.toml ??

**Comment by Manishjodhani** [comment]
I have done some changes in this. But it did not effect.

# Max size for messages uploaded via APPEND
maxMB=30

# delete messages from \Trash and \Junk after retention days
retention=30

# Default max donwload bandwith per day in megabytes
maxDownloadMB=100000

# Default max upload bandwith per day in  megabytes
maxUploadMB=100000

# Default max concurrent connections per service per client
maxConnections=30

Please tell me another solution for this.
